### ISSUE TITLE
No translation files after 16.02.08 Qt5 build

### ISSUE THREAD

**Issue by DAP-DarkneSS** [zaps166/QMPlay2#10]
openSUSE 13.2 x64
Qt 5.4

[   82s] + export QT_SUFFIX=-qt5
[   82s] + QT_SUFFIX=-qt5
[   82s] ++ grep -o '[0-9]*'
[   82s] ++ echo -j2
[   82s] + NOTERM=1
[   82s] + SYSTEM_BUILD=1
[   82s] + ./compile_unix 2
[   82s] Could not find qmake configuration file default.
[   82s] lrelease error: cannot process project file 'QMPlay2.pro'.
[   82s] mv: cannot stat 'lang/*.qm': No such file or directory
[   82s] cd src/ && ( test -e Makefile || /usr/bin/qmake-qt5 /home/abuild/rpmbuild/BUILD/QMPlay2-src-16.02.08/src/src.pro -o Makefile ) && make -f Makefile 
[   82s] make[1]: Entering directory '/home/abuild/rpmbuild/BUILD/QMPlay2-src-16.02.08/src'
[   82s] cd qmplay2/ && ( test -e Makefile || /usr/bin/qmake-qt5 /home/abuild/rpmbuild/BUILD/QMPlay2-src-16.02.08/src/qmplay2/qmplay2.pro -o Makefile ) && make -f Makefile 
[   82s] make[2]: Entering directory '/home/abuild/rpmbuild/BUILD/QMPlay2-src-16.02.08/src/qmplay2'

**Comment by zaps166** [comment]
Hmm, weird. Which Qt5 version? It is reproducible on Qt 4.8 or Qt >= 5.5 ?

**Comment by DAP-DarkneSS** [comment]
Not reproducible with Qt4. I'll check other Qt5 versions today.

**Comment by DAP-DarkneSS** [comment]
Not reproducible with Qt5.5 too.

**Comment by zaps166** [comment]
Ok :smile:
It is really a regression?
```
lrelease error: cannot process project file 'QMPlay2.pro'.
```
Which Qt version causes this "lrelease" error?

**Comment by DAP-DarkneSS** [comment]
Hm, 15.12.25 & Qt 5.4 provide the same issue, so I am not really sure if it is a regression.

**Comment by DAP-DarkneSS** [comment]
If it is a Qt bug, it may be skipped.

**Comment by zaps166** [comment]
Maybe, but I'll compile Qt 5.4 to be sure :smiley:

Qt 5.4 causes the error, right?

**Comment by DAP-DarkneSS** [comment]
I wrote it three times ;) 
Yep, 5.4.2.

**Comment by zaps166** [comment]
```
Could not find qmake configuration file default.
lrelease error: cannot process project file 'QMPlay2.pro'.
```
Looks like incorrect qt/qmake/qttools installation. I've got the same on Qt 5.4 and Qt 5.6 if I compile "lrelease" and I'll try to use it. Do you use custom Qt build?

**Comment by DAP-DarkneSS** [comment]
I am an openSUSE package maintainer and use only distribution packages.

**Comment by zaps166** [comment]
I don't know... OpenSUSE 13.2?

**Comment by DAP-DarkneSS** [comment]
Yes.

**Comment by zaps166** [comment]
Ok, please try:
```
lrelease-qt5 QMPlay2.pro
```
in QMPlay2 source directory.

I've just tried openSUSE-13.2-KDE-Live-i686.iso + libqt5-linguist, Qt 5.4.2 - no problems :)

//btw. why LiveCD download link isn't available on SUSE download page?

**Comment by DAP-DarkneSS** [comment]
[  233s] + lrelease-qt5 QMPlay2.pro
[  233s] Could not find qmake configuration file default.
[  233s] lrelease error: cannot process project file 'QMPlay2.pro'.
PS https://software.opensuse.org/132/en Click here to display these alternative versions.

**Comment by DAP-DarkneSS** [comment]
F*ck, multimedia:apps project uses Qt 5.3.2 that is the default not updated version for openSUSE 13.2. Sorry, any chance for 5.3?

**Comment by zaps166** [comment]
Ok, now I can reproduce it

**Comment by zaps166** [comment]
Ok, I know what is wrong and how to fix it :) This is Qt 5.3 bug and/or openSUSE packaging problem (missing envvar, bad config?). This is not QMPlay2 bug. Please modify the compilation script:
```
export QMAKESPEC=/usr/lib/qt5/mkspecs/linux-g++
lrelease$QT_SUFFIX QMPlay2.pro
unset QMAKESPEC
```
For 64bit probably it will be "lib64" instead of "lib".

**Comment by DAP-DarkneSS** [comment]
[   83s] + export QT_SUFFIX=-qt5
[   83s] + QT_SUFFIX=-qt5
[   83s] + export QMAKESPEC=/usr/lib64/qt5/mkspecs/linux-g++
[   83s] + QMAKESPEC=/usr/lib64/qt5/mkspecs/linux-g++
[   83s] + lrelease-qt5 QMPlay2.pro
[   83s] Could not find qmake configuration file default.
[   83s] lrelease error: cannot process project file 'QMPlay2.pro'.
[   83s] + unset QMAKESPEC
> ls /usr/lib64/qt5/mkspecs/linux-g++
qmake.conf  qplatformdefs.h
> lrelease-qt5 -version
lrelease version 5.3.2

**Comment by zaps166** [comment]
Sorry, this works for lupdate-qt5, not for lrelease-qt5 :smile:

Please try:
```
export QMAKE=/usr/bin/qmake-qt5
```
instead of export/unset of QMAKESPEC

**Comment by DAP-DarkneSS** [comment]
Works nice, thank you very much!
