### ISSUE TITLE
[suggestion] use clazy to check for "inefficient Qt coding mistakes"

### ISSUE THREAD

**Issue by ahjolinna** [zaps166/QMPlay2#100]
I just saw the phoronix news about the new tool from KDE team that checks the Qt code quality, I was thinking this would be useful for QMPlay2 also as clazy isn't for KDE usage only it's for all Qt projects...:

> Clazy is a Clang-based static analyzer for Qt that can warn about unnecessary memory allocations, poor API decisions, inefficient usage of some API calls, and more. Additional checks are still being added to Clazy.
> 
> Qt developers wishing to learn more can find out all of the details via this [KDAB blog post](https://www.kdab.com/uncovering-32-qt-best-practices-compile-time-clazy/). The code checker is available via the[ KDE Git repository.](https://github.com/KDE/clazy)

---source [phoronix](http://phoronix.com/scan.php?page=news_item&px=Clang-Clazy-Qt-Slow-Mistakes)

**Comment by zaps166** [comment]
Thanks for the info!

**Comment by ahjolinna** [comment]
@zaps166 : I hope you will find it useful...and maybe little bit pain in the ass, when you notice how much you need to fix :D

**Comment by ahjolinna** [comment]
I just remember that you had reverted some changes because of qt4... I notice that clazy has "[Qt4 compatibility mode](https://github.com/KDE/clazy#qt4-compatibility-mode)" also, I was wondering if you ever tried that?

PS. as clazy is still in its early stages (feature wise) It would be good to run/use it once in a while to check for new issues

**Comment by zaps166** [comment]
OK, but I'll remove Qt4 in near future :)
