### ISSUE TITLE
replay gain tags from ape ignored

### ISSUE THREAD

**Issue by Amaunator** [zaps166/QMPlay2#101]
https://www.dropbox.com/sh/37gboxllyapnwn6/AACS9MEPMBzFDYLrSogawJc9a?dl=0 please compare those 2 files. same song, same source. one is flac the other ape. both tracks normalized by foobar2000 as all my tunes are. only flac one is being played back with a proper loudness. ape tags seem to be ignored. thanks

**Comment by zaps166** [comment]
IMHO bug in FFmpeg, but I can fix it easily :)
