### ISSUE TITLE
Full screen on macOS

### ISSUE THREAD

**Issue by zaps166** [zaps166/QMPlay2#102]
@RJVB

Moved from #95

**Comment by zaps166** [comment]
> when you use the fullscreen button and then double-click the video window you don't get fullscreen video. Instead, QMPlay2 drops out of fullscreen mode.

It is intended :) You can toggle compact mode in native full screen and you'll get similar effect than in previous QMPlay2 version.

---

> Yes, the auto-hiding of Dock and menubar shouldn't be activated when they are on a different screen than the window that will be maximised. My Dock is always set to auto-hide, but for the menubar it really looks strange when it disappears from the screen while the rest of that screen's contents don't change.

If you have 2 physical screens than dock and menu bar disappears on another screen, right?

**Comment by RJVB** [comment]
On Thursday April 20 2017 10:43:16 Błażej Szczygieł wrote:


> It is intended :) You can toggle compact mode in native full screen and you'll get similar effect than in previous QMPlay2 version.

Your call. I don't see the point in having 2 kinds of fullscreen mode in a single application, with an MDI design at that ...

> > Yes, the auto-hiding of Dock and menubar shouldn't be activated when they are on a different screen than the window that will be maximised. My Dock is always set to auto-hide, but for the menubar it really looks strange when it disappears from the screen while the rest of that screen's contents don't change.
> 
> If you have 2 physical screens than dock and menu bar disappears on another screen, right?

Currently they do, yes. But AFAIK not if you have "screens have separate spaces", then the menubars and Docks on those screens remain visible. My goal with the legacy fullscreen mode is to get a consistent behaviour regardless of how Mission Control is configured. So menubar and Dock should only disappear when they're "in the way". If they're on another screen that doesn't get a fullscreen window there is no reason for them to hide, on the contrary.

BTW, I no longer call this "legacy" mode. Not sure yet how it should be called, but it shouldn't have connotations with obsolete behaviour...

R.

**Comment by zaps166** [comment]
I don't understand your code, I don't know what it should do... :(

Please open a PR then I'll check it :)

**Comment by zaps166** [comment]
Or how can i do to return `false` in `[NSScreen screensHaveSeparateSpaces];`, because I have always `true` :) ?

**Comment by RJVB** [comment]
On Thursday April 20 2017 23:29:49 Błażej Szczygieł wrote:
>Or how can i do to return `false` in `[NSScreen screensHaveSeparateSpaces];`, because I have always `true` :) ?

Even when your desktop is configured to use a single Space for all screens? Note that you have to log off and back in if you change the "screens have separate spaces" setting in the Mission Control prefpanel.

R.

**Comment by RJVB** [comment]
On Thursday April 20 2017 12:19:22 Błażej Szczygieł wrote:
>I don't understand your code, I don't know what it should do... :(
>
>Please open a PR then I'll check it :)

You'll need to tell me what you're trying to do first because I cannot really do a PR of a different project hosted on a different git server ;)

**Comment by zaps166** [comment]
> "screens have separate spaces" setting in the Mission Control

I didn't know about this option :)
Done: https://github.com/zaps166/QMPlay2/commit/ac1855712b775cd57c533813d04c13e905fc9aeb
