### ISSUE TITLE
Video adjustment hue has an off by one error which leads to a green video

### ISSUE THREAD

**Issue by Lasering** [zaps166/QMPlay2#110]
Screenshots with and without the error:

http://imgur.com/a/IU3QL

**Comment by zaps166** [comment]
Which video output is used (you can paste a screenshot from Information window)?

**Comment by Lasering** [comment]
http://imgur.com/a/LueSE

**Comment by zaps166** [comment]
I assume that you use Intel drivers. Currently I can't reproduce.
- Does it happen on other movies?
- Does it work if you don't touch Hue slider (by default it is set to 0)?
- Does it happen on VA-API via OpenGL (install `libva-intel-driver` (Arch Linux package name), move VA-API decoder to the top in settings and apply - it should be visible as "FFmpeg/VA-API, OpenGL 3.0 VA-API" in information window)?

**Comment by Lasering** [comment]
I use the `xf86-video-ati` driver on a Radeon HD 4890 (RV790).
I installed `libva-mesa-driver` and `mesa-vdpau` and set the VDPAU decoder to the top and that fixed the problem.

Thanks for the solve :)

**Comment by zaps166** [comment]
Ah, so this is Radeon :) Currently VDPAU in QMPlay2 doesn't use OpenGL, so you can't rotate or use spherical video.

I thing that I should make a workaround for a Radeon OpenGL, but I can't reproduce... Maybe there is a problem with conditions in GLSL using Radeon Mesa drivers?

**Comment by Lasering** [comment]
It also worked with VA-API on top. I guess the problem was just not having them installed (or at least one of them).

**Comment by zaps166** [comment]
> It also worked with VA-API on top

Is it VA-API over OpenGL (`FFmpeg/VA-API, OpenGL 3.0 VA-API` on Information window)?

---

Moreover, the bug with hue mustn't happen without VA-API or VDPAU :)

**Comment by Lasering** [comment]
Yup its VA-API over OpenGL exactly with that text. And with VDPAU is `FFmpeg/VDPAU, VDPAU`.

Should I reopen the issue?

**Comment by zaps166** [comment]
> Should I reopen the issue?

If it happens on pure OpenGL - yes :)

---

I forgot that VA-API over OpenGL uses other shader, so it might not trigger this bug 😄 I must check it on Radeon - I have old Radeon HD GPU, so I'll try to reproduce this bug later.

**Comment by zaps166** [comment]
Can't reproduce on Radeon HD 5450 and Mesa 17.1.2.
