### ISSUE TITLE
Ability to hide "Artist" metadata from playlist?

### ISSUE THREAD

**Issue by Chromace** [zaps166/QMPlay2#111]
Currently, QMPlay2 takes into account both the "artist" and "title" metadata of files to create its playlist names. It would be nice if it had the ability to only show the file's title, thus saving some space.

This could be useful if files were arranged in groups representing separate artists for example, rendering the "artist" metadata unnecessary.

**Comment by zaps166** [comment]
QMPlay2 returns always both as a playlist title, so it needs additional argument.
Probably I'll add this into next release 👍

**Comment by Chromace** [comment]
It works, thank-you! Hopefully it wasn't too difficult to do.
