### ISSUE TITLE
improve fetching of lyrics.

### ISSUE THREAD

**Issue by penguin31** [zaps166/QMPlay2#114]
Sometimes qmplay2 does do not find lyrics of songs.
I use cmus and mocp as terminal mp3 players and clyrisc of trixen (Daniel Șuteu) > https://github.com/trizen/clyrics,to fetch and show lyrics lyrics.Very rarely clyrics does not find lyrics.Have a look in list of lyric sites: https://github.com/trizen/clyrics/tree/master/plugins.
Would be worthy to add some of lyrics sites to qmplay2.
Another site that fetches lyrics for cmus : https://github.com/hakerdefo/cmus-lyrics also 
another one : https://github.com/febuiles/makeitpersonal

**Comment by zaps166** [comment]
> Sometimes qmplay2 does do not find lyrics of songs.

Does those lyrics exist on http://tekstowo.pl ? Or is it QMPlay2 bug which cannot find it ? Please notice, that you must have valid metadata - QMPlay2 doesn't extract artist and title from file name.

**Comment by penguin31** [comment]
I mean, the same song/songs.Played in deadbeef, clementine, audacious, qmplay2 or qmmp also played in cmus/or mocp. Clyrics beats them all.As I said, Very rarely Clyrics does not find lyrics.I am far way from my laptop now to give a real example.

**Comment by zaps166** [comment]
https://makeitpersonal.co/lyrics?artist=Myartist&title=Mytitle looks good and it is easy to implement 👍
