### ISSUE TITLE
Further playlist options?

### ISSUE THREAD

**Issue by Chromace** [zaps166/QMPlay2#12]
It would be nice if specific files present in QMPlay2's playlist could persist after closing the media player (e.g. remember a folder). That way, files are more easily accessible, with the additional benefit of having multiple playlists in QMPlay2, using the 'repeat, random in group' option to do this.

And this brings up another sort of remembering for playlists: might it be possible for QMPlay2 to remember the specific repeat option that it used in the last session? It's just a small time-saver thing.

Finally, on a slightly different tangent, could QMPlay2 have the option to display a file's name instead of its ID3 tag name? It's a very niche thing, but sometimes after downloading tons of videos, one finds it troublesome relabelling all of them, even if the metadata titles do not suit the file.

Thanks for the great media player.

**Comment by zaps166** [comment]
> And this brings up another sort of remembering for playlists: might it be possible for QMPlay2 to remember the specific repeat option that it used in the last session? It's just a small time-saver thing.

Yes it is possible to do. It can be done as an additional option to save the repeat settings on exit.

> Finally, on a slightly different tangent, could QMPlay2 have the option to display a file's name instead of its ID3 tag name? It's a very niche thing, but sometimes after downloading tons of videos, one finds it troublesome relabelling all of them, even if the metadata titles do not suit the file.

QMPlay2 automatically reads tags when they exists. I can add an option for not doing this. Additionally you can open file properties and remove tags.

> It would be nice if specific files present in QMPlay2's playlist could persist after closing the media player (e.g. remember a folder). That way, files are more easily accessible, with the additional benefit of having multiple playlists in QMPlay2, using the 'repeat, random in group' option to do this.

I don't understand this paragraph :smile:

**Comment by Chromace** [comment]
Um...so after closing and opening QMPlay2, the playlist is forgotten. I thought it'd be nice if there was an option to for the playlist to persist even after QMPlay2 is closed.

Furthermore, I've found categorising the playlist into folders to be a neat substitute for playlist files, since I can make QMPlay2 play music in a single folder. This would work even better if the media player had the ability to remember the playlist after closing.

However, this does not take into account files which a person plays outside of their playlists (e.g. random video from the internet). Therefore if persistent playlists were implemented, it'd be done selectively (e.g. playlist folder 'A' stays in the playlist after closing + reopening, but random video 'xyz' is removed from the playlist after closing QMPlay2).

Apologies. My wording was confusing.

**Comment by zaps166** [comment]
> Um...so after closing and opening QMPlay2, the playlist is forgotten.

QMPlay2 stores the entire playlist in `~/.qmplay2/Playlist.pls`. On Windows it is in `$APPDATA%\QMPlay2\Playlist.pls`.

Which OS do you use (Windows, Linux)? Is the settings directory writable? Does the `FFmpeg` module work properly (it is also responsible for reading files and network streams, so it reads the playlist from file)?

**Comment by Chromace** [comment]
I use Linux. The settings directory is indeed writable. I am fairly certain the FFmpeg module works properly...

But none of that matters. I'm such an _idiot_. I disabled PLS support for some reason (guess I thought I didn't need it, cause I only use M3Us). Re-enabling it makes it work again. Apologies.

**Comment by Chromace** [comment]
Another observation: when toggling the option 'Player -> Repeat -> Random/Random in group', QMPlay2 stops itself from playing anymore files than the number of files in the playlist. Might there be a way to keep playing without manually pressing play? Thanks.

**Comment by zaps166** [comment]
Ah, I forgot about ability to disable `PLS`...
QMPlay2 uses modified PLS format (which should be compatible in other players) for storing playlists.

So what about reading tags on playlist? Can it be done as additional option (in settings)?

> Another observation: when toggling the option 'Player -> Repeat -> Random/Random in group', QMPlay2 stops itself from playing anymore files than the number of files in the playlist.

It is weird, because it is in "Repeat" menu, but it stops when all files has been played (it doesn't repeat). My idea was to not repeat this, but maybe your idea is better :smile: I'll think about this :)

**Comment by Chromace** [comment]
Unfortunately, I am unable to find an option to disable reading tags in the playlists. Apart from that though, QMPlay2 has a surprisingly extensive amount of options.

**Comment by zaps166** [comment]
> Unfortunately, I am unable to find an option to disable reading tags in the playlists.

Because it doesn't have it yet. I think about implementing it :smile: But it'll affect both audio and video, OK ?

**Comment by Chromace** [comment]
That sounds logical. And in fact, ideal. Thanks! :)

**Comment by zaps166** [comment]
Don't show tags only on playlist or also on window title bar?

**Comment by Chromace** [comment]
Also not showing it on the window title bar would be nice - consistency.

**Comment by zaps166** [comment]
Done, please compile & test :smile:

**Comment by zaps166** [comment]
> (...) might it be possible for QMPlay2 to remember the specific repeat option that it used in the last session?

Done

**Comment by zaps166** [comment]
> Another observation: when toggling the option 'Player -> Repeat -> Random/Random in group', QMPlay2 stops itself from playing anymore files than the number of files in the playlist.

I think about adding two additional menu items for random+repeat (new issue), so closing this issue.

**Comment by zaps166** [comment]
Random+repeat issue: https://github.com/zaps166/QMPlay2/issues/14

**Comment by Chromace** [comment]
Thanks! :) I've reinstalled QMPlay2 using the AUR git version of it. I can't seem to find the options though...

Do I need to manually compile it?

**Comment by zaps166** [comment]
![qmp2-settings](https://cloud.githubusercontent.com/assets/6239090/15670508/25da2f1e-2726-11e6-89fd-dfb62fd190d2.png)

> I've reinstalled QMPlay2 using the AUR git version of it (...) Do I need to manually compile it?

This is also manual compilation.

**Comment by Chromace** [comment]
The AUR git version works! Thank-you! :)
