### ISSUE TITLE
feature request: option to NOT auto-play the next playlist entry

### ISSUE THREAD

**Issue by RJVB** [zaps166/QMPlay2#121]
It'd be nice to have a option to prevent QMPlay2 from moving on automatically to play whatever entry is next in the playlist. That next entry can be completely unrelated (except for random matching of words in the title) if you use the quick search feature.

We often use QMPlay2 to watch tutorials (for instance for new dances we're learning) and then the player should really just stop when it reaches the end of the video.

(Apologies if the option exists under a name I didn't understand).

**Comment by zaps166** [comment]
There is "Stop after" function in Playlist menu (Alt+A). I'll add that function (not auto-play) if not "Stop after" is not sufficient.

**Comment by RJVB** [comment]
On Sunday October 15 2017 10:11:58 Błażej Szczygieł wrote:

>There is "Stop after" function in Playlist menu (Alt+A). 
>I'll add that function (not auto-play) if not "Stop after" is not sufficient.

It'd be enough if

1) the action is always visible
2) the state is remembered

In that case you could consider adding a toggle button to the playback toolbar, where it's easy to find for users who are already mind-boggled by all the options and functions or can never remember shortcuts ;)

R.

**Comment by zaps166** [comment]
@RJVB Is it OK ? 😃

**Comment by RJVB** [comment]
Sorry, haven't had time to look into this. Will try to some time the next few days.

**Comment by RJVB** [comment]
Finally remembered this at an opportune moment.

Yes, it does the trick but only because it's sticky ;)
I really had to search for the option though, I don't see the relationship with repeat modes. It seems fine to group it with the repeating options in the Player menu, I'd probably do something like this myself:

```
-----
Repeat >
A-B Repeat
Continue to next playlist entry
-----
```

Or I'd make it a global setting that controls behaviour of the standard play commands except the play button (i.e. in the Playback Settings dialog) and add a control next to the standard play button that launches a playlist playback. You must of course do as you see fit, but maybe you can think of a useful and intuitive distinction between file playback and playlist playback modes?
