### ISSUE TITLE
mp3 or other format from yotube downloader/enhancement

### ISSUE THREAD

**Issue by penguin31** [zaps166/QMPlay2#123]
Can you add possibility to download a file from youtube downloader as 
mp3 or mp4 (other formats), instead just webm format ? 
Also having possibility to decide format settings  of mp3 ?

**Comment by zaps166** [comment]
> Can you add possibility to download a file from youtube downloader as mp3 or mp4

MP3 is an audio codec, MP4 is a container which mostly has AAC audio codec.

YouTube has AAC, Vorbis and Opus codecs only, so downloading MP3 is impossible - it requires lossy conversion, but QMPlay2 is not an audio converter. Is it possible to add MP4 with AAC codec (QMPlay2 already supports Matroska muxing).

Btw. why not using better Vorbis/Opus codecs?

**Comment by penguin31** [comment]
something like this ...

youtube-dl --extract-audio --audio-format mp3 <video URL>

-b            Best quality
-m            Mobile version
-d            High Definition
-g            Don’t download, just show the url
-c            Resume download of a video which was interrupted before
-w            Don’t overwrite existing file

youtube-dl should be included in qmplay2 package /linux or windows/ 

or folks should be advised to install it before from :
`https://rg3.github.io/youtube-dl/download.html`

download mp3 from youtube by youtube-dl as instructed in : `https://askubuntu.com/questions/178481/how-to-download-an-mp3-track-from-a-youtube-video`

**Comment by zaps166** [comment]
> youtube-dl should be included in qmplay2 package /linux or windows/

No, it is downloaded and updated automatically. QMPlay2 uses youtube-dl for a long time.

> youtube-dl --extract-audio --audio-format mp3 

youtube-dl downloads AAC or Opus and then uses ffmpeg executable for MP3 **codec** conversion.

---

Temporarily use this: https://github.com/dfaust/soundkonverter, https://www.archlinux.org/packages/community/x86_64/soundkonverter/ for downloaded files. Later I'll do something with this.

**Comment by zaps166** [comment]
I'm curious why you need the MP3. All Android devices supports Vorbis and AAC and new supports Opus codecs. Moreover I assume that iPhone supports AAC codec. There are also pocket MP3 players with Vorbis support. Is it a car MP3 player?

Maybe you need downloading in OGG (instead of Matroska) container for Vorbis/Opus audio streams?

**Comment by penguin31** [comment]
I am an old school guy.Maybe CD or USB with mp3 files on it.I do not spend in vain, when I can use old equipments.But is not a problem.I suggested someone to use qmplay2 to download a video/song in webm and convert is in mp3 . In Linux converting is simple.A command line string.In windows, i suggested Pazera Converter. But in windows or Linux, youtube-dl (gui) can download file directly in mp3. Please.Do not forget to make an editor that can read and write radio station list and include also small icons for them :). Wishing all the best for you !

**Comment by zaps166** [comment]
I have an idea to run external custom command (e.g. `ffmpeg`) after downloading a file, then you can convert any format/codec to any other format/codec.
