### ISSUE TITLE
Prostopleer seems did not find any songs / not function any more

### ISSUE THREAD

**Issue by penguin31** [zaps166/QMPlay2#124]
Prostopleer seems did not find any songs / not function any more.
Said : Connection Error or the Prostopleer website is down?

**Comment by zaps166** [comment]
http://pleer.net/ website doesn't work....

**Comment by zaps166** [comment]
We need a replacements, e.g.:
https://datmusic.xyz
https://my-free-mp3.net

**Comment by zaps166** [comment]
@penguin31 Added Datmusic, it contains MP3 files :)
