### ISSUE TITLE
"Remember playback position" don't work

### ISSUE THREAD

**Issue by Diablopc** [zaps166/QMPlay2#127]
build 17.10.24
Os's: OpenSUSE 42.3; Mageia 6

**Comment by zaps166** [comment]
Could you add more details?

**Comment by Diablopc** [comment]
Despite of enabled function playback starts from  the beginning of file

**Comment by zaps166** [comment]
1. Check "Remember playback position" and apply.
2. Play something which is seekable (e.g. audio file).
3. Don't change selected playlist item and close QMPlay2.
4. Run QMPlay2 again - it should continue playback. (you can also check accurate seek in settings especially for video files).

If QMPlay2 doesn't remember playback position, try to disable MPRIS2 (Modules/Extensions) - maybe MPRIS2 client seeks to beginning at startup?

**Comment by zaps166** [comment]
Does it work ?

**Comment by Diablopc** [comment]
Ou, thx. 
I have not understood this func, because it have really different logic from similar func's in other players, that i had use.

**Comment by zaps166** [comment]
So, how does it work in other players ? 😄

**Comment by Diablopc** [comment]
It remembers It remembers state for files.  Also no matter what you play before reopening that file, and never mind  how you open that file, e.g. from file manager or from playlist.

**Comment by zaps166** [comment]
Ok, so here it works differently :)

**Comment by Diablopc** [comment]
eg in vlc or smplayer
here a screencast https://youtu.be/Z58nJ0JfdG0

**Comment by zaps166** [comment]
So it is another feature (e.g. separate check box and logic for this), but not a bug. I.e. for me this logic is weird - when I want to open a file, I want it plays from beginning.

**Comment by Diablopc** [comment]
>  So it is another feature, but not a bug

I agree. I just did not understand it at the beginning ;)

> when I want to open a file, I want it plays from beginning.

this feature well done in vlc, it have 3 options: never; ask; always.
The best it looks with "ask" option. When you opened a file, playback starts from beginning and at the top, for several seconds, appears a question about this and you can press "Continue" button. Also if you ignorring it, playback continues without jumping to previous timestamp.
