### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by SolarAquarion** [zaps166/QMPlay2#129]
[ 16%] Building CXX object src/modules/FFmpeg/CMakeFiles/FFmpeg.dir/FFmpeg.cpp.o
[ 17%] Building CXX object src/modules/FFmpeg/CMakeFiles/FFmpeg.dir/FFDemux.cpp.o
[ 17%] Building CXX object src/modules/FFmpeg/CMakeFiles/FFmpeg.dir/FFDec.cpp.o
[ 17%] Building CXX object src/modules/FFmpeg/CMakeFiles/FFmpeg.dir/FFDecSW.cpp.o
/home/solaraquarion/build/qmplay2-git/src/QMPlay2/src/modules/FFmpeg/FFDecSW.cpp: In member function ‘virtual int FFDecSW::decodeVideo(Packet&, VideoFrame&, QByteArray&, bool, unsigned int)’:
/home/solaraquarion/build/qmplay2-git/src/QMPlay2/src/modules/FFmpeg/FFDecSW.cpp:216:25: error: ‘CODEC_FLAG2_FAST’ was not declared in this scope
    codec_ctx->flags2 |= CODEC_FLAG2_FAST;
                         ^~~~~~~~~~~~~~~~
/home/solaraquarion/build/qmplay2-git/src/QMPlay2/src/modules/FFmpeg/FFDecSW.cpp:216:25: note: suggested alternative: ‘AV_CODEC_FLAG2_FAST’
    codec_ctx->flags2 |= CODEC_FLAG2_FAST;
                         ^~~~~~~~~~~~~~~~
                         AV_CODEC_FLAG2_FAST
/home/solaraquarion/build/qmplay2-git/src/QMPlay2/src/modules/FFmpeg/FFDecSW.cpp:223:26: error: ‘CODEC_FLAG2_FAST’ was not declared in this scope
    codec_ctx->flags2 &= ~CODEC_FLAG2_FAST;
                          ^~~~~~~~~~~~~~~~
/home/solaraquarion/build/qmplay2-git/src/QMPlay2/src/modules/FFmpeg/FFDecSW.cpp:223:26: note: suggested alternative: ‘AV_CODEC_FLAG2_FAST’
    codec_ctx->flags2 &= ~CODEC_FLAG2_FAST;
                          ^~~~~~~~~~~~~~~~
                          AV_CODEC_FLAG2_FAST
make[2]: *** [src/modules/FFmpeg/CMakeFiles/FFmpeg.dir/build.make:135: src/modules/FFmpeg/CMakeFiles/FFmpeg.dir/FFDecSW.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:277: src/modules/FFmpeg/CMakeFiles/FFmpeg.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by zaps166** [comment]
Which FFmpeg version do you use?

**Comment by SolarAquarion** [comment]
I was using git to build it

**Comment by zaps166** [comment]
Thanks, fixed!
