### ISSUE TITLE
Move settings UI into QtDesigner

### ISSUE THREAD

**Issue by zaps166** [zaps166/QMPlay2#13]
Modifying the settings window is very inconvenient in pure C++, so move settings UI into `*.ui` files.

**Comment by arthurzam** [comment]
I would like to work on this task. But for this I have some questions:

1. In my opinion, for easier managing of the various object with names, it is better to create a ui file per every tab (or page as it is called in the code). To every ui file an appropriate class file will be created for managing the information associated with it (making it much more grouped).
2. `*.ui` files don't handle something like [ifdef](https://github.com/zaps166/QMPlay2/blob/master/src/gui/SettingsWidget.cpp#L477). I can fix this problem by setting the hidden flag when the ifdef happens.
3. ui files don't support partial translatability. For example you have lines like `(tr("Style") + ": ")`. Should I make it just as "Style: " or set the text in C++ code?
4. For grouping of files, should we move all future files of Settings From to specific folder named "settings"?

**Comment by zaps166** [comment]
I'll think about this later, but:

- I want to do one folder with all `*.ui` files,
- hidden flag is not the same - it can create visible small space in grid layout.

One form with all tabs or tabs in different UIs and merge it in C++ (C++ main settings window) - I don't know which will be better.

**Comment by zaps166** [comment]
Done: 2dc9b610b70c4b347b2ab48884aba36053f17023 (#38, #39, #40), 961e533c9f17eea20b68cdb1dbf1bf93fb67da1e, dc3d73fcac766f93f0e75c31bf9a926d5fb60ad4

@arthurzam Thanks!!!

**Comment by arthurzam** [comment]
@zaps166 Was happy to contribute!
