### ISSUE TITLE
Osd and subtitles position on zoom

### ISSUE THREAD

**Issue by Diablopc** [zaps166/QMPlay2#130]
Osd position linked to video, not to videoframe.
e.g. with zoom more than 1.0 it moves outside the screen %)
![](http://i.piccy.info/i9/31407dc6dc157acb9e16b1d2d2638cb7/1514377098/33515/1199641/Screenshot_20171227_141559.png)

**Comment by zaps166** [comment]
I need more info, e.g. is it OpenGL or VA-API video output?

**Comment by Diablopc** [comment]
Video out & decoder priorities set to next values:

VO
-  XVideo
-  OpenGL2

Decoders
-  FFmpeg VDPAU
-  FFmpeg
-  FFmpeg VAAPI

Where i can find info about currently used?

**Comment by zaps166** [comment]
You can find it on "Information" widget (underline are active streams), example screenshot:

![obraz](https://user-images.githubusercontent.com/6239090/34382525-cfced034-eb0f-11e7-8edd-ffe6dfeed042.png)

**Comment by Diablopc** [comment]
Video streams:
Stream 1 - FFmpeg, XVideo
codec: mpeg4
size: 720x400
aspect ratio: 1.8
FPS: 23.976
bitrate: 1505kbps
format: yuv420p

**Comment by zaps166** [comment]
Maybe something is wrong with XVideo drivers, could you try OpenGL output?
Which graphics card and drivers do you have?

**Comment by Diablopc** [comment]
Have tried. (Stream 1 - FFmpeg, OpenGL 2.1)
No effect.
Video: Intel mobile GM45
Drivers:
- intel (openGL output)
- modesetting (XVideo output)

**Comment by zaps166** [comment]
> e.g. with zoom more than 1.0 it moves outside the screen %)

is it a bug that it goes outside screen or a missing feature that it should go outside screen?

**Comment by Diablopc** [comment]
Looks like bug
It should not go beyond the screen. But it is going (

But even if osd we are can put to screen center (despite the fact that look ugly), with subs it not good idea =)

**Comment by zaps166** [comment]
Subtitles are always when they should be (e.g. what is specified in ASS file or in QMPlay2 settings for normal subs). OSD like volume is always on video center. It can go away when zoomed only on VA-API (and VA-API video surface) on some configurations (driver/vaapi bug e.g. VAAPI with VDPAU). On OpenGL (recommended), QPainter and XVideo your bug shouldn't happen.

Maybe something is wrong with your Qt or Qt style (try "Fusion" style to be sure - change it in QMPlay2 settings)? You can try QPainter video output (full software scaling using FFmpeg swscaler) with FFmpeg software decoder. If you set it in settings, restart QMPlay2 and check again.

**Comment by zaps166** [comment]
Does it work now ? 😄

**Comment by zaps166** [comment]
Hmm, QMPlay2 doesn't change OSD position on zoom, i.e. Volume information is always in the center of the video. I can't reproduce reported bug on Windows/Linux/macOS and OpenGL2/XVideo/QPainter/VDPAU video outputs. The only output which might have similar problem is VAAPI video output (not VAAPI via OpenGL) and some video drivers (not all video drivers).

Closing, because there is no response for more than a month.
