### ISSUE TITLE
Build failed with USE_FREEDESKTOP_NOTIFICATIONS

### ISSUE THREAD

**Issue by reagentoo** [zaps166/QMPlay2#134]
```
CMake Error at src/qmplay2/CMakeLists.txt:107 (qt5_add_dbus_interface):
  Unknown CMake command "qt5_add_dbus_interface".
```
Qt-5.9.3 with qtdbus installed.

**Comment by zaps166** [comment]
Hmm, `USE_FREEDESKTOP_NOTIFICATIONS` is enabled by default, I don't have any problems, hmm... Could you add more info?

**Comment by reagentoo** [comment]
https://gist.github.com/reagentoo/77eb604dac42abb4dbec445440f53356

**Comment by zaps166** [comment]
Is Qt5DBus installed with CMake files ? On Arch Linux it is here: `/usr/lib/cmake/Qt5DBus`

**Comment by reagentoo** [comment]
```
# ls -1 /usr/lib/cmake/Qt5DBus/
Qt5DBusConfig.cmake
Qt5DBusConfigExtras.cmake
Qt5DBusConfigVersion.cmake
Qt5DBusMacros.cmake
```
```
# cat /usr/lib/cmake/Qt5DBus/Qt5DBusMacros.cmake | grep qt5_add_dbus_interface
        qt5_add_dbus_interface(${_sources} ${_infile} ${_basename}interface)
```
I have no idea why cmake is not find this macro.

**Comment by zaps166** [comment]
Could you try to remove everything and checkout & compile again? Do you have many Qt versions or single Qt installed on your OS? Does this problem happen earlier?

**Comment by reagentoo** [comment]
I just add `find_package` inside `if(USE_FREEDESKTOP_NOTIFICATIONS)` and it is build:
https://gist.github.com/reagentoo/77eb604dac42abb4dbec445440f53356#file-qmplay2-dbus-patch

**Comment by reagentoo** [comment]
I see typo here: https://github.com/zaps166/QMPlay2/blob/master/CMakeLists.txt#L292
USE_FREEDESKTOP_NOTIFICATION instead of USE_FREEDESKTOP_NOTIFICATIONS

**Comment by zaps166** [comment]
Right, I always used `USE_MPRIS2`, so it worked 😃  PR welcome :)
