### ISSUE TITLE
[feature request] put "radio browser" next to "my stations," drag and drop between them

### ISSUE THREAD

**Issue by adpads** [zaps166/QMPlay2#136]
Congratulations. I created an account just so I could give feedback on this awesome project. I cannot believe the radio browser part did not exist six months ago - so new, yet in ways more robust than mature projects like clementine or mythtv.
Currently this is the best internet radio browser for linux in my opinion. It should be possible to put the "radio browser" into the right column, in place of the "QMplay2 radio stations," so that stations can be selected and put into the "my radio stations" list on the left. Also, it should be possible to import and export station lists.

**Comment by zaps166** [comment]
I'll improve something for the next release :)

**Comment by zaps166** [comment]
> Also, it should be possible to import and export station lists.

So you think about exporting "My radio stations"? Ok, it can be done.

---

You want "My radio stations" (maybe rename it to "Favourites"?) in "Radio browser" as a left collapsible panel (as in QMPlay2 radio stations) + add Drag and Drop, right?

**Comment by adpads** [comment]
Yes - that is exactly what I had in mind! I do not know why this got closed but these features would have very happy users! Thank you

**Comment by adpads** [comment]
I have seen the changes and will give them a try. Thank you

**Comment by zaps166** [comment]
Oops, I forgot to add export/import. I'll add it soon.

**Comment by zaps166** [comment]
> Oops, I forgot to add export/import. I'll add it soon.

Done (9a0bb7133464aa3de70c67a3a851d298d238694e).

**Comment by adpads** [comment]
Thank you! For everyone of these lines of code there will be hundreds of hours of listener enjoyment.
