### ISSUE TITLE
[Feature Request] Export and Import Settings

### ISSUE THREAD

**Issue by lbkvu** [zaps166/QMPlay2#138]
It would be great if export and import settings feature is added. Or could you please me tell me where settings file is stored? I can export and import it myself. I'm using Mac version built from source.

**Comment by zaps166** [comment]
Settings and caches on macOS are located in: `~/Library/Application Support/QMPlay2`. `Library` is a hidden directory, so use "Go to Folder..." (Cmd+Shit+G) in Finder to open it.
