### ISSUE TITLE
Youtube live streams only play for few seconds and then freeze.

### ISSUE THREAD

**Issue by stevenpusser** [zaps166/QMPlay2#139]
Net monitor shows the stream also stops at this time.  This is the current qmplay2 on Linux.

example live stream: https://www.youtube.com/watch?v=zv79hQhRrf4 (NASA ISS stream)

There aren't any error messages showing when qmplay2 is run from the terminal and the video attempts to play.

**Comment by zaps166** [comment]
I'm just watching for more than 3 minutes - no freezes. It is HLS stream, so it should work. It works through "youtube-dl", not "YouTube" or if I paste direct HLS stream link obtained from terminal. How do you play it?
I use QMPlay2-git and FFmpeg 3.4.1 (Arch/manjaro Linux).

**Comment by stevenpusser** [comment]
I have tried with qmplay2 compiled against both ffmpeg 3.2.5 and 3.4.1 on MX Linux (Debian Stretch with lots of backports).   I tried with "qmplay2 --open {huge HLS URL}" but it still stopped after a few seconds.  Could you tell me how you are using youtube-dl instead of the Youtube widget?

For what it's worth, SMPlayer 18.1.0 using mpv 0.28 as the backend worked in the GUI up to a couple days ago, but still works if you paste in the huge HLS url for the live stream.

**Comment by zaps166** [comment]
Could you do a few tests?

1. Paste huge HLS URL into QMPlay2 and try - it must work properly.
2. Paste YouTube URL (https://www.youtube.com/watch?v=zv79hQhRrf4) as youtube-dl (Ctrl+U, change "Direct address" to "youtube-dl" and paste). If still doesn't work - please update youtube-dl manually: go to QMPlay2 settings and click "Remove youtube-dl" - QMPlay2 will download recent version automatically when starting playback.

Both steps should work, but pasting it as "YouTube" URL or from YouTube browser doesn't work for me - it needs to be fixed.

**Comment by stevenpusser** [comment]
Perhaps it's this particular ISP at the public library that's slowing it down.  I only get a blip of motion about every 15 seconds, which is when I get a burst of bits for a second...otherwise, no stream.  Let me see if it affects other QMPlay2 users on MX Linux.

**Comment by zaps166** [comment]
>  Let me see if it affects other QMPlay2 users on MX Linux.

Ok.

---

The HLS chunk is about 5 sec as I can see. But something is wrong if it is played as "YouTube", because it doesn't work for my at all in this mode (otherwise it works properly).

**Comment by zaps166** [comment]
I don't know what's wrong at the moment.

My results:
- FFmpeg 3.4.1 and Arch Linux - works properly,
- FFmpeg 3.4.1 and Windows 7 - 5 seconds of video, long freeze and then next 5 seconds of video.

Looks like in some cases FFmpeg doesn't load next video chunk on time.

**Comment by zaps166** [comment]
@stevenpusser Could you try on the same OS run huge HLS URL via `ffplay` (which links to the same FFmpeg libs)?

**Comment by zaps166** [comment]
> @stevenpusser Could you try on the same OS run huge HLS URL via ffplay (which links to the same FFmpeg libs)?

The same problem on Arch Linux (tested on `ffplay`) and manually compiled FFmpeg 3.4.1, so something is wrong with FFmpeg and compilation flags.

**Comment by zaps166** [comment]
This is FFmpeg bug, not QMPlay2 bug. Currently Arch Linux ffmpeg package uses [additional patch](http://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=a606f27f4c610708fa96e35eed7b7537d3d8f712) which causes that HLS works properly. Please apply this patch and recompile FFmpeg or ask ffmpeg package maintainer of your Linux distribution to apply the patch.

I'll apply this for my Windows/Ubuntu/macOS packages for next release.

**Comment by zaps166** [comment]
More details: without a patch (see my previous comment) FFmpeg hangs [here](https://github.com/FFmpeg/FFmpeg/blob/n3.4.1/libavformat/hls.c#L896) for a long time (e.g. ~30 seconds).
