### ISSUE TITLE
logging-related crash-on-exit

### ISSUE THREAD

**Issue by RJVB** [zaps166/QMPlay2#145]
QMplay2's (new?) log output handler can trigger what I consider a bug in Qt when a (3rd party) function calls qDebug() and family during global destruction. Full analysis of the nullptr dereference:

https://bugreports.qt.io/browse/QTBUG-66584

No idea how you'd solve this in user code; the function returning the nullptr is private.

**Comment by zaps166** [comment]
It is not a Qt bug, but QMPlay2 bug (two bugs - one is calling the `QDateTime::toString()` method after deinitializing some of static data, second is calling method `QMPlay2CoreClass::log()` when it is also deinitialized).

**Comment by zaps166** [comment]
KIO Widgets probably uses static data and its destructor is called after deinitializing `QSystemLocaleSingleton`.

**Comment by RJVB** [comment]
Yeah, this was a local change I made to check something unrelated. But that shouldn't really matter, should it?

**Comment by zaps166** [comment]
Hmm, so it is not from KIO Widgets, but from your local change :smile: But now I have an additional check for it.
