### ISSUE TITLE
Video window gradient colour resets on startup

### ISSUE THREAD

**Issue by Chromace** [zaps166/QMPlay2#15]
Going to "Options -> Settings -> Set appearance -> Gradient in video window" and changing the colour options there yields only a temporary change in appearance. Closing and re-opening QMPlay2 is sufficient for it to reset back to its regular black-purple background and white text.

**Comment by zaps166** [comment]
Because is can't override the "Default color scheme".
Create a "New" color scheme, name it and then set the gradient color :)

**Comment by zaps166** [comment]
The message box about creating a new color scheme should be enough for fixing this :smile:

**Comment by Chromace** [comment]
Thanks! :)
