### ISSUE TITLE
[Feature Request]  Option to autodelete playlist on close

### ISSUE THREAD

**Issue by Connor84** [zaps166/QMPlay2#151]
I would liike the playlist to autodelete itself on close.  Each time I open the player, it is almost always for different music/video/etc than the previous time.

**Comment by zaps166** [comment]
This is already implemented :)

![screenshot](https://user-images.githubusercontent.com/6239090/36617838-4e4edcf4-18e9-11e8-8126-8c9faab827ba.png)
