### ISSUE TITLE
automatically clear the playlist on closing the application

### ISSUE THREAD

**Issue by Connor84** [zaps166/QMPlay2#152]
I would like an option to automatically clear the playlist on closing the application.

This IS NOT what it is covered by "automatically delete ungrouped entries".  That option is only for files that no longer exist.

**Comment by zaps166** [comment]
You can leave a comment on existing issues (closed or not). This is a duplicate.

**Comment by kn00tcn** [comment]
it's definitely working for files that exist for me, i opened a couple files, saw them in playlist, closed player while it was playing, closed player, opened another file from file manager (or player itself), the playlist was reset

maybe i changed some other setting like turning off 'remember position'

**Comment by zaps166** [comment]
@kn00tcn
> it's definitely working for files that exist for me, i  opened a couple files, saw them in playlist, closed player while it was  playing, closed player, opened another file from file manager (or player  itself), the playlist was reset

It is correct behavior, doesn't it? It always remove all non-locked top-level entries from playlist.

---

Original issue #151

**Comment by kn00tcn** [comment]
i didnt actually know what the option did until i randomly browsed the issues list, i was about to make a new post asking to turn off history... originally i thought playlist>lock would lock an empty playlist

maybe the option should be renamed

**Comment by zaps166** [comment]
> maybe the option should be renamed

Ok, which name can be good ? :smile:

**Comment by zaps166** [comment]
*Automatically remove top-level playlist entries?*

hmm :smile:

**Comment by kn00tcn** [comment]
the word 'playlist' definitely needs to be there, even if it's in (parenthesis), i really had no idea what grouping it was talking about

if there are other playlist settings, it could all go into a set of playlist settings

so maybe... 'automatically remove ungrouped playlist entries', not sure if it should be 'remove' or 'clear', but pretty sure it shouldnt be 'delete'

can i make a pull request for fun? but something's wrong with github's search, finds nothing for 'ungrouped' even though it's right there in `/src/gui/Ui/SettingsGeneral.ui`
