### ISSUE TITLE
automatically open and display the player on the desktop when opening a file

### ISSUE THREAD

**Issue by Connor84** [zaps166/QMPlay2#153]
I would like QMPlay2 to automatically open and display the player on the desktop when opening a file.

Right now when you open a file, QMPlay2 stays minimized (in the task bar).  You have to click on it in the taskbar to display the player.

**Comment by zaps166** [comment]
QMPlay2 should automatically restore window for all files or for video files only?

**Comment by Connor84** [comment]
"QMPlay2 should automatically restore window for all files or for video files only?"

Yes, this is what I would like it to do.  At the moment, as noted above, opening a video file does not open a window.  It instead only opens in the task bar, minimized.
