### ISSUE TITLE
[Feature Request] Add an option to remember playback position

### ISSUE THREAD

**Issue by Lastique** [zaps166/QMPlay2#156]
Please, add an option to remember last playback position (time) for a particular file or stream. This is useful to be able to continue watching a lengthy video where I last stopped.

**Comment by zaps166** [comment]
Currently playback position is stored only for last played file (to continue playback after close).

Similar/the same as #127 (but this issue exactly explains what is needed), right?

**Comment by Lastique** [comment]
It doesn't remember the position for streams (e.g. Youtube streams).

**Comment by Lastique** [comment]
> Similar/the same as #127 (but this issue exactly explains what is needed), right?

I guess so. I'm watching some multi-hour streams on Youtube and other websites and I'm not always able to watch them in full. Resuming playback later from the same position is very helpful in this case.

**Comment by zaps166** [comment]
> It doesn't remember the position for streams (e.g. Youtube streams).

Did you checked this:
![screenshot_20180303_222418](https://user-images.githubusercontent.com/6239090/36939453-aee7d20c-1f31-11e8-9980-79a93e211190.png)

And is the youtube stream seekable?

**Comment by Lastique** [comment]
> And is the youtube stream seekable?

Yes.

> Did you checked this

I didn't and at first I didn't see this option, sorry. However, it doesn't seem to save the position when I stop the stream. Only if I pause the stream or close while playing. And when I restart QMPlay2 it automatically starts playing even when it normally doesn't.

I'm quite used to how it works in SMPlayer. It remembers position in a number of files/streams and it saves the position even when I stop the playback. When I restart SMPlayer it doesn't start playback automatically but when I press play it starts playback from the remembered position.

**Comment by zaps166** [comment]
> Only if I pause the stream or close while playing. And when I restart QMPlay2 it automatically starts playing even when it normally doesn't.

Yes, it is that option (I like this behavior).

> When I restart SMPlayer it doesn't start playback automatically but when I press play it starts playback from the remembered position.

This is other option which doesn't exist in QMPlay2. Will be in the future :)

**Comment by cup** [comment]
https://github.com/zaps166/QMPlay2/issues/202

**Comment by zaps166** [comment]
Done! Over 5 years later... :smile:
