### ISSUE TITLE
Man page

### ISSUE THREAD

**Issue by DAP-DarkneSS** [zaps166/QMPlay2#16]
Please add a man page, f.e. attached one: [QMPlay2.1.txt](https://github.com/zaps166/QMPlay2/files/298802/QMPlay2.1.txt)

**Comment by zaps166** [comment]
Where should I put this (`/usr/share/man/...`)? :smiley:
Copy it to `/usr/share/man/something` or is it a special command for installing this?

**Comment by DAP-DarkneSS** [comment]
At openSUSE general man pages are located in /usr/share/man/man1/  
directory. For historical reason they are gzip'ed, but other archives and  
not archived are fine too. If man page is installed fine `man QMPlay2`  
will show it.

**Comment by zaps166** [comment]
Ok, so what `man2`, `man3`, etc are ?
I'll put this into `/usr/share/man/man1/` as gzip (I'll add it to compilation script).

**Comment by zaps166** [comment]
The MAN page doesn't have version (https://github.com/zaps166/QMPlay2/commit/eb0e16c0534b6f8148aa91f96089333151408c2d#diff-694ac15345cf2b4ab6deacb404fadef2R1). It is set in `compile_unix` script.

**Comment by DAP-DarkneSS** [comment]
Thank you!

According to `man man`:

        0   Header files (usually found in /usr/include)
        1   Executable programs or shell commands
        2   System calls (functions provided by the kernel)
        3   Library calls (functions within program libraries)
        4   Special files (usually found in /dev)
        5   File formats and conventions eg /etc/passwd
        6   Games
        7   Miscellaneous (including macro packages and conventions), e.g.  
man(7), groff(7)
        8   System administration commands (usually only for root)
        9   Kernel routines [Non standard]

**Comment by zaps166** [comment]
Ok, thanks :smiley: I didn't know that `man` has also its own manual :)
