### ISSUE TITLE
Various tiny requests.

### ISSUE THREAD

**Issue by wissssam** [zaps166/QMPlay2#162]
Thnx for this great player. It's my default media player now with all my collection added to the playlist so that I can find songs instantly and I don't have to use media managers like clementine or rythmbox.
I'm using KDE Neon (based on ubuntu 16.04) and QMPlay2 18.03.02.

1. I noticed that QMPlay2 can't open .vgz and.vgm files while it plays .nsf files nicely.
2. when selecting a track from the playlist (with a mouse click or Up and Down arrows then Enter), seeking forward and backward with Left and Right arrows doesn't work unless you click on the video area or the seek bar.
3. It would be nice to add an option for closing to system tray so that closing the window make it close to sytem tray instead of clicking on the tray icon to minimize the window. and IMHO it's better to show some play options only on right click on the tray icon (like play, pause, previous, next....etc ) instead of showing all the menu bar options.
4. It would be nice to add an option for adding another tab for the tracks in queue and for using multiple playlists.
5. It would be nice to display "lyrics not found" when the lyrics not found so that one don't wait some seconds thinkning that it is a network delay. And I noticed that QMPlay2 uses [this site](http://www.tekstowo.pl) to fetch lyrics and it displays the polish translation of lyrics so it's better to display the lyrics only without translation and add an option to display translation for polish users.
6. Regarding subtitles download from within QMPlay2, smplayer supports downloading from opensubtitles.org and it's written in Qt. so is it easy to implement this feature using smplayer code for doing this since it's open source and writte in qt?. I am not very good at programming sorry if my question is stupid.

Thank you again for making this great player.

**Comment by zaps166** [comment]
> I noticed that QMPlay2 can't open .vgz and.vgm files while it plays .nsf files nicely.

Which library is used in other players for these files?

> when selecting a track from the playlist (with a mouse click or Up and Down arrows then Enter), seeking forward and backward with Left and Right arrows doesn't work unless you click on the video area or the seek bar.

I know, but you can use also arrow keys for expanding tree and navigate up/down, so in this case you don't want to seek. Try pressing tab key (i.e. 3x) to focus something else instead of using mouse.

> and IMHO it's better to show some play options only on right click on the tray icon (like play, pause, previous, next....etc ) instead of showing all the menu bar options.

Good idea.

> It would be nice to add an option for closing to system tray so that closing the window make it close to sytem tray instead of clicking on the tray icon to minimize the window.

You can press the `` ` `` button to hide, IMHO it is convenient.

> It would be nice to add an option for adding another tab for the tracks in queue and for using multiple playlists.

There is PR for tabbed playlist, but it is buggy. The playlist code is ugly, but I don't have plans to rewrite it now. I'll think about this.

> It would be nice to display "lyrics not found"

Good idea.

> so is it easy to implement this feature using smplayer code for doing this since it's open source and writte in qt?

I don't want to copy the code from another software, but maybe I'll use opensubtitles. I also thought about this a long time ago.

**Comment by wissssam** [comment]
> Which library is used in other players for these files?

these are retro file formats used in multiple video game platforms, such as NES, Sega Master System, Game Gear, Mega Drive/Genesis, MSX, Neo Geo, IBM PC AT (Adlib/SoundBlaster)... 
I know these are retro file formats and It's not a big deal, but since QMPlay2 uses chiptune module it should play vgz just fine, I think [game-music-emu](https://github.com/sergiobenrocha2/game-music-emu) is used in chiptune module and it's used in deadbeef  [see here](https://github.com/DeaDBeeF-Player/deadbeef/tree/master/plugins/gme) as a plugin too.

> You can press the ` button to hide, IMHO it is convenient.

Sorry I didn't know that. still adding an option to close to system tray is not a bad idea IMHO.

Another thing is that after choosing (player--> repeat--> random), I think it would be better to remember previously played track when clicking on previous instead of jumping to track just before the current track on the playlist.
Showing playlist and other tabs when moving cursor to the left of the screen in full screen mode is a great convenient by the way.
Thnx in advance.

**Comment by kn00tcn** [comment]
so ffmpeg doesnt have support for those chiptunes? but distros can choose which modules to compile their ffmpeg with

gstreamer probably in a similar situation

vlc seems to use libs, but i dont have those files on hand for testing

not sure what audacious would use

> remember previously played track when clicking on previous instead of jumping to track just before the current track on the playlist

nice, yes, i dont use random but that's definitely what the user would expect

**Comment by zaps166** [comment]
> It would be nice to display "lyrics not found" when the lyrics not found

Done.

**Comment by v-fox** [comment]
> > Which library is used in other players for these files?
> 
> these are retro file formats used in multiple video game platforms, such as NES, Sega Master System, Game Gear, Mega Drive/Genesis, MSX, Neo Geo, IBM PC AT (Adlib/SoundBlaster)...
> I know these are retro file formats and It's not a big deal, but since QMPlay2 uses chiptune module it should play vgz just fine, I think [game-music-emu](https://github.com/sergiobenrocha2/game-music-emu) is used in chiptune module and it's used in deadbeef [see here](https://github.com/DeaDBeeF-Player/deadbeef/tree/master/plugins/gme) as a plugin too.

I just tried to play VGZs from Project2612.org collection but couldn't. However, QMPlay2 does play them after uncompressing and renaming into VGM, so it seems to be a file-detection and/or compression problem. I came here to write a request for a fix but found this thread.

But even when QMPlay2 plays VGM and NSF, it also interprets their length very weirdly: all of my NSFs repeat and cut off until 3 minutes regardless of their real length and "X-Men 2 - Clone Wars/01 - Opening Level.vgz" was set to something like 72 hours.

**Comment by zaps166** [comment]
@v-fox vgz is a gzipped vgm. libgme 0.6.2 doesn't support it (doesn't unpack it, at least I need to decompress it manually in QMPlay2). But libgme-master is able to decompress vgz. Could you try again with libgme-master (just compile and use `LD_PRELOAD` for new library and check if it works with QMPlay2) ?

**Comment by v-fox** [comment]
@zaps166 So, I've managed to overcome some kind of mismanaged IP filter on Bitbucket, where libgme is hosted, and have [made OBS package for openSUSE](https://build.opensuse.org/package/show/home:X0F:branches:multimedia/libgme) from latest git-snapshot, even fixed up vanilla [ffmepg package](https://build.opensuse.org/package/show/home:X0F:branches:multimedia/ffmpeg-4) to actually link with libgme and libmodplug like it was supposed too then [rebuilt QMPlay2](https://build.opensuse.org/package/show/home:X0F:branches:multimedia/QMPlay2). But no changes in QMPlay2's behaviour happened :(

**Comment by procobain** [comment]
Opensubtitle Downloader please...

**Comment by zaps166** [comment]
> It would be nice to add an option for closing to system tray so that closing the window make it close to sytem tray instead of clicking on the tray icon to minimize the window.

Just press hotkey:
```
`
```

> It would be nice to display "lyrics not found" when the lyrics not found so that one don't wait some seconds thinkning that it is a network delay. 

Done already.

---

For opensubtitles, there's another issue open.
