### ISSUE TITLE
[feature request] enable window movement by dragging from inside the window

### ISSUE THREAD

**Issue by kn00tcn** [zaps166/QMPlay2#164]
it would be much more pleasing (also easier) to be able to drag the video screen itself instead of only by the titlebar

i would also enable it on other non-button parts of the window, such as the statusbar

**Comment by zaps166** [comment]
@kn00tcn Do you use Windows or macOS?

Most Linux WMs allow to move window with a key modifier :)

**Comment by kn00tcn** [comment]
i disable many hotkeys & sometimes it's mouse-only if using a television for example

several video players let you move them by the video area, it's very intuitive (though smplayer seems to do it at an awful framerate, not sure if that's intentional, hope it's not a qt issue)

maybe not as many image viewers do it, but looks like viewnior can be dragged by the toolbar or menubar

i dont know how much work it is to implement, especially multiplatform

**Comment by zaps166** [comment]
> viewnior can be dragged by the toolbar or menubar

I cant drag viewnior by toolbar/menubar.

---

> i dont know how much work it is to implement, especially multiplatform

I is not difficult, I can do it

**Comment by kn00tcn** [comment]
> I cant drag viewnior by toolbar/menubar.

![simplescreenrecorder-2018-03-22_22 52 47](https://user-images.githubusercontent.com/8087411/37809397-823a7b1c-2e25-11e8-999b-bb8d862a1ec1.gif)

if it's not difficult, then dragging from the video area specifically should be done as minimum, there are probably interference issues on other parts of the window (like how panels can be dragged & resized)

**Comment by zaps166** [comment]
Done.

---

My Viewnior (Arch/Manjaro official package, GTK2 BlueMenta style) can't be moved like yours :smile:

**Comment by kn00tcn** [comment]
> My Viewnior (Arch/Manjaro official package, GTK2 BlueMenta style) can't be moved like yours

that's so weird, also why is arch's 'upstream url' wrong? it's supposed to be http://siyanpanayotov.com/project/viewnior / https://github.com/hellosiyan/Viewnior

upon further testing, i can drag by menubar in other apps, even both gtk2 & gtk3 versions of gtkhash...  could it be compiz allowing moves? but i dont remember such an option, also funny thing is i just noticed i had hotkey moving enabled, so apparently i could alt+drag the whole time

**Comment by zaps166** [comment]
Patch reverted, after some fixes it worked properly on Windows, macOS and Linux with "normal" window manager (xfwm4, openbox), but on Compiz window jumps on entire screen, so it is not a good idea to have this.

**Comment by kn00tcn** [comment]
i thought i had good news, but looks like i misremembered, thought whisker-menu fixed a similar issue, but maybe compiz has to do something https://github.com/compiz-reloaded/compiz/issues/20

**Comment by zaps166** [comment]
I'll check this later, maybe there is a workaround. QMPlay2 18.04.01 is only a bugfix release, so it was better to not add new known bugs :smile:
