### ISSUE TITLE
[usability / bug] left mouse button pause has a long delay / fade sound not working?

### ISSUE THREAD

**Issue by kn00tcn** [zaps166/QMPlay2#165]
this doesnt seem right, pressing middle mouse is totally instant pausing & unpausing, but with that option enabled for the left mouse button, there is a delay until it actually pauses

is this caused by listening for double-click? but then how do other players like MPCHC do it, hmm... plus they drag with left click... maybe MPCHC pauses the video for miliseconds during a double click, it does feel more right compared to having a delay after a click

now i noticed my 'fade sound' option doesnt seem to work, i turned it off on the previous version due to the delay it caused, did it break?

i was thinking that fade would be better to fade audio, but keep the video frozen, so that you can resume from the part you paused on rather than a moment after the fade-out delay

**Comment by zaps166** [comment]
Pause with left click is delayed due to listening for double click. Otherwise you'll get pause while toggling full screen.

Audio fade on video is disabled now, because it annoyed me too much :smile:

**Comment by kn00tcn** [comment]
probably shouldnt delay it, the experience of the delay is worse (more stressful) than the minor pause when double clicking

fade makes more sense like i described, or just remove the option if it's been disabled

**Comment by zaps166** [comment]
Done
