### ISSUE TITLE
[Feature Request] support for shaders

### ISSUE THREAD

**Issue by killerjn** [zaps166/QMPlay2#167]
There is some possibility to include support for shaders
for example .hlsl or something similar like those used by the mpc
I'm not saying it's a copy of mpc
just be it  compatible with .hlsl type shaders
Would this be possible?
that would be the coolest thing in the world

**Comment by zaps166** [comment]
HLSL is not supported and won't be (it is DirectX).
I use GLSL which is already available, but every change requires software recompilation, because it is added as resource.
I assume that you want to use any shader by selecting a GLSL file, right?

**Comment by killerjn** [comment]
I did not know about hsls sorry
I do not know if there is a way to convert hlsl to glsl or something Similary

**Comment by zaps166** [comment]
So, GLSL can be loadable at runtime in the future, but HLSL not. You'll need to convert HLSL to GLSL manually.

**Comment by zaps166** [comment]
HLSL will not be supported. I'll think about GLSL custom shaders loaded by user.
