### ISSUE TITLE
thanks for the program

### ISSUE THREAD

**Issue by mrkaban** [zaps166/QMPlay2#169]
I just wanted to say thank you for a very high-quality program with translation into Russian and a license with an open source code! I added the program to my site, here's the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%BC%D1%83%D0%BB%D1%8C%D1%82%D0%B8%D0%BC%D0%B5%D0%B4%D0%B8%D0%B0/%D0%B2%D0%BE%D1%81%D0%BF%D1%80%D0%BE%D0%B8%D0%B7%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5/qmplay2-%D0%B2%D0%B8%D0%B4%D0%B5%D0%BE%D0%BF%D0%BB%D0%B5%D0%B5%D1%80.html).

**Comment by zaps166** [comment]
Thanks :)
