### ISSUE TITLE
Crash when selecting the 'Next' option while over a group folder

### ISSUE THREAD

**Issue by Chromace** [zaps166/QMPlay2#17]
If 'Next' is pressed, either from the button in the main toolbar or going to 'Player -> Next', and the current selection is on a group folder, QMPlay2 crashes.

In the terminal, the player reports this: 'Program się wysypał (SIGFPE)', if that's of any help.

Something like this:
![qmplay2-screen](https://cloud.githubusercontent.com/assets/16624211/15804882/901e1afa-2b5b-11e6-9272-6057195e75f8.png)
Then pressing the 'Next' button causes a crash. A crash also occurs even if the group is expanded.

**Comment by zaps166** [comment]
> Program się wysypał

I should change it into english :smiley:

> If 'Next' is pressed, either from the button in the main toolbar or going to 'Player -> Next', and the current selection is on a group folder, QMPlay2 crashes.

Can't reproduce following this steps. Which OS, which compiler, which version (or GIT SHA-1)? What should I do to reproduce (any special items on playlist, settings, etc.)?
And the most important: Which Qt version? Is is Qt 5 older than 5.6.1?

If your binaries aren't stripped you can run QMPlay2 through debugger and show the backtrace. SIGFPE probably means integer division by 0, but it can be outside QMPlay2...

```bash
gdb QMPlay2 #start QMPlay2
r #run it
bt #show backtrace after crash
```

**Comment by Chromace** [comment]
OS is Arch Linux. Compiler is GCC 6.1.1-1. QMPlay2 version from AUR, git version (16.06.03-1)? Qt 5 is older than 5.6.1 (5.6.0-7).

Steps to reproduce: Create a group in QMPlay2 (doesn't require adding files), then highlight it via a click. Click the fast forward/next button.

**Comment by zaps166** [comment]
So I've downgraded Qt 5.6-git + custom-patches to 5.6.0 from repo on my Arch (Manjaro/unstable) and still can't reproduce a crash.

Which style do you use?

Could you paste a backtrace from gdb?

**Comment by Chromace** [comment]
I apologise. I am unfamiliar with the word style. What is its meaning?

Backtrace from QMPlay2 rebuilt with debug options:
[Backtrace.txt](https://github.com/zaps166/QMPlay2/files/299332/Backtrace.txt)

**Comment by zaps166** [comment]
> word style

What is 'word style' :smile: ? I thought about Qt style :) But it is not important now, it shouldn't be caused by the style :smile:

Ok, thx for backtrace. I assume that you're using random playback, otherwise the code with division (modulo) won't be used. To be more accurate it is "Random in group (...)", right?

**Comment by zaps166** [comment]
Ok, I've got a crash

**Comment by zaps166** [comment]
"Random in group and repeat", introduced in commit 3f218c820a31c1e8a72fbe3c480568e1fd3e9763 - wrong condition in `PlaylistDock::next()` which causes division by 0.

**Comment by Chromace** [comment]
Apologies for the slow response. Yes, I'm using random in group and repeat.

**Comment by zaps166** [comment]
Thanks for the bug report!

**Comment by Chromace** [comment]
Happy to help. :)
