### ISSUE TITLE
Going fullscreen from undocked video panel results in black screen

### ISSUE THREAD

**Issue by parkerlreed** [zaps166/QMPlay2#170]
Arch
qmplay2-git 18.04.01-1 (18.04.01-git-c8e1d062)
Default settings

I undocked the video tab, started playing video, plays fine windowed, fulscreen is black, exiting fullscreen video continues to play fine in window.

**Comment by zaps166** [comment]
This happen sometimes, not always. Also when left panel will open, video became visible. Do you have the same results?

**Comment by zaps166** [comment]
I can't reproduce on Qt 5.12.2
