### ISSUE TITLE
Open YouTube links in plugin

### ISSUE THREAD

**Issue by notramo** [zaps166/QMPlay2#173]
Currently, when a YouTube URL is given to QMPlay, it try to open it directly. It should open it in the YouTube plugin instead.

**Comment by notramo** [comment]
@zaps166 Thank you!
Could you make a new release soon? https://github.com/void-linux/void-packages/pull/560

**Comment by zaps166** [comment]
I want to release QMPlay2 very soon

**Comment by zaps166** [comment]
Released!
