### ISSUE TITLE
How to get dependencies for Ubuntu 18.04?

### ISSUE THREAD

**Issue by cipricus** [zaps166/QMPlay2#175]
A deb file is available for Ubuntu 18.04. When trying to install, missing dependencies are reported:

```
dpkg: dependency problems prevent configuration of qmplay2:              
 qmplay2 depends on libcdio13; however:                                  
  Package libcdio13 is not installed.                                    
 qmplay2 depends on libva1; however:                                     
  Package libva1 is not installed.                                       
 qmplay2 depends on libva-x11-1; however:                                
  Package libva-x11-1 is not installed.                                  
 qmplay2 depends on libva-glx1; however:                                 
  Package libva-glx1 is not installed.                                   
 qmplay2 depends on libva-drm1; however:
  Package libva-drm1 is not installed.
 qmplay2 depends on libpcre16-3; however:
  Package libpcre16-3 is not installed.
```
Among all dependencies reported missing only libpcre16-3 is available.

libcdio13, libva1, libva-x11-1,  libva-glx1, libva-drm1 are not available, but  libva-x11-2, libva-drm2 are already installed, while libva-glx2 can be installed. Are these alternate/newer packages?

How to install these dependencies?

**Comment by N0rbert** [comment]
I confirm this issue on clean installation of your player on Ubuntu 18.04 LTS Bionic Beaver amd64:

```
$ uname -a
Linux bionic 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic

$ wget https://github.com/zaps166/QMPlay2/releases/download/18.04.01/qmplay2-ubuntu-amd64-18.04.01-1.deb

$ sudo apt install ./qmplay2-ubuntu-amd64-18.04.01-1.deb 
[sudo] password for mate: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'qmplay2' instead of './qmplay2-ubuntu-amd64-18.04.01-1.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 qmplay2 : Depends: libcdio13 but it is not installable
           Depends: libva1 but it is not installable
           Depends: libva-x11-1 but it is not installable
           Depends: libva-glx1 but it is not installable
           Depends: libva-drm1 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by zaps166** [comment]
QMPlay2 DEB was released before Ubuntu 18.04, so it might not be compatible. On Ubuntu 17.10 QMPlay2 works properly.

You can install QMPlay2 from sources or just unpack it from DEB and copy missing files from Ubuntu 16.04.

I'll add Ubuntu 18.04 support for next release.

**Comment by zaps166** [comment]
> A deb file is available for Ubuntu 18.04

It is available for Ubuntu from 16.04 to 17.10. `18.04.01` in DEB file name is QMPlay2 version :smiley:

**Comment by N0rbert** [comment]
You can see what packages are needed for 18.04 LTS in my [answer on AskUbuntu](https://askubuntu.com/a/1036046/66509) `libcdio13`, `libva`, `libva-x1`, `libva-glx`, `libva-drm1`. The problem is temporarily solved by installing these packages from 17.10 to 18.04 LTS.

**Comment by zaps166** [comment]
> But if you can, please prepare special version for 18.04 LTS with dependencies from its repository.

I don't use any automated tools for building Ubuntu package. It costs too much time to prepare package for every Ubuntu version.

In the future I want to use generic Linux package.

**Comment by zaps166** [comment]
Updated, please test: https://github.com/zaps166/QMPlay2/releases/download/18.04.01/qmplay2-ubuntu-amd64-18.04.01-2.deb
