### ISSUE TITLE
Ever-expanding Playlist

### ISSUE THREAD

**Issue by Connor84** [zaps166/QMPlay2#178]
![qmplay - playlist](https://user-images.githubusercontent.com/33960967/40618417-ab7ce8b8-624e-11e8-9ec1-3aa8fcd49b4d.png)

Every time I change the name of the playlist and re-save it, it creates a new sub-folder in QMPlay2's playlist.  Ideally there would be no folder showing at all, just the files.  However if there has to be a parent folder showing, it should only be the most recent name of it.

**Comment by zaps166** [comment]
Save a play list to e.g. PLS and then load it again?

**Comment by Connor84** [comment]
I don't understand what you mean.  I sometimes will save the PLS as a slightly modified name, and then load it at a later date.  This results in the ever-expanding nested-folder structure you see in the png.

**Comment by zaps166** [comment]
You can save the entire playlist or chosen group as playlist.
Loaded playlist will become a new group.

---

The only thing I can do is to not load playlists from directory with other songs - is it that what you want?

**Comment by zaps166** [comment]
Maybe this is a fix: https://github.com/zaps166/QMPlay2/commit/0da1403d53c4d96655df80fb782c1da2f6f92529
