### ISSUE TITLE
PGS multilanguage subtitles

### ISSUE THREAD

**Issue by dimitrissch** [zaps166/QMPlay2#179]
Hello and thanks for your awesome player!!
I have found an mkv with dual language subtitles in PGS format and QMPlay2 doesn't seem to have the option to cycle between them so it displays only the first in order subtitle track.

Some info about the subs : 
`Subtitle #1 
ID : 4 
Format : PGS 
Muxing mode : zlib 
Codec ID : S_HDMV/PGS 
Codec ID/Info : Picture based subtitle format used on BDs/HD-DVDs 
`
`
Subtitle #2 
ID : 5 
Format : PGS 
Muxing mode : zlib 
Codec ID : S_HDMV/PGS 
Codec ID/Info : Picture based subtitle format used on BDs/HD-DVDs `
tested on QMPlay2 18.04.01.

**Comment by zaps166** [comment]
Hi!

Is it possible to change subtitles track by clicking on stream on "Information" panel?

**Comment by dimitrissch** [comment]
Yes indeed it does.Thanks a lot!!
Since this handling is not exactly intuitive,maybe flag this as enhancement for future release?

**Comment by zaps166** [comment]
Done!
