### ISSUE TITLE
Hide cursor while audio file is playing?

### ISSUE THREAD

**Issue by Chromace** [zaps166/QMPlay2#18]
At the moment, QMPlay2 automatically hides the cursor while playing video files if it doesn't move after a few seconds. It would be aesthetically pleasing if it could extend this behaviour to other file types, such as audio.

**Comment by zaps166** [comment]
On full screen or also windowed mode?

**Comment by Chromace** [comment]
If it is possible, both? Basically just like video.

**Comment by zaps166** [comment]
It is possible, but I don't know why it is necessary? Does mouse cursor cover the CD-Cover which is displayed in VideoDock?

**Comment by Chromace** [comment]
Yes. The mouse cursor covers the album art a little. Putting it to the side partially works in full-screen, but not entirely. It's an aesthetic niggle.

![cursor](https://cloud.githubusercontent.com/assets/16624211/15901970/fa328f5e-2de8-11e6-8b1b-cd38b2e346e8.png)

**Comment by zaps166** [comment]
Ok, only when cover image is visible.

**Comment by zaps166** [comment]
@Chromace Is the patch working properly for you?

**Comment by Chromace** [comment]
Yes it is. Thank-you! :)

**Comment by zaps166** [comment]
Ok! :)
