### ISSUE TITLE
Context menu to find the file

### ISSUE THREAD

**Issue by Connor84** [zaps166/QMPlay2#181]
I would like to right click in the playlist on a file and have the option to goto where the file is stored.

**Comment by zaps166** [comment]
Do yo want to option to open system file browser with path to the file?

**Comment by Connor84** [comment]
Yes please.

(When I received the response emails from GitHub, there are three options listed at the bottom of the email: Reply to this email directly, view it on GitHub, or mute the thread.  I responded to each issue directly, but it appears that you did not receive the responses so I will post them on GitHub).

**Comment by zaps166** [comment]
Added to properties dialog, because context menu is already very long.
