### ISSUE TITLE
Expanded Cover Art for music files

### ISSUE THREAD

**Issue by Connor84** [zaps166/QMPlay2#183]
![qmplay album art](https://user-images.githubusercontent.com/33960967/40633393-b6cfa4cc-62ac-11e8-9991-caca06af5ae9.png)

I really dig that there some algorithm in QMPlay2 that colours **the background surrounding** the cover art based on the album cover itself.  However I would like the option (under settings) to expand the cover art to fill the whole video pane, rather than the tiny icon you see in this photo.

**Comment by zaps166** [comment]
Try to disable "Blurred covers as background" - you can have a little larger covers. If you have small cover it won't be resized to window (you'll lose the quality) - use large covers.

**Comment by Connor84** [comment]
Disabling "Blurred covers as background" did not enlarge the cover.  The covers are encoded in the mp3s and flac files.  To resize my entire music collection would be a monumental task.  I would be happy with losing visual quality in order for an option in the preferences to be able to expand the cover art to fill the window.  If some person is unhappy with losing quality in the cover art, they can just leave the box under the option "resize cover art to fill window" unchecked.

**Comment by nathan2423** [comment]
I have the same request and feeling about this as Connor 84.  In addition, if the larger cover is too blurry, we can always resize the window panel to make it not quite so large. But other programs (QMMP comes to mind) seem to be able to render my covers much larger than QMPlay2 with no real loss in video quality.  Thanks for the GREAT program!

**Comment by zaps166** [comment]
Done :)
