### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [zaps166/QMPlay2#184]
Hi @zaps166 . I'm graphic disigner. I would like to know if you are interested that I make a logo for your project? If you allowed me, i"ll make logo for your project.

**Comment by mirzazulfan** [comment]
Hi @zaps166 . I've designed a logo for your project, if you like it, you can use it, i'll send you files. Tell me if you need something else,,, i'll fix it. Thanks
![qmplay2](https://user-images.githubusercontent.com/36124339/41195990-95a51dea-6c61-11e8-92fc-0d4dfe76cf65.png)

**Comment by mirzazulfan** [comment]
How about this @zaps166 ? waiting your feedback..
![qmplay v2](https://user-images.githubusercontent.com/36124339/41703530-d4e7900a-755d-11e8-98d2-5bc16076167a.png)

**Comment by zaps166** [comment]
The last one is very good :+1:, but I'm not sure about changing the main icon (the only graphics in QMPlay2 which I made ~10 years ago, a long time before QMPlay2 :smile:)

Btw. Currently I have less time for QMPlay2

**Comment by mirzazulfan** [comment]
Good luck. If you need changing the main icon feel free to contact me. I'll make it for free. Especially for open source projects.
Email : mirzazulfan@gmail.com
Best Regard.
