### ISSUE TITLE
record played song or video

### ISSUE THREAD

**Issue by penguin31** [zaps166/QMPlay2#185]
would be great with some improvements :

- record a song that is playing by a radio station 
- record a piece of video that is playing by qmplay2.
- add editor to read radio stations (edit,move up and down, icon etc.)
- search possibility of station name on radio station list

**Comment by zaps166** [comment]
Record is not yet possible (it is my also TODO), but you can download e.g. radio stream (right click -> extensions -> download) :)

**Comment by lsjiaowo** [comment]
It's 2023, we still waiting for Record function :)

**Comment by blzos** [comment]
> but you can download e.g. radio stream (right click -> extensions -> download) :

Indeed, this function works, but unfortunately the capture begins from the moment you click “download”. Those some of the data that I saw before and liked will not be recorded.

I propose to expand the capabilities of the player with the following function. When you click the "capture" button, the buffered data (video, audio), as well as incoming data, is now written to a file TS (for video stream). The function can be implemented through a button in the Information window (see picture), through the context menu, and by pressing a specific button (Rec/Stop)

![QM-CaptureStream](https://github.com/zaps166/QMPlay2/assets/166966429/6c2a5d7d-20fb-47c1-a950-d2a8dfb7698f)


**This function is especially relevant for video streams, since some video data is unique and you want to have a kind of “time machine” to capture this data! (HLS stream)** 

*_Then, in the any editor, trim it as needed._
**_By default, use the "Download directory" folder to capture_
***_You can see the implementation of the function in the Potplayer by clicking Ctrl+A_

**Comment by zaps166** [comment]
Ok, I need to mux data from all choosen streams buffers into MKV before decoding them and finally save to the file.

**Comment by blzos** [comment]
> Ok, I need to mux data from all choosen streams buffers into MKV before decoding them and finally save to the file.

By the way, when you click the "Download" button, the player opens a separate stream to receive data, even if this stream is currently being played.In our case, we need to think about how to implement recording the data that we are already we get at the moment, accumulating them in RAM, and when pressing the “STOP” button, place it in a file container MKV or TS.

The diagram is given below:

![QM-CaptureStream2](https://github.com/zaps166/QMPlay2/assets/166966429/b81b4fbb-f61d-43bc-924e-df9fad720a9c)

**Comment by lsjiaowo** [comment]
Wow, thank you for still focus on this Record function, I'm waiting for the update!

**Comment by zaps166** [comment]
I don't think I'll do it for upcoming release, but I'll work on this soon.

**Comment by zaps166** [comment]
Should it record what is really playing right now (record at playback position, pause record on pause, etc) or record all forward buffered data (where the buffer indicator is)?

**Comment by blzos** [comment]
> I don't think I'll do it for upcoming release, but I'll work on this soon.

It is clear that the implementation of such a function will take time. But now not a single Linux player has such a function.

> Should it record what is really playing right now (record at playback position, pause record on pause, etc) or record all forward buffered data (where the buffer indicator is)?

Of course, record data from the buffer in real time, even if playback is paused (variant 2). The task is to save the stream that was 125 seconds ago and the one that comes after, until the recording stops. If you press pause in the Potplayer while capturing a stream, the current stream will continue to be recorded. If you stop playing a stream (close the file - F4), recording the stream stops. However, there is also a separate button that stops capturing the stream into a file, and the playback itself continues.

The point is that the buffer is 125 seconds long, and the fragment to be captured can be longer, for example 4-5 minutes. Potplayer does this: when you press the “capture” button, it writes the buffer to a file on the disk (Buffer size 100Mb ~2-3 min FHD video), and then adds the data received from the network to the same file in small portions.

**Comment by zaps166** [comment]
Ok, another questions:
- recording from local files - doesn't make any sense, right?
- recording non-live stream network data - this should be possible, too?

**Comment by blzos** [comment]
> Ok, another questions:
> 
> * recording from local files - doesn't make any sense, right?

Recording local data from files is not necessary. The recording option is simply not available.

> * recording non-live stream network data - this should be possible, too?

No, only current stream, "stream capture" (CURRENT)
To capture a stream outside the current broadcast, there is a download button (Extensions)

Related issue: https://github.com/zaps166/QMPlay2/issues/573

**Comment by zaps166** [comment]
Done, but there are still things which should be done in the future:
- icon in Information panel
- avoid MKV for simple recording scenarios (like MP3 radio)
- fix bugs (it's obvious)

**Comment by jediafr** [comment]
Thanks for QMplay2, great and versatile tool, i use it to listen to my SID et MOD songs but i'd like to record them in wav or ogg or MP3 would it be possible within QMplay2 ? (hence recording local files can be useful) ?

**Comment by zaps166** [comment]
> Thanks for QMplay2, great and versatile tool, i use it to listen to my SID et MOD songs but i'd like to record them in wav or ogg or MP3 would it be possible within QMplay2 ? (hence recording local files can be useful) ?

Done.
