### ISSUE TITLE
Fullscreen playlist fails to completely leave screen after toggled

### ISSUE THREAD

**Issue by EpicureanGit** [zaps166/QMPlay2#186]
I really love QMPlay2 and its the best media player I've come across. I recently updated my Plasma 5 and my qt to qt5-5.9.6-x86_64-1alien for Slackware64 Current. It produces this error in full screen when toggling the playlist on the side of the screen with the mouse. I can use the handle on the side of the playlist and make a small adjustment on my 2nd monitor and move the mouse onto my first monitor and the error goes away until I toggle it again with a mouse hover.

My QMPlay2 version is QMPlay2-18.04.01-x86_64. I built it myself using SlackBuild's script and repository.

![qmplay2 plasma 5 error](https://user-images.githubusercontent.com/40360919/41540970-54eb2c84-72df-11e8-82a4-1343b06a0697.png)

Also there is a minor issue I've come across with the binary NVIDIA drivers released since last Fall but its not a big deal. The first video played will freeze the computer for a second at the start of it on a GTX 960 and GTX 1070. I can close the application and restart it and it doesn't do it again unless I reboot. Playback top priority is set to XVideo (then OpenGL), ALSA, and CUVID decoder (then VDPAU).

**Comment by zaps166** [comment]
Could you paste me `xrandr` output? Do you use HiDPI mode (Device Pixel Ratio > 1.0 on one or both screens)?

---

> Also there is a minor issue I've come across with the binary NVIDIA drivers released since last Fall but its not a big deal.

If you use CUVID as first video decoder, it is nvidia drivers bug. CUVID uses CUDA and it loads very slow at first time. I can confirm that it didn't happen a few months ago with older drivers.

**Comment by EpicureanGit** [comment]
Thank you the reply zaps166!

bash-4.4$ xrandr 
Screen 0: minimum 8 x 8, current 7680 x 2160, maximum 32767 x 32767
DVI-D-0 connected 1920x1200+5760+480 (normal left inverted right x axis y axis) 518mm x 324mm
   1920x1200     59.95*+
   1920x1080     60.00  
   1680x1050     59.95  
   1600x1200     60.00  
   1280x1024     60.02  
   1280x960      60.00  
   1024x768      60.00  
   800x600       60.32  
   640x480       59.94  
HDMI-0 disconnected (normal left inverted right x axis y axis)
DP-0 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
DP-2 connected primary 3840x2160+1920+0 (normal left inverted right x axis y axis) 698mm x 393mm
   3840x2160     60.00*+  59.94    50.00    29.97    25.00    23.98  
   2560x1440     59.95  
   1920x1080     60.00    59.94    50.00  
   1680x1050     59.95  
   1440x900      59.89  
   1280x1024     60.02  
   1280x960      60.00  
   1280x800      59.81  
   1280x720      60.00    59.94    50.00  
   1024x768      60.00  
   800x600       60.32    56.25  
   720x576       50.00  
   720x480       59.94  
   640x480       59.94    59.93  
DP-3 disconnected (normal left inverted right x axis y axis)
DP-4 connected 1920x1200+0+480 (normal left inverted right x axis y axis) 518mm x 324mm
   1920x1200     59.95*+
   1920x1080     60.00  
   1680x1050     59.95  
   1600x1200     60.00  
   1440x900      59.89  
   1280x1024     60.02  
   1280x800      59.81  
   1280x720      60.00  
   1024x768      60.00  
   800x600       60.32  
   640x480       59.94  
DP-5 disconnected (normal left inverted right x axis y axis)

I don't think I am using HiDPI mode. Plasma 5 display settings say scaling is set to 1.

bash-4.4$ xdpyinfo | grep -B 2 resolution
screen #0:
  dimensions:    7680x2160 pixels (2055x578 millimeters)
  resolution:    95x95 dots per inch

I hope NVIDIA fixes that bug and doesn't introduce more of them. I happened upon QMPlay2 looking for a stable video player with good performance and a good playlist setup. CUVID has worked great for my hardware.

**Comment by zaps166** [comment]
Could you try with:
```
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_SCALE_FACTOR=1
QMPlay2
```

Does it help?

**Comment by EpicureanGit** [comment]
I tried it and no it doesn't help. 

The rectangular playlist box that contains the handles along its side remains on screen. The handle sometimes stay visible for the divider between the Information, Youtube, MediaBrowser section, and the playlist after I stop hovering the mouse over the panel. There is a point to where I move my mouse towards the QMPlay2 logo where the contents of the playlist and information tab are still visible but they disappear when the playback bar at the bottom disappears, leaving the box with handles. They comeback when the playback bar comes back after I mouse hover over the box with handles again.

**Comment by zaps166** [comment]
Thanks for explanation. I'll try to reproduce it later (1 AM here :D).

**Comment by EpicureanGit** [comment]
Here are screenshots showing what happens based on mouse position.
![qmplay2 mouse playlist](https://user-images.githubusercontent.com/40360919/41577473-f38763fa-735a-11e8-8cb3-124f29ccb0ae.jpeg)
![mouse outside playlist](https://user-images.githubusercontent.com/40360919/41577479-fa81450e-735a-11e8-966a-fb9760cfcb79.jpeg)
![qmplay2 playlist disappears](https://user-images.githubusercontent.com/40360919/41577483-ff49f73e-735a-11e8-9246-b35d0b31d397.jpeg)
![qmplay2 mouse on playback bar](https://user-images.githubusercontent.com/40360919/41577485-02f3d2f6-735b-11e8-90d5-9bc775808ffd.jpeg)

**Comment by zaps166** [comment]
I can't reproduce. I know that I had some issues with two screens in Qt 5.9 or 5.10 (I don't remember, maybe both). Now I have Qt 5.11.0 and no issues so far. Could you try with Qt 5.11.0?

**Comment by EpicureanGit** [comment]
Qt 5.11.0 works fine so its definitely a new feature introduced in Qt 5.9.6!

**Comment by zaps166** [comment]
Ok, so it is a Qt bug...
