### ISSUE TITLE
QMPlay2 not seen styles

### ISSUE THREAD

**Issue by varlesh** [zaps166/QMPlay2#189]
QMPlay2 not seen Breeze, Oxygen and Kvantum styles on settings. Available only:
- Windows
- GTK+
- Fusion

Distro: **KDE Neon (Ubuntu 16.04)**
DE: **Plasma 5.13.2**
QMPlay2: **18.04.1**

System styles:
![image](https://user-images.githubusercontent.com/8083855/41936822-81ab8b44-799f-11e8-98c6-0d4e6e27005f.png)
on QMPlay2:
![image](https://user-images.githubusercontent.com/8083855/41936862-a34948d6-799f-11e8-961c-aafaa4222f18.png)

**Comment by zaps166** [comment]
Hmmm, did you install QMPlay2 from my DEB package?

**Comment by varlesh** [comment]
yes... also i'm try other versions QMPlay2 **17.12.31 - 18.04.01**. But styles not available...
LOG form terminal is empty and from home too `~/.qmplay2/QMPlay2.log`

**Comment by varlesh** [comment]
if i'm change option on `QMPlay2.ini` to  `Style=breeze` > anyway used fusion style.

**Comment by zaps166** [comment]
QMPlay2 from my DEB package won't use system styles, sorry. It is not possible, because inside the package I have included patched Qt 5.6.3 which won't load KDE styles (other file paths, incompatible library versions).

At least (except manual QMPlay2 compilation) you can try to manually remove my Qt 5.6 compilation from `/opt/QMPlay2/...` directory - maybe it'll run with your system Qt5 (but you need Qt 5.6 or higher)... Which Qt version do you have is your OS?

**Comment by varlesh** [comment]
Thx for info Błażej, yes it's worked. I'm remove all Qt libs from QMPlay2 directory:
`rm /opt/QMPlay2/lib/libQt5*`
On KDE Neon usedf higher Qt version (than on Ubuntu) - now Qt 5.11

**Comment by zaps166** [comment]
Ok, so problem solved :)

**Comment by varlesh** [comment]
now all fine :)
![image](https://user-images.githubusercontent.com/8083855/41939789-d920f38e-79a7-11e8-957b-2adb630c63fd.png)

**Comment by cipricus** [comment]
Is there a deb package for later versions like 22.08? In the appimage version only Fusion and Windows styles are available. I'm in Kubuntu and I don't like to see this great player looking so drab in Plasma.

**Comment by cipricus** [comment]
This should be reopened, there are no deb files available as before. 

I have found some in a MX Linux repo [here](http://mxrepo.com/mx/repo/pool/main/q/qmplay2/), but they cannot be installed in my version of Linux (Kubuntu 22.10):

```
Depends: libavcodec58 (>= 7:4.0) but it is not installable
           Depends: libavdevice58 (>= 7:4.0) but it is not installable
           Depends: libavformat58 (>= 7:4.1) but it is not installable
           Depends: libavutil56 (>= 7:4.0) but it is not installable
           Depends: libcdio18 (>= 2.0.0) but it is not installable
           Depends: libsidplayfp4 but it is not installable
           Depends: libswresample3 (>= 7:4.0) but it is not installable
           Depends: libswscale5 (>= 7:4.0) but it is not installable
```

I think I have more recent versions: 

![image](https://user-images.githubusercontent.com/3447868/208886946-00380f4d-0135-40a8-89ff-49ee6f74f2d3.png)

**Comment by zaps166** [comment]
try:
- unpack AppImage - run QMPlay2 with `--appimage-extract`
- open unpacked directory
- remove all Qt libs and Qt plugins directories
- start QMPlay2 from unpacked directory (install required Qt 5 >= 5.15.2 64-bit libs in your system)

**Comment by cipricus** [comment]
> try:
> 
>     * unpack AppImage - run QMPlay2 with `--appimage-extract`
> 
>     * open unpacked directory
> 
>     * remove all Qt libs and Qt plugins directories
> 
>     * start QMPlay2 from unpacked directory (install required Qt 5 >= 5.15.2 64-bit libs in your system)

After deleting these files in the `lib` directory:

![image](https://user-images.githubusercontent.com/3447868/209410695-b16254d1-b8fc-43f0-b3cd-51940e6dd4a3.png)

the players starts but freezes and hen crashes if started from unpacked directory when clicking "Settings".

I don't know what to delete in `plugins` directory...

**Comment by zaps166** [comment]
Remove:
- `usr/lib/libQt*.so.5` files
- `usr/bin/qt.conf` file
- `usr/plugins` directory

Run `AppRun`. Be sure you have Qt5 >= 5.15.2 installed in your system with all required components. It works on my Manjaro Linux.

**Comment by cipricus** [comment]
> Remove:
> 
>     * `usr/lib/libQt*.so.5` files
> 
>     * `usr/bin/qt.conf` file
> 
>     * `usr/plugins` directory
> 
> 
> Run `AppRun`. Be sure you have Qt5 >= 5.15.2 installed in your system with all required components. It works on my Manjaro Linux.

This works perfectly in Kubuntu 22.10 too! Thank you for your concern!
Great player! All the best!

**Comment by cipricus** [comment]
The solution works after I have updated to Kubuntu daily 23.04.
