### ISSUE TITLE
CMake Build System

### ISSUE THREAD

**Issue by arthurzam** [zaps166/QMPlay2#19]
Firstly I want to thank you for this excellent application.
I wanted to ask your thoughts on adding CMake building script to this project. I think it will make it easier to manage cross-platform building. The *.pro files can still remain (it is a little easier to work with them while using QtCreator).
Another advantage for this approach is easier packaging and building for the various Linux Distributions (for Windows and Mac it won't be a big difference).
If you support this idea, I can help by writing the CMake files and send a pull request.

**Comment by zaps166** [comment]
CMake is good idea, but I don't know its script. Please do a PR, then we can work on this (Linux only, OS X and Windows can still use qmake, my Windows build scripts uses qmake) :)

**Comment by arthurzam** [comment]
OK, thank you.
I will start it now.

**Comment by zaps166** [comment]
@arthurzam Many thanks, merged!

**Comment by zaps166** [comment]
> The *.pro files can still remain (it is a little easier to work with them while using QtCreator).

Pro files are still necessary, but with QtCreator 4.0 I think that CMake works very well or maybe better than `*.pro` files (I've got RPATH automatically, so no need to set `LD_LIBRARY_PATH` on every change of Release/Debug and I've got the progress of compilation) - thanks for CMake build system for QMPlay2!

**Comment by arthurzam** [comment]
Using CMake on QtCreator 4.0 is still a hassle. You can't add new files. You need to manually create a file in the needed location and list the file in the CMake file. But other than that it is nearly the same as with pro files. It has great potential, and QtCreator devs are continuing to improve the CMake support.

I'm happy to help :) This program is very useful (I prefer watching Youtube using QMPlay2 than using my browser, and it is an excellent video player and the best - it's size is less than 3 MB on my system).

**Comment by zaps166** [comment]
> You can't add new files. You need to manually create a file in the needed location and list the file in the CMake file.

In QMPlay2 I'm creating files manually very often :smiley:

> This program is very useful

Thanks!
