### ISSUE TITLE
something's horribly wrong with the widgets, possible QT issue

### ISSUE THREAD

**Issue by kn00tcn** [zaps166/QMPlay2#190]
right now, the video area takes up half of the window, or other awkward positions on the top or right side, i try to drag, it looks ok, reopen the player & it's messed up again, fullscreen may or may not be ok until mousing over the left side to show the info area, then the video area is condensed

i dont think it's the qmplay 18.04 version since that updated longer ago, it must be the QT 5.9.6 update?

**Comment by zaps166** [comment]
This is not a first Qt 5.9.6 issue, so maybe it is Qt 5.9.6 bug.

**Comment by zaps166** [comment]
I'll try to compile and check Qt 5.9.6 for curiosity :smile:

**Comment by zaps166** [comment]
The same issue as #186

---

Qt 5.9.5 is OK, 5.9.6 and upcomming 5.9.7 (5a8b2e1bb0) are broken.

> Going forward Qt 5.9 continues to receive important bug fixes and significant performance fixes during the ‘Strict’ phase. 

Hmmm.... :cry: Nowadays libraries becomes very unstable, unfortunately. Even if the third minor number is "6"...

**Comment by zaps166** [comment]
Please don't use Qt 5.9.6. Maybe I should create a patch for Qt or report a bug... Hopefully Qt 5.11.1 works fine :)

**Comment by kn00tcn** [comment]
ok, but the distro did it

well, more specifically it seems this version of the distro is on 5.9 series while the next version is 5.10 (distro has two overlapping OS versions, current version goes out of support in a few months anyway)

makes me wonder about other distros, especially LTS ones

**Comment by zaps166** [comment]
This patch caused issue: https://codereview.qt-project.org/#/c/209128/. I think it is a Qt bug, but I'll investigate later.

**Comment by kn00tcn** [comment]
fixed

* Wed Jun 27 2018 Rex Dieter <rdieter@fedoraproject.org> - 5.9.6-3 - pull in candidate fix for QTBUG-68939

* Wed Jun 27 2018 Rex Dieter <rdieter@fedoraproject.org> - 5.9.6-2 - revert commit causing layout regressions (QTBUG-68939)
