### ISSUE TITLE
Built 18.07.03 packages, but "about" dialog shows 18.05.14

### ISSUE THREAD

**Issue by stevenpusser** [zaps166/QMPlay2#193]
issue in title. :(

Patched the version.cpp and Changelog, but should be fixed.

**Comment by zaps166** [comment]
Where did you get the code from?

**Comment by zaps166** [comment]
Maybe you should pull git tags again, because git tag has been set incorrectly after release and fixed soon after.

`.tar.xz` archive from "releases" section (which should be used) is correct.
