### ISSUE TITLE
White Video Output Using OpenGL 3.0 VA-API

### ISSUE THREAD

**Issue by Chromace** [zaps166/QMPlay2#194]
QMPlay2 (18.07.03-git-32d76758) currently displays a completely white screen when attempting to play videos using the FFmpeg VA-API Decoder, with the Modules > FFmpeg > Decoder VAAPI - hardware decoding > Use OpenGL option enabled.

This problem is only seen with this option checked. With "Use OpenGL" disabled, VA-API video output displays media normally. All other options inside the "Decoder VAAPI - hardware decoding" section do not affect these results.

**FFmpeg/VA-API, OpenGL 3.0 VA-API**
![va-api opengl](https://user-images.githubusercontent.com/16624211/42305921-6fe30e1e-8070-11e8-9035-85dc492a91f4.png)

**FFmpeg/VA-API, VA-API**
![va-api](https://user-images.githubusercontent.com/16624211/42305931-7453ae68-8070-11e8-82e6-cc4d43fc732f.png)

**Comment by zaps166** [comment]
Which OS, FFmpeg version, driver and Mesa version?

**Comment by zaps166** [comment]
IMHO it is a driver BUG. I use va-glx (`vaCreateSurfaceGLX` and `vaCopySurfaceGLX`) for VA-API/OpenGL which might have a bug. Another attempt to use VA-API with OpenGL (e.g. what Kodi does) works.

On PC i7-8700k works always OK, but on notebook i7-6700HQ + nvidia I also have white screen and/or X11 freeze by default. Place this config file in `/etc/X11/xorg.conf.d` (e.g. `10-intel.conf`), it fixes white video and/or X11 freeze for me:
```
Section "Device"
	Identifier "Intel"
	Driver "intel"
EndSection
```
You can also set other drivers options.

**Comment by Chromace** [comment]
Let's see...I'm currently using Arch Linux (4.17.3-1-ARCH), FFMpeg is at version 4.0.1, Mesa is at 18.1.3. Apologies, could you please clarify what driver version I ought to retrieve please?

I will test the configuration file after installing the relevant driver (xf86-video-intel, I believe), and report my findings!

**Comment by zaps166** [comment]
Do you have notebook or PC? Do you have nvidia in your computer? I use very similar software configuration (ffmpeg, mesa, etc.) and the config file which I pasted is used, video works properly (no white screen) - but dunno why :smile:

**Comment by Chromace** [comment]
I'm using a notebook at the moment; there is only Intel's integrated graphics on it (HD 3000). It does, however, appear to be a driver problem. I installed xf86-video-intel onto my system, added the configuration file you recommended and rebooted. Previously, I was using the recommended modesetting driver for the graphics.

![new driver](https://user-images.githubusercontent.com/16624211/42425444-fcec4742-8360-11e8-89e0-809e904f9c4a.png)
