### ISSUE TITLE
No CUVID with NVIDIA 396.45 binary blob

### ISSUE THREAD

**Issue by EpicureanGit** [zaps166/QMPlay2#195]
QMPlay2 does not use CUVID with the new Short Lived Branch 396.45 NVIDIA binary driver. CUVID decoder is set to top priority in Settings. The 396.24 NVIDIA binary driver works fine. I hope NVIDIA isn't taking CUVID away because it worked so well.

**Comment by EpicureanGit** [comment]
The driver should be properly installed. I use the .run file and --uninstall the old driver and then use the run file to install the new driver. I've gone back and forth between the 396.24 and 396.45 drivers this way. The 396.24 driver loads nvidia_uvm module and it works fine with CUVID. The 396.45 driver does not load nvidia_uvm unless I use modprobe. CUVID doesn't work after nvidia_uvm is loaded with the 396.45 driver. Videos that did use CUVID are defaulting to VDPAU (2nd highest in priority) with the 396.45 driver.

Before modprobe with the 396.45 driver:
bash-4.4$ lsmod | grep nvidia
nvidia_drm             45056  8
nvidia_modeset       1093632  20 nvidia_drm
nvidia              14061568  925 nvidia_modeset
drm_kms_helper        192512  1 nvidia_drm
drm                   425984  11 drm_kms_helper,nvidia_drm
ipmi_msghandler        45056  2 ipmi_devintf,nvidia
i2c_core               73728  5 drm_kms_helper,nvidia,i2c_i801,i2c_dev,drm

After modprobe with the 396.45 driver:
bash-4.4# modprobe nvidia_uvm
bash-4.4# lsmod | grep nvidia
nvidia_uvm            909312  0
nvidia_drm             45056  8
nvidia_modeset       1093632  20 nvidia_drm
nvidia              14061568  926 nvidia_uvm,nvidia_modeset
drm_kms_helper        192512  1 nvidia_drm
drm                   425984  11 drm_kms_helper,nvidia_drm
ipmi_msghandler        45056  2 ipmi_devintf,nvidia
i2c_core               73728  5 drm_kms_helper,nvidia,i2c_i801,i2c_dev,drm

**Comment by zaps166** [comment]
I fixed one CUVID bug which happens with FFmpeg 4.0 (https://github.com/zaps166/QMPlay2/commit/1808f3a99fa6581c672eae3a698af2f5d9296524), but probably it is not your issue. I'll install drivers from nvidia official installer (396.45 works fine from Manjaro repository).

**Comment by zaps166** [comment]
> I hope NVIDIA isn't taking CUVID away because it worked so well.

Everything is working properly :) I installed manually `NVIDIA-Linux-x86_64-396.45.run` and I don't have any problems with CUVID (if you use FFmpeg 4.0 use QMPlay2 from GIT with https://github.com/zaps166/QMPlay2/commit/1808f3a99fa6581c672eae3a698af2f5d9296524 patch).

---

Which Linux distribution do you use? Is it x86-64? Could you locate `libcuda.so` file from old and new drivers?

**Comment by EpicureanGit** [comment]
Thank you for checking. I'm sorry for wasting your time on this.  I'm using Slackware64 Current with multilib and Plasma 5. I'm using FFMPEG 3.4.4. 

bash-4.4# locate libcuda.so
/usr/lib/libcuda.so
/usr/lib/libcuda.so.1
/usr/lib/libcuda.so.396.45
/usr/lib64/libcuda.so
/usr/lib64/libcuda.so.1
/usr/lib64/libcuda.so.396.45

bash-4.4# ls -l /usr/lib64/libcuda.so
lrwxrwxrwx 1 root root 12 Jul 23 14:11 /usr/lib64/libcuda.so -> libcuda.so.1
bash-4.4# ls -l /usr/lib64/libcuda.so.1
lrwxrwxrwx 1 root root 17 Jul 23 14:11 /usr/lib64/libcuda.so.1 -> libcuda.so.396.45
bash-4.4# ls -l /usr/lib64/libcuda.so.396.45 
-rwxr-xr-x 1 root root 14074072 Jul 23 14:11 /usr/lib64/libcuda.so.396.45

**Comment by zaps166** [comment]
Do you have 64-bit QMPlay2?
Check `ldd /usr/lib64/libcuda.so` - is everything OK?

What about other CUVID or CUDA software?

**Comment by EpicureanGit** [comment]
Yes I am using QMPlay2 64-bit.

bash-4.4# ldd /usr/lib64/libcuda.so
        linux-vdso.so.1 (0x00007ffdb8dfe000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f3b541dc000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f3b53df2000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f3b53bee000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f3b539cf000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f3b537c7000)
        libnvidia-fatbinaryloader.so.396.45 => /usr/lib64/libnvidia-fatbinaryloader.so.396.45 (0x00007f3b5357b000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f3b554f2000)

Blender shows an error. I am using the official binary package provided by Blender. Cycles doesn't show CUDA in User Preferences and it did with the 396.24 NVIDIA driver.

bash-4.4$ blender
Read prefs: /home/epicurean/.config/blender/2.79/config/userpref.blend
found bundled python: /opt/blender/2.79/python
CUDA cuInit: Unknown error

**Comment by EpicureanGit** [comment]
I was looking at the NVIDIA forum and came across a thread with Slackware users having problems with CUDA in the latest NVIDIA driver releases. I'm going to report this to Slackware's maintainer. https://devtalk.nvidia.com/default/topic/1037521/linux/cuda-broken-in-396-24-02-and-396-24-10-vulkan-beta-drivers-on-linux/

**Comment by zaps166** [comment]
Ok, I don't have any idea (it works on my OS). I hope the issue will be solved :)
