### ISSUE TITLE
[Feature request] YouTube search options and ordering

### ISSUE THREAD

**Issue by parkerlreed** [zaps166/QMPlay2#20]
I understand the main use for the YouTube plugin is for playing music. My use tends to be following certain users and watching latest uploads. A user/channel search and sort options (date/rating/etc) would be great to have.

**Comment by zaps166** [comment]
Yeah, YouTube browser needs improvements :) But this means a lot of work especially because that I'm not using the YouTube API. I don't know when all features will appear...

Currently you can search by title, see which user uploads the video (checkbox in settings), load YouTube playlists, watch 360° movies in sphere (OpenGL only) and watch 60FPS up to 8k movies (change it in settings).

Maybe add a scripting language (Lua?) for such extensions like YouTube, etc... ? Then everyone will able to write an extension using the scripting language and QMPlay2 API and share it somewhere.

**Comment by zaps166** [comment]
Sorting by date is available in settings.

**Comment by parkerlreed** [comment]
Is this a new addition?

**Comment by zaps166** [comment]
> Is this a new addition?

Yes, initially it was fa7d1f5f5574dea95c07d56c214574bc3b783952, but now I improved this in e62c6db1fb06150753fd39f46c2e6215836a146d (all YouTube sorting: relevance, date, views, rating).

**Comment by parkerlreed** [comment]
Ahh cool. I'll test it out right now! :D

**Comment by parkerlreed** [comment]
Ok so I can test my use case at least: Is there a search operator for say channel/username?

I see the date options and those seem to work great.

**Comment by zaps166** [comment]
> channel/username

Not implemented, it needs much changes.

**Comment by parkerlreed** [comment]
Ok no worries. I'll let you close this out of needed. Thanks for all the help!

**Comment by parkerlreed** [comment]
Better late than never :D 

Been meaning to get around to checking out the new changes. I've noticed the git package updating a few times.

**Comment by zaps166** [comment]
> I've noticed the git package updating a few times.

AUR?

**Comment by parkerlreed** [comment]
Yeah. I use yay so it checks upstream directly for updates :)

**Comment by zaps166** [comment]
Ok, `qmplay2-git` package is now updated :)

**Comment by parkerlreed** [comment]
Oh that's the cool thing. At least yay checks the git hashes and not the actual PKGBUILD (Unless there is a PKGBUILD update). 

Good to have for the helpers that don't have that behavior though!

**Comment by parkerlreed** [comment]
Oh I meant to ask, any update on if the YouTube plugin will be able to do user/channel search? I still tend to search for a user's video and sort by date rather than searching for words in titles.

**Comment by zaps166** [comment]
You want to search by user name or channel name? Or something more complicated ?

**Comment by parkerlreed** [comment]
Search by user/channel name and get the video list back that can then be sorted by date for example. Just a nice quick way to see and watch latest uploads.

**Comment by zaps166** [comment]
Is it possible to do it on youtube website?

**Comment by parkerlreed** [comment]
If you just mean in general then yeah. Channel page > videos https://www.youtube.com/user/Google/videos

If you use the API then there's a function for that too 

```
https://www.googleapis.com/youtube/v3/search?key={your_key_here}&channelId={channel_id_here}&part=snippet,id&order=date&maxResults=20
```

So it would need the unique channel ID first and then it could list videos

For example here's the json returned for my channel

```
{
 "kind": "youtube#searchListResponse",
 "etag": "\"8jEFfXBrqiSrcF6Ee7MQuz8XuAM/VjsLEw7BxX45RcUd-stg6yFx5yo\"",
 "nextPageToken": "CAUQAA",
 "regionCode": "US",
 "pageInfo": {
  "totalResults": 647,
  "resultsPerPage": 5
 },
 "items": [
  {
   "kind": "youtube#searchResult",
   "etag": "\"8jEFfXBrqiSrcF6Ee7MQuz8XuAM/Z5jZIrRKyr7uZoUD1Ag8do5wkXE\"",
   "id": {
    "kind": "youtube#video",
    "videoId": "VUmjEs0jEZI"
   },
   "snippet": {
    "publishedAt": "2019-08-21T02:24:58.000Z",
    "channelId": "UCe8XucXL8gVEwzvmfHM6nBA",
    "title": "Dude on Tinder in the middle of a concert",
    "description": "Literally in the middle. Who the crap holds up their phone for that? RIP my recording of a great song. 1:20 for cringe. And yes he does that for most of the song.",
    "thumbnails": {
     "default": {
      "url": "https://i.ytimg.com/vi/VUmjEs0jEZI/default.jpg",
      "width": 120,
      "height": 90
     },
     "medium": {
      "url": "https://i.ytimg.com/vi/VUmjEs0jEZI/mqdefault.jpg",
      "width": 320,
      "height": 180
     },
     "high": {
      "url": "https://i.ytimg.com/vi/VUmjEs0jEZI/hqdefault.jpg",
      "width": 480,
      "height": 360
     }
    },
    "channelTitle": "Parker Reed",
    "liveBroadcastContent": "none"
   }
  },
  {
   "kind": "youtube#searchResult",
   "etag": "\"8jEFfXBrqiSrcF6Ee7MQuz8XuAM/ckdiKjeAQy8VZEC4Q4zUnFOgXVg\"",
   "id": {
    "kind": "youtube#video",
    "videoId": "7JTG2YKsyWs"
   },
   "snippet": {
    "publishedAt": "2019-08-15T01:02:57.000Z",
    "channelId": "UCe8XucXL8gVEwzvmfHM6nBA",
    "title": "My speaker setup",
    "description": "",
    "thumbnails": {
     "default": {
      "url": "https://i.ytimg.com/vi/7JTG2YKsyWs/default.jpg",
      "width": 120,
      "height": 90
     },
     "medium": {
      "url": "https://i.ytimg.com/vi/7JTG2YKsyWs/mqdefault.jpg",
      "width": 320,
      "height": 180
     },
     "high": {
      "url": "https://i.ytimg.com/vi/7JTG2YKsyWs/hqdefault.jpg",
      "width": 480,
      "height": 360
     }
    },
    "channelTitle": "Parker Reed",
    "liveBroadcastContent": "none"
   }
  },
  {
   "kind": "youtube#searchResult",
   "etag": "\"8jEFfXBrqiSrcF6Ee7MQuz8XuAM/6sDydBfE9YPz96kAdLRuxWtICYA\"",
   "id": {
    "kind": "youtube#video",
    "videoId": "Ib7wP0fwXYQ"
   },
   "snippet": {
    "publishedAt": "2019-07-19T00:34:42.000Z",
    "channelId": "UCe8XucXL8gVEwzvmfHM6nBA",
    "title": "Discord notifications on char display",
    "description": "",
    "thumbnails": {
     "default": {
      "url": "https://i.ytimg.com/vi/Ib7wP0fwXYQ/default.jpg",
      "width": 120,
      "height": 90
     },
     "medium": {
      "url": "https://i.ytimg.com/vi/Ib7wP0fwXYQ/mqdefault.jpg",
      "width": 320,
      "height": 180
     },
     "high": {
      "url": "https://i.ytimg.com/vi/Ib7wP0fwXYQ/hqdefault.jpg",
      "width": 480,
      "height": 360
     }
    },
    "channelTitle": "Parker Reed",
    "liveBroadcastContent": "none"
   }
  },
  {
   "kind": "youtube#searchResult",
   "etag": "\"8jEFfXBrqiSrcF6Ee7MQuz8XuAM/20BUOby0dXkjKmxBM1lQdYQWhwc\"",
   "id": {
    "kind": "youtube#video",
    "videoId": "1o4gN-FV7p8"
   },
   "snippet": {
    "publishedAt": "2019-07-18T16:17:29.000Z",
    "channelId": "UCe8XucXL8gVEwzvmfHM6nBA",
    "title": "Discord on smart watch",
    "description": "",
    "thumbnails": {
     "default": {
      "url": "https://i.ytimg.com/vi/1o4gN-FV7p8/default.jpg",
      "width": 120,
      "height": 90
     },
     "medium": {
      "url": "https://i.ytimg.com/vi/1o4gN-FV7p8/mqdefault.jpg",
      "width": 320,
      "height": 180
     },
     "high": {
      "url": "https://i.ytimg.com/vi/1o4gN-FV7p8/hqdefault.jpg",
      "width": 480,
      "height": 360
     }
    },
    "channelTitle": "Parker Reed",
    "liveBroadcastContent": "none"
   }
  },
  {
   "kind": "youtube#searchResult",
   "etag": "\"8jEFfXBrqiSrcF6Ee7MQuz8XuAM/s8HmSm16idCfwzGlPa9VwM28ieE\"",
   "id": {
    "kind": "youtube#video",
    "videoId": "5D-Lx3Ap_VE"
   },
   "snippet": {
    "publishedAt": "2019-06-19T21:31:42.000Z",
    "channelId": "UCe8XucXL8gVEwzvmfHM6nBA",
    "title": "Tapwave Zodiac",
    "description": "",
    "thumbnails": {
     "default": {
      "url": "https://i.ytimg.com/vi/5D-Lx3Ap_VE/default.jpg",
      "width": 120,
      "height": 90
     },
     "medium": {
      "url": "https://i.ytimg.com/vi/5D-Lx3Ap_VE/mqdefault.jpg",
      "width": 320,
      "height": 180
     },
     "high": {
      "url": "https://i.ytimg.com/vi/5D-Lx3Ap_VE/hqdefault.jpg",
      "width": 480,
      "height": 360
     }
    },
    "channelTitle": "Parker Reed",
    "liveBroadcastContent": "none"
   }
  }
 ]
}```

**Comment by zaps166** [comment]
> If you use the API then there's a function for that too

I don't use API, I don't want to register this app in Google. A long time ago I used API when it worked without registration. Is it possible to do it on the website?

**Comment by zaps166** [comment]
On YouTube website I can search for channels only, not for channel/user videos. Moreover I can't find such option in NewPipe Android app which also doesn't use YouTube API.
Currently I don't have plans for using YouTube API. Maybe when search will cease to work due to website changes...
