### ISSUE TITLE
Disable autoplay with remember position

### ISSUE THREAD

**Issue by ghost** [zaps166/QMPlay2#202]
If you choose option "Remember playback position"

then when you restart player it autoplays the file

would prefer to manually play the file - or have some option

thank you

**Comment by zaps166** [comment]
> would prefer to manually play the file - or have some option

I don't understand. If you don't want to autoplay - just disable this option :)

**Comment by cup** [comment]
@zaps166 the "remember" and "autoplay" should be separate options

**Comment by zaps166** [comment]
Does it mean that "remember" should be per file? Is it now a duplicate of #156?

**Comment by cup** [comment]
not necessarily

multiple files would be nice, but even a single file would be acceptable - just need "remember" and "autoplay" to be separate if possible - thanks again

**Comment by zaps166** [comment]
Let's do remembering position in #156.
