### ISSUE TITLE
Other programs not visible in full screen mode

### ISSUE THREAD

**Issue by cup** [zaps166/QMPlay2#205]
If you use a program like http://github.com/malensek/3RVX for volume control - and you are playing for example a fullscreen youtube video in your browser - you can still see 3RVX when changing the volume

however with QMPlay2 - if it is fullscreen you cannot see 3RVX when changing volume

**Comment by zaps166** [comment]
When OpenGL works in "Exclusive Fullscreen" on Windows, nothing else is visible (Windows BUG? - IMHO Windows should switch to borderless window in this case like it happens in Linux/X11). You can avoid this in "Settings/Modules/OpenGL" - check proper checkbox and apply. But it is not recommended, if you have high FPS video smoothness issues, go back to default settings.
