### ISSUE TITLE
What does "Detach from receiving commands" menu entry do?

### ISSUE THREAD

**Issue by notramo** [zaps166/QMPlay2#207]

**Comment by zaps166** [comment]
You can use `QMPlay2` from command line to control the main process, e.g. `QMPlay2 --toggle` toggles the playback. Only first QMPlay2 instance can receive commands. "Detach from receiving commands" stops receiving commands, so next QMPlay2 instance which will be started can start listening for commands.
This has no effect for D-Bus MPRIS2 interface.

**Comment by notramo** [comment]
Thanks.
