### ISSUE TITLE
Add 1440p60 H.264 youtube support

### ISSUE THREAD

**Issue by Ilya87** [zaps166/QMPlay2#212]
There is no 1440p60 H.264 parameter for youtube in settings in QMPlay2 18.11.20, so when I watch the stream in QuadHd 60 fps QMPlay2 youtube-dl chooses only 1080p 60fps.

**Comment by zaps166** [comment]
1440p60 H.264 probably doesn't exist, only VP9 is available according to `youtube-dl` format list.

**Comment by zaps166** [comment]
Please reselect preset after update :)

**Comment by Ilya87** [comment]
For stream source does exist. For recorded videos I agree, doesn't.

**Comment by chovy** [comment]
any update on this?

**Comment by zaps166** [comment]
There is already 1440p60 VP9 in QMPlay2. I can't see 1440p60 H.264 format on YouTube:

```
$ .qmplay2/youtube-dl "https://www.youtube.com/watch?v=LXb3EKWsInQ" --all-formats --get-format | grep 1440
400 - 2560x1440 (1440p60)
271 - 2560x1440 (1440p)
308 - 2560x1440 (1440p60)
336 - 2560x1440 (1440p60 HDR)
```
