### ISSUE TITLE
associations fail on 64-bit operating system

### ISSUE THREAD

**Issue by cup** [zaps166/QMPlay2#213]
here are my test results - note i didnt have a windows 8.1 32-bit or windows 10
32-bit to test:

os                 | installer      | result
-------------------|----------------|--------
windows 7 32-bit   | QMPlay2 32-bit | success
windows 7 64-bit   | QMPlay2 32-bit | failure
windows 7 64-bit   | QMPlay2 64-bit | failure
windows 8.1 64-bit | QMPlay2 32-bit | failure
windows 8.1 64-bit | QMPlay2 64-bit | failure
windows 10 64-bit  | QMPlay2 32-bit | success
windows 10 64-bit  | QMPlay2 64-bit | success

**Comment by cup** [comment]
@zaps166 perhaps you need to retest - Windows 7 64-bit and QMPlay2 64-bit - these tests were all done on pristine virtual machines

**Comment by zaps166** [comment]
[Icon test Win7 - Download](https://github.com/zaps166/QMPlay2/files/2683440/icon-test-win7.mkv.zip)
