### ISSUE TITLE
windowed to full screen sets it to current desktop when it was set to all desktops

### ISSUE THREAD

**Issue by EpicureanGit** [zaps166/QMPlay2#217]
Hello! 

I like to run QMPlay2 over all virtual desktops on one Screen while doing other stuff on my main Screen. I start the application in windowed mode then set it across all desktops. I do this in Plasma 5 by right clicking the window's title bar and "Move to Desktop->All Desktops." I then press F or hit the "Full screen" button in QMPlay2. In QMPlay2-18.07.03 the application goes full screen across all virtual desktops on one Screen. In QMPlay2-18.12.26 the application goes full screen but it changes the settings from all desktops to whatever the current one is only. I can go around this issue in Plasma 5 by putting QMPlay2 in full screen and then pressing alt+F3 and selecting "Move to Desktop: All Desktops."

This occurs in QMPlay2-18.12.26 but not in QMPlay2-18.07.03. I am using qt5-everywhere-src-5.11.3.

Have a good day!

**Comment by zaps166** [comment]
This is probably caused by workaround a Qt 5.12 bug. I'll try to fix it soon.

**Comment by EpicureanGit** [comment]
Thank you! That fixed it!
