### ISSUE TITLE
feature request : yadif_cuda filter

### ISSUE THREAD

**Issue by taktiker12** [zaps166/QMPlay2#218]
hi
ffmpeg 4.1 has added support of yadif_cuda filter ..it is possible to add this option to cuvid ?
thank You in advance

**Comment by zaps166** [comment]
I'll check this soon.
Is it really faster, did you tried this in ffmpeg?

**Comment by taktiker12** [comment]
i did not ..because it is enabled by default .
i should recompile ffmpeg with yadif cuda enabled .

**Comment by zaps166** [comment]
avfilter can be added, but in QMPlay2 it won't run faster - it is not easy to filter the image in GPU memory using CUVID as a separate QMPlay2 module and pass it to another FFmpeg/avfilter QMPlay2 module.

**Comment by zaps166** [comment]
I think it is better to add yadif deint into compute shader and use modern OpenGL 4.3 for it (and for other filters in the future). It can be used also on Intel and AMD, not only on NVIDIA GPUs.

**Comment by zaps166** [comment]
I don't want do add Yadif (CUDA) especially for CUVID. CUVID has its own deinterlacing filter which can be used. In the future I want to add Yadif for OpenGL (compute shader). I can also add avfilter support, but it won't be specially optimized for CUVID (to prevent data copy through CPU).

**Comment by zaps166** [comment]
See #158
