### ISSUE TITLE
User-agent for internet radio

### ISSUE THREAD

**Issue by Driglu4it** [zaps166/QMPlay2#219]
Hi, can you add this functional in future release?
Thank's.

**Comment by zaps166** [comment]
Could you explain: do you want settings in GUI or config file is sufficient?

---

QMPlay2 sets its own user agent - which radio doesn't work?

**Comment by Driglu4it** [comment]
Not all station are played (some require custom user agent for playing).

**Comment by cprog** [comment]
I also need user-agent fot TV in my case.
Tv is private for my ISP .
Config file is sufficient, I suppose it will be easier to implement.
