### ISSUE TITLE
CMake improvements

### ISSUE THREAD

**Issue by zaps166** [zaps166/QMPlay2#22]
Task for PR #32 (DONE):
- [x] Support for static linking for cross-compilation for Windows

Task for PR #31 (DONE):
- [x] CMake support for cross-compilation for Windows

Task for commit 2b9e1aa3c8c710fe4c8e169693592769588c9fd7 (DONE):
- [x] CMake support for OS X

Task for commit 4e30dc47e14bbae15b3d7b12dfa64c61c356feb7 (DONE):
- [x] detect OpenGL|ES for Qt4 and set compiler macros for it

Task for PR #28 (DONE):
- [x] show Solid actions in summary
- [x] review scripts and do small cleanup
- [x] use `pkg-config` for X11 in XVideo
- [x] detect OpenGL|ES 1.0, stop CMake and show error
- [x] option to keep RPATH after install (for `QMPlay2` executable to `libqmplay2.so`)

Task list for PR #24 (DONE):
- some modules should be optional (enabled by default only when the dependency exists):
 - [x] GME (libgme; on \*Ubuntu `pkg-config` doesn't exists for this, so detect it like in `*.pro` file)
 - [x] SID (libsidplayfp)
 - [x] PulseAudio (libpulse-simple)
 - [x] AudioCD (libcdio and libcddb)
 - [x] XVideo (libX11 and libxv)
 - [x] VA-API (libX11 and libva and libva-x11)
 - [x] VDPAU (libX11 libvdpau)
- [x] show warning when above modules will be disabled due to missing dependencies
- [x] show summary which modules will be built (needed for the previous point)
- [x] fallback to Qt4 if Qt5 doesn't exists
- [x] fallback to Qt4 if Qt5 is older than 5.6.1 instead of warning (if packager wants to use Qt5 < 5.6.1, then he/she can just enable it from command line `-DUSE_QT5=Yes`)
- [x] do something with MAN page for FreeBSD (it is installed to incorrect directory in `/usr/local`)
- [x] install the license
- [x] install ChangeLog, TODO, README.md
- [x] `make uninstall` should remove empty directories
- [x] detect the FFmpeg version (FFmpeg 2.2.0 or newer is needed)
- [x] install `QMPlay2-opencda.desktop` into proper directory (see e8d60d936789df0abbd45ebecfadf3182af15b35)
- [x] allow to disable ProstoPleer via CMake (enabled by default, see 9aac5d112681094a3e1429896bc122d0eff73891)
- [x] remove `QX11Extras` dependency from CMake
- [x] use CMake 2.8.11 for compatibility
- [x] add C++11 (`-std=c++11`) flags for CMake < 3.1.0 and GCC and Clang (also for GCC 6, no need to detect compiler version) and Qt 5.7.0
- [x] detect OpenGL|ES 2.0 for Qt5 and set compiler macros for it

**Comment by zaps166** [comment]
@arthurzam - improvements for the future :)

**Comment by arthurzam** [comment]
I will look about it.

About FFmpeg version - we will support only >= 2.2.0, and what about version 3.** - does it work ? (I don't have this version to check).

Where should the man pages be installed in FreeBSD?

**Comment by zaps166** [comment]
> About FFmpeg version (...)

FFmpeg >= 2.2.0 and >= 3.0.0 works properly (Arch and Windows build uses FFmpeg 3.0.2). Probably you must see version for every module separately (the lowest version which allows to compile).

> Where should the man pages be installed in FreeBSD?

It depends :smiley: It has MAN in `/usr/share/man` and for local in `/usr/local/man` (not in `share` subdir). The `/usr/local` is default for software for FreeBSD (also for software from repositories). Does CMake have an exception for this (or is it a BUG in CMake)?

> About OS X - I will need more information about the properties there.

Later, this is less important. Probably nobody uses it there :smiley: (btw. OS X is derived from FreeBSD).
