### ISSUE TITLE
Can't open video in fullscreen

### ISSUE THREAD

**Issue by linok9757** [zaps166/QMPlay2#223]
Qmplay2 doesn't want to open video in fullscreen mode on Gnome and Deepin DE. If you press F or double click left mouse button, window with Qmplay2 hides and new window is created with video witout controls. You can resize this window but can't open it in fullscreen.

**Comment by linok9757** [comment]
Until press F and after.
![DeepinScreenshot_20190402111737](https://user-images.githubusercontent.com/23215051/55386881-17110900-5539-11e9-8952-10d75a0f935f.png)
![DeepinScreenshot_20190402111747](https://user-images.githubusercontent.com/23215051/55386886-19736300-5539-11e9-96c6-99c435596f2d.png)

**Comment by zaps166** [comment]
Do you use 18.12.26? Or recent git version?

**Comment by linok9757** [comment]
> Do you use 18.12.26? Or recent git version?
18.12.26

![DeepinScreenshot_20190402135200](https://user-images.githubusercontent.com/23215051/55397273-8513fb00-554e-11e9-9765-eb775e23f03e.png)

**Comment by zaps166** [comment]
This bug is already fixed (271db07af63ffccfecefdf8bc14fd8470c084155).
Please wait for the next release or compile manually from GIT.

---

Do you use `qmplay2-ubuntu-amd64-18.12.26-1.deb` package from my github? I can compile a new package (pre-release) if necessary :)

**Comment by linok9757** [comment]
> This bug is already fixed ([271db07](https://github.com/zaps166/QMPlay2/commit/271db07af63ffccfecefdf8bc14fd8470c084155)).
> Please wait for the next release or compile manually from GIT.
> 
> Do you use `qmplay2-ubuntu-amd64-18.12.26-1.deb` package from my github? I can compile a new package (pre-release) if necessary :)

So.. I use Arch Linux. I uninstalled qmplay2 package and installed qmplay2-git. I then opened a video and tried to switch it into fullscreen mode.
The first several i tried to do thatr there were visual artifacts instead of the video and a few more attempts later (switching to fullscreen and back)  artifacts disappeard and i could see the video just fine
![DeepinScreenshot_20190402140307](https://user-images.githubusercontent.com/23215051/55418712-df778080-557b-11e9-92a0-d6efd26b9486.png)
![DeepinScreenshot_20190402140250](https://user-images.githubusercontent.com/23215051/55418718-e1d9da80-557b-11e9-830e-1c5e35617aeb.png)
![DeepinScreenshot_20190402191550](https://user-images.githubusercontent.com/23215051/55418724-e43c3480-557b-11e9-80d7-c7765b7ec1c5.png)

**Comment by zaps166** [comment]
Which graphics driver do you have? Is it Intel or AMD? Or nvidia?

**Comment by linok9757** [comment]
Intel HD 3000 with xf86-video-intel driver.

**Comment by zaps166** [comment]
Looks like a driver/WM compositor bug.

---

You can try OpenBox (this WM doesn't have compositor):
```
sudo pacman -S openbox
openbox --replace
```

then restart QMPlay2 and try again (your Deepin desktop can partially disappear, re-login to get normal behavior).

I'm curious about this :smile:

---

You can also try this solution (don't forget to click `Apply` for every change):

![a](https://user-images.githubusercontent.com/6239090/55419888-0a5ed600-5576-11e9-8525-b493b363acb8.png)

![b](https://user-images.githubusercontent.com/6239090/55419865-f9ae6000-5575-11e9-8632-5ac07291553f.png)

If this won't fix your issue I suggest to revert these changes.

**Comment by linok9757** [comment]
This bug appeared only several times after install. After trying switching to fullscreen and back several times artifacts disappeard. It is unlikely to be able to reproduce it. After several restarts and switches to full-screen mode and back this no longer happened.

**Comment by zaps166** [comment]
Ok!

**Comment by linok9757** [comment]
I can try to produce the same under OpenBox or by disabling compositing in DeepinDE, but not think that this will give outcome. More like a one-time bug... If I notice something like this again, I will send a new bug report and try to test without composing and with the settings that you wrote above.

**Comment by zaps166** [comment]
Ok, thanks for testing!
