### ISSUE TITLE
QMPlay2 player doesn't have always on top module can you add that?

### ISSUE THREAD

**Issue by iFarhaan** [zaps166/QMPlay2#224]
Almost every popular player has this "always on top" feature. but i couldn't find that in QMPlay2. Although it can be temporarily availed by the window control. it would be great to have "always on top" module in this awesome player.

**Comment by zaps166** [comment]
Do you use Windows?

**Comment by iFarhaan** [comment]
No i'm using Ubuntu Bionic beaver 18.04.

**Comment by zaps166** [comment]
The feature is now available.

Btw. almost all Linux WMs have this feature in context menu - why it was necessary? Does Ubuntu WM (whatever it is currently) lacks it?

**Comment by iFarhaan** [comment]
Yes this feature is available in every Linux from the WM we can avail this. but there is a catch that its not persistent whenever i close the player for once i need to check that "**Always on top**" box again. Like **SMPlayer** there is a dedicated module to keep on top the player persistently no matter if i closed the player. next time i play something on it, it just simply keeps it on above the other windows so i can enjoy my work side by side uninterruptedly. [N.B. the fact is that i want to keep QMPlay2 on top of other applications window wherever QMPlay2 player is running]

**Comment by zaps166** [comment]
Ok, I'll store it in config file.

**Comment by iFarhaan** [comment]
Thanks a lot for considering this issue.

**Comment by zaps166** [comment]
Done: https://github.com/zaps166/QMPlay2/commit/6675f9a9ecc3fe6c4d8c70d02c0dc2a2426f2ea9
