### ISSUE TITLE
windows 10  qt5.7 

### ISSUE THREAD

**Issue by liujia1000** [zaps166/QMPlay2#228]
Win10 qtmingw530-5.7. camke3.14 how to compile Qmplay2 and run it successfully?
我的环境是win10  qt5.7  mingw530  camke3.14  如何编译源码？还需要如何才可以正常编译成功？

**Comment by zaps166** [comment]
Compiling under Windows is not easy. You need to compile all needed dependencies. It is much more easier to run Arch Linux, install MinGW (+dependencies) from AUR and cross-compile. Possibly you'll need to specify libraries to link in CMake.
