### ISSUE TITLE
Running multiple QMPlay2 instances

### ISSUE THREAD

**Issue by shorewall** [zaps166/QMPlay2#229]
I'm running QMPlay2 build 18.04.01 on my Mageia 6.1 64 bit.
The player is great but I cannot run multiple instances.
Starting a stream from command line if QMPlay2 is already running it stop the current media and start the new one. Also starting it in background into an xterm.
It's my fault? Can I keep actives at the same time more than one QMPlay2 instances running different media?

Tks

**Comment by zaps166** [comment]
Do you have "Allow only one instance" enabled i "General settings"?

**Comment by shorewall** [comment]
No this option is unchecked. Is the first thing I did.
![Settings](https://user-images.githubusercontent.com/15981554/57917723-8f3b5000-7895-11e9-973e-2ed8cc314780.png)

**Comment by shorewall** [comment]
Hi, doing further check I discovered that just starting the player w/o any url to play opens multiple instances.
but starting the player from a script as: QMplay2 http:.........................
queues the link to the currently running instance that stop playing the current stream and switches playing to the last queued link.
In my scripts I would automatically start as many stream I need keeping all the other running.
This works fine using i.e mpv, bomi etc etc

**Comment by zaps166** [comment]
> In my scripts I would automatically start as many stream I need keeping all the other running.

This is not currently supported.

**Comment by shorewall** [comment]
"This is not currently supported."
Tks for your quick reply. 
In this case what is the meaning of the flag '"Allow only one instance" being enabled/disabled?

**Comment by zaps166** [comment]
> Allow only one instance

Normally you can run multiple instances of QMPlay2. Otherwise (when this option is checked) launching a new instance will activate current instance (restore window, show if hidden in tray). But you can't open every file in separate instance (you can, but not automatically, you need to click on `Player->Detach from receiving commands` in every new instance...).

---

Can it be a feature request? Why this is important?

**Comment by shorewall** [comment]
"Can it be a feature request? Why this is important?"
Just an example. I had set QMPlay2 as default player for many multimedia sources (avi, mp3, mp4) on my Linux system. I just clicked a movie and it automatically started QMPlay2. It is ok.
Then I would check the content of another  media file. I just clicked on and the current playing movie was stopped and the new media file was started.  I was really surprised. Never happened using many other players as like as native mpv o gui's as like as bomi or smplayer.
Another example. I wrote many script to watch sport sreaming events, that very often broadcast at the same time (MotoGp and F1).  So I'm used to have a couple of running flows at the same time.
This can't be done automatically using QMPlay2. So, at least for now, I switched back to Smplayer gui. I't is a pity. Your player is great.

**Comment by shorewall** [comment]
Hi, tested this quick'n dirty  workaround and it works, as soon as a QMPlay2 instance is started:
	if [ "$Player" = "QMPlay2" ]; then
        Window=$(xdotool search --name QMPlay2 | tail -1)
        xdotool windowactivate --sync $Window key x
	fi
after havig associated the x to 'Detach from receiving commands', but much better could be having a command line switch when the player is started or make this option global and persistent as like as the 'Allow only one instance'

Tks

**Comment by zaps166** [comment]
I'll add this soon

**Comment by shorewall** [comment]
Thanks very much

**Comment by zaps166** [comment]
Is a new argument `--opennew` ok?

**Comment by shorewall** [comment]
Sure, whatever name you'll use is good. :-) 
Thanks again

**Comment by zaps166** [comment]
Done :)

**Comment by shorewall** [comment]
Many thanks, I appreciated a lot your speed fixing thi issue. Now I need some time to setup one of my thinkpad to compile QMPlay2, otherwise I should wait fot a new deb snapshot to be released..
