### ISSUE TITLE
[Feature Rquest] Add support to Subtitles of extension ".vtt"

### ISSUE THREAD

**Issue by joaoeudes7** [zaps166/QMPlay2#233]
I love QMPlay2! But need to support subtitles of extension ".vtt", some courses have this extension in their subtitles and I need to rename it to ".str"

**Comment by zaps166** [comment]
Does the file with renamed suffix works properly?

**Comment by joaoeudes7** [comment]
> Does the file with renamed suffix works properly?

Yes

**Comment by zaps166** [comment]
Weird, it should work. Could you send the file?

**Comment by joaoeudes7** [comment]
lol, I'm sorry. I believe that in the test that I had done had not arrived in time of legend '-' Excuse
