### ISSUE TITLE
Audio and subtitle preference

### ISSUE THREAD

**Issue by Nosirus** [zaps166/QMPlay2#234]
Hello, when I select the default language "french" it still chose the language forced in the mkv

For subtitles, is it possible that it does not start automatically? without having to press "N" every time?

**Comment by zaps166** [comment]
> Hello, when I select the default language "french" it still chose the language forced in the mkv

I'll check it. Could you upload the mkv (you can use mkvtoolnix to copy only a few seconds of the video)?

> For subtitles, is it possible that it does not start automatically? without having to press "N" every time?

I'll add an option, good idea.

**Comment by zaps166** [comment]
Done.
