### ISSUE TITLE
Support reading lyrics from file meta-data

### ISSUE THREAD

**Issue by Martchus** [zaps166/QMPlay2#238]
Most tagging formats support adding lyrics to a file and ffmpeg generally has support for this, too (1). So it shouldn't be hard show these lyrics also within QMPlay2 - especially because other tag information is already visible as well.

I would even go ahead and implement this myself but I've noticed that the "Lyrics" tab is completely bound to the "Tekstowo" plugin. So I'm not sure where to add this in the best way. The existing "Tekstowo" plugin could be generalized. It would also be possible to extend `DemuxerThr::emitInfo()` but it is likely not a good idea to show the whole lyrics within this tab. So maybe just add another dock to the `MainWidget` (like the existing `InfoDock`)?

---

(1) At least when converting e.g. a FLAC file to AAC/MP4 the lyrics are taken over although the tag format changes.

**Comment by zaps166** [comment]
In this case the `Tekstowo` needs to be improved - user should be able to see lyrics from file metadata and user also should be able to use `Tekstowo` (and a fallback site). Also the class and file name must be changed. In case of missing lyrics metadata user should see lyrics only from network.
How to create a UI for it? Tabs in `Lyrics` widget?

The second solution is to display the lyrics stream in `Information` widget as a hyperlink which opens lyrics somewhere (e.g. in `Tekstowo` widget, but it won't trigger the network connection).

---

I can do it, but it will take some time and I need sample file.

**Comment by Martchus** [comment]
Thanks for the quick response.

You're obviously more familiar with the code base so just pick the solution which seems best from the technical perspective.

Regarding the UI: I would not create tabs inside the `Lyrics` widgets because it is already a "dock-tab" itself. I guess I would only show the lyrics from the file if present and otherwise the lyrics from the network. So there would no new UI be required.

I attached a well-tagged MP4 file created with ffmpeg: [test.zip](https://github.com/zaps166/QMPlay2/files/3512304/test.zip)

You can remux/convert it with ffmpeg to other formats like FLAC and Ogg to test these, too. (But likely the underlying format is abstracted by ffmpeg anyways so it shouldn't make a difference.)

**Comment by Martchus** [comment]
Thanks for implementing this so soon after all. I've just gave it a test and it seems to work nicely.
