### ISSUE TITLE
Possible 100% CPU usage by a background thread with FFmpeg 4.2 and GnuTLS

### ISSUE THREAD

**Issue by zaps166** [zaps166/QMPlay2#239]
Aborting FFmpeg GnuTLS connection causes infinity loop inside libavformat library. When changing entries on QMPlay2 playlist background, LastFM connection for covers can be aborted causing 100% CPU usage by a background thread. In this case QMPlay2 needs to be closed.

This is regression found in 4.2 version.

See:
https://trac.ffmpeg.org/ticket/8080
https://patchwork.ffmpeg.org/patch/14550/

**Comment by zaps166** [comment]
To workaround this issue on Arch Linux or Manjaro Linux, please use [`qmplay2-bin`](https://aur.archlinux.org/packages/qmplay2-bin/) package from AUR.

**Comment by zaps166** [comment]
Already fixed on ffmpeg master.

**Comment by zaps166** [comment]
FFmpeg 4.3.1 is already available in Arch Linux repository.

**Comment by hooke007** [comment]
Still 100% here. Tested the latest release version (win64). It cannot start and finally lead my device‘s crash.
![Snipaste_2021-02-25_19-14-59](https://user-images.githubusercontent.com/41094733/109146138-63edd080-779e-11eb-8765-bdc9a7642f29.jpg)
![Snipaste_2021-02-25_19-17-45](https://user-images.githubusercontent.com/41094733/109146144-65b79400-779e-11eb-962b-8eb79ed03c22.jpg)

**Comment by zaps166** [comment]
@hooke007 

This issue is for GnuTLS (not used on Windows, Linux only), FFmpeg 4.2.x only and special case when connection is aborted on connecting state.

---

I need more details, maybe create a new issue?
