### ISSUE TITLE
Visualizations have transparent background under Wayland

### ISSUE THREAD

**Issue by Martchus** [zaps166/QMPlay2#240]
A picture says more than words here:

![Screenshot_20190824_124942](https://user-images.githubusercontent.com/10248953/63636289-a85e5480-c66d-11e9-978a-5e455de78e14.png)

**Comment by zaps166** [comment]
Isn't it a Qt bug? It happens when OpenGL is used for visualizations (forced on Wayland).
I don't have any issues with OpenGL on visualization on Windows, X11, macOS, Android.

Btw. what about full screen? I have garbage and crash when I'm going fullscreen on Wayland.

**Comment by Martchus** [comment]
I haven't read your code but of course it might be a Qt bug as well.

Fullscreen works - at least on my system under Plasma with Intel HD Graphics.

**Comment by zaps166** [comment]
> Fullscreen works - at least on my system under Plasma with Intel HD Graphics.

Ok :) I tested on AMD Vega 8 and Weston.

The transparent bug is fixed by painting a black rectangle on Wayland.

**Comment by zaps166** [comment]
Btw. QMPlay2 master branch supports VA-API on Wayland.

**Comment by Martchus** [comment]
> QMPlay2 master branch supports VA-API on Wayland

Yes, it "just" worked :-)
