### ISSUE TITLE
Can QMPlay2 compile & debug using Qt Creator on Windows ? 

### ISSUE THREAD

**Issue by lovelypp777** [zaps166/QMPlay2#242]
Hi
    I tried QMPlay2，it very very wonderful. 
    I am very interested in this project and want to join the development of it. But I think  it  will be better if it can compile on Windows using Qt Creator or MSVC, because these two IDEs can provide better debugging and coding environment and experience.
    So, can you give me some hint to compile it on Windows using Qt Creator or MSVC ?
    Thanks.

**Comment by zaps166** [comment]
Hi, QMPlay2 doesn't support MSVC, you need GCC compiler on Windows.
You need to install Qt5, CMake, QtCreator, mingw-w64, compile FFmpeg, libass, taglib, and other dependencies, than properly configure CMake and compile. It is not an easy task.

**Comment by lovelypp777** [comment]
thank you for your reply.
i think i maybe easier to use qt creator to build it on windows. can you try it,thank you again



---Original---

**Comment by zaps166** [comment]
> can you try it,thank you again

I don't understand, what I can try?

**Comment by zaps166** [comment]
> i think i maybe easier to use qt creator to build it on windows

QtCreator is not a compiler. QtCreator is not sufficient to build QMPlay2, you need to have a lot of other dependencies (including a GCC compiler).

**Comment by lovelypp777** [comment]
yes,you are right. I willl try it,thank you



---Original---

**Comment by lovelypp777** [comment]
try to compile it on windows using qt&nbsp; creator environment



---Original---

**Comment by lovelypp777** [comment]
I have finished compile ffmpeg using ShifMediaPfoject:
https://github.com/ShiftMediaProject

this project include most the extra dependency in QMPlay2. I suggest you can try it.
it's really good.

**Comment by zaps166** [comment]
For FFmpeg you can use: https://ffmpeg.zeranoe.com/builds/
But I recomnend to compile it yourself with needed compile flags.

**Comment by zaps166** [comment]
Windows compilation instruction: https://github.com/zaps166/QMPlay2/wiki/Compilation-on-Windows-x86-64

It works only for master branch, not for the 20.07.04 release
