### ISSUE TITLE
can not add file to filelist on Android

### ISSUE THREAD

**Issue by lovelypp777** [zaps166/QMPlay2#245]
I want to add file to file list, but the dialog can not list media files on android.
another issue is the layout of  add file dialog is not correct, not close button displayed

**Comment by zaps166** [comment]
Be sure that you added permission to "Storage". Then write `/sdcard` in file dialog and tap enter. Tap back to cancel the dialog.

It is experimental build and I'm aware of issues.

**Comment by zaps166** [comment]
Does it work?

**Comment by lovelypp777** [comment]
i can generate wav tone but can not add file to play



---Original---

**Comment by lovelypp777** [comment]
dont't kbow what's mean of&nbsp;
&nbsp;added permission to "Storage"


---Original---

**Comment by zaps166** [comment]
Try this: https://cloud.addictivetips.com/wp-content/uploads/2015/10/android-6-app-permis.png
But choose QMPlay2 app instead of Chrome.

**Comment by lovelypp777** [comment]
hiver: QMPlay2-18.11.20
os: windows


the error is as the attached pic.


thanks!

**Comment by zaps166** [comment]
> the error is as the attached pic.

where is the attached pic?

**Comment by lovelypp777** [comment]
------------------ 原始邮件 ------------------
发件人: "Błażej Szczygieł"<notifications@github.com>;
发送时间: 2019年9月1日(星期天) 晚上7:27
收件人: "zaps166/QMPlay2"<QMPlay2@noreply.github.com>;
抄送: "alone"<2455196031@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [zaps166/QMPlay2] can not add file to filelist on Android (#245)



 
the error is as the attached pic.
  
where is the attached pic?

**Comment by zaps166** [comment]
I know that it is inconvenient, but it works - tested on more then one device.

**Comment by zaps166** [comment]
> hiver: QMPlay2-18.11.20 os: windows the error is as the attached pic. thanks!

I don't understand this message

**Comment by zaps166** [comment]
> os: windows

This issue is about Android, hmm...

**Comment by lovelypp777** [comment]
you are&nbsp; right,the url I given worked. but my rtmp server in lan has this problem


thank you,i will try it



---Original---
