### ISSUE TITLE
YouTube video quality/resolution/framerate/size

### ISSUE THREAD

**Issue by zaps166** [zaps166/QMPlay2#246]
It's here: ![Screenshot_20190823_121536](https://user-images.githubusercontent.com/6239090/63585569-bba2ee80-c59f-11e9-959d-13c2e59c6ff2.png)

I'll also add this option to the settings in the near future.

**Comment by parkerlreed** [comment]
I was just about to yell asking where it moved to :P

Thanks!

**Comment by zaps166** [comment]
But it is here for a long time :smile: Now I decided to remove complicated settings and keep only the simple settings :D
