### ISSUE TITLE
Removal of old things

### ISSUE THREAD

**Issue by zaps166** [zaps166/QMPlay2#247]
I want to remove in the near future:
- VA-API surface ~~and VA-API host memory copy~~ (only OpenGL interop will be available),
- ~~VDPAU support (use VA-API and CUVID for NVIDIA proprietary drivers),~~

~~At least~~ VDPAU surface ~~and VDPAU host memory copy~~ will be removed and VDPAU OpenGL interop will be introduced.

Next I want to remove:
- [ ] DirectDraw (it is usable mostly on very old GPUs on Windows XP),
- [x] Windows XP support,

Does anybody still use these features?

**Comment by lovelypp777** [comment]
not sugges to remove DirectDraw support cause there are some xp stll.
suggest to add sdl render support.

**Comment by lovelypp777** [comment]
another suggestion: suggest add qt creator project file, it's very useful  on windows. thanks!
