### ISSUE TITLE
[macOS] PortAudio compilation error

### ISSUE THREAD

**Issue by zaps166** [zaps166/QMPlay2#248]
@RJVB 

On some macOS/XCode configurations I'm unable to compile PortAudio due to `verify_noerr`. What does it do and why it is needed?

**Comment by RJVB** [comment]
> On some macOS/XCode configurations I'm unable to compile PortAudio due to `verify_noerr`. What does it do and why it is needed?

It's a kind of ASSERT that checks if the argument expression indeed returned 0, but from what I can see, never raises a signal. It shouldn't be needed but                                                                                                                                                                                                                                                            in case of doubt you should be able to use the more moreder `__Verify_noErr` instead.

**Comment by zaps166** [comment]
Ok. Can I just use `assert` from C or `Q_ASSERT`?

**Comment by RJVB** [comment]
I hate those :) but I suppose you could, yes. But you'd have to do the assert on a return value of `noErr` (0).

**Comment by zaps166** [comment]
Done by PR.

**Comment by RJVB** [comment]
Works fine as far as I can tell.
