### ISSUE TITLE
PowerPC: Can't compile due to "-funsigned-char"

### ISSUE THREAD

**Issue by DAP-DarkneSS** [zaps166/QMPlay2#25]
Distro: openSUSE Factory
Compiler: gcc6
Arch: ppc64 & ppc64le only.
Build log:
[  127s] Rayman2.cpp: In function 'float decode(unsigned char, short int&, int&)':
[  127s] Rayman2.cpp:23:68: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
[  127s]   static const char ima_index_table[8] = {-1, -1, -1, -1, 2, 4, 6, 8};
[  127s]                                                                     ^
[  127s] Rayman2.cpp:23:68: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
[  127s] Rayman2.cpp:23:68: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
[  127s] Rayman2.cpp:23:68: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]

**Comment by zaps166** [comment]
Looks like `-Werror` parameter is used.

**Comment by zaps166** [comment]
Fixed, now it uses `qint8` which is `signed char`.

**Comment by DAP-DarkneSS** [comment]
Thank you!

**Comment by zaps166** [comment]
:smiley:
But I don't know how does QMPlay2 work on big-endian machines (not tested). Probably it'll be buggy - PPC (and ARM and MIPS) can be also big-endian.

**Comment by DAP-DarkneSS** [comment]
Me too. Btw I am not really sure that openSUSE users have ppc64 desktops…

**Comment by zaps166** [comment]
AFAIK ppc64 (big-endian) is in PlayStation3 (2 cores from Cell CPU) and ppc(big-endian; 32bit?) was on old Apple computers. But probably nobody uses big-endian + QMPlay2 :smiley:

**Comment by DAP-DarkneSS** [comment]
openSUSE supports now ppc64 and ppc64le (little-endian). The latest is IBM  
next generation servers arch afaik.

**Comment by zaps166** [comment]
So `ppc64` means big-endian. Maybe I'll try to compile it via qemu some day...

**Comment by zaps166** [comment]
@DAP-DarkneSS New QMPlay2 uses CMake build system, Prostopleer can be disabled via CMake option.
