### ISSUE TITLE
video hangs when reconnect to rtmp server

### ISSUE THREAD

**Issue by lovelypp777** [zaps166/QMPlay2#250]
Use a direct address to play a rtmp stream.  when connected and playing the stream,  close the rtmp server, and reopen it. QMPlay2 will try to reconnect to the rtmp server and play the stream. but when it reconnect the rtmp server, video is hang(no video stream data) and audio is normal. 
you need to press the stop and then start play, then it recovered.

**Comment by zaps166** [comment]
I need to test it, so I need an rtmp URL.

**Comment by lovelypp777** [comment]
try this:
rtmp://202.69.69.180:443/webcast/bshdlive-pc




------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>; 
发送时间: 2019年9月2日(星期一) 下午5:59
收件人: "zaps166/QMPlay2"<QMPlay2@noreply.github.com>; 
抄送: "alone"<2455196031@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [zaps166/QMPlay2] video hangs when reconnect to rtmp server(#250)




I need to test it, so I need an rtmp URL.

**Comment by zaps166** [comment]
The stream worked, now it doesn't, but I need my own stream to check server stop error. I'll try my server later, but I can't guarantee that I can fix it quickly.

**Comment by zaps166** [comment]
Old, closing.
