### ISSUE TITLE
need new features: to show multi player window simultaneously

### ISSUE THREAD

**Issue by lovelypp777** [zaps166/QMPlay2#251]
In some circumstance (ex. Video Surveillance App), I need to show multi video window in an App, for example 1, 4, 9, 16 window. 
I don't know if the qmplay2 classes using some global stiatc variables, so If I want to modify, it will be some issue. or if the video render or audo play engine support muliti instance.

**Comment by zaps166** [comment]
Do I understand correctly, you want to display e.g. 16 different video files/streams in a single window in tiled mode?

**Comment by lovelypp777** [comment]
yes,maybe 2,4,9&nbsp; or 16



---Original---

**Comment by zaps166** [comment]
Ok, but it is not possible and I don't have any plans for this, sorry.
