### ISSUE TITLE
AppImage video flickers with GL2 output, plus va-api hwaccel doesn't work in MX Linux 18 or 19

### ISSUE THREAD

**Issue by stevenpusser** [zaps166/QMPlay2#253]
The flickering resembles that from a bad fluorescent light tube at maybe 60 Hz. 
I don't get it with the native 19.0.03 deb packages I just built for MX ( I'm the lead packager), plus the va-api works great with my Intel UHD 630 GPU.

I could set up an openSUSE Build Service repository that builds and provides 64 and 32-bit packages for the compatible Debian, Ubuntu, and Rasbian releases, plus armhf (Pi) and aarch64 for Debian if those build. They should also have those nice extra features working. Would you add that to your list if I set it up?

**Comment by stevenpusser** [comment]
Here's the repos I set up:  https://build.opensuse.org/package/show/home:stevenpusser:QMPlay2/qmplay2

**Comment by zaps166** [comment]
> The flickering resembles that from a bad fluorescent light tube at maybe 60 Hz.

Does it decode on CPU and play on OpenGL? What if you change output to QPainter?

> native 19.0.03 deb packages

19.09.03?

> They should also have those nice extra features working.

VA-API is working properly on AppImage. I don't have problems with VA-API on Manjaro and Ubuntu 19.04. Maybe VA-API 2.5.0 is too new for old drivers, unfortunately VA-API doesn't have good backward compatibility.

Could you upload VA-API logs from terminal output? Does it find the driver library? Does it open the driver library? Does it find the initial function?

---

Could you upload the video somewhere? Or at least a part of it (you can cut it loslessly using `ffmpeg` command line).

**Comment by zaps166** [comment]
Just testing:
- no problems with VA-API on Fedora 30,

**Comment by zaps166** [comment]
On MX Linux 18.3 "LiveCD" - `whereis` command is unable to find the `dri` directory in `/usr/lib/x86-64-linux-gnu/dri` (it works on Ubuntu). It is not problem with AppImage, but with `whereis` command on MX Linux and with `FIND_HWACCEL_DRIVERS_PATH` defined in CMake, so with the QMPlay2 itself (C++ code). Moreover QMPlay2 is unable to find/use EGL when it checks it at early startup (required e.g. for zero-copy VA-API mode and for correct video output on AMD).

Could you try with:
```
export LIBVA_DRIVERS_PATH=/usr/lib/x86-64-linux-gnu/dri
export QT_XCB_GL_INTEGRATION=xcb_egl
```
?


For creating universal packages you need to define `-DFIND_HWACCEL_DRIVERS_PATH=ON`. Otherwise QMPlay2 might not find VA-API/VDPAU drivers on other distributions.

---

Btw. I can't see any flickering.

**Comment by stevenpusser** [comment]
Sorry, I did mean 19.09.03 packages. You don't really have to fix the AppImage for MX, since we have native packages working well now that our in our own repo. I did have to add the Mesa EGL headers along with the Qt 5 headers for this build to get rid of those problems.

I do wonder about the LTS Ubuntu releases that don't have the latest va-api 2.5, since it does seem to be fragile. I build two different versions of QMPlay2, one for our "main" repo, and another against the newer Mesa, ffmpeg, and libva in our backport test repo, just for that reason. The builds in my OBS repo could help them if the AppImage can't work for them, plus it supports more architectures like the Pi and PineBook, along with the 32-bit x86.

There's another Debian-based distro called Sparky Linux which also packages QMPlay2, but I think they also need to make the changes I just did. I don't know if they build packages in a Debian "clean room" chroot like we do at MX, though, so maybe they had the headers installed anyway.  https://sparkylinux.org/repo/pool/main/q/qmplay2/

I'll test your changes with the Appimage on MX later today, though!

**Comment by stevenpusser** [comment]
The export commands didn't help the flickering. I ran this after running them in the terminal:

```
 ./QMPlay2-19.09.03-1-x86_64.AppImage Elysium_trailer_1-4K-HDTN\(4ksamples.com\).mp4 
libva info: VA-API version 1.5.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86-64-linux-gnu/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
VA-API :: Unable to initialize device: renderD128
libva info: VA-API version 1.5.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86-64-linux-gnu/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
[ass] Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 1.4.2 (COMPLEX)
[ass] Using font provider fontconfig

```
I'm pretty sure our MX users will prefer the native version, since it also uses the native theming and font choice, where the Appimage doesn't seem to. You can install the MX 17 "main" version on the Live session if you want to check it out--just extract the zip and click on the .deb file to install it with gdebi:

https://drive.google.com/open?id=1OQxwSGrjP9x2DuoLGbd1RzPy9nWIN6Pz

**Comment by zaps166** [comment]
I edited the previous comment, sorry for the typo. The directory should be `x86_64-linux-gnu`, so:
```
export LIBVA_DRIVERS_PATH=/usr/lib/x86_64-linux-gnu/dri
export QT_XCB_GL_INTEGRATION=xcb_egl
```

**Comment by zaps166** [comment]
The flickering looks like a OpenGL driver issue. I don't know why it doesn't flicker on native build. Did you try CPU decode + OpenGL display on native build?

**Comment by stevenpusser** [comment]
I built the 19.08.27 version yesterday with the same build-depends as the 18.12.26 build. It also showed the flickering on the GL2 output, plus didn't show the ffmpef va-api decoder option. When I built the new version today, I paid attention to what CMAKE was saying this time, and it said that it wasn't going to enable va-api because it couldn't find the EGL headers. When I added those (and the new QT SVG headers build-dep, too) to the build-depends and ran the builds again, it was all fixed when I tested them--ffmpeg-vaapi was back and the flickering was gone. 

I've never enabled the CPU decode--I thought that was rather experimental...Did you want me to try it now that QMPlay's working great without it on the native build?

**Comment by zaps166** [comment]
> Did you want me to try it now

Yes, if you have a time for testing :) I'm curious.

For CPU decoding use OpenGL with two envvars for comparition:

`export QT_XCB_GL_INTEGRATION=xcb_egl`
and next
`export QT_XCB_GL_INTEGRATION=xcb_glx`

---

If you run VA-API, what is in Information panel displayer?

**Comment by stevenpusser** [comment]
```
Here's the information for a sample 4K h.264 movie trailer with the MX native build:

File path: /home/steve/Desktop/downloads/mozilla-downloads/
File name: Elysium_trailer_1-4K-HDTN(4ksamples.com).mp4
Bitrate: 26628kbps
Format: mov,mp4,m4a,3gp,3g2,mj2
Video streams:
Stream 1 - FFmpeg/VA-API, OpenGL 3.0 VA-API (GLX)
codec: h264
size: 4096x1716
aspect ratio: 2.38695
FPS: 24
bitrate: 26252kbps
format: yuv420p
language: english
Audio streams:
Stream 1 - FFmpeg, PulseAudio
codec: aac
sample rate: 48000Hz
channels: 6
bitrate: 382kbps
format: fltp
language: english
```
With the CPU decoding commands exported to the environment first, there's no change in that or in the output in the terminal. CPU remains minimal with va-api working.

**Comment by stevenpusser** [comment]
MX Linux is a lightweight distro, and we do have users with old or underpowered computers that complain about Youtube videos in the browser pegging the CPU, or a modern browser eating up all their RAM. If we can get hardware acceleration working for those videos in an external player, that's all the better for them.

**Comment by zaps166** [comment]
Ok, thx. `FFmpeg/VA-API, OpenGL 3.0 VA-API (GLX)` this means that VA-API doesn't work with full speed. I already figured it out and fixed here: d7d3712b6ac744cbdc3122152078d1c4d0cbe308. With VA-API when QMPlay2 don't display `(GLX)` it means that it runs over EGL in zero-copy mode (OpenGL displays the decoded frame instead of converting it into RGB and then displaying it - it is not available in GLX mode).

I hope d7d3712b6ac744cbdc3122152078d1c4d0cbe308 will work properly (& faster - check `intel_gpu_top`) on MX Linux :)

> With the CPU decoding commands exported to the environment first, there's no change in that or in the output in the terminal. 

Doesn it mean that the video flickers on both: GLX and EGL with CPU decode, but doesn't flicker with QPainter video output ?

**Comment by stevenpusser** [comment]
The MX Linux build of 19.08.27 flickered using the GL output only, as does the AppImage. The 19.09.03 build with the added Mesa EGL headers doesn't flicker in any mode. I'll test the revision-- va-api seems to be working nicely already in terms of no extra CPU use, even for 4K h.265 video, but perhaps the change will make it even easier on the Intel GPU.

**Comment by zaps166** [comment]
Added commit to fix AppImage and added more info about VA-API to README: https://github.com/zaps166/QMPlay2/commit/cc26e3624cb14ccfc18af82cda36eaf90e1b3822 espeacially for MX Linux where auto detection of EGL can fail.

---

I'm, curious about flickering on CPU decode + OpenGL...
