### ISSUE TITLE
video get stuck when enable high quality video scaling using OpenGL2

### ISSUE THREAD

**Issue by lovelypp777** [zaps166/QMPlay2#254]
I test it on Windows 7 SP1 
QMPlay2 version : 19.09.03 build for x86

thanks!

**Comment by zaps166** [comment]
Sometimes it can happen. This feature should be marked as "experimental". It is not optimized, it will be improved in the future. Which graphics card do you have? Maybe it is too slow?

**Comment by lovelypp777** [comment]
maybe. i use a notebook with a integrated graphics card.



---Original---

**Comment by zaps166** [comment]
Integrated graphics can be too slow. Maybe after optimization, but it needs a lot of changes and it doesn't guarantee the it will work on slow iGPU.

**Comment by lovelypp777** [comment]
I test another player - fanplayer using OpenGL2, it can play normaly.

**Comment by zaps166** [comment]
How fanplayer do hq scaling?

**Comment by lovelypp777** [comment]
sorry, I did not study the source code of fanplayer, but it really works



------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>; 
发送时间: 2019年9月11日(星期三) 下午5:29
收件人: "zaps166/QMPlay2"<QMPlay2@noreply.github.com>; 
抄送: "alone"<2455196031@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [zaps166/QMPlay2] video get stuck when enable high quality videoscaling using OpenGL2 (#254)




How fanplayer do hq scaling?

**Comment by zaps166** [comment]
is it available for linux?

**Comment by zaps166** [comment]
Fanplayer uses `SWS_FAST_BILINEAR`, so it is not HQ video scaling. Moreover fanplayer uses GDI or D3D on Windows; it doesn't support OpenGL. I'm not sure, but probably fanplayer copies video from GPU memory to host memory and then uploads it again (again, I'm not sure).

**Comment by zaps166** [comment]
High quality video scaling has been removed from OpenGL long time ago. It's available in Vulkan now.
