### ISSUE TITLE
question: how to optimize latency when playing rtmp stream

### ISSUE THREAD

**Issue by lovelypp777** [zaps166/QMPlay2#256]
When playing rtmp stream, I find there is some  latency.
how to  optimize it ?

thanks!

**Comment by zaps166** [comment]
QMPlay2 has a buffer, check the Information panel:
![Screenshot_20190907_104745](https://user-images.githubusercontent.com/6239090/64472334-f5a5f000-d15c-11e9-9a9d-34ce287dd1ae.png)

For live streams it can add latency. There is no auto mechanism to reduce latency. If latency became too large, press the right arrow to seek in buffer and check Information panel again. Also you can reduce this: ![Screenshot_20190907_105007](https://user-images.githubusercontent.com/6239090/64472352-43baf380-d15d-11e9-9534-06bb8d253b8b.png), but don't set to 0.0.

**Comment by lovelypp777** [comment]
thanks,i will try it



---Original---
