### ISSUE TITLE
request to genete qt creator pro file or withdrawal the pro file 

### ISSUE THREAD

**Issue by lovelypp777** [zaps166/QMPlay2#257]
I have compiled QMPlay2 18.12.26 on windows using qt creator successfully. I think i'ts better to obtain the pro file in later vertion.

thanks

**Comment by zaps166** [comment]
QMake files are removed.

Use CMake:
- download CMake + [Ninja](https://github.com/ninja-build/ninja) for Windows,
- install them, put Ninja into global path for simplicity,
- Configure CMake + Ninja in QtCreator,
- open `CMakeLists.txt` in QtCreator,
- go to "Projects" tab and select `Build`:
  - disable all things you don't want to compile (e.g. you don't have libs),
  - specify paths for all libs directory,
  - see https://github.com/zaps166/QMPlay2#other-information-for-windows,

**Comment by lovelypp777** [comment]
if i use cmake,can it be debugged line by line in qt creator



---Original---

**Comment by zaps166** [comment]
> can it be debugged line by line in qt creator

The source code? Yes, compile in debug mode and run via debugger. Exactly like in qmake files.

**Comment by lovelypp777** [comment]
thanks



---Original---

**Comment by lovelypp777** [comment]
thank you.  in qt creator, when parsing CMakeLists.txt file, it failed as following (see the attachment pic also):



Starting to parse CMake project.
 
Could NOT find TAGLIB (missing: TAGLIB_LIBRARY TAGLIB_INCLUDE_DIR) 
 
Enabled features:
 
 * MediaBrowser, Build with MediaBrowser support




I have compile taglib in my local disk, but how to specifiy the include & lib path in qt ?

can you give me a hint ? thanks very much.

**Comment by lovelypp777** [comment]
hi    I have resolved the LIBTAG_LIBRARY problem now, but it comes another error:



Scanning dependencies of target libqmplay2_autogen
 
[  1%] Automatic MOC for target libqmplay2
 
[  1%] Built target libqmplay2_autogen
 
[  1%] Automatic RCC for languages.qrc
 
Scanning dependencies of target libqmplay2
 
[  2%] Building CXX object src/qmplay2/CMakeFiles/libqmplay2.dir/libqmplay2_autogen/mocs_compilation.cpp.obj
 
[  2%] Building CXX object src/qmplay2/CMakeFiles/libqmplay2.dir/QMPlay2Core.cpp.obj
 
F:\QMplay2-cmake\QMPlay2-master\src\qmplay2\QMPlay2Core.cpp:54:14: fatal error: libavformat/avformat.h: No such file or directory
 
     #include <libavformat/avformat.h>
 
              ^~~~~~~~~~~~~~~~~~~~~~~~
 
compilation terminated.







I don't find any option to set the ffmpeg path in qt creator 

any hint ? thanks!

**Comment by lovelypp777** [comment]
hi  I find the following statements in CMakeLists.txt：
link_directories(     ${LIBAVFORMAT_LIBRARY_DIRS}     ${LIBAVCODEC_LIBRARY_DIRS}     ${LIBSWSCALE_LIBRARY_DIRS}     ${LIBAVUTIL_LIBRARY_DIRS} )
include_directories(    headers    ${LIBAVFORMAT_INCLUDE_DIRS}    ${LIBAVCODEC_INCLUDE_DIRS}    ${LIBSWSCALE_INCLUDE_DIRS}    ${LIBAVUTIL_INCLUDE_DIRS})
but I don't know where to define theres dirs in qt creator.if I need to modify CMakieLists.txt file manually ?
thanks!

**Comment by zaps166** [comment]
Windows compilation instruction: https://github.com/zaps166/QMPlay2/wiki/Compilation-on-Windows-x86-64
