### ISSUE TITLE
video filters is not effect when using DirectDraw as video output

### ISSUE THREAD

**Issue by lovelypp777** [zaps166/QMPlay2#258]
when select DirectDraw as the first video output device, video filters has no effects.

**Comment by zaps166** [comment]
Deinterlacing filters?

**Comment by lovelypp777** [comment]
brightness,contrast...




------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>; 
发送时间: 2019年9月11日(星期三) 下午5:26
收件人: "zaps166/QMPlay2"<QMPlay2@noreply.github.com>; 
抄送: "alone"<2455196031@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [zaps166/QMPlay2] video filters is not effect when usingDirectDraw as video output (#258)




Deinterlacing filters?

**Comment by zaps166** [comment]
It depends on driver and it might not work on modern drivers. DirectDraw is for very old hardware and WindowsXP. Using it on Windows 8 and higher doesn't nake any sense. Also using it when OpenGL works properly does't make any sense.
