### ISSUE TITLE
X11Extras still present?

### ISSUE THREAD

**Issue by mmetak** [zaps166/QMPlay2#26]
https://github.com/zaps166/QMPlay2/commit/8323be5fcd5ceca40dfff1a6cc6ac323f330c9f3
sed 's/ X11Extras//' -i "${pkgname}-${pkgver}"/src/{gui/CMakeLists.txt,modules/XVideo/CMakeLists.txt}

**Comment by zaps166** [comment]
In progress, see #24 and #22 :)

**Comment by mmetak** [comment]
Just asking because you removed qt5-x11extras from depends in archlinux pkgbuild and it fails to build.

**Comment by zaps166** [comment]
Aaah, sorry. I forgot about this that AUR now uses CMake :smiley:
Updated AUR package.

**Comment by zaps166** [comment]
Fixed 5533615cde0893cfbe92eb6421687259ad317f73
