### ISSUE TITLE
Change audio and subtitles with keyboard?

### ISSUE THREAD

**Issue by Diskutant** [zaps166/QMPlay2#261]
Would it be possible to add keyboard shortcuts to change audio (language) and subtitles?

Also is the only way to change those the info widget? I had a hard time to even find a way to change the audio in qmplay2.

**Comment by zaps166** [comment]
I need to do more changes than just adding a shortcut, so it won't be immediately.

**Comment by zaps166** [comment]
Done!

**Comment by Diskutant** [comment]
awesome, thank you! 
Will try this in the next release.
