### ISSUE TITLE
Version 19.11.06 does not compile against openSUSE Leap 15.0 & 15.1

### ISSUE THREAD

**Issue by DarkWav** [zaps166/QMPlay2#264]
When compiling QMPlay2 against openSUSE Leap 15.0 and 15.1 I get the following errors:

> [  107s] [ 72%] Building CXX object src/modules/FFmpeg/CMakeFiles/FFmpeg.dir/FFmpeg_autogen/mocs_compilation.cpp.o
> [  107s] cd /home/abuild/rpmbuild/BUILD/QMPlay2-src-19.11.06/build/src/modules/FFmpeg && /usr/bin/g++-7  -DFFmpeg_EXPORTS -DQMPlay2_VAAPI -DQMPlay2_VDPAU -DQMPlay2_libavdevice -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_USE_FAST_OPERATOR_PLUS -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DUSE_OPENGL -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/home/abuild/rpmbuild/BUILD/QMPlay2-src-19.11.06/build/src/modules/FFmpeg -I/home/abuild/rpmbuild/BUILD/QMPlay2-src-19.11.06/src/modules/FFmpeg -I/home/abuild/rpmbuild/BUILD/QMPlay2-src-19.11.06/build/src/modules/FFmpeg/FFmpeg_autogen/include -I/usr/include/ffmpeg -I/usr/include/libdrm -I/home/abuild/rpmbuild/BUILD/QMPlay2-src-19.11.06/src/modules/FFmpeg/../../qmplay2/headers -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtX11Extras -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/qt5/QtWidgets  -Wall -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG -O2 -g -DNDEBUG -fPIC   -fPIC -std=gnu++11 -o CMakeFiles/FFmpeg.dir/FFmpeg_autogen/mocs_compilation.cpp.o -c /home/abuild/rpmbuild/BUILD/QMPlay2-src-19.11.06/build/src/modules/FFmpeg/FFmpeg_autogen/mocs_compilation.cpp
> [  107s] /home/abuild/rpmbuild/BUILD/QMPlay2-src-19.11.06/src/modules/FFmpeg/FFDecVAAPI.cpp: In member function 'virtual bool FFDecVAAPI::open(StreamInfo&, VideoWriter*)':
> [  107s] /home/abuild/rpmbuild/BUILD/QMPlay2-src-19.11.06/src/modules/FFmpeg/FFDecVAAPI.cpp:488:16: error: 'struct AVCodecContext' has no member named 'extra_hw_frames'; did you mean 'max_b_frames'?
> [  107s]      codec_ctx->extra_hw_frames = 3;
> [  107s]                 ^~~~~~~~~~~~~~~
> [  107s]                 max_b_frames
> [  107s] make[2]: *** [src/modules/FFmpeg/CMakeFiles/FFmpeg.dir/build.make:306: src/modules/FFmpeg/CMakeFiles/FFmpeg.dir/FFDecVAAPI.cpp.o] Error 1
> [  107s] make[2]: *** Waiting for unfinished jobs....

and

> [  109s] [ 74%] Building CXX object src/modules/Chiptune/CMakeFiles/Chiptune.dir/Chiptune_autogen/EWIEGA46WW/qrc_icons.cpp.o
> [  109s] cd /home/abuild/rpmbuild/BUILD/QMPlay2-src-19.11.06/build/src/modules/Chiptune && /usr/bin/g++-7  -DChiptune_EXPORTS -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_USE_FAST_OPERATOR_PLUS -DQT_WIDGETS_LIB -DUSE_GME -DUSE_SIDPLAY -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/home/abuild/rpmbuild/BUILD/QMPlay2-src-19.11.06/build/src/modules/Chiptune -I/home/abuild/rpmbuild/BUILD/QMPlay2-src-19.11.06/src/modules/Chiptune -I/home/abuild/rpmbuild/BUILD/QMPlay2-src-19.11.06/build/src/modules/Chiptune/Chiptune_autogen/include -I/home/abuild/rpmbuild/BUILD/QMPlay2-src-19.11.06/src/modules/Chiptune/../../qmplay2/headers -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtWidgets  -Wall -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG -O2 -g -DNDEBUG -fPIC   -fPIC -std=gnu++11 -o CMakeFiles/Chiptune.dir/Chiptune_autogen/EWIEGA46WW/qrc_icons.cpp.o -c /home/abuild/rpmbuild/BUILD/QMPlay2-src-19.11.06/build/src/modules/Chiptune/Chiptune_autogen/EWIEGA46WW/qrc_icons.cpp
> [  109s] /usr/bin/make -f src/modules/QPainter/CMakeFiles/QPainter.dir/build.make src/modules/QPainter/CMakeFiles/QPainter.dir/depend
> [  109s] make[2]: Entering directory '/home/abuild/rpmbuild/BUILD/QMPlay2-src-19.11.06/build'
> [  109s] cd /home/abuild/rpmbuild/BUILD/QMPlay2-src-19.11.06/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/abuild/rpmbuild/BUILD/QMPlay2-src-19.11.06 /home/abuild/rpmbuild/BUILD/QMPlay2-src-19.11.06/src/modules/QPainter /home/abuild/rpmbuild/BUILD/QMPlay2-src-19.11.06/build /home/abuild/rpmbuild/BUILD/QMPlay2-src-19.11.06/build/src/modules/QPainter /home/abuild/rpmbuild/BUILD/QMPlay2-src-19.11.06/build/src/modules/QPainter/CMakeFiles/QPainter.dir/DependInfo.cmake
> [  109s] /home/abuild/rpmbuild/BUILD/QMPlay2-src-19.11.06/src/modules/FFmpeg/FFDecVDPAU.cpp: In member function 'virtual bool FFDecVDPAU::open(StreamInfo&, VideoWriter*)':
> [  109s] /home/abuild/rpmbuild/BUILD/QMPlay2-src-19.11.06/src/modules/FFmpeg/FFDecVDPAU.cpp:402:16: error: 'struct AVCodecContext' has no member named 'extra_hw_frames'; did you mean 'max_b_frames'?
> [  109s]      codec_ctx->extra_hw_frames = 3;
> [  109s]                 ^~~~~~~~~~~~~~~
> [  109s]                 max_b_frames
> [  109s] Dependee "/home/abuild/rpmbuild/BUILD/QMPlay2-src-19.11.06/build/src/modules/QPainter/CMakeFiles/QPainter.dir/DependInfo.cmake" is newer than depender "/home/abuild/rpmbuild/BUILD/QMPlay2-src-19.11.06/build/src/modules/QPainter/CMakeFiles/QPainter.dir/depend.internal".
> [  109s] Dependee "/home/abuild/rpmbuild/BUILD/QMPlay2-src-19.11.06/build/src/modules/QPainter/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/home/abuild/rpmbuild/BUILD/QMPlay2-src-19.11.06/build/src/modules/QPainter/CMakeFiles/QPainter.dir/depend.internal".
> [  109s] Scanning dependencies of target QPainter
> [  109s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/QMPlay2-src-19.11.06/build'
> [  109s] /usr/bin/make -f src/modules/QPainter/CMakeFiles/QPainter.dir/build.make src/modules/QPainter/CMakeFiles/QPainter.dir/build
> [  109s] make[2]: Entering directory '/home/abuild/rpmbuild/BUILD/QMPlay2-src-19.11.06/build'

openSUSE Tumbleweed and Factory work fine as they use newer VDPAU Libraries.
Nevertheless, do you think It's possible to make it work on Leap again?
Thanks in advance.

**Comment by zaps166** [comment]
Oops, I forgot to update README and add ifdefs... `extra_hw_frames` requires FFmpeg 4.0 or higher

**Comment by zaps166** [comment]
which FFmpeg is used for compilation?

**Comment by DarkWav** [comment]
On Leap probably 3.5, I don't know. The .spec file sets requirement to 3.5, but I'll try to force 4.0, that might work. Thanks!

**Comment by zaps166** [comment]
Ok, you can try. I'll fix it soon, but without this change VA-API and VDPAU deinterlacing filters might not work properly, so I don't know how to fix it - maybe require FFmpeg >= 4.0 for VA-API and VDPAU filters...

**Comment by DarkWav** [comment]
It indeed worked, now I get an error that opensuse leap can't provide ffmpeg <= 4.0.0 and that's now SUSE's problem, not yours or mine. Factory and Tumbleweed work great.
I think I can close this now.

**Comment by zaps166** [comment]
> now SUSE's problem, not yours

I have to update README at least :)

**Comment by zaps166** [comment]
19.11.26 should compile properly now.

**Comment by DarkWav** [comment]
Thanks, adding a libavcodec dependency apparently solved the issue already, but its even better now :)
