### ISSUE TITLE
Video and audio Codecs not found 

### ISSUE THREAD

**Issue by taktiker12** [zaps166/QMPlay2#267]
since the version 18 , i could not find any codecs vp9 or h264 for videos and others for audio . does qmplay2 chooose automatically the codecs ?
Thank U
regards

**Comment by zaps166** [comment]
Version 18? Which operating system? Is QMPlay2 downloaded from github?

**Comment by taktiker12** [comment]
Ubuntu 16xenial...
With the Version 18 of qmplay2, i can choose vp9 .. But internationale
Version 19 , igot only résolutions without codecs.

Le jeu. 7 nov. 2019 à 19:58, Błażej Szczygieł <notifications@github.com> a
écrit :

**Comment by taktiker12** [comment]
Yes.. Downloaded
from github

**Comment by zaps166** [comment]
I guess that you want choose codec for YouTube videos. I removed it, codecs are chosen automatically. Why do you need it?

**Comment by taktiker12** [comment]
Today I downloaded the image app of the latest qmplay2, and run it on
ubuntu 16.04 .. Inside the app there is only prefered resolutions, unlike
with qmplay2 version 18  where I can choose resolution with codec for video
and audio..

**Comment by taktiker12** [comment]
Ok.. I understand now. The codecs are automatically choosen from the app...
Because I would like to test vdpau_vp9, that s why I am asking...
I thank you for your great work.

Le jeu. 7 nov. 2019 à 23:15, Błażej Szczygieł <notifications@github.com> a
écrit :

**Comment by zaps166** [comment]
`vdpau_vp9` should work on AppImage if you have nvidia 440.xx drivers.

If you want to test VP9 codec, set 1440p or higher (with or without 60 fps capability) and try high resolution YouTube video, e.g. search for "4k" :)

Let me know if it works.

**Comment by taktiker12** [comment]
i tried but it does not work ..
i have the nvidia-440.31 and GTX1050 Ti 4GB
i am trying to compile the version of qmpla2-18. + vdpau_vp9 patch .

**Comment by taktiker12** [comment]
sorry  ;  as you said , it works . 4k in search makes vdpau_vp9 working
when i set 2160 or 1440 .
thank you

**Comment by zaps166** [comment]
ok :)

**Comment by taktiker12** [comment]
I have à question if you allow;
Why is it possible to play 1080p with cuvid_vp9 but not with vdpau_vp9 ?


Le ven. 8 nov. 2019 à 18:16, Błażej Szczygieł <notifications@github.com> a
écrit :

**Comment by zaps166** [comment]
> Why is it possible to play 1080p with cuvid_vp9 but not with vdpau_vp9 ?

QMPlay2 19.11.06? Is it youtube? Which driver version? Can I check this video file?

**Comment by taktiker12** [comment]
with the version QMPlay2 18.12.26
<https://github.com/zaps166/QMPlay2/releases/tag/18.12.26> deb on
ubuntu-16.04 , just set priority to vp9  and play taylor swift "calm down".

**Comment by zaps166** [comment]
QMPlay2 18.12.26 doesn't support VP9 on VDPAU. You need FFmpeg 4.3 which is not released yet, VDPAU 1.3, nvidia 440.xx and QMPlay2 19.11.06. You can use my newest AppImage which is able to play it if you have recent nvidia drivers (all other dependencies are included in AppImage).

**Comment by taktiker12** [comment]
ok .
thanks

**Comment by taktiker12** [comment]
hallo
eac3 streams seem , not to be detected .is it true ?
just try watching servus tv deutschland hd , they have dolby digital plus
but the format showed on qmplay2 is AC3 .
just for fun
thank you

**Comment by zaps166** [comment]
> Es tut uns leid, der Stream ist in Ihrer Region nicht verfügbar.

I don't want to search for VPN/Proxy... Could you upload sample video? You can try download the stream in QMPlay2 (right click->extenstions->download), then go to the "Downloader" tab and cancel after a while.

**Comment by taktiker12** [comment]
Ok..

Le dim. 17 nov. 2019 à 01:17, Błażej Szczygieł <notifications@github.com> a
écrit :

**Comment by taktiker12** [comment]
https://drive.google.com/open?id=0B_BXtpPZAMrnNTd1R3I5UEdJcjVlcFJvcW8tSTBOaDVqd3k0

**Comment by zaps166** [comment]
Looks like this stream doesn't have eac3 codec. QMPlay2 (FFmpeg) reads EAC3 properly, see the sample files: https://samples.ffmpeg.org/A-codecs/AC3/eac3/. Maybe it is just not visible? Or it is a mistake?

**Comment by taktiker12** [comment]
When I have played the stream on VLC , the média codec info shows "ac3 aka"
And the avr receiver shows "Dolby d ".. Played on Kodi, i have the same
result as vlc..
But in qmplay2, there is something wrong with pass through mechanism.. The
avr does not show dolby d, even if I played normal dolby d stream.

Le dim. 17 nov. 2019 à 16:23, Błażej Szczygieł <notifications@github.com> a
écrit :

**Comment by zaps166** [comment]
Do you have the same on the captured file? or only from stream directly?

**Comment by taktiker12** [comment]
on the two ..captured and directl streaming .

**Comment by taktiker12** [comment]
what i think is that a52 not working on qmplay2

**Comment by zaps166** [comment]
How many audio streams this file really have? 3 or 4?

**Comment by zaps166** [comment]
I've got 2x MP2 (english, german - but both are german) and 1x AC3/a52 (german, 5.1 channels).  Tested on VLC, ffplay, ffprobe, QMPlay2.

**Comment by taktiker12** [comment]
3 audio streams

Le lun. 18 nov. 2019 à 18:09, Błażej Szczygieł <notifications@github.com> a
écrit :

**Comment by zaps166** [comment]
I don't know what's going on, in QMPlay2 I can select the AC3 stream in information panel (it is not selected by default) and it can play 5.1 audio.

- Did you select the AC3 stream in QMPlay2?
- Could you check if `ffplay 1_1_0_19_1332_3EF_1_C00000_0_0_0_ -ast 4 -vf yadif=1` is OK for you?

**Comment by taktiker12** [comment]
yes it plays
ffplay /home/mounir/Downloads/1_1:0:19:1332:3EF:1:C00000:0:0:0: -ast 4 -vf
yadif=1
ffplay version N-95671-gc79307b Copyright (c) 2003-2019 the FFmpeg
developers
  built with gcc 5.3.1 (Ubuntu 5.3.1-14ubuntu2) 20160413
  configuration: --enable-decoder=h264 --enable-decoder=hevc
--enable-decoder=vp9 --enable-decoder=vp8 --enable-vdpau --enable-shared
--enable-hwaccel=vp9_vdpau --enable-hwaccel=hevc_vdpau --enable-nonfree
--enable-nvenc --enable-libx264 --enable-gpl --enable-cuda --enable-cuvid
--enable-cuda-nvcc --enable-libvpx --enable-ffplay --enable-libnpp
--enable-openssl --extra-cflags=-I/usr/local/cuda/include
--extra-ldflags=-L/usr/local/cuda/lib64 --extra-cflags=-I/usr/local/include
--enable-hwaccels --enable-hwaccel=h264_vdpau
  libavutil      56. 35.101 / 56. 35.101
  libavcodec     58. 60.100 / 58. 60.100
  libavformat    58. 34.101 / 58. 34.101
  libavdevice    58.  9.100 / 58.  9.100
  libavfilter     7. 66.100 /  7. 66.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
[h264 @ 0x7f37b4027480] SPS unavailable in decode_picture_timing0
[h264 @ 0x7f37b4027480] non-existing PPS 0 referenced
[h264 @ 0x7f37b4027480] SPS unavailable in decode_picture_timing
[h264 @ 0x7f37b4027480] non-existing PPS 0 referenced
[h264 @ 0x7f37b4027480] decode_slice_header error
[h264 @ 0x7f37b4027480] no frame!
[h264 @ 0x7f37b4027480] SPS unavailable in decode_picture_timing
[h264 @ 0x7f37b4027480] non-existing PPS 0 referenced
[h264 @ 0x7f37b4027480] SPS unavailable in decode_picture_timing
[h264 @ 0x7f37b4027480] non-existing PPS 0 referenced
[h264 @ 0x7f37b4027480] decode_slice_header error
[h264 @ 0x7f37b4027480] no frame!
[h264 @ 0x7f37b4027480] SPS unavailable in decode_picture_timing
[h264 @ 0x7f37b4027480] non-existing PPS 0 referenced
[h264 @ 0x7f37b4027480] SPS unavailable in decode_picture_timing
[h264 @ 0x7f37b4027480] non-existing PPS 0 referenced
[h264 @ 0x7f37b4027480] decode_slice_header error
[h264 @ 0x7f37b4027480] no frame!
[h264 @ 0x7f37b4027480] SPS unavailable in decode_picture_timing
[h264 @ 0x7f37b4027480] non-existing PPS 0 referenced
[h264 @ 0x7f37b4027480] SPS unavailable in decode_picture_timing
[h264 @ 0x7f37b4027480] non-existing PPS 0 referenced
[h264 @ 0x7f37b4027480] decode_slice_header error
[h264 @ 0x7f37b4027480] no frame!
[h264 @ 0x7f37b4027480] SPS unavailable in decode_picture_timing
[h264 @ 0x7f37b4027480] non-existing PPS 0 referenced
[h264 @ 0x7f37b4027480] SPS unavailable in decode_picture_timing
[h264 @ 0x7f37b4027480] non-existing PPS 0 referenced
[h264 @ 0x7f37b4027480] decode_slice_header error
[h264 @ 0x7f37b4027480] no frame!
[h264 @ 0x7f37b4027480] SPS unavailable in decode_picture_timing
[h264 @ 0x7f37b4027480] non-existing PPS 0 referenced
[h264 @ 0x7f37b4027480] SPS unavailable in decode_picture_timing
[h264 @ 0x7f37b4027480] non-existing PPS 0 referenced
[h264 @ 0x7f37b4027480] decode_slice_header error
[h264 @ 0x7f37b4027480] no frame!
[h264 @ 0x7f37b4027480] SPS unavailable in decode_picture_timing
[h264 @ 0x7f37b4027480] non-existing PPS 0 referenced
[h264 @ 0x7f37b4027480] SPS unavailable in decode_picture_timing
[h264 @ 0x7f37b4027480] non-existing PPS 0 referenced
[h264 @ 0x7f37b4027480] decode_slice_header error
[h264 @ 0x7f37b4027480] no frame!
[h264 @ 0x7f37b4027480] SPS unavailable in decode_picture_timing
[h264 @ 0x7f37b4027480] non-existing PPS 0 referenced
[h264 @ 0x7f37b4027480] SPS unavailable in decode_picture_timing
[h264 @ 0x7f37b4027480] non-existing PPS 0 referenced
[h264 @ 0x7f37b4027480] decode_slice_header error
[h264 @ 0x7f37b4027480] no frame!
[h264 @ 0x7f37b4027480] SPS unavailable in decode_picture_timing
[h264 @ 0x7f37b4027480] non-existing PPS 0 referenced
[h264 @ 0x7f37b4027480] SPS unavailable in decode_picture_timing
[h264 @ 0x7f37b4027480] non-existing PPS 0 referenced
[h264 @ 0x7f37b4027480] decode_slice_header error
[h264 @ 0x7f37b4027480] no frame!
[h264 @ 0x7f37b4027480] SPS unavailable in decode_picture_timing
[h264 @ 0x7f37b4027480] non-existing PPS 0 referenced
[h264 @ 0x7f37b4027480] SPS unavailable in decode_picture_timing
[h264 @ 0x7f37b4027480] non-existing PPS 0 referenced
[h264 @ 0x7f37b4027480] decode_slice_header error
[h264 @ 0x7f37b4027480] no frame!
[h264 @ 0x7f37b4027480] SPS unavailable in decode_picture_timing
[h264 @ 0x7f37b4027480] non-existing PPS 0 referenced
[h264 @ 0x7f37b4027480] SPS unavailable in decode_picture_timing
[h264 @ 0x7f37b4027480] non-existing PPS 0 referenced
[h264 @ 0x7f37b4027480] decode_slice_header error
[h264 @ 0x7f37b4027480] no frame!
[h264 @ 0x7f37b4027480] SPS unavailable in decode_picture_timing
[h264 @ 0x7f37b4027480] non-existing PPS 0 referenced
[h264 @ 0x7f37b4027480] SPS unavailable in decode_picture_timing
[h264 @ 0x7f37b4027480] non-existing PPS 0 referenced
[h264 @ 0x7f37b4027480] decode_slice_header error
[h264 @ 0x7f37b4027480] no frame!
[h264 @ 0x7f37b4027480] SPS unavailable in decode_picture_timing
[h264 @ 0x7f37b4027480] non-existing PPS 0 referenced
[h264 @ 0x7f37b4027480] SPS unavailable in decode_picture_timing
[h264 @ 0x7f37b4027480] non-existing PPS 0 referenced
[h264 @ 0x7f37b4027480] decode_slice_header error
[h264 @ 0x7f37b4027480] no frame!
[h264 @ 0x7f37b4027480] SPS unavailable in decode_picture_timing
[h264 @ 0x7f37b4027480] non-existing PPS 0 referenced
[h264 @ 0x7f37b4027480] SPS unavailable in decode_picture_timing
[h264 @ 0x7f37b4027480] non-existing PPS 0 referenced
[h264 @ 0x7f37b4027480] decode_slice_header error
[h264 @ 0x7f37b4027480] no frame!
[h264 @ 0x7f37b4027480] SPS unavailable in decode_picture_timing
[h264 @ 0x7f37b4027480] non-existing PPS 0 referenced
[h264 @ 0x7f37b4027480] SPS unavailable in decode_picture_timing
[h264 @ 0x7f37b4027480] non-existing PPS 0 referenced
[h264 @ 0x7f37b4027480] decode_slice_header error
[h264 @ 0x7f37b4027480] no frame!
[h264 @ 0x7f37b4027480] SPS unavailable in decode_picture_timing
[h264 @ 0x7f37b4027480] non-existing PPS 0 referenced
[h264 @ 0x7f37b4027480] SPS unavailable in decode_picture_timing
[h264 @ 0x7f37b4027480] non-existing PPS 0 referenced
[h264 @ 0x7f37b4027480] decode_slice_header error
[h264 @ 0x7f37b4027480] no frame!
[h264 @ 0x7f37b4027480] SPS unavailable in decode_picture_timing
[h264 @ 0x7f37b4027480] non-existing PPS 0 referenced
[h264 @ 0x7f37b4027480] SPS unavailable in decode_picture_timing
[h264 @ 0x7f37b4027480] non-existing PPS 0 referenced
[h264 @ 0x7f37b4027480] decode_slice_header error
[h264 @ 0x7f37b4027480] no frame!
[mpegts @ 0x7f37b4000940] start time for stream 0 is not set in
estimate_timings_from_pts
[mpegts @ 0x7f37b4000940] PES packet size mismatch
    Last message repeated 2 times
[mpegts @ 0x7f37b4000940] Could not find codec parameters for stream 1
(Unknown: none ([5][0][0][0] / 0x0005)): unknown codec
Consider increasing the value for the 'analyzeduration' and 'probesize'
options
Input #0, mpegts, from
'/home/mounir/Downloads/1_1:0:19:1332:3EF:1:C00000:0:0:0:':
  Duration: 00:00:10.84, start: 60721.870022, bitrate: 9521 kb/s
  Program 4911
  Program 4912
  Program 4913
  Program 4914
    Stream #0:1[0x5b]: Unknown: none ([5][0][0][0] / 0x0005)
    Stream #0:2[0x1338]: Video: h264 (High) ([27][0][0][0] / 0x001B),
yuv420p(top first), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn,
50 tbc
    Stream #0:3[0x1339](ger): Audio: mp2 ([4][0][0][0] / 0x0004), 48000 Hz,
stereo, s16p, 160 kb/s (clean effects)
    Stream #0:4[0x133a](eng): Audio: mp2 ([4][0][0][0] / 0x0004), 48000 Hz,
stereo, s16p, 160 kb/s (clean effects)
    Stream #0:5[0x133c](ger): Audio: ac3 ([6][0][0][0] / 0x0006), 48000 Hz,
5.1(side), fltp, 384 kb/s (clean effects)
    Stream #0:6[0x133d](ger): Subtitle: dvb_teletext ([6][0][0][0] / 0x0006)
  Program 4916
  No Program
    Stream #0:0[0x12]: Data: epg
No decoder could be found for codec dvb_teletext
[h264 @ 0x7f37b403efc0] co located POCs unavailableq=    0B f=0/0
[h264 @ 0x7f37b42e05c0] reference picture missing during reorder
    Last message repeated 1 times
[h264 @ 0x7f37b42e05c0] Missing reference picture, default is 0
    Last message repeated 1 times
[h264 @ 0x7f37b41c9940] reference picture missing during reorder/0
[h264 @ 0x7f37b41c9940] Missing reference picture, default is 65584
[mpegts @ 0x7f37b4000940] PES packet size mismatch sq=    0B f=0/0

**Comment by taktiker12** [comment]
Hi blaze
Sorry if I Disturb.. If you allow, is it possible to play m3u files that
have code inside like next?

**Comment by taktiker12** [comment]
The format looks so:

http://nkdn.redi-vo.com/iptv/ch10?code=xxxxxxxxxxxxxxx&key=xxxxx

Regards

**Comment by zaps166** [comment]
The link returns an empty content

**Comment by taktiker12** [comment]
Sorry.. Qmplay2 can play this, I just test it on Android.. Fabulous😋✨
