### ISSUE TITLE
Translation files

### ISSUE THREAD

**Issue by zaps166** [zaps166/QMPlay2#270]
This issue is used for updating translations files. I'll write here before a new release if texts changes.

**Comment by zaps166** [comment]
@Lan72 @martinkg I'm adding both of you here for notifications :) Thanks for your translation files!

**Comment by zaps166** [comment]
I'm preparing QMPlay2 for the new release in next few days :)

**Comment by Lan72** [comment]
Thank you very much! Ukrainian language file updated.

**Comment by zaps166** [comment]
@Lan72 Thanks!

**Comment by Lan72** [comment]
Ukrainian language file updated.

**Comment by zaps166** [comment]
I'm preparing the new release soon, I hope english texts won't change before release. Thanks!

**Comment by martinkg** [comment]
attached is the german language file.
[de.ts.txt](https://github.com/zaps166/QMPlay2/files/4533516/de.ts.txt)

**Comment by zaps166** [comment]
Thanks!
