### ISSUE TITLE
audio passthrough 

### ISSUE THREAD

**Issue by taktiker12** [zaps166/QMPlay2#274]
hi 
i do not know if the passthrough is enabled like vlc and kodi ..or i should tweak inside qmplay2 .
thank you
regards
mounir

**Comment by zaps166** [comment]
I don't understand, I need more info :)

**Comment by taktiker12** [comment]
if i play a video stream with dolby sound on kodi or vlc , the avr receiver show this ..but on qmplay2 , it does not do this .

**Comment by zaps166** [comment]
Is it still Ubuntu 16.04 as in #267? Do you use PulseAudio on your OS?

**Comment by zaps166** [comment]
Try this (don't forget to press "Apply" on every step!):

Disable: ![Screenshot_20191223_220346](https://user-images.githubusercontent.com/6239090/71380586-1b51ea80-25d0-11ea-9048-df2621274be7.png)
and put ALSA as first: ![Screenshot_20191223_220504](https://user-images.githubusercontent.com/6239090/71380617-489e9880-25d0-11ea-85ce-b73fd8726ae8.png)

Try various ALSA settings, like: ![Screenshot_20191223_220542](https://user-images.githubusercontent.com/6239090/71380645-623fe000-25d0-11ea-806b-bbde912df0cf.png)

**Comment by zaps166** [comment]
OR use PulseAudio and set 5.1 or 7.1 output in `pavucontrol`:
![Screenshot_20191223_220917](https://user-images.githubusercontent.com/6239090/71380793-ec884400-25d0-11ea-8354-7b9954fe2ab2.png)

**Comment by taktiker12** [comment]
thank you . i will try and give feedback

**Comment by taktiker12** [comment]
i am in 18.04

**Comment by taktiker12** [comment]
i do not have spdif on mobo ..
 am relaying hdmi out from mobo to hdmi in audio extractor ..from audio extractor , there is spdif out that i connect to spdif in of denon avr receiver .
i do not have arc hdmi on tv and avr .

**Comment by zaps166** [comment]
And... does it finally work? :D

**Comment by taktiker12** [comment]
no it does not work

**Comment by taktiker12** [comment]
do you understand my audio connection from pc to avr ?

**Comment by zaps166** [comment]
> do you understand my audio connection from pc to avr ?

Is it something like this: https://audio.com.pl/i/images/5/3/1/YWRkPTUyMng1MjJ4ZmZmZmZm_src_44531-amplituner-av-denon-avr-x3300w-audiocompl-fot.jpg

?

**Comment by taktiker12** [comment]
yes ..denon 1908

**Comment by taktiker12** [comment]
a good beast

**Comment by zaps166** [comment]
In next few weeks I'll probably have access to Onkyo...

**Comment by zaps166** [comment]
Did you manually choose the `Stream 3` in the Information panel?

On HD Audio multichannel works properly, I can hear it properly (left/right, center, etc.):

![Screenshot_20191223_224555](https://user-images.githubusercontent.com/6239090/71381926-0b3d0980-25d6-11ea-8054-fa2f33c67c6d.png)
![Screenshot_20191223_224546](https://user-images.githubusercontent.com/6239090/71381927-0bd5a000-25d6-11ea-81b4-9569e0ff2a82.png)
![Screenshot_20191223_224536](https://user-images.githubusercontent.com/6239090/71381928-0bd5a000-25d6-11ea-9c0f-9d2654eaab9c.png)

Sorry for the Polish language screens :D

**Comment by taktiker12** [comment]
try onkyo who can decode bitstreams 
but your mainboard hast more then on audio output

**Comment by taktiker12** [comment]
i choose the stream 3 reserved for ac3 ..but no soound

**Comment by taktiker12** [comment]
do you have something like "sync to display" on settings ?

**Comment by zaps166** [comment]
I connected my notebook (Huawei Matebook D14 with Kernel 5.4) via HDMI to LG TV, I chose 5.1 in `pavucontrol` and I heard front channels only (I don't have 5.1speakers, only stereo).

> i choose the stream 3 reserved for ac3 ..but no soound

Do you use pulseaudio in your OS (most distributions including Ubuntu uses it by default)? Could you run `pavucontrol` (install if not exists)? How QMPlay2 is configured - if you use pulseaudio it should be configured to default settings.

**Comment by zaps166** [comment]
> do you have something like "sync to display" on settings ?

You can use FreeSync or G-Sync if Monitor/TV supports it. For 50 Hz video (like yours after deinterlacing) it syncs perfectly on QMPlay2 (be sure to bypass the compositor in OpenGL2 settings - but some compositor doesn't allow this).

Otherwise you need to choose it manually in your OS display settings or via `xrandr`.

At least I can add this option, but for Linux/X11 only :D

**Comment by taktiker12** [comment]
i do not have freesync and gsync ..
i revert to pulseaudio ..it is ok 
thank you for your help .

**Comment by taktiker12** [comment]
denon has a good dsp , it can change stereo to dolby prologic22222 and dts neo .

**Comment by zaps166** [comment]
> i revert to pulseaudio ..it is ok

does it work properly now?

**Comment by taktiker12** [comment]
with pulseaudio ac3 works good

**Comment by taktiker12** [comment]
good night blazej .
do you know TYMBARK ?

**Comment by zaps166** [comment]
> with pulseaudio ac3 works good

ok, so the issue is fixed :)

**Comment by zaps166** [comment]
> do you know TYMBARK ?

https://en.wikipedia.org/wiki/Tymbark_(company)

?

**Comment by taktiker12** [comment]
yes ..i buy this drink ..very good product from poland

**Comment by zaps166** [comment]
> yes ..i buy this drink ..very good product from poland

yes :)

**Comment by zaps166** [comment]
> "sync to display"

you can create a separate feature request about this.

---

Btw. I have Grundig V1000 & V2000 stereo ampli :D

**Comment by taktiker12** [comment]
how do you connect your pc to grundig ?

**Comment by taktiker12** [comment]
with green line out ?

**Comment by taktiker12** [comment]
i bought avr denon1908 for 100€ in morocco  and jbl 5.1 system for 110 € from germany.it is okay

**Comment by taktiker12** [comment]
you can mark so far the issue as fixed . i thank you very much

**Comment by taktiker12** [comment]
Good night and good luck

**Comment by zaps166** [comment]
> how do you connect your pc to grundig ?

DIN to audio jack cable, directly to MOBO, ALC1220 (green output) or to TV headphone output :D

---

good night

**Comment by taktiker12** [comment]
Hallo blazej
It is possible to yadifx2 to cuvid?
Thanx

Le lun. 23 déc. 2019 à 23:50, Błażej Szczygieł <notifications@github.com> a
écrit :

**Comment by zaps166** [comment]
> It is possible to yadifx2 to cuvid?

When you copy data to host memory (can be very slow, check CUVID settings).
Using Yadif on CUDA is currently not possible in QMPlay2 (AFAIK it is already in libavfilter).

Why NVIDIA deinterlacing filter is not good for you?
CUVID deinterlacing settings: ![Screenshot_20191227_122824](https://user-images.githubusercontent.com/6239090/71515615-699f0c00-28a4-11ea-8d64-367c245ec23a.png)
Check this if you want to use CPU filters (not recommended): ![Screenshot_20191227_122854](https://user-images.githubusercontent.com/6239090/71515630-7e7b9f80-28a4-11ea-88fc-21839ac3ac74.png)

---

Maybe in the future I will add Vulkan support and compute shaders for filters (like yadif on GPU).

**Comment by taktiker12** [comment]
hi
it is possible to add 4.1 on playback like kodi .
thank you .


Le ven. 27 déc. 2019 à 12:29, Błażej Szczygieł <notifications@github.com> a
écrit :

**Comment by zaps166** [comment]
> hi
it is possible to add 4.1 on playback like kodi .
thank you .

I'll think about it. I don't have audio samples for this and I never used 4.1.

---

> Hallo blazej
It is possible to yadifx2 to cuvid?
Thanx

It should work on temporary vulkan branch.
