### ISSUE TITLE
radio-browser support

### ISSUE THREAD

**Issue by segler-alex** [zaps166/QMPlay2#278]
thank you for adding radio-browser.info
i am the admin of radio-browser, if you have any questions please feel free to ask, or suggest improvements.
greetings from vienna/austria!

**Comment by segler-alex** [comment]
i added qmplay2 to the link list on radio-browser.info

**Comment by segler-alex** [comment]
the issue page is on
https://github.com/segler-alex/radiobrowser-api-rust

**Comment by segler-alex** [comment]
one thing
it would be nice if you would call the following after a station click, so the click will get counted:

http://www.radio-browser.info/webservice/v2/xml/url/stationuuid
example:
http://www.radio-browser.info/webservice/v2/xml/url/9617a958-0601-11e8-ae97-52543be04c81

always use "stationuuid" instead of "id" field

**Comment by zaps166** [comment]
Hi!

> i added qmplay2 to the link list on radio-browser.info

thanks!

I'll check your suggestions later :)

**Comment by lupusic** [comment]
I couldn't list and listen to radio. Could you please elaborate how to do?

**Comment by segler-alex** [comment]
simple example:
http://de1.api.radio-browser.info/json/stations/topclick/5

**Comment by lupusic** [comment]
Thanks for your prompt answer Alex. I thought it's a "download it and use it" type of software. Now I understand it is not for me since I'm not a coder. Thanks for your time. Regards

**Comment by zaps166** [comment]
I don't understand what's going on here.

All info provided by @segler-alex are for developer (me), not for user @lupusic .

However I can use radio browser in QMPlay2, so what's your issue @lupusic ?

- click "Internet radios" tab (if you don't have it - use "Widgets" menu to enable it)
- use the search bar to search for radios (combo box on the left changes search criteria)
- press Enter key and wait for results
- double click to listen

You can also drag and drop found radio station to "My radio stations" panel.

**Comment by lupusic** [comment]
Thanks a lot Błażej..
"press Enter key and wait for results" solved my problem. I waited 3-5 seconds and it worked.
Probably some other middle level intelligence guys (like me) may not fint out to "press Enter key in an empty Search Bar area"
Brilliant, it is working very well. I appreciate
