### ISSUE TITLE
very slow load on windows

### ISSUE THREAD

**Issue by neon9999** [zaps166/QMPlay2#281]
hi. installed latest version on windows 7 x64 .
but every time open qmplay2, its slow and getting time to open, (8 seconds)
and when open video or audio files  its not responds for seconds and overally is slow in start!
system hardware is powerful.  
core i5 . 8gb ram
gpu driver is up to date.
qmplay is very fast and good player but in startup and load up files is weak!

**Comment by zaps166** [comment]
Is the first QMPlay2 load slow or is every QMPlay2 load slow?

**Comment by neon9999** [comment]
only in first load.after first load on every windows boot,its ok .
when come back to windows from shot down or hibernate,its slow on load again.
