### ISSUE TITLE
Some QLineEdit Translations Missing

### ISSUE THREAD

**Issue by zo-shin** [zaps166/QMPlay2#288]
The translation files for **Hungarian** and **Chinese** are missing in the directory of **translations**.

**Comment by zaps166** [comment]
I don't understand, could you explain?

**Comment by zo-shin** [comment]
The context menus of the text edit field are all localized except Hungarian and Chinese because their translation files are missing. Please go to the "translations" folder of QMPlay2, and you'll find there are two languages missing.

**Comment by zaps166** [comment]
Ok, so it is a Windows package issue.

**Comment by zo-shin** [comment]
It’s due to the incompleteness of the translation file qtbase_xx.ts.
