### ISSUE TITLE
Option to enable mouse scroll wheel from changing volume on screen

### ISSUE THREAD

**Issue by varlesh** [zaps166/QMPlay2#29]
This available on QMPlay2? Please add this option :)

**Comment by zaps166** [comment]
So mouse wheel should change the volume instead of seeking?

**Comment by varlesh** [comment]
Maybe better create togglebutton - volume/seek.

**Comment by zaps166** [comment]
Yes as an option. Ok, I'll do it :)

**Comment by varlesh** [comment]
Big thx, that's will be very comfortably!

**Comment by zaps166** [comment]
Ok! You can also use "/" and "*" keys (key bindings in TODO...)

**Comment by varlesh** [comment]
Yes i know, but mostly players use mouse scroll wheel from changing volume as default and i used to it

**Comment by zaps166** [comment]
Please reinstall `qmplay2-git` from AUR and test :)

**Comment by varlesh** [comment]
Thx, Ok

**Comment by varlesh** [comment]
@zaps166 Working fine 👍
