### ISSUE TITLE
Appimage GLIBC  2.17 support

### ISSUE THREAD

**Issue by h1z1** [zaps166/QMPlay2#294]
Is it possible to lower the required glibc version to 2.17?  It would add support for CentOS, RHEL, etc.

The delicious irony of packing like appimage is it's not really portable *sigh*

I tried to compile but that too fails with some errors I'm assuming are gcc related.

**Comment by zaps166** [comment]
It's very difficult to achieve. I have Ubuntu (IIRC 16.04) Docker image with GCC 5.x and compiled all dependencies. Lowering Ubuntu version and compiling much more dependencies for older OS isn't what I want to do for lowering the glibc minimum version :smile: I'm also not sure if it will work.
Moreover I think about introducing C++17 (it is more convenient and I can do some minor optimizations...).

> I tried to compile but that too fails with some errors I'm assuming are gcc related.

Which compiler version do you use? At least you can try clang. Could you paste the compile error log?

**Comment by h1z1** [comment]
Understood.  It's not the compiler that is the problem though, it's glibc.


> Which compiler version do you use? At least you can try clang. Could you paste the compile error log?

gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC) 

https://gist.github.com/h1z1/4f923b21bacc5f6940ed213d24039cde

**Comment by zaps166** [comment]
Sorry, your OS os too old for VA-API in QMPlay2... You have to upgrade libva and also mesa drivers and all other dependencies to get it work. Current master branch requires libva 2.1.0 (vaapi 1.1.0).

The GCC errors are weird, for me works on old GCC 7.x (Mingw) and GCC 5.x (Linux).

---

Maybe it's time to drop `CppUtils.hpp` with Qt 5.6.x and Windows XP ? :laughing:

**Comment by h1z1** [comment]
o_O   I recompiled them fine.  Spose it would make more sense to detect and warn about it though?

Just have to find out why jack doesn't work now heh.

**Comment by zaps166** [comment]
Could you check this: https://github.com/zaps166/QMPlay2/commit/4a51382c11dddb8d5b355875d4d5037bdcf77a57 ?

> Just have to find out why jack doesn't work now heh.

Jack? IIRC you need to compile PortAudio modeule (disabled by default).

**Comment by h1z1** [comment]
> Could you check this: 4a51382 ?

That works too.

> Jack? IIRC you need to compile PortAudio modeule (disabled by default).

Had no idea about portaudio support.  Was using the alsa module.  It refuses to connect for some reason, no issues with other applications *shrug*.     Tried compiling with it though it does build, there are a lot of errors I can only assume are API related.

[for shits](https://gist.github.com/h1z1/6f29e7328038f78db19b1cd8dfcf02d8)

**Comment by zaps166** [comment]
hmmm
