### ISSUE TITLE
What libva and intel-vaapi version are required nowadays?

### ISSUE THREAD

**Issue by RJVB** [zaps166/QMPlay2#301]
I tried to build git/master last week and got a build failure that led me to believe that I needed to upgrade to libva 2.x (I didn't write down the exact error). Took me a while but today I tried to build the current HEAD again, against libva 2.6.1 . This built, but I now get a runtime error:

```
libva info: VA-API version 0.40.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_40
libva info: va_openDriver() returns 0
VA-API :: Unsupported deinterlacing algorithm - Motion adaptive
[26 Mar 2020 15:46:40.316] VA-API :: Unable to export surface handle
[26 Mar 2020 15:46:40.541] OpenGL 2 :: VA-API texture map error
```

At first I thought my i965 driver was too old , so I updated that one (intel-vaapi) from 1.8.3 to 2.1.0 ... and discovered that QMplay2 doesn't at all use libva2 but still the older libva1 I kept installed (and that marvelously work with the libva2 headers, somehow).

As  a result I'm back to using the last known-to-work version, a9af85b093a3bdd6ef530ccc1f5cac31c4699c43 .

**Comment by zaps166** [comment]
Something is wrong, I have to check it

**Comment by zaps166** [comment]
Ah, I removed GLX support in db576a60d0f3fdd0a6c1cb03428f90d3e55f6ba7, you have too old driver version (not libva itself). You need `vaExportSurfaceHandle` now.

**Comment by zaps166** [comment]
Could you check if db576a6 breaks this?

**Comment by zaps166** [comment]
You need va 1.1.0 / 2.1.0 (I really don't understand vaapi versioning :laughing: - why it has two versions??)

**Comment by RJVB** [comment]
>Could you check if db576a6 breaks this?

Must be it, yes.

I'm beginning to get the impression I just might have to rebuild ffmpeg against the newer libva (as I said, I have updated it to 2.6.1):

```
> ldd libFFmpeg.so | fgrep libva
        libva-glx.so.2 => /usr/lib/x86_64-linux-gnu/libva-glx.so.2 (0x00007f0667874000)
        libva-drm.so.2 => /usr/lib/x86_64-linux-gnu/libva-drm.so.2 (0x00007f0667671000)
        libva.so.2 => /usr/lib/x86_64-linux-gnu/libva.so.2 (0x00007f066744b000)
        libva.so.1 => /usr/lib/x86_64-linux-gnu/libva.so.1 (0x00007f065fb1e000)
        libva-drm.so.1 => /usr/lib/x86_64-linux-gnu/libva-drm.so.1 (0x00007f065f91b000)
        libva-x11.so.1 => /usr/lib/x86_64-linux-gnu/libva-x11.so.1 (0x00007f065f715000)
        libva-x11.so.2 => /usr/lib/x86_64-linux-gnu/libva-x11.so.2 (0x00007f065df63000)
```

**Comment by RJVB** [comment]
OK, so the issue was indeed that my ffmpeg binaries were still linked against the older libva...
