### ISSUE TITLE
What  build tools does  the  windows release use?

### ISSUE THREAD

**Issue by lovelypp777** [zaps166/QMPlay2#305]
to use mingw or msvc2017 ?

thanks！

**Comment by zaps166** [comment]
msvc2017 is not supported
mingw - use Linux for cross-compilation, e.g. Arch Linux has mingw packages in AUR

Or install Qt on Windows from online installer and choose mingw 64 bit and prepare FFmpeg libs (and other dependencies) on your own. Then set proper paths for CMake.

**Comment by lovelypp777** [comment]
thank you. 
When I open CMakeLists.txt using qtcreator(4.10.2, build tools mingw 64), it's failed as following: 
Build type: Debug
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
TAGLIB_INCLUDE_DIR (ADVANCED)
   used as include directory in directory E:/qmplay2/QMPlay2-19.12.19/src/gui
   used as include directory in directory E:/qmplay2/QMPlay2-19.12.19/src/gui
   used as include directory in directory E:/qmplay2/QMPlay2-19.12.19/src/gui
   used as include directory in directory E:/qmplay2/QMPlay2-19.12.19/src/gui
   used as include directory in directory E:/qmplay2/QMPlay2-19.12.19/src/gui
   used as include directory in directory E:/qmplay2/QMPlay2-19.12.19/src/gui
   used as include directory in directory E:/qmplay2/QMPlay2-19.12.19/src/gui
TAGLIB_LIBRARY (ADVANCED)
    linked by target "QMPlay2" in directory E:/qmplay2/QMPlay2-19.12.19/src/gui

Configuring incomplete, errors occurred!

I have compiled taglib, which is located in e:\taglib，I don't know where to add the location in qtcreator to sovle the up problem. Is it ot modiy settings in qt creator  or modify the CMakeLists.txt file directly?  Can you give me a hint ? Thanks in advance

**Comment by zaps166** [comment]
Example (try to add top of the main CMakeLists below the first line):
```
include_directories(C:/path/to/include)
link_directories(C:/path/to/libs)
```
and click run cmake and try again

**Comment by zaps166** [comment]
also add path with include dirs to `PATH` envvar for build environment

**Comment by lovelypp777** [comment]
add path with include dirs to PATH envvar for build environment <---
the PATH envvar is used to locate dll or exe,  do you mean to add path with **lib** dirs to PATH ?

**Comment by lovelypp777** [comment]
I add two line in the main CMakeLists.txt as following:
`cmake_minimum_required(VERSION 3.1)
project(QMPlay2)

**include_directories("E:/old/QMPlay2-pro/build/include")
include_directories("E:/old/QMPlay2-pro/build/include/taglib")**

if(NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE "Release")
endif()
`
but when execute CMake, it still complians error:
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
**TAGLIB_INCLUDE_DIR (ADVANCED)**
   used as include directory in directory E:/qmplay2/QMPlay2-19.12.19/src/gui
   used as include directory in directory E:/qmplay2/QMPlay2-19.12.19/src/gui
   used as include directory in directory E:/qmplay2/QMPlay2-19.12.19/src/gui
   used as include directory in directory E:/qmplay2/QMPlay2-19.12.19/src/gui
   used as include directory in directory E:/qmplay2/QMPlay2-19.12.19/src/gui
   used as include directory in directory E:/qmplay2/QMPlay2-19.12.19/src/gui
   used as include directory in directory E:/qmplay2/QMPlay2-19.12.19/src/gui
**TAGLIB_LIBRARY (ADVANCED)**
    linked by target "QMPlay2" in directory E:/qmplay2/QMPlay2-19.12.19/src/gui

Configuring incomplete, errors occurred!

**Comment by zaps166** [comment]
>  do you mean to add path with lib dirs to PATH

Include path to build `PATH` (cmake can find includes in path), DLLs path and `libqmplay2.dll` path from build directory to run `PATH`.

**Comment by lovelypp777** [comment]
dou you mean set(CMAKE_INCLUDE_PATH "include_path") & set(CMAKE_LIBRARY_PATH "lib_path") ?
thanks

**Comment by zaps166** [comment]
Software development on Windows is much more difficult, especially for cross-platform software and it is IMHO inconvenient... QMPlay2 Windows compile guideline doesn't exist.

I develop the player on Linux and I use cross-compiler to build it for Windows. Moreover if I need to develop on Windows (e.g. DirectX) I can link to DLLs I use for cross-compilation and prepare the environment myself (install Qt with GCC compiler, set paths, etc). I even don't remember how to configure it properly, so I need to configure everything from scratch to write you the instruction...

---

Maybe I'll simplify CMake for Windows in the future and write the instruction, but not now...

---

To compile it on Windows:
- install Qt (64-bit, MinGW) from their online installer (now you have to use your Qt account)
- use QtCreator
- obtain/compile additional includes, link libraries and DLLs (64-bit, compiled by MinGW/GCC); FFmpeg is mandatory, libass is highly recommended (with its dependencies like libfreetype), other libs are optional - depends what you need
- set paths to includes and link libraries (global `PATH` for **build** environment and CMake paths) - read my previous posts
- set global `PATH` for **run** environment for additional DLLs **and** for compiled `libqmplay2.dll` somewhere inside the build directory (for Release **or** Debug build - choose the directory you actually build and use)

**Comment by lovelypp777** [comment]
thanks a lot.
It's great if you provide a manual on howto compile on windows using qt creator.

**Comment by zaps166** [comment]
Windows compilation instruction: https://github.com/zaps166/QMPlay2/wiki/Compilation-on-Windows-x86-64

It works only for master branch, not for the 20.07.04 release
