### ISSUE TITLE
grey border on bottom, left and right in fullscreen

### ISSUE THREAD

**Issue by MPdaedalus** [zaps166/QMPlay2#310]
Hi

There is an issue with qmplay2 that i've had for years but never managed to fix, When I go fullscreen there is a 3-4 pixel dark grey border at the edge of the screen except the top an I can not get rid of it. VLC does not do this.

Qmplay2 19.12.19 on fedora 31  video output priority opengl2 and decoder priority VDPAU and then ffmpeg.  radeon 6800 turks xt graphics card.

**Comment by zaps166** [comment]
Hi

I need more info and a screenshot.

- does it happen for all videos?
- how does it work on CPU decoder and OpenGL (non-VDPAU) or on CUVID?
- which Qt style do you use - could you check "Fusion" style (and restart the application after changing the style)?
- do you use QMPlay2 from repositories, from AppImage or is it compiled by you?

---

Are you able to compile QMPlay2 master and try Vulkan video output (but VDPAU is unavailable in Vulkan)?

**Comment by zaps166** [comment]
> or on CUVID

Sorry, you use VDPAU, but it is Radeon, so CUVID is not available. Try VA-API instead.

**Comment by zaps166** [comment]
Check on "Information" panel for info which decoder and video output is used.

**Comment by MPdaedalus** [comment]
problem solved, I was using adwaita-dark it was the theme that causes the borders, adwaita, adwaita-dark and qt5ct all cause the borders but windows and fusion theme does not. Luckily I was able to darken the fusion theme in qt5 prefs. Changing the render made no difference although I will now use VA-API as it works and it never used VDPAU and fell through to ffmpeg cpu.  I must have checked the themes before but not restarted as it changes the themes without restarting but restart is required for borders to disappear.  Thanks for your help and for maintaining QMPlay2. FYI I always to the official fedora repository for QMPlay2 as it is kept up to date.

**Comment by zaps166** [comment]
Fixed, thanks for the bug report. Many years ago I've made a workaround for Breeze style, but there are other styles with the same issue. Now this is (I hope) properly fixed.
