### ISSUE TITLE
stop playlist becoming visible in fullscreen

### ISSUE THREAD

**Issue by MPdaedalus** [zaps166/QMPlay2#311]
Hi

I haven't found and option for it but maybe i'm blind but how do you stop the playlist from showing when you move your mouse to the left border in fullscreen mode, I have a dual monitor setup so keep moving the mouse to the left border, I also accidentally activate it when I click play or pause sometimes which is annoying.

**Comment by zaps166** [comment]
Not possible so far.

Do you have HiDPI screen?
