### ISSUE TITLE
Build Failure on i586 architecture (openSUSE)

### ISSUE THREAD

**Issue by DarkWav** [zaps166/QMPlay2#313]
I've been trying to build the latest QMPlay2 master on openSUSE's Build Service again and it works great on ARM, PPC64LE and x86_64, but on i586 the following error occurs:

> [  244s] [ 64%] Linking CXX shared module libExtensions.so
> [  244s] cd /home/abuild/rpmbuild/BUILD/QMPlay2-src-19.12.19+git.1587895757.517345fc/build/src/modules/Extensions && /usr/bin/cmake -E cmake_link_script CMakeFiles/Extensions.dir/link.txt --verbose=1
> [  244s] /usr/bin/g++ -fPIC -Wall -fomit-frame-pointer -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -DNDEBUG -O2 -g -DNDEBUG -flto=auto -Wl,--as-needed -shared  -o libExtensions.so CMakeFiles/Extensions.dir/Extensions_autogen/mocs_compilation.cpp.o CMakeFiles/Extensions.dir/Extensions.cpp.o CMakeFiles/Extensions.dir/YouTube.cpp.o CMakeFiles/Extensions.dir/Downloader.cpp.o CMakeFiles/Extensions.dir/Radio.cpp.o CMakeFiles/Extensions.dir/Radio/RadioBrowserModel.cpp.o CMakeFiles/Extensions.dir/MPRIS2.cpp.o CMakeFiles/Extensions.dir/LastFM.cpp.o CMakeFiles/Extensions.dir/Lyrics.cpp.o CMakeFiles/Extensions.dir/MediaBrowser.cpp.o CMakeFiles/Extensions.dir/MediaBrowserJS.cpp.o CMakeFiles/Extensions.dir/Extensions_autogen/EWIEGA46WW/qrc_icons.cpp.o CMakeFiles/Extensions.dir/Extensions_autogen/EWIEGA46WW/qrc_js.cpp.o  -Wl,-rpath,/home/abuild/rpmbuild/BUILD/QMPlay2-src-19.12.19+git.1587895757.517345fc/build/src/qmplay2: ../../qmplay2/libqmplay2.so /usr/lib/libQt5DBus.so.5.14.1 /usr/lib/libQt5Qml.so.5.14.1 /usr/lib/libQt5Network.so.5.14.1 /usr/lib/libQt5Svg.so.5.14.1 /usr/lib/libQt5Widgets.so.5.14.1 /usr/lib/libQt5Gui.so.5.14.1 /usr/lib/libQt5Core.so.5.14.1 -lavformat -lavcodec -lswscale -lavutil -lswresample ../../qmvk/libQmVk.a 
> [  246s] /home/abuild/rpmbuild/BUILD/QMPlay2-src-19.12.19+git.1587895757.517345fc/src/modules/FFmpeg/VDPAUOpenGL.cpp: In member function 'virtual bool VDPAUOpenGL::mapFrame(Frame&)':
> [  246s] /home/abuild/rpmbuild/BUILD/QMPlay2-src-19.12.19+git.1587895757.517345fc/src/modules/FFmpeg/VDPAUOpenGL.cpp:132:33: error: invalid conversion from 'intptr_t*' {aka 'int*'} to 'const GLvdpauSurfaceNV*' {aka 'const long int*'} [-fpermissive]
> [  246s]   132 |         VDPAUUnmapSurfacesNV(1, &displayingOutputSurface->glSurface);
> [  246s]       |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> [  246s]       |                                 |
> [  246s]       |                                 intptr_t* {aka int*}
> [  246s] /home/abuild/rpmbuild/BUILD/QMPlay2-src-19.12.19+git.1587895757.517345fc/src/modules/FFmpeg/VDPAUOpenGL.cpp:163:27: error: invalid conversion from 'intptr_t*' {aka 'int*'} to 'const GLvdpauSurfaceNV*' {aka 'const long int*'} [-fpermissive]
> [  246s]   163 |     VDPAUMapSurfacesNV(1, &outputSurface.glSurface);
> [  246s]       |                           ^~~~~~~~~~~~~~~~~~~~~~~~
> [  246s]       |                           |
> [  246s]       |                           intptr_t* {aka int*}
> [  246s] /home/abuild/rpmbuild/BUILD/QMPlay2-src-19.12.19+git.1587895757.517345fc/src/modules/FFmpeg/VDPAUOpenGL.cpp: In member function 'void VDPAUOpenGL::deleteGlSurface(VDPAUOutputSurface&)':
> [  246s] /home/abuild/rpmbuild/BUILD/QMPlay2-src-19.12.19+git.1587895757.517345fc/src/modules/FFmpeg/VDPAUOpenGL.cpp:233:33: error: invalid conversion from 'intptr_t*' {aka 'int*'} to 'const GLvdpauSurfaceNV*' {aka 'const long int*'} [-fpermissive]
> [  246s]   233 |         VDPAUUnmapSurfacesNV(1, &surface.glSurface);
> [  246s]       |                                 ^~~~~~~~~~~~~~~~~~
> [  246s]       |                                 |
> [  246s]       |                                 intptr_t* {aka int*}
> [  246s] make[2]: *** [src/modules/FFmpeg/CMakeFiles/FFmpeg.dir/build.make:318: src/modules/FFmpeg/CMakeFiles/FFmpeg.dir/VDPAUOpenGL.cpp.o] Error 1
> [  246s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/QMPlay2-src-19.12.19+git.1587895757.517345fc/build'
> [  246s] make[1]: *** [CMakeFiles/Makefile2:745: src/modules/FFmpeg/CMakeFiles/FFmpeg.dir/all] Error 2
> [  246s] make[1]: *** Waiting for unfinished jobs....

**Comment by zaps166** [comment]
Could you apply this patch and check again?

```diff
diff --git a/src/modules/FFmpeg/VDPAUOpenGL.hpp b/src/modules/FFmpeg/VDPAUOpenGL.hpp
index 2a03e46a..e4c6496e 100644
--- a/src/modules/FFmpeg/VDPAUOpenGL.hpp
+++ b/src/modules/FFmpeg/VDPAUOpenGL.hpp
@@ -59,7 +59,7 @@ private:
     void deleteGlSurface(VDPAUOutputSurface &surface);
 
 private:
-    using GLvdpauSurfaceNV = GLintptr;
+    using GLvdpauSurfaceNV = intptr_t;
 
     std::shared_ptr<VDPAU> m_vdpau;
 
```

**Comment by DarkWav** [comment]
Thanks, I will try if it works.

**Comment by DarkWav** [comment]
The build on i586 works fine with the patch in place. Will you merge it into the master?

**Comment by zaps166** [comment]
Fixed :)
