### ISSUE TITLE
progress bar WavPack

### ISSUE THREAD

**Issue by wcasanova** [zaps166/QMPlay2#316]
progress bar no working  WavPack files..

Audio
Format                                   : WavPack
Format profile                           : 4.06
Format settings                          : Lossless
Duration                                 : 5 min 31 s
Bit rate mode                            : Variable
Bit rate                                 : 9 205 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 192 kHz
Bit depth                                : 32 bits
Compression ratio                        : 1.335
Stream size                              : 364 MiB (100%)
Encoding settings                        : -h -m

FFmpeg, PulseAudio
codec: wavpack
Sampling rate : 192000Hz
Channel(s): estereo
formato: s32p

![imagen](https://user-images.githubusercontent.com/12401985/80896746-971b1c80-8cbf-11ea-9371-e8426b43a3ac.png)

**Comment by zaps166** [comment]
Can't reproduce, could you upload your file?

**Comment by wcasanova** [comment]
[file.wv](https://upload.disroot.org/r/xmam2zTn#NJEgT9NvwCO/dieShOXd6skTJ50oXL6XeHmVCch03zg=)

**Comment by zaps166** [comment]
Ok... This file is weird, I have a working workaround for it, but is the file really OK? I decompressed it and compressed again to WV and the new file is working properly. Do you have more files? Or some special compression flags or something to reproduce the issue?

If this file is not corrupted I can push the workaround/fix, but I want to know the file is ok.

**Comment by wcasanova** [comment]
all the files in that album give the same error, but qmplay2 plays other * .wav files well, the fault is with this encode only, the funny thing is that deadbeef and cantata, the progress bar works, but if you like I could upload another file from the same album.

I saw the same problem also with vlc and mpv. using this album / encode

**Comment by zaps166** [comment]
Now QMPlay2 should read the duration properly, could you check it?

**Comment by wcasanova** [comment]
it works thank you
