### ISSUE TITLE
What's the minimum required version of ffmeg now?

### ISSUE THREAD

**Issue by stevenpusser** [zaps166/QMPlay2#323]
It used to be 3.3, so I tried building 20.05.02 against MX 17's ffmpeg 3.4 as usual, and CMake accepted that. But the build failed down the line with what looked like a ffmpeg-type error, so I then tried building against ffmpeg's 4.2.1 from its test repo, which succeeded.

Update: Seems that something else was causing the error, since it doesn't have any problem with Ubuntu 18.04's 3.4.2 on my OBS builds: https://build.opensuse.org/package/show/home:stevenpusser:QMPlay2/qmplay2

BTW, you may want to point Debian and Ubuntu 32-bit and ARM users to my OBS repo, since I don't see any packages for those guys listed.

**Comment by zaps166** [comment]
I tested FFmpeg 3.x compilation with 3.x libraries and 4.2 headers, sorry :D

**Comment by zaps166** [comment]
Could you use the patch 2002903 and try again?
