### ISSUE TITLE
OSD Notifications Not Work on Certain Conditions

### ISSUE THREAD

**Issue by zo-shin** [zaps166/QMPlay2#329]
Hide the tray icon. When the player is idle, perform some notification operations like changing volume, the OSD notifications don’t work. When audio files are played, they don’t work, either.

**Comment by zaps166** [comment]
I don't understand. Could you upload a GIF?

OSD works only on video content.

**Comment by zo-shin** [comment]
Can it be useful to make it work on audio files?

**Comment by notramo** [comment]
Duplicate of #176
