### ISSUE TITLE
CMake should create OS X bundle

### ISSUE THREAD

**Issue by zaps166** [zaps166/QMPlay2#33]

**Comment by arthurzam** [comment]
I would like to ask you to comment and attach those files (If you can):

1. OS X bundle files (I mean what should be in the resulting - so I know to where to go). Also the list of resulting `make install ...` on OS X (like if you configure cmake -> make -> `make install DESTDIR=...`). 
2. NSIS creating scripts
3. If it is possible, all other building scripts or configurations files. The more the easier for me.

About the bundle - CMake should have something builtin for this, but I have no idea how to check the results and/or how it handles now. Is there something like mingw-w64 on Arch but for OS X?

About the building scripts - I need those to get the needed configuration (like Name, Author, Vendor, Contact Info, etc). I prefer that the result would be identical to your NSIS build, but a little more automatic and versatile.

Also about depending dll for Windows. I managed to create a Unix script (Windows scripting isn't my forte) for printing all the recursive dll depends (excluding system libs). CMake has something builtin, but when I was checking on Arch with mingw-w64, there were problems with distinguishing system libs (like `KERNEL32.dll`) from not system (I used the check of `"^[A-Z0-9]*.dll$"` is a system one). And in case it distinguishes, we need to continue in recursive check and etc. Many hack had to be done to make it possible to find the dlls. Even though a Unix script isn't portable, I guess it is the only option.
Do you prefer building QMPlay2 package on Windows or on Linux using cross compiling?

**Comment by zaps166** [comment]
> Is there something like mingw-w64 on Arch but for OS X?

I can't see anything for OS X cross compilation, is it possible? You can run OSX on VirtualBox or I can test it :)

> I prefer that the result would be identical to your NSIS build

Where is my NSIS build ? :smiley: I've got my own installer (WinAPI+Qt4+7-Zip SDK for compression algorithm).

Name you know - QMPlay2 :smile:
Author is on GitHub
Vendor - the same as author?
Contact info - also on github (email)

> Also about depending dll for Windows. I managed to create a Unix script(...)

I've got my scripts - one call, ~2 minutes and everything is packed into two EXE - 32 and 64bit - no need for doing this, I prefer my own scripts :)

`KERNEL32.dll` and similar - this is system library and it can't be distributed with software. It must fit to OS (something like `glibc` which can be replaced (`glibc` can be only static, but never shared distributed with application - otherwise crash when they are incompatible)).

> Do you prefer building QMPlay2 package on Windows or on Linux using cross compiling?

Corss-compiling is easy and convenient. Building on Windows is a pain (I did it for years and I've switched to cross-compiling).

---

I think that I can handle Windows as is, everything is automated. Windows should have only one installer from developer - it is not like Linux repositories. If I'll change the installer I can just modify local scripts.

OS X can have bundle with dependencies - then I'll release it for OS X (maybe someone will use it there :smile:). QMake creates bundle, but I've got problem with dependencies (at least I can fix it by script).

> OS X bundle files (I mean what should be in the resulting - so I know to where to go).

I don't know how to create bundle, I'm not OS X developer. If CMake will can create it w/o full (paid?) XCode it will be great :) I'll think about it later (low priority), but here is something (https://cmake.org/Wiki/CMake:Bundles_And_Frameworks) and here is a qmake script which uses bundle and moves some files into it: https://github.com/zaps166/QMPlay2/blob/782ef1784c410f1f33317c3eb2154d0346524be4/compile_unix#L34

**Comment by zaps166** [comment]
Not important, currently no plans.

**Comment by zaps166** [comment]
Done:
9100525aca0216af777ad3730f823117285fc502
98eb738a96e78ea0fe8f10f1c2d6016ea3c01605
e57ce215eb4e11e1c8fb9e6fbf4ce0441ddf097b
