### ISSUE TITLE
VA-API fails to initialize

### ISSUE THREAD

**Issue by barolo** [zaps166/QMPlay2#331]
qmplay2 20.05.2
ffmpeg 4.2.2
libva 2.7.1
mesa 20.1.0

GPU is AMD RAVEN APU , I have identical system with Intel Broadwell iGPU and VA-API/Vulkan works there.
ffmpeg alone can play the same files with vaapi just fine

```libva info: VA-API version 1.7.0
libva info: Trying to open /usr/lib64/va/drivers/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva info: va_openDriver() returns 0
VA-API :: Initialized device: renderD128
[ass] Shaper: FriBidi 1.0.9 (SIMPLE) HarfBuzz-ng 2.6.5 (COMPLEX)
[ass] Using font provider fontconfig
[ass] Shaper: FriBidi 1.0.9 (SIMPLE) HarfBuzz-ng 2.6.5 (COMPLEX)
[ass] Using font provider fontconfig
[13 maj 2020 09:40:13.130] VA-API :: Cannot find specified memory type: ErrorInitializationFailed
[ass] Shaper: FriBidi 1.0.9 (SIMPLE) HarfBuzz-ng 2.6.5 (COMPLEX)
[ass] Using font provider fontconfig
[ass] Shaper: FriBidi 1.0.9 (SIMPLE) HarfBuzz-ng 2.6.5 (COMPLEX)
[ass] Using font provider fontconfig
```

**Comment by zaps166** [comment]
Does it work with OpenGL?
I have AMD RAVEN APU (mesa 20.0.6, libva 2.7.1, ffmpeg 4.2.2) and no issues there with Vulkan. Could you check mesa 20.0.6?

**Comment by barolo** [comment]
> Does it work with OpenGL?
> I have AMD RAVEN APU (mesa 20.0.6, libva 2.7.1, ffmpeg 4.2.2) and no issues there with Vulkan. Could you check mesa 20.0.6?

The issue is with va-api/vulkan, not vulkan itself

It's known it seems, vulkan/vaapi combo fails under mpv 
Relevant bugs and workaround:
https://gitlab.freedesktop.org/mesa/mesa/-/issues/2854
https://gitlab.freedesktop.org/mesa/mesa/-/issues/2351

**Comment by zaps166** [comment]
> The issue is with va-api/vulkan, [ hw decoding ] not vulkan itself

Yes, I understand, and it works on my computer (mesa 20.0.6). Maybe mesa 20.1.x has a new bug (your gitlab URLs?) or requires something new I don't have in QMPlay2.

**Comment by barolo** [comment]
> > The issue is with va-api/vulkan, [ hw decoding ] not vulkan itself
> 
> Yes, I understand, and it works on my computer (mesa 20.0.6). Maybe mesa 20.1.x has a new bug (your gitlab URLs?) or requires something new I don't have in QMPlay2.

Are you sure that you're using va-api? As long as I remember it was broken because it's just not implemented, no matter the version. Not to be rude but I'd have to see it to believe.

**Comment by zaps166** [comment]
> [ and holy shit, it barely registers as using any cpu ]

VA-API/Vulkan doesn't do any image copy in QMPlay2, so it uses as less CPU and GPU as possible. 

Depends on your X11 config and X11 compositor config, you can bypass the compositor on full screen to reduce GPU usage even more to not copy the image by the X11 compositor (check QMPlay2 vulkan settings).

> You were right, it's fixed in 20.0.6. Sorry for the ruckus

I'm sure it also worked on mesa 19.x, I tried this in August 2019 first time on AMD :)

---

Anyway I have to check mesa 20.1 (it is not yet released AFAIK).

**Comment by barolo** [comment]
> I'm sure it also worked on mesa 19.x, I tried this in August 2019 first time on AMD :)

I've got the wrong idea because it's still unfixed in mpv....
I am bypassing the compositor but it's already so low that it barely makes any difference. Great job!

**Comment by zaps166** [comment]
Workaround for Mesa 20.1 is ready: https://github.com/zaps166/QmVk/commit/b7d2af8ab67e9ff3d32e63a28c855c4c896123ed

**Comment by barolo** [comment]
@zaps166  Don't want to open a new issue yet because I'm still investigating but current/git QMPlay2 crashes my gpu, with mesa-20.3.0+ and vulkan enabled

**Comment by zaps166** [comment]
Do you have a backtrace?
