### ISSUE TITLE
HLS flows runs at lowest bitrate

### ISSUE THREAD

**Issue by shorewall** [zaps166/QMPlay2#333]
Hi, testing the player on RAI Italian brodcasting streams I noticed that the hls streams are reproduced at low res, while all the other player I tested runs at full res.
Here an example link to the hls manifest:

http://mediapolisvod.rai.it/relinker/relinkerServlet.htm?cont=P6ZoPMUH5BweeqqEEqual
 
I've to get the manifest by curl, extract the best bitrate link and pass it directly to QMPlay2.
https://uspushmp4-vh.akamaihd.net/i/VOD/raiuno/Sanremo_2016/Sanremo_2016_EP_Puntate/5014616_,800,1800,.mp4.csmil/index_1_av.m3u8?null=0

**Comment by zaps166** [comment]
You can change the video size / bitrate and the same for audio in "Information" panel (click on second stream).

Unfortunately, QMPlay2 downloads both streams at once (low quality and high quality), but display the chosen stream.

I need to improve this in the future.

**Comment by shorewall** [comment]
Thanks for your fast response :-)

**Comment by zaps166** [comment]
It has been improved a while ago.

> Unfortunately, QMPlay2 downloads both streams at once (low quality and high quality), but display the chosen stream.

This also has been fixed a while ago.

---

Closing.
