### ISSUE TITLE
windows security warning for opening file

### ISSUE THREAD

**Issue by neon9999** [zaps166/QMPlay2#335]
after Association files with qmplay,windows show security warning for opening files in each time.
here is screen shot:
![Capture](https://user-images.githubusercontent.com/59704366/82203724-eb0d3e80-9918-11ea-847a-a828a6af88ee.PNG)

**Comment by zaps166** [comment]
Is it warning for file downloaded from the network or for QMPlay2 itself?

**Comment by neon9999** [comment]
its for qmplay2

**Comment by zaps166** [comment]
Hmm, if certificate is needed, i won't pay for this :( I have to check it, I don't have this on Windows IIRC.

**Comment by neon9999** [comment]
update:
i followed this instructions and its worked! 

 [http://www.door2windows.com/disable-open-file-security-warning-message/](url)

**Comment by zaps166** [comment]
The address is displayed properly, but links to github :smile:
