### ISSUE TITLE
mpeg-ts stream :image freezing while audio still playing

### ISSUE THREAD

**Issue by taktiker12** [zaps166/QMPlay2#339]
hi
i have strange issue on the latest version , when i play a stream from enigma box , the image freezes after  few seconds while audio plays normally .i got this errors
[h264 @ 0x7f7374018540] SPS unavailable in decode_picture_timing
[h264 @ 0x7f7374018540] non-existing PPS 0 referenced
[h264 @ 0x7f7374018540] SPS unavailable in decode_picture_timing
[h264 @ 0x7f7374018540] non-existing PPS 0 referenced
[h264 @ 0x7f7374018540] decode_slice_header error
[h264 @ 0x7f7374018540] no frame!

videoplayback of video files is normal .

thank U

**Comment by zaps166** [comment]
Hi, I need sample stream for testing purposes.

**Comment by taktiker12** [comment]
it a local stream on my LAN from enigma box to pc .i use channel list with local ip inside ..

**Comment by taktiker12** [comment]
hi blazej
here is the link of stream that causes freez
http://160.176.87.105:8001/1:0:19:2331:442:1:C00000:0:0:0:

regards
mounir

**Comment by taktiker12** [comment]
hi zaps166
i just realized that the freeze not happen when i play the stream in full screen .

**Comment by zaps166** [comment]
Could you upload you "Information" panel screenshot?

**Comment by taktiker12** [comment]
[](url)

**Comment by taktiker12** [comment]
[image: Screenshot at 2020-06-23 16-01-16.png]

**Comment by taktiker12** [comment]
sorry , it freezes on fullscreen too

**Comment by taktiker12** [comment]
maybe the problem come from this

FFDecHWAccel: Don't discard frames on HW decoding
if (hurryUp > 1)
codec_ctx->skip_frame = AVDISCARD_NONREF;
else if (hurryUp == 0)
codec_ctx->skip_frame = AVDISCARD_DEFAULT;

**Comment by taktiker12** [comment]
commit c72c3adcb8b001dbe1dade308c9f440782be19e1

**Comment by zaps166** [comment]
I can revert this commit if it helps. So it looks like your hardware is too slow.

**Comment by taktiker12** [comment]
GTX1050 Ti 4GB(GP107) and i5 4th generation ..it plays 4k smoothly without lags .but only this streaming story from enigma box is enigmatic .
playing the same streams on kodi and previous qmplay is correct ..

**Comment by zaps166** [comment]
A/V sync and frame dropping in QMPlay2 is old and needs to be fixed. If in your case reverting of c72c3ad can fix the issue, I can revert this.

Do you use Windows or Linux? Do you play on Vulkan? Is it CUVID decoder?

**Comment by taktiker12** [comment]
i use linux , vulkan cuvid but i prefer  vdpau .
  thank you for your friendly help 
regards

**Comment by zaps166** [comment]
Ok, you can check statis in `nvidia-settings` when playing a video. If it is about 100% of GPU or Video Engine load, it means that your graphics card is too slow and the software (QMPlay2 in this case) needs to skip some frames. If frame skipping or reducing the video quality doesn't work properly, the video will freeze, because it won't sync to audio.

![Screenshot_20200623_203339](https://user-images.githubusercontent.com/6239090/85442783-d6b00780-b590-11ea-863f-48ccbe09f9bc.png)

---

Does previous QMPlay2 work properly on both: VDPAU and CUVID?
Does new version of QMPlay2 work bad on all VDPAU, CUVID/OpenGL and CUVID Vulkan?

**Comment by taktiker12** [comment]
the previous version work perfectly .here is a snapshot of previous qmplay

**Comment by taktiker12** [comment]
can you make an image of latest qmplay2 without the commit
c72c3adcb8b001dbe1dade308c9f440782be19e1
?
thank u

**Comment by zaps166** [comment]
> can you make an image of latest qmplay2 without the commit

Done, but I can't upload it here in comment (10 MB limit). I'll upload again if needed: https://send.firefox.com/download/a6d707b683e9cd06/#eeUNwvTGaCs7TfI97fsL0g

It is 45d0456c33b8f4f47595682d68d99423eb8d3e83 without c72c3ad.

```
$ sha256sum QMPlay2-20.05.02-git-d30da59-1-x86_64.AppImage
b0e87ccd8d8efb78b67d3b26084f943257835b61b3e808933036612d338904dc  QMPlay2-20.05.02-git-d30da59-1-x86_64.AppImage
```

**Comment by taktiker12** [comment]
> > can you make an image of latest qmplay2 without the commit
> 
> Done, but I can't upload it here in comment (10 MB limit). I'll upload again if needed: https://send.firefox.com/download/a6d707b683e9cd06/#eeUNwvTGaCs7TfI97fsL0g
> 
> It is [45d0456](https://github.com/zaps166/QMPlay2/commit/45d0456c33b8f4f47595682d68d99423eb8d3e83) without [c72c3ad](https://github.com/zaps166/QMPlay2/commit/c72c3adcb8b001dbe1dade308c9f440782be19e1).
> 
> ```
> $ sha256sum QMPlay2-20.05.02-git-d30da59-1-x86_64.AppImage
> b0e87ccd8d8efb78b67d3b26084f943257835b61b3e808933036612d338904dc  QMPlay2-20.05.02-git-d30da59-1-x86_64.AppImage
> ```

yes
thank You  blazej .using this image and playback with vdpau everything seems to be correct ..
cuvid decoder is problematic , because it seems not handle correctly the A/V sync .
thank u

**Comment by zaps166** [comment]
>  cuvid decoder is problematic , because it seems not handle correctly the A/V sync .

Maybe, CUVID has some issues with video timestamps, so I've made some workarounds there, but it still can fail to synchronize.

If you can do the last check CUVID on OpenGL (instead of Vulkan) to be sure (because VDPAU runs always on OpenGL).

**Comment by zaps166** [comment]
And the second thing is QMPlay2 CUVID decoder doesn't skip frames when decoding is too slow (c72c3adcb8b001dbe1dade308c9f440782be19e1 isn't work for CUVID).

**Comment by taktiker12** [comment]
> > cuvid decoder is problematic , because it seems not handle correctly the A/V sync .
> 
> Maybe, CUVID has some issues with video timestamps, so I've made some workarounds there, but it still can fail to synchronize.
> 
> If you can do the last check CUVID on OpenGL (instead of Vulkan) to be sure (because VDPAU runs always on OpenGL).

trying cuvid opengl caused freezing 
vdpau opengl is clean
