### ISSUE TITLE
[Idea] New icons for modules or more...

### ISSUE THREAD

**Issue by varlesh** [zaps166/QMPlay2#34]
Your icons have different style, i'm create new. Maybe you like that? :)
![screenshot_20160628_091837](https://cloud.githubusercontent.com/assets/8083855/16409904/909d122c-3d28-11e6-864d-d5847df72527.png)
Now available 32px icons for modules on SVG.

**Comment by varlesh** [comment]
All, preview:
![screenshot_20160628_120702](https://cloud.githubusercontent.com/assets/8083855/16409970/de8e9a64-3d28-11e6-9e5b-f95e8ba13453.png)

**Comment by zaps166** [comment]
Do you want to add these icons to QMPlay2?
If yes - I'll create icon scheme feature for QMPlay2 (later). For this I need to attach all icons in SVG and its name (also author name in text file).

**Comment by varlesh** [comment]
Yes, if you want and like this icons.
Do you agree?
Need other icons - main logo, and actions icons (i think this icon used on Windows only, but i can't create this icons for better looking one style if you need)?

**Comment by varlesh** [comment]
For example, main logo:
![screenshot_20160628_152126](https://cloud.githubusercontent.com/assets/8083855/16415068/02285a58-3d44-11e6-8b4a-75e3b276cc12.png)

**Comment by zaps166** [comment]
Main logo is OK for me (The only icon which I've done (+ the blue next/prev icons). It was about 8 years ago for QMPlay1) :smiley:

You can create the new QMPlay2 icon style which can be chosen in settings. I'll also think about extending the current default icons, but they are hicolor + original logos like OpenGL or X11...

**Comment by zaps166** [comment]
About the new icons:
- maybe Modplug module should illustrate that this is for music (maybe something associated with old games, Amiga, DOS, trackers. etc.)?
- Inputs module is more like audio input rather than keyboard/mouse, maybe it should have jack or chinch or something similar?
- Why XVideo icon looks like Windows (DirectX) ? :smiley:

**Comment by varlesh** [comment]
Ok, i'm create git-repo and add new style icons. You can add this style later on player and issues. I think this will be comfortable for you and me.

**Comment by zaps166** [comment]
OK, so I'll use your icons if the new feature will be available :) You can paste link to your repo here.
Thanks!

**Comment by varlesh** [comment]
https://github.com/varlesh/QMPlay2-Concept

**Comment by varlesh** [comment]
Inputs, DirectX and Modplug fixed

**Comment by varlesh** [comment]
@zaps166 gui-icons added

**Comment by varlesh** [comment]
16px
![screenshot_20160628_192859](https://cloud.githubusercontent.com/assets/8083855/16423892/9a554526-3d66-11e6-9723-10ed84c97528.png)
22px
![screenshot_20160628_192842](https://cloud.githubusercontent.com/assets/8083855/16423904/a297feae-3d66-11e6-9846-fb9a1497050b.png)

**Comment by varlesh** [comment]
and modules 32px (fiixed)
![screenshot_20160628_193130](https://cloud.githubusercontent.com/assets/8083855/16424005/031f428c-3d67-11e6-9e85-4e16984cfd37.png)

**Comment by zaps166** [comment]
Thanks :)

I've got one question - modules icons are on black background, not transparent - is it OK? And how does it look on transparent background for you?

And I wonder what about HiDPI - QMPlay2 currently doesn't support it (and I don't have HiDPI screen to test it :smiley:)...

**Comment by varlesh** [comment]
You want remove black background or add transparent?
I'm not have HiDPI too... hm, icons have SVG-fromat and maybe port to other size. Only i'm not shure Windows support showing SVG's or only PNG's on program?

**Comment by varlesh** [comment]
Added not-background version https://github.com/varlesh/QMPlay2-Concept/commit/162470f1998d0ac1de0e8860269f2f0ad7def7c2:
![screenshot_20160628_213026](https://cloud.githubusercontent.com/assets/8083855/16427791/b26fbbc6-3d77-11e6-8869-5f379acc59f1.png)

**Comment by varlesh** [comment]
extensions added https://github.com/varlesh/QMPlay2-Concept/commit/9afbf3e5538c591ef7c030bb233e400ec20f6ae8
![screenshot_20160629_114143](https://cloud.githubusercontent.com/assets/8083855/16446092/8fa67d92-3dee-11e6-8ff3-5670c1a5217c.png)

**Comment by varlesh** [comment]
Any versions good look with dark themes:
![screenshot_20160629_115852](https://cloud.githubusercontent.com/assets/8083855/16446595/0a0e2092-3df1-11e6-9c63-db7c34fe0d3b.png)
![screenshot_20160629_115914](https://cloud.githubusercontent.com/assets/8083855/16446596/0a0f8dce-3df1-11e6-9694-27d6ae8af616.png)
But i like  background version, because all icons have one scale

**Comment by zaps166** [comment]
> But i like background version

Dark background also looks Ok for me :)

Licesne (I'm not a lawyer):
- Icons: GPL,
- QMPlay2: LGPL.

Does it mean that if I'll include these icons the QMPlay2 will be now on GPL license?

About modules icons:
- I like current XVideo icon - the cross (X) differs too much from X11 cross - X11 has thick line from left to right and thin and splitted line from right to left + ellipse.
- I like current ALSA icon with the walking TUX :smiley:

Is it possible to do a little fixes for this :) ?

**Comment by varlesh** [comment]
XVideo fixed, but i'm not have idea how add Tux :) License changed to LGPL:
https://github.com/varlesh/QMPlay2-Concept/commit/f3f368e1322a911d2bebe426490120f222657530

**Comment by zaps166** [comment]
XVideo looks good to me now :+1:, I'll try new icons soon :)

> but i'm not have idea how add Tux

Icons can be fixed in any time, right? :smiley: So we can defer it now :)

**Comment by varlesh** [comment]
Maybe better use as original icon style for ALSA?
![alsa-logo](https://cloud.githubusercontent.com/assets/8083855/16477537/22218458-3e9b-11e6-8815-8261b3705781.png)

![alsa-2](https://cloud.githubusercontent.com/assets/8083855/16477568/5d980f52-3e9b-11e6-94d6-fec477b98a54.png)

**Comment by varlesh** [comment]
I'm add another ALSA icon, fix colors on Subtilte and small fix OpenGL2. Nobackground-version removed.
https://github.com/varlesh/QMPlay2-Concept/commit/a9a6141c8e38f084a28d854dc9c98f4f5a7bd09a
https://github.com/varlesh/QMPlay2-Concept/commit/fa0cccb82d3cc5616cd59e22fa9685d285518d61

**Comment by zaps166** [comment]
Hmm, ALSA looks good :) but the Tux was cute :smiley:
Visualizations looks weird :smile: but I don't have good idea - maybe something associated with FFT spectrum, oscilloscope or something else?

**Comment by varlesh** [comment]
fixed https://github.com/varlesh/QMPlay2-Concept/commit/5604080a81cfd07d49343e1b5941cd51a7db384f

**Comment by zaps166** [comment]
:+1: :)

**Comment by zaps166** [comment]
Currently I don't want to create icon themes :smiley: (maybe later). I can try to replace QMPlay2's icons, OK? Modules icons will be in modules directories, etc., so where should I put license (is the same, so it is needed?) and authors files? The icons theme name is "Concept", right?

Little fixes:
- AudioCD - bigger disk icon
- Video/Audio filters - hard to see what is it (black rows on dark background, maybe lighter rows and smaller circles?)
- folder and folder-orange - OK, but the difference is small between them.
- applications-multimedia - maybe a little dark gradient on a black "thingie"

Without Tux the ALSA-2.svg is better :smile:

**Comment by zaps166** [comment]
Missing icon: `media-playback-pause`

**Comment by zaps166** [comment]
About the black background: Looks very good on modules list, but doesn't look good on playlist or on context menu... :(

**Comment by zaps166** [comment]
`folder-orange.png` and `folder.png` should be 22x22 as default

**Comment by varlesh** [comment]
QMPlay2-Concept this temporary repo, you merge icons and i'm delete. Need only AUTHORS.
Icons fixed https://github.com/varlesh/QMPlay2-Concept/commit/d7ece30ed54e3dfc9e12a3ab6e1d9fa92c0f93cb
I'm change color line on filters icons and reduce logo.

**Comment by zaps166** [comment]
So I'll create AUTHORS for me, you and for other contributors, is it OK :) ?

`archive-remove` - i know that its name is `archive`, but it can look more like playlist i.e. white color or something (similar to Oxygen) :)

**Comment by zaps166** [comment]
I'll merge icons into my temporary branch (maybe today), so I'm waiting for last fixes :)

I don't know what to do with dark background on e.g. playlist, maybe it needs two different icons (with and w/o background)?

**Comment by varlesh** [comment]
folders fixed https://github.com/varlesh/QMPlay2-Concept/commit/81be7643a8e42e167f1c8c7ebd55dfa0e759738f
Maybe disable this icons on context menu?

**Comment by zaps166** [comment]
Btw. I'm using this for creating PNG:
```bash
for f in *.svg; do
	inkscape -z -e $f.png $f
	rename .svg.png .png *.svg.png
done
```

**Comment by varlesh** [comment]
rsvg-convert good util too

**Comment by varlesh** [comment]
![screenshot_20160703_204536](https://cloud.githubusercontent.com/assets/8083855/16546808/9a8f6b8e-4167-11e6-9d31-1b84eda79cdd.png)

like that archive-remove ?

**Comment by zaps166** [comment]
> like that archive-remove ?

looks good, I'll see in QMPlay2 :)

**Comment by zaps166** [comment]
> applications-multimedia

Now everything is black

**Comment by varlesh** [comment]
archive icon fixed https://github.com/varlesh/QMPlay2-Concept/commit/4a1708f833f585ddb17b32247ed6437b29bb4c4f

**Comment by zaps166** [comment]
Ok!

`applications-multimedia` I thought about adding a little gradient to the black note, the blue arrow was OK

**Comment by varlesh** [comment]
all blue, note and play?

**Comment by varlesh** [comment]
or for example
![screenshot_20160703_210405](https://cloud.githubusercontent.com/assets/8083855/16546868/1c93879e-416a-11e6-81f2-2fa396e32169.png)

**Comment by zaps166** [comment]
Good :smile: 

And what about green note (with gradient like above) and blue (like before) arrow?

**Comment by zaps166** [comment]
Btw. do you able to do new icons if I'll add a now module?

**Comment by varlesh** [comment]
multimedia fixed
https://github.com/varlesh/QMPlay2-Concept/commit/eb206a7b7e5df2842c5ed9d6ebff8a614b8dbec1
Yes, what you need?

**Comment by zaps166** [comment]
![1](https://cloud.githubusercontent.com/assets/6239090/16546922/925434e8-415a-11e6-99d7-2a110513cf55.png)
![2](https://cloud.githubusercontent.com/assets/6239090/16546924/93522f94-415a-11e6-950d-a8acd10656b9.png)
![3](https://cloud.githubusercontent.com/assets/6239090/16546926/946fd412-415a-11e6-812a-d7ae9b0d9259.png)

You can see that here that black background isn't good... So the only thing is to create two icons: for module and for context menu/playlist. I think I'm able to remove the background in Inkscape (only for some modules) :)

**Comment by zaps166** [comment]
> multimedia fixed

Ok, testing - this icon is the most frequent icon, so I want it to be as good as possible :)

> Yes, what you need?

1. Future modules :)
2. QMPlay2 lacks of icons in context menus, so if you have a time you can always do some icons :)

**Comment by varlesh** [comment]
need add other sizes for context, because more icons blurred. For example, Files, Directory, YouTube and etc

**Comment by zaps166** [comment]
> need add other sizes for context, because more icons blurred. For example, Files, Directory, YouTube and etc

Yes, but it is less important (later). The best idea is to use SVG, but it needs QtSvg module :/

**Comment by zaps166** [comment]
![playlist](https://cloud.githubusercontent.com/assets/6239090/16546988/d1c38546-415c-11e6-846c-c3ae5549c110.png)

Looks very good, but on blue selection the arrow is almost invisible (depends on style and color scheme). Maybe it should be dark-blue or like https://github.com/zaps166/QMPlay2/issues/34#issuecomment-230166599 (only arrow)?

**Comment by varlesh** [comment]
fixed

**Comment by varlesh** [comment]
build for xenial soon available?

**Comment by zaps166** [comment]
Xenial == Ubuntu 16.04 - DEB is already here https://github.com/zaps166/QMPlay2/releases/tag/16.07.02 (Ubuntu 15.10, 16.04, Mint 18) for yesterdays release.

**Comment by varlesh** [comment]
ok

**Comment by varlesh** [comment]
Context menu only for Windows?  On Linux this icons really not needed, because better use native icons... but only for Modules,  because this icons specific and not available on freedesktop  icon themes and other too.

**Comment by zaps166** [comment]
How to create `svgz` from command line ?

**Comment by zaps166** [comment]
How to create `svgz` from command line ?

**Comment by varlesh** [comment]
ou... i don't know. maybe on inkscape

**Comment by zaps166** [comment]
> Context menu only for Windows?

Ah Ok, so if I'll use more theme icons in context menu then I'll notify you about it:)

> On Linux this icons really not needed, because better use native icons...

It depends - sometimes it can't find, sometimes somebody wants to have native icons for software (QMPlay2 has option for it).

**Comment by zaps166** [comment]
> ou... i don't know. maybe on inkscape

Ok, maybe later - it is not necessary now (I hope inkscape can handle it in command line :smiley: ) :)

**Comment by varlesh** [comment]
Maybe for Windows use native icons too? It's possible? For example, **list-add** **list-remove** **view-refresh** and etc there are similar on Windows system. We create for modules only

**Comment by varlesh** [comment]
This icon already exist on all native Linux icon themes:
application-exit
applications-multimedia
archive-remove
audio-volume-high
audio-volume-muted
configure
document-properties
edit-clear
edit-copy
edit-find
edit-paste
folder-new
folder-open
folder-orange
folder
list-add
list-remove
media-playback-pause
media-playback-start
media-playback-stop
media-skip-backward
media-skip-forward
process-stop
view-fullscreen
view-refresh

Why this icons really needed?

Only application-x-mswinurl maybe not available on native Linux icon theme.

**Comment by zaps166** [comment]
https://github.com/zaps166/QMPlay2/tree/new-icons - pushed a commit to temporary branch

Looks like "application-x-mswinurl" is KDE-only (Breeze and Oxygen).

> Why this icons really needed?

Windows, OS X, whatever (Android) and for QMPlay2's native icons (can be visible also on Linux if someone wants it) :)

**Comment by varlesh** [comment]
Oh no! For Linux only native (if available)!!!

**Comment by zaps166** [comment]
> Oh no! For Linux only native (if available)!!!

1. It depends on user :)
2. It depends on software (i.e. game or special software with own themes + linux-native icon will look bad and inconsistent).
3. What if someone has ugly theme-icons and he/she wants to have native icons in software?
4. If available - yes, so it must exists if not available or if it is a bug somewhere (e.g. Manjaro (Arch Linux), Qt4 and Mate desktop - can't find icons from theme).

**Comment by varlesh** [comment]
Linux have more beautiful icon themes - Breeze, Numix, Moka, Nitrux, Faenza and etc. Please not hardcoded icons - it's not linux way.

**Comment by varlesh** [comment]
More Linux users like customize your distro and DE

**Comment by zaps166** [comment]
> Please not hardcoded icons - it's not linux way.

QMPlay2 has two options and it will not change (![settings](https://cloud.githubusercontent.com/assets/6239090/16547160/69733efc-4164-11e6-8724-4d095256458a.png)):
- from theme (only on Linux/BSD and default),
- from QMPlay2 (other OS'es and also on Linux/BSD as option).

**Comment by varlesh** [comment]
See, this really beautiful - all look very good in the same style:
![screenshot_20160703_222438](https://cloud.githubusercontent.com/assets/8083855/16547176/7dfd389e-4175-11e6-85b7-aa06ffea6499.png)
And compare with Windows 10 :)

**Comment by zaps166** [comment]
> And compare with Windows 10 :)

Windows 10 is ugly for me :smiley: Windows 3.11 looks much better :)

**Comment by varlesh** [comment]
Windows 10 ugly for me too, i hate Windows and MS.
Ok.. we create 16px icons later, i go sleep

**Comment by zaps166** [comment]
Ok!

![desktop](https://cloud.githubusercontent.com/assets/6239090/16547217/082ec2ae-4166-11e6-8a5f-a129c4d026ac.jpg)

BlueMenta GTK2 theme + Qt GTK2 style + Oxygen icons.

**Comment by zaps166** [comment]
I like customizable software, so I want to add many options (also for icons & styles & colors) into QMPlay2. It is not good if developers forces their conception to others without allowing them to change it (e.g. Windows 10 and forced auto-updates, you can only disable completely the service or Window themes in Windows - how to change it?).

Currently key bindings are in QMPlay2 TODO list.

**Comment by zaps166** [comment]
Non-background icons (merged into `new-icons` branch):
- Modplug - should have other icon for playlist (no text),
- Chiptune and AudioCD - needs little color fixes - too much gray color,
- FFmpeg - is OK.

Maybe Game-Music-Emu can have other icon - something like old game console?

Examples (bad looking on playlist):
![ct](https://cloud.githubusercontent.com/assets/6239090/16547432/f4b86c5e-416d-11e6-8ee3-7ec1fb6ba90e.png)
![mp](https://cloud.githubusercontent.com/assets/6239090/16547433/f4b8f7fa-416d-11e6-9e6f-fc79f5c9e525.png)

Missing icons:
- Inputs/PCM Audio,
- Inputs/ToneGenerator,
- *Inputs/Rayman2* - maybe don't touch this? :smile:

**Comment by zaps166** [comment]
Maybe also other icons for VDPAU (something with nvidia) and VA-API (something with intel)? Or just graphics card in icon for both? Or mixed FFmpeg + Graphics card?

**Comment by zaps166** [comment]
Hmm, maybe use FFmpeg icon for playlist? I wrote that it is OK, but it is too light.

**Comment by zaps166** [comment]
The icons w/o background: https://github.com/zaps166/QMPlay2/tree/8372cc5898312dee8a460ab4436941a142b868e8/src/svg/Concept/modules/NoBackground

**Comment by zaps166** [comment]
Or just add gradient to non-bg FFmpeg icon and use darker green colors :)

**Comment by zaps166** [comment]
> we create 16px icons later

Is it necessary? 16x16 are very small and they are only in context menus and only when non-linux theme is used...

> Ah Ok, so if I'll use more theme icons in context menu then I'll notify you about it:)

Not really necessary, so let's deffer it :)

**Comment by varlesh** [comment]
Please post list wrong icons (with comments, if need), it's will be better for me and you.
For example,
16px - Modplug
16px - AudioCD
... and etc

**Comment by zaps166** [comment]
Modules icons for playlist needed (w/o background). Removing only background looks bad (https://github.com/zaps166/QMPlay2/tree/8372cc5898312dee8a460ab4436941a142b868e8/src/svg/Concept/modules/NoBackground):
- 22px Modplug - should have other icon for playlist (no text),
- 22px AudioCD - needs little color fixes - currently too much gray color,
- 22px Chiptune - darker chip, lighter pins?
- 22px FFmpeg - darker green with gradient?

Missing icons:
- Inputs/PCM Audio,
- Inputs/ToneGenerator - replace old icon, can be very similar,
- Inputs/Rayman2 - maybe don't touch this? :smile:
- Chiptune/Game-Music-Emu - maybe something like old game console?
- VDPAU and VA-API - maybe graphics card?

**Comment by varlesh** [comment]
Missing icons size?

**Comment by zaps166** [comment]
> Missing icons size?

Updated, now it also has icon sizes

**Comment by zaps166** [comment]
Icons are Inkscape SVG or Plain SVG ?

**Comment by varlesh** [comment]
inkscape svg

**Comment by zaps166** [comment]
Ok, but now I've got better idea to compress icons that Inkscape:
```sh
gzip * && rename .svg.gz .svgz *.svg.gz
```
:)

**Comment by varlesh** [comment]
updated

**Comment by zaps166** [comment]
:+1: 

ToneGenerator:
```
** (inkscape:13623): WARNING **: Unimplemented style property SP_PROP_INTERPOLATION_FILTERS: value: linearRGB

** (inkscape:13623): WARNING **: Unimplemented style property SP_PROP_COLOR_INTERPOLATION: value: sRGB

** (inkscape:13623): WARNING **: Unimplemented style property SP_PROP_CLIP_RULE: value: nonzero
```
features from new Inkscape (I've got 0.48)?

**Comment by varlesh** [comment]
i'm use 0.91

**Comment by zaps166** [comment]
Ok, looks very good thanks!

Questions:
- VAAPI - red is associated with AMD, but VAAPI is mainly Intel - how does it look in blue color?
- maybe do something with `ToneGenerator.svg` to silence warning on old Inkscape?

**Comment by varlesh** [comment]
But intel not have discrete videocards. Red and black very good combined.
Save tonegenerator as Plain SVG https://github.com/varlesh/QMPlay2-Concept/commit/811d5a9b4c1c4f184f042e47092309e5b7962cd2

**Comment by zaps166** [comment]
> But intel not have discrete videocards. Red and black very good combined.

Ok :smile:

> Save tonegenerator as Plain SVG

If every icon is compatible with Plain SVG it can be saved in this format to reduce size - I can do it, but you should look if it is not corrupted, OK ?

**Comment by varlesh** [comment]
Ok

**Comment by zaps166** [comment]
Done: https://github.com/zaps166/QMPlay2/commit/f52f2113698e21e80c1ddbeac6677daec74e6804

If icons are OK I'll generate PNG one again.

**Comment by varlesh** [comment]
When new release with new icons? ;)

**Comment by zaps166** [comment]
> When new release with new icons? ;)

Soon :) But currently I'm not changing the main icon - it can be replaced in Linux via icon theme (like Firefox and any other icon).

---

So the plain SVG are OK (not corrupted)? (created via Inkscape 0.48 from command line)

**Comment by varlesh** [comment]
You don't like new main icon variants? Maybe make other or modify...
i don't know why show WARNING messages. Icon look as original.

**Comment by varlesh** [comment]
Also i found not native icon on modules Youtube an Prostopleer - "search" icon.
![screenshot_20160704_162421](https://cloud.githubusercontent.com/assets/8083855/16561800/2c7176c4-420c-11e6-9485-9e56292ceff2.png)

Please fix it

**Comment by zaps166** [comment]
> I don't know why show WARNING messages

With plain SVG it doesn't show warning (probably my OLD inkscape - I've downgraded it to 0.48) :)

> You don't like new main icon variants?

Currently main icon is the only icon created by my in 2008 for QMPlay1 and then modified for QMPlay2 in (probably in 2011, blue->green). This is the only icon created by my and it is with QMPlay from the beginning... It can be simply replaced via theme after a bugfix (f2facc5734e65a9b2a90cf9216cbffbf1c8ff7f3) :)

> Also i found not native icon on modules Youtube an Prostopleer - "search" icon.

because currently it uses submodule icon.

**Comment by zaps166** [comment]
Fixed: https://github.com/zaps166/QMPlay2/commit/7e7fc28d25f1a70ba8354c18f2a335a871762aa7

**Comment by varlesh** [comment]
thx for fix.
Ok, you don't like my variants - you developer you right :) But if you want upgrade main logo on the future, please tell me.

**Comment by zaps166** [comment]
Ok :) So I'm merging it into master branch, many thanks for new icons :) !!!

Could you tell me if replacing the main in Linux-theme icon work now properly?

**Comment by varlesh** [comment]
Now if run - use Xorg icon :(

**Comment by zaps166** [comment]
> Now if run - use Xorg icon :(

Which distibution? I must try it there...

**Comment by varlesh** [comment]
I'm test now KDE Neon, but not recommend install it now, because ubiquity (Live installer) crashed

**Comment by zaps166** [comment]
So please test on more stable distribution, maybe Manjaro with Plasma5? :)

**Comment by varlesh** [comment]
My friends have manjaro i'm ask this question

**Comment by varlesh** [comment]
![photo_2016-07-04_18-15-56](https://cloud.githubusercontent.com/assets/8083855/16565060/f49ae6f8-421b-11e6-86e0-7a3fc644a723.jpg)
On Manjaro working.
Maybe for tray use better another icon name? For example, **qmplay2-panel** 
because more icon themes have monochrome tray

**Comment by zaps166** [comment]
> On Manjaro working.

Looks like bug in Kwin on your OS (as I remember - you tried other WM on Plasma5 and it worked, right?)...

> Maybe for tray use better another icon name? For example, qmplay2-panel
because more icon themes have monochrome tray

Hmm, I use color icons on tray and I don't know which themes uses monochrome tray icons (Breeze and High Contrast only?), but OK, if QMPlay2 panel icon will exist then it will use it :)

**Comment by varlesh** [comment]
Duplicate QMPlay2 icon with new name QMPlay2-panel and fix this on code. It's all

**Comment by zaps166** [comment]
Please test: 29dbd6a208e3334d85b26a8287d5be1746de6b5b :)

**Comment by varlesh** [comment]
Thx, later only

**Comment by varlesh** [comment]
My friends test on Manjaro. Looks very good
![image_2016-07-05_12-44-12](https://cloud.githubusercontent.com/assets/8083855/16581086/b4cca97e-42b8-11e6-8893-e8e29b18e0a5.png)
Thx for you work! You best developer :)

**Comment by zaps166** [comment]
Thanks!

Btw. try to remove: `/usr/share/icons/hicolor/icon-theme.cache` - maybe this will help with main icon on task bar.

**Comment by zaps166** [comment]
Or generate new cache: `sudo gtk-update-icon-cache -f /usr/share/icons/hicolor`

**Comment by varlesh** [comment]
No, this icon theme not updated for him only )

**Comment by zaps166** [comment]
> No, this icon theme not updated for him only )

Hmm, I don't fully understand this sentence :)

> When new release with new icons? ;)

Released: 16.07.07 :)

**Comment by varlesh** [comment]
Wow, thx :+1:  It's all fine
![screenshot_20160707_185655](https://cloud.githubusercontent.com/assets/8083855/16659921/38b0edac-447d-11e6-9844-7791c2997ac1.png)

**Comment by zaps166** [comment]
@varlesh Could you create one quality icon for new YouTube button (to replace "Quality" text) ? :) Thanks!

![qualitymenubutton](https://cloud.githubusercontent.com/assets/6239090/17952592/5d66290e-6a6c-11e6-8640-38b1291b763a.png)

**Comment by varlesh** [comment]
![quality](https://cloud.githubusercontent.com/assets/8083855/18122842/f01f2e06-6f73-11e6-85d3-b33ac4eeaca4.png)

rename **zip** to **svg**
[quality.zip](https://github.com/zaps166/QMPlay2/files/446802/quality.zip)

**Comment by zaps166** [comment]
Thx, b5dba1c27aa24bd45ffc1bcaf06bfabb82ecfedb (+ little background change)

**Comment by varlesh** [comment]
@zaps166 For Linux need native icon name. Maybe **view-fullscreen**, **view-restore** or **view-filter**?
Oxygen:
![view-fullscreen](https://cloud.githubusercontent.com/assets/8083855/18125630/fbfecafe-6f7f-11e6-9c49-e2bfbcb91dc5.png)
![view-restore](https://cloud.githubusercontent.com/assets/8083855/18125634/00d663d4-6f80-11e6-9225-d0d13d913a6f.png)
![view-filter](https://cloud.githubusercontent.com/assets/8083855/18125641/0ae65640-6f80-11e6-8917-d67458c7e945.png)
Breeze:
![view-fullscreen](https://cloud.githubusercontent.com/assets/8083855/18125702/56af57ac-6f80-11e6-8634-c6884d939269.png)
![view-restore](https://cloud.githubusercontent.com/assets/8083855/18125710/5a43c75e-6f80-11e6-9504-6ef456dc2a89.png)
![view-filter](https://cloud.githubusercontent.com/assets/8083855/18125712/5d6d1da4-6f80-11e6-9abb-d8cefa5177f7.png)

**Comment by zaps166** [comment]
But the quality icon shouldn't be the same as fullscreen or filter icon, hmmm... Is it any other icon which could be used for quality in oxygen/breeze theme?

**Comment by varlesh** [comment]
**view-restore** not used on player and good looking

**Comment by zaps166** [comment]
**view-restore** is obvious for users that this restores the window. Also forcing KDE icons is not good idea (e.g. **view-filter** doesn't exist in other schemes AFAIK).

Also other software (e.g. Firefox) has its own icons and extensions also have own icons...

In this case maybe it is better to use **video-display** ![video-display](https://cloud.githubusercontent.com/assets/6239090/18128642/24244778-6f87-11e6-8f85-92dc54cf93fb.png) and fix https://github.com/zaps166/QMPlay2/issues/34#issuecomment-243705102 ?

**Comment by varlesh** [comment]
Sorry I did not answer for a long time... i'm not have time for github :(
Yes, maybe better use this icon. Also i'm redesign this icon. You decide!
preview:
![image](https://cloud.githubusercontent.com/assets/8083855/18268811/20a90a9c-742e-11e6-90f3-eb47e7d47976.png)
source (rename zip to svg):
[video-display.zip](https://github.com/zaps166/QMPlay2/files/456389/video-display.zip)

**Comment by varlesh** [comment]
@zaps166 this icon not use white background, because other icons not use background
![image](https://cloud.githubusercontent.com/assets/8083855/18269158/a159bc4e-742f-11e6-92e1-ea5fae2d2f6d.png)
If you want add white background. Maybe better add background for other icons too?

**Comment by varlesh** [comment]
For example:
![image](https://cloud.githubusercontent.com/assets/8083855/18269530/281f1f84-7431-11e6-93f2-7ee25597a10a.png)
[gui.tar.gz](https://github.com/zaps166/QMPlay2/files/456423/gui.tar.gz)

**Comment by varlesh** [comment]
or nobackground version:
![image](https://cloud.githubusercontent.com/assets/8083855/18269745/157daf5c-7432-11e6-977c-a403eb1c227a.png)
[gui-noback.tar.gz](https://github.com/zaps166/QMPlay2/files/456439/gui-noback.tar.gz)

**Comment by zaps166** [comment]
Ok, thanks! (6ee351ce6b9197c20696c2b1d833e65bd70997c5)

**Comment by zaps166** [comment]
@varlesh Hi! QMPlay2 has got a new module: Notifications :) Could you make an icon in your free time? :) Thanks!

**Comment by varlesh** [comment]
Ok, latter only.
Icons size?

**Comment by zaps166** [comment]
Ok!
32x32, module icon :)

**Comment by varlesh** [comment]
Rename **Subtitles.svgz** to **Notifications.svgz**
And add new icon for **Subtitles** (rename zip to svg):
[Subtitles.zip](https://github.com/zaps166/QMPlay2/files/614880/Subtitles.zip)

**Comment by zaps166** [comment]
Ok, thanks :)

**Comment by zaps166** [comment]
@varlesh Hi! It is a long time from previous conversation. QMPlay2 needs a new icon - "document-save" (16x16) :) Do you have time for this? Thanks!

**Comment by varlesh** [comment]
Hi :) Icon size? If use floppy symbol?

**Comment by zaps166** [comment]
Size 16x16, it can be a floppy symbol :)

**Comment by varlesh** [comment]
[floppy.zip](https://github.com/zaps166/QMPlay2/files/1692175/floppy.zip)

**Comment by zaps166** [comment]
Thanks!
