### ISSUE TITLE
First impression improvements suggestions.

### ISSUE THREAD

**Issue by MariasStory** [zaps166/QMPlay2#340]
Hi, thanks for the player. It looks good. A specially the appimage is helpful.
I just tried the player and that it works well with some tuning. Although, not everyone is able to tune it and deal with some bugs.
I suggest to:
1) Change the "Decoders priority" in the "Playback settings" tub of the "Settings" menu
  a) CUVID decoder 
  b) FFmpeg VA-API Decoder
  c) FFmpeg Decoder
2) Set "High quality image scaling up" in "Rendering settings". I am not sure if it does something.
3) Improve the youtube search. In my case it searches every 3rd time. Most of the time there are no results.
4) Show when the youtube video was uploaded.
5) Youtube playlists
6) Arrows up and down should control volume.

**Comment by zaps166** [comment]
Hi!

1. Nope, CUVID is buggy and depends on graphics hardware and drivers, so it is not a good idea. In some rare cases GPU decoding can be slower than CPU decoding (e.g. old/slow graphics hardware) and move can stutter on this. I can add a first run question for HW acceleration.
2. It does, e.g. display 640x480 video on 4k display with and without this. It is blurry bicubic filtering. It can be slow especially with sharpness adjustment.
3. It is something new and doesn't happen every time - this must be fixed (I'm aware of this).
4. Nice improvement.
5. QMPlay2 supports YouTube playlists, but probably it needs to be improved.
6. Go to settings, in "General settings" tab scroll to the end and use "Set key bindings".

**Comment by zaps166** [comment]
3. Fixed 0f1fde7f
4. Added (in tooltip) 0f1fde7f
