### ISSUE TITLE
no youtube search result (most of the time)

### ISSUE THREAD

**Issue by RJVB** [zaps166/QMPlay2#341]
Something has changed somewhere (upstream?) and now I mostly get no results on YouTube searches. Sometimes it helps to change the search preferences but only for a single search.
I'm seeing this with a fresh git/head build against Qt 5.12.6 on Linux as well as a 10 commits old build against Qt 5.9.8 on Mac. Both builds were made with a new-enough clang version (5.0.2 on Mac, 8 on Linux).

This is a real bummer for me; QMPlay2 has become my main YouTube browser and I'd hate to have to give that up so I hope we can quickly get at the bottom of this.

**Comment by taktiker12** [comment]
the same here on linux ..youtube do not return any result after search .

**Comment by zaps166** [comment]
YouTube has changed, I'll fix this soon.

**Comment by RJVB** [comment]
Looks like you nailed it, thanks for the quick fix!
