### ISSUE TITLE
class QByteArray

### ISSUE THREAD

**Issue by pavroo** [zaps166/QMPlay2#343]
Hi
Trying to build 20.07.04 on Debian stable & testing got the error:
`error: ‘class QByteArray’ has no member named ‘compare’`
Stable Qt is 5.11.3, testing is 5.14.2.
Any clue, please?
regards
pavroo

**Comment by zaps166** [comment]
Hi!

Is it `QMPlay2Core.cpp` line 406? Oops, it is Qt 5.12 feature, so 5.14.2 should compile.

**Comment by pavroo** [comment]
Build with the latest patch on Debian stable, so it installed on stable and testing.
Thanks a lot.
Wielkie dzieki, pozdrawiam.
