### ISSUE TITLE
[Wayland] Power management is not inhibited on Gnome

### ISSUE THREAD

**Issue by Digitalone1** [zaps166/QMPlay2#344]
Hello, I tried out qmplay2 on Arch Linux, Gnome desktop environment.

The application is very good, but unfortunately the power management is not inhibited during playback and the screen is turned off after some minutes.

Can this be prevented? Thanks.

**Comment by zaps166** [comment]
Hello, screen power management is inhibited on Mate, so it should also work on Gnome.

Btw. Wayland power management is not supported.

**Comment by Digitalone1** [comment]
So it's not working even in Plasma Wayland?

**Comment by zaps166** [comment]
Power management on X11, Windows, macOS and Android are supported so far. Unfortunately, every platform needs separate code :/

**Comment by Digitalone1** [comment]
I found out how to do it in Gnome. Prepending `gnome-session-inhibit` to the executable name.

https://github.com/mpv-player/mpv/wiki/FAQ#I_use_GNOME_Wayland_and_I_have_xyz_problem
