### ISSUE TITLE
Image not rendered and crashes on fullscreen under Wayland Plasma session

### ISSUE THREAD

**Issue by Martchus** [zaps166/QMPlay2#345]
When playing a video the image is not rendered. I can reproduce this issue for a while now under Plasma's Wayland session. I haven't tested whether the problem is reproducible under other Wayland compositors. The problem started likely with an update of Plasma or any underlying libraries as provided by Arch Linux. Under X11 it works on the same system.

If one nevertheless tries to enable the fullscreen mode the player even crashes (see attached [backtrace](https://github.com/zaps166/QMPlay2/files/4878679/backtrace.txt)).

I've produced the back trace by making a debug build from the latest master but the problem is also reproducible with the latest AUR package and also the version before. Although I think 20.05.02 worked at some point and only updating other packages triggered the problem.

I'd like to note that also VLC player is not working in that environment. However, mpv works (and uses "gpu" rendering according to its log). I've not been using hardware video decoding in my tests and the system is using Intel HD graphics. (I don't have any other Wayland compatible hardware to cross-check.)

**Comment by zaps166** [comment]
Tried on `weston-launch` and Qt 5.15.0 (Manjaro), AMD GPU, `qt5-wayland` installed.

Vulkan works, VA-API + Vulkan also works - I can see the video. Vulkan windows is too large and window title bar flickers when Vulkan internal windows is resized.

Fullscreen crashes and/or causes the image to be black (renderer doesn't matter: Vulkan, QPainter, OpenGL).
Software crash is inside the Qt5 Wayland plugin, so it is a Qt bug. I don't have any issues on Windows, X11, macOS and even on Android with fullscreen.
