### ISSUE TITLE
Change label in PulseAudio module to Maximum Latency

### ISSUE THREAD

**Issue by Digitalone1** [zaps166/QMPlay2#351]
PulseAudio module has a spinbox with _Delay_ label.

I think that this is easily misunderstood to setting a delay to the audio playback, which in most cases is not wanted.

As I see in the [source code](https://github.com/zaps166/QMPlay2/blob/master/src/modules/PulseAudio/Pulse.cpp#L86), its value is used to calculate the [tlength](https://freedesktop.org/software/pulseaudio/doxygen/structpa__buffer__attr.html#aa7e8f3348cbda863b6f1dd55a9024b7a) buffer.

So it's not really a delay, but a value which can influence the latency since higher the buffer more the latency. As I understood, it's not guaranteed that a specific buffer value leads to a specific fixed delay, instead it depends more on the system load.

Therefore I think that the proper label for this option would be _Maximum latency_.

**Comment by zaps166** [comment]
I'll check this, thanks!
