### ISSUE TITLE
XDG Base Directory Specification

### ISSUE THREAD

**Issue by sukanka** [zaps166/QMPlay2#352]
I found the software create a folder called `.qmplayer2` in `~`. But according to the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) (also avaliable on archwiki [XDG Base Directory](https://wiki.archlinux.org/index.php/XDG_Base_Directory). 
>User-specific configurations should be written (analogous to /etc) into `XDG_CONFIG_HOME`, which should default to `$HOME/.config`.

Could you please follow this specification? 
BTW, QMPlay2 is an awsome project, I really enjoy it! Thanks for your hard work.

**Comment by zaps166** [comment]
Ok, but the old config files needs to be moved.

**Comment by wcasanova** [comment]
you can have both, just give priority to XDG_CONFIG_HOME if it doesn't get it to read the config from ~/.qmplay2
