### ISSUE TITLE
Is there a way to change audio track in QMPlay2? 

### ISSUE THREAD

**Issue by Digitalone1** [zaps166/QMPlay2#354]
I can't find the command to change the audio track. Is it possible in this player?

**Comment by zaps166** [comment]
Hi, this is possible, but only from Information panel (click on another auto stream).

**Comment by Digitalone1** [comment]
Thanks. Anyway it's so unintuitive.

Can you please add track entries inside playback menu?

**Comment by zaps166** [comment]
Similar issues: #179 #261 

> Can you please add track entries inside playback menu?

Ok

**Comment by HakanDOGAN1981** [comment]
> Thanks. Anyway it's so unintuitive.
> 
> Can you please add track entries inside playback menu?

I want too!!

**Comment by zaps166** [comment]
Done!
