### ISSUE TITLE
Fullscreen

### ISSUE THREAD

**Issue by podtor** [zaps166/QMPlay2#359]
During full screen don't block turn off the display.

**Comment by Digitalone1** [comment]
Maybe a duplicate of #344

**Comment by podtor** [comment]
Similar but this problem regard Windows

**Comment by zaps166** [comment]
I'll check it

**Comment by zaps166** [comment]
Works properly on Windows 10, hmm. On full screen audio and video playback blocks turn off the display.

**Comment by zaps166** [comment]
I can't reproduce on 3 computers with Windows 10 - QMPlay2 properly inhibits screensaver. (fullscreen with stopped playback doesn't inhibit!)
