### ISSUE TITLE
YoutTube search broke yet another time.

### ISSUE THREAD

**Issue by DarkWav** [zaps166/QMPlay2#367]
Hello, 
since yesterday YouTube search seems to be broken again, perhaps YouTube changed their backends again. 
We could eventually wait for a few days to check if they change the behavior back.
If not, yet another fix might be required.
I have to admit that YT changing their algorithms and protocols so often is getting really annoying , I hope google can some day decide which protocol they want to use...

**Comment by zaps166** [comment]
Ok... I'll remove YouTube for next release, this will be the last release with Qt 5.6 and Windows XP support. Then I'll rewrite YouTube into JS script (like MediaBrowser) if still possible...

**Comment by DarkWav** [comment]
By the way, playing specific URLs with youtube-dl still works great, so you can leave that functionality remain in the code and only remove the search functionality.

**Comment by RJVB** [comment]
Maybe the direct opening could parse a full URL?

BTW, doesn't youtube-dl allow to search too?

**Comment by zaps166** [comment]
> By the way, playing specific URLs with youtube-dl still works great, so you can leave that functionality remain in the code and only remove the search functionality.

Only YouTube search will be removed.

> doesn't youtube-dl allow to search too?

I don't know, can you give a command line example?

Anyway youtube-dl is a zipped python script, so it starts very slowly (unzip, bytecode compile, and execute slow python code). On i7-8700k it starts ~0.95 seconds, so searching will be slow (+ 100% CPU core usage).

**Comment by RJVB** [comment]
> I'll see if I can figure it out. I'm pretty certain I did manage to get a long list with output a while back.

> Anyway youtube-dl is a zipped python script, so it starts very slowly
Indeed it does. But didn't we discuss working around that, some time back? It's not that hard to uncompress it into qmplay's cache directory and then let the python interpreter handle caching the byte-compiled version. I recall tinkering with that and it makes a significant difference.

Slow searching is always better than no searching. Searching via JS might not be any faster because that too is an interpreted language.

**Comment by RJVB** [comment]
>I don't know, can you give a command line example?

```
> youtube-dl -s --flat-playlist [--no-color] --default-search auto "search key" --yes-playlist --dump-json
```

would be useful ... if I knew how to make it return (download) all matching videos instead of (apparently) just the 1st match.

Maybe an idea for a feature request?

R.

**Comment by zaps166** [comment]
> Searching via JS might not be any faster because that too is an interpreted language.

It depends, but for sure you skips the zip decompression and bytecode compilation on every search :smiley:

> Slow searching is always better than no searching.

True, especially that I don't have to fix the code every week when google changes their website :smile:

**Comment by zaps166** [comment]
Fixed...

**Comment by DarkWav** [comment]
Thanks, it works! (for now xD)
