### ISSUE TITLE
Wrong shared objects installation directory with openSUSE cmake packaging macro

### ISSUE THREAD

**Issue by DAP-DarkneSS** [zaps166/QMPlay2#37]
16.07.02 + f274748b8e7875508f20ddb5bf18698a4676d3a1 + 65f826cf97aebc8bc16aaeeddd628967ba8f8c75.
[cmake4.build.log.txt](https://github.com/zaps166/QMPlay2/files/345087/cmake4.build.log.txt)

**Comment by zaps166** [comment]
It copies libs to `/usr/usr/lib64`.
As a workaround: does `-DCMAKE_INSTALL_LIBDIR=lib64` help?

@arthurzam Any ideas :smiley: ?

**Comment by zaps166** [comment]
Something is wrong with `-DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib64` and/or `-DLIB_INSTALL_DIR:PATH=/usr/lib64` in QMPlay2's CMake script.

**Comment by zaps166** [comment]
Also we should test `-DLIB_SUFFIX=64`

**Comment by arthurzam** [comment]
I found the problem. In 5 minutes the patch will be ready and uploaded here (please apply it).

**Comment by DAP-DarkneSS** [comment]
@zaps166 , -DCMAKE_INSTALL_LIBDIR=lib64 changes nothing.

**Comment by zaps166** [comment]
@DAP-DarkneSS maybe because it is already set to `-DCMAKE_INSTALL_LIBDIR:PATH=/usr/lib64`
@arthurzam Ok

**Comment by arthurzam** [comment]
The patch

[fix-prefix.patch.txt](https://github.com/zaps166/QMPlay2/files/345093/fix-prefix.patch.txt)

**Comment by zaps166** [comment]
@arthurzam Ok, but now uninstallation script need fixes :)

**Comment by DAP-DarkneSS** [comment]
@arthurzam , excellent! Thank you!

**Comment by arthurzam** [comment]
@zaps166

Will investigate and report here :)

**Comment by zaps166** [comment]
@arthurzam Ok!

**Comment by arthurzam** [comment]
@DAP-DarkneSS

Btw, I would like to ask about openSUSE support - does it have automatic system for using CMake and creating RPM - we shouldn't add any support in QMPlay2?

@zaps166 
Uninstall fix
[fix-uninstall.patch.txt](https://github.com/zaps166/QMPlay2/files/345117/fix-uninstall.patch.txt)

**Comment by DAP-DarkneSS** [comment]
@arthurzam , sorry I didn't get the question…

**Comment by arthurzam** [comment]
@DAP-DarkneSS 
The package of QMPlay2 for openSUSE, which is using CMake: how does it constructs the RPM package file? Does you have an script for creating the RPM or you have specific patch that it applied?
I would like to add support for QMPlay2's CMake creating DEB & RPM packages. But in case that it is trivial on the appropriate systems then there is no need to add specific support for them.

**Comment by DAP-DarkneSS** [comment]
@arthurzam , I use openSUSE Build Service & PackMan Build service with such configs: https://github.com/DAP-DarkneSS/obs/tree/master/home:DarkSS:branches:multimedia:apps/QMPlay2 & https://github.com/DAP-DarkneSS/obs/tree/master/home:dap/QMPlay2 respectively. I don't use any party tools except ones provided by obs. F.e. I make local builds via `osc build`.

**Comment by DAP-DarkneSS** [comment]
If needed rpm & deb could be built at OBS triggered via github api.

**Comment by zaps166** [comment]
@arthurzam Thanks!

**Comment by zaps166** [comment]
Is it necessary to add RPM specs here? Every distribution and repo has its own settings (e.g. Packman uses Prostopleer, Multimedia does not).

**Comment by zaps166** [comment]
@DAP-DarkneSS Prostopleer can be disabled by removing three lines here (for qmake build): https://github.com/zaps166/QMPlay2/blob/b977b3066fc2b2b8737fda77018876d954b78db5/src/modules/Extensions/Extensions.pro#L31

**Comment by DAP-DarkneSS** [comment]
@zaps166 , thank you! I hope I'll switch it to cmake before the patch has  
to be updated.

**Comment by zaps166** [comment]
`I hope I'll switch it to cmake before the patch has to be updated.`

I don't understand this sentence :) But with all CMake patches (from today) which are already in `master` branch should work fine. Adding `-DUSE_PROSTOPLEER=OFF` in CMake command line should disable ProstoPleer.

**Comment by DAP-DarkneSS** [comment]
OBS:Multimedia:Apps still uses legacy build way (with monkey patching)  
because my release (13.2) doesn't provide cmake(Qt5LinguistTools) and  
because I want to check packages locally. Just don't care :)

**Comment by zaps166** [comment]
Ok :smile: 

> cmake(Qt5LinguistTools)

Btw. additional languages can be disabled `-DLANGUAGES=""` (no dependency for Qt5LinguistTools) :)
