### ISSUE TITLE
can't seek by mouse wheel

### ISSUE THREAD

**Issue by harujisaku** [zaps166/QMPlay2#374]
Mouse wheel can't scrolls video and audio on video dock in version 20.12.07.
But I can do it on the seek bar.

**Comment by zaps166** [comment]
I think it can be Qt 5.15.2 bug. 20.07.04 use Qt 5.14.2.

**Comment by zaps166** [comment]
It is Windows, right?

**Comment by zaps166** [comment]
I have to do a workaround for Qt 5.15.2 and Windows (Linux/X11 is OK).

**Comment by harujisaku** [comment]
Yes it is windows 10.

**Comment by zaps166** [comment]
Ok, I already reproduced the issue, it is a bug in Qt 5.15.2 (comparing to Qt 5.14.2). I will do a workaround for it. For unknown reason the mouse wheel event (only this) is not passed from native window to the parent widgets.

**Comment by harujisaku** [comment]
In qt 5.15.0 it was okay.

**Comment by zaps166** [comment]
hmm so 5.15.1 or 5.15.2 has a bug

**Comment by harujisaku** [comment]
Since the event has not come, it cannot be changed even if the volume change is set.
(It may be strange English because it is google translated)

**Comment by harujisaku** [comment]
This bug occurs when playing a video. It did not occur when playing audio.

**Comment by zaps166** [comment]
> This bug occurs when playing a video. It did not occur when playing audio.

Yes, because Vulkan and OpenGL create a native windows inside.

---

Bug is since Qt 5.15.1, I will check it, maybe is better to fix Qt this case.

---

The best solution for now is to re-release it with Qt 5.14.2 and this fix: a545ad4b1d812e9ab4d282d390c8d174f2e0b731. But I already removed my old compilation toolkit and I need to build old libs again :cry:

**Comment by harujisaku** [comment]
But that's not a serious problem, so I think it's a good idea to wait until the qt bug is fixed. I would like to help, but I have little knowledge of qt.

**Comment by harujisaku** [comment]
Thank you for releasing the old qt.

**Comment by zaps166** [comment]
Bad hash :/ Going to re-release....

**Comment by zaps166** [comment]
> Bad hash :/ Going to re-release....

Ok, done.

---

Now I used old Qt 5.14.2 and I'll try to fix it for Qt 5.15.2 for future releases!
