### ISSUE TITLE
YouTube starts playing video at 0:05, not 0:00

### ISSUE THREAD

**Issue by DarkWav** [zaps166/QMPlay2#375]
I recently noticed that with 20.12.07, YouTube videos are started at 0:05 instead of 0:00. It might be due to some change in YouTube-DL though.

**Comment by zaps166** [comment]
Hmm, weird. How did you get QMPlay2? What OS do you have?

**Comment by DarkWav** [comment]
Latest QMPlay2 build from AUR, I rebuilt it like 5 minutes ago and no changes. Happens with both QMPlay2-git and QMPlay2 packages. It might be due to a youtube-dl update, as I don't remember it happening yesterday.

**Comment by zaps166** [comment]
I also can see it, weird, but the AppImage works OK, hmm.

**Comment by DarkWav** [comment]
Thanks, it works!
