### ISSUE TITLE
The future of QMPlay2 on openSUSE Leap 15.X

### ISSUE THREAD

**Issue by DarkWav** [zaps166/QMPlay2#376]
Hello,
I recently noticed that you dropped support for a few library versions:
https://github.com/zaps166/QMPlay2/commit/02684fec6217ac87a37dbd40d7b07683122e5997
Namely Qt < 5.10, FFmpeg < 4.0, TagLib < 1.9 and CMake < 3.9.
Now, when trying to package the latest git master for openSUSE Leap 15.1 and 15.2 the following Issuess appeared:
- openSUSE Leap 15.1 does not provide Qt >= 5.10.

This isn't a big deal as openSUSE Leap 15.1 will go EOL by the beginning of next year and Qt 5.12 is available in openSUSE Leap 15.2
- No current openSUSE Leap version provides FFmpeg >= 4.0

This issue could in theory be circumvented by using the multimedia:libs repo for building, but in practice, in order to play non-free codecs, FFmpeg needs to be installed from packman repository which only offers FFmpeg 3.X for openSUSE Leap 15.2
This is quite dramatic as it forces me to either
- Freeze QMPlay2 at 20.12.07 for openSUSE Leap 15.2 and backport all madatory patches such as YouTube fixes.

This seems like a quite realistic solution to me, but it would mean the end of QMPlay2 feature updates for openSUSE Leap until at least mid-2021. It would allow me to retain support for Leap 15.1 though.
- Remove all FFmpeg 4 features out of QMPlay2 via a patch when compiling on openSUSE Leap 15.2

This will be a lot of work during next year, I'm not sure if this is even realistically possible.
- Disable FFmpeg support on openSUSE Leap 15.2 alltogether.

This would cripple QMPlay2 immensely and make the openSUSE Leap users' situation even worse than it was before.
Therefore, I would't recommend this solution.

Note that even with openSUSE Leap 15.3 the situation might not get better, so a delay until mid-2022 could happen.

Now, since you are the App's developer, which solution would you prefer?
I know that ffmpeg 4 not being availabe on Leap 15.X by now is ridiculous, but that's all the options I have right now.

**Comment by zaps166** [comment]
Hi

- Qt 5.10 is not a problem in this case,
- CMake 3.9 also shouldn't be a problem (it is required only for build, it can be used outside of repository),
- FFmpeg - weird that openSUSE still use 3.x. Another solution is to compile FFmpeg for QMPlay2 with suffix like `libavcodec.so.58.91.100-qmplay2`. Or I can still support FFmpeg 3.4.x. What do you think, which solution of these two is better?

> Disable FFmpeg support on openSUSE Leap 15.2 alltogether.

- QMPlay2 can't be compiled without FFmpeg - it is used in main app and in all other modules. Also it is used for audio resampling and all network connections.
- compiling without FFmpeg module makes no sense - only AudioCD and some chiptune and raw PCM files will play and still requires FFmpeg...

**Comment by DarkWav** [comment]
Thanks for the information, I think keeping support for FFmpeg 3.4.x would be the easier solution as getting proper ffmpeg4 libraries for openSUSE Leap is near-impossible at build time. Maybe you could add support for a cmake config option like `-DUSE_LEGACY_FFMPEG` to support FFmpeg 3.4.x. Then you could use new FFmpeg 4 features if the option isn't set.
Alternatively, I can freeze QMPlay2 at 20.12.07 for openSUSE Leap if you want to use FFmpeg 4 in QMPlay2

**Comment by zaps166** [comment]
FFmpeg 4.x is not really necessary now. The most important thing is that VA-API and VDPAU deinterlacing filters can fail when compiled using FFmpeg 3.x headers due to lack of one parameter in structure. Other things can be done on if-defs, they are not as important.

**Comment by zaps166** [comment]
What about this: https://software.opensuse.org/package/ffmpeg-4
Can QMPlay2 require this?

**Comment by zaps166** [comment]
I can see that FFmpeg 4.2.1 is in openSUSE 15.2 repository (http://download.opensuse.org/distribution/leap/15.2/repo/oss/x86_64/libavformat58-4.2.1-lp152.1.4.x86_64.rpm), but FFmpeg 4.2.x has a bug causes QMPlay2 to use 100% CPU core in some cases (see #239) when it is using GnuTLS instead of OpenSSL.

**Comment by DarkWav** [comment]
https://software.opensuse.org/package/ffmpeg-4 this is just a source package. It exists, but the full ffmpeg 4 it isn't being built for Leap due to compatibility issues. Some core components like libavformat do get built, but as you said they haven't been updated to 4.3.X yet and are pretty bare-bones which might become an issue later on. I can experiment with that libavformat version a bit and see if it works, if not I'll just disable  VA-API and VDPAU deinterlacing for openSUSE Leap.
Thanks for the help!

**Comment by zaps166** [comment]
I'll restore FFmpeg 3.4.x for simplicity!

**Comment by DarkWav** [comment]
Thanks!

**Comment by DarkWav** [comment]
Nevermind, I think you don't even need to lower the limit of ffmpeg in CMakeLists.txt, the latest git master builds just fine on openSUSE Leap 15.2 with a recent libavcodec package.

**Comment by zaps166** [comment]
QMPlay2 20.12.16 is a bugfix release and still can be compiled using old libraries for openSUSE Leap 15.1.
