### ISSUE TITLE
LastFM Cover Problem

### ISSUE THREAD

**Issue by zo-shin** [zaps166/QMPlay2#378]
When stations with metadata are being played, there is no cover displayed from LastFM, even **download covers** and **allow to download big covers** are enabled.

**Comment by zaps166** [comment]
Works fo rme

**Comment by zo-shin** [comment]
The station I tested is http://94.130.113.214:8000/chill
Could you give me your station?

**Comment by zaps166** [comment]
Something is wrong with encoding:
```
Title: ��M
Artist: ��M
```

**Comment by zaps166** [comment]
ffplay output:
```
Input #0, mp3, from 'http://94.130.113.214:8000/chill':
  Metadata:
    icy-br          : 128
    icy-description : *** Chill 24x7 *** http://schizoid.in ***
    icy-genre       : Chillout/Ambient/Psychill
    icy-name        : Radio Schizoid
    icy-pub         : 1
    icy-url         : http://94.130.113.214:8000/chill
    StreamTitle     : ��M - ��M
```

**Comment by zaps166** [comment]
Also twi problems on their website (wrong bitrate and text encoding):

![Screenshot_20201214_110849](https://user-images.githubusercontent.com/6239090/102068480-c1f45400-3dfc-11eb-99a2-852b04b9c192.png)

**Comment by zaps166** [comment]
This stream provides title/artist properly: http://stream14.shoutcastsolutions.com:8057/256stream

**Comment by zo-shin** [comment]
Unfortunately, there is no cover displayed from LastFM with the station you provided.
I found another app in which LastFM works well uses the API root URL `http://ws.audioscrobbler.com/2.0/?method=track.getInfo&api_key=xx&artist=xx&track=xx&format=json`. It’s not the HTTPS protocol and it’s in JSON format. I don’t know if they caused the problem.

**Comment by zaps166** [comment]
> Unfortunately, there is no cover displayed from LastFM with the station you provided.

Maybe it depends on song which is currently playing. Tried just now - works.

**Comment by barolo** [comment]
Can also confirm that it works, tested with some soma stations, and was surprised that it works, I'm unaware of any other linux player that does that.

**Comment by zo-shin** [comment]
It seems that cover display only supports online streams. Can local files with meta data also be supported?

**Comment by zaps166** [comment]
All files and online streams can download covers if they have correct Title and Artist metadata.

**Comment by zo-shin** [comment]
OK.
