### ISSUE TITLE
[Feature request] playback speed control

### ISSUE THREAD

**Issue by barolo** [zaps166/QMPlay2#383]
I'm using playback speedup constantly with podcasts and some youtube videos. 
The one in ffmpeg isn't worth adding
mpv [ https://github.com/mpv-player/mpv/pull/7865 ] and mpc-hc added scaletempto2 from chromium which makes it possible to have intelligible dialogue even at speeds above 2x

**Comment by zaps166** [comment]
> The one in ffmpeg isn't worth adding

Which filter is used in FFmpeg? Is [rubberband](https://rubberbandaudio.com/) ok?

**Comment by barolo** [comment]
Yup, it's rubberband. It's better than nothing ;)

**Comment by zaps166** [comment]
Ok, maybe I'll check the algo from Chromium. I tried to listen rubberband using pulseeffects 5.0 and it doesn't sound good.

**Comment by Augusto7743** [comment]
that feature plus voice normalization and auto playback next file when current file is finished are default for current players.

**Comment by barolo** [comment]
The thing is, no desktop player that I know of has a skipsilence feature the way android players do, it can cut hour from a 2h lectures, podcasts without being annoying. 
So I've just stopped using anything else for that purpose.

**Comment by zaps166** [comment]
> there's nothing that can beat scaletempo

You're wrong, because it is your use case and your feelings about algorithm. It depends on audio file. For me for user speech (audio book) Chromium algorithm can be better, but for many other music files, Rubberband is much better than Chromium.

**Comment by barolo** [comment]
> > there's nothing that can beat scaletempo
> 
> You're wrong, because it is your use case and your feelings about algorithm. It depends on audio file. For me for user speech (audio book) Chromium algorithm can be better, but for many other music files, Rubberband is much better than Chromium.

You're misquoting me, I said:  

> since there's nothing that can beat scaletempo PLUS skip silence from exo

I don't care about actual speedup algo that much It's the skipsilence feature that really matters to me.

**Comment by Augusto7743** [comment]
The feature speed playback and add automatically next file in same folder when current playback is finished are default to current players.

**Comment by Augusto7743** [comment]
Thanks.
