### ISSUE TITLE
No output in YouTube tab

### ISSUE THREAD

**Issue by TellNoLies** [zaps166/QMPlay2#384]
Hello.
I just found out about this project and am learning how to use it. Qmplay2 looks awesome, it is impressive with the features you have in it. I am using Gentoo Linux with KDE plasma, so it is nice to have a program that respects my theme.
However, I have an issue with the YouTube search tab not showing any results when using the search. When I do a search in the MediaBrowser I have output and I can play from the list no problem. Is there something that I am missing or need to check in the settings?
This is what I have for my use build options: "alsa audiofilters cuvid dbus extensions libass modplug opengl pulseaudio vdpau videofilters visualizations xv"
Am I missing what I need for the the youtube search to work? 
Also, is there a way that I can paste a youtube links and not drag the video from my browser into the playlist, or is that a similar problem with the search not showing up?

Thank you for your work and time.

**Comment by zaps166** [comment]
Hi, please upgrade to the recent version 20.12.16.

> Also, is there a way that I can paste a youtube links

Yes, just Ctrl+C link and Ctrl+V in QMPlay2.

**Comment by TellNoLies** [comment]
Thank you for the reply.
The Gentoo version for 20.12.16 is not available yet, but it should be updated soon. So I will upgrade as soon as it is procurable.
The keyboard copy and paste worked in the playlist. I was used to smtube and using the search bar to paste it into, so pasting it into the playlist page wasn't what I tried.
Thanks again for the help.
