### ISSUE TITLE
updater(?) problem

### ISSUE THREAD

**Issue by deathtrip** [zaps166/QMPlay2#387]
I have "Automatically check for updates" ticked off, but QMPlay2 still connects to `raw.githubusercontent.com`
So i assume it's the updater not respecting the setting, as that's the host it connects to.
I use the AUR source package on Arch Linux.

**Comment by zaps166** [comment]
It can connect to GitHub in two cases:
- media browser if the tab is visible (to check scripts update),
- updater to check if new version is available (only if checked, working properly - tested),

**Comment by deathtrip** [comment]
I always had the media browser widget disabled. Now i disabled all tabs except for video and equalizer, and it still connects on player startup.

**Comment by zaps166** [comment]
When it tries to connect? I have `aur/qmplay2` installed, `Automatically check for updates` unchecked - I can't see any connections.

**Comment by deathtrip** [comment]
After further testing i've found out that it's a dns request. But with all updates turned off, it's still unnecessary.

**Comment by zaps166** [comment]
> it's a dns request

How do you know that this is updater issue? When the checkbox is unchecked, the code which connects to the server is not called. Could you tell me how do you test it? When it happens - on application startup or later?

**Comment by deathtrip** [comment]
I assumed that if something within the player is connecting to the internet, it must be the updater.
I used to check it with wireshark some time ago, now i just see an entry in my [opensnitch](https://github.com/evilsocket/opensnitch) logger on port 53 on every player start.

**Comment by zaps166** [comment]
If the option is unchecked, updater doesn't do anything: https://github.com/zaps166/QMPlay2/blob/20.12.16/src/gui/MainWidget.cpp#L459. Connection to github is inside the function, which is not called at all: https://github.com/zaps166/QMPlay2/blob/20.12.16/src/gui/Updater.cpp#L93.

Moreover I can't see any connection in Wireshark on QMPlay2 startup when updater is disabled.

Be sure that:
- you use the newest version,
- you have unchecked updater option and pressed the apply button.
