### ISSUE TITLE
Sudden build failure

### ISSUE THREAD

**Issue by cbirchinger** [zaps166/QMPlay2#390]
Today i've tried to build the source (0e69506) and got the following build failure:

```
> FAILED: src/qmvk/CMakeFiles/QmVk.dir/PhysicalDevice.cpp.o 
> /usr/bin/x86_64-pc-linux-gnu-g++ -DNOMINMAX -DQT_USE_FAST_OPERATOR_PLUS -DUSE_OPENGL -DUSE_VULKAN -DUSE_YOUTUBEDL -DVK_NO_PROTOTYPES -DVULKAN_HPP_TYPESAFE_CONVERSION -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -Isrc/qmvk/QmVk_autogen/include  -Wall -Wno-deprecated-declarations -ggdb -march=haswell -maes -mabm -O2 -pipe -fPIC   -std=gnu++14 -MD -MT src/qmvk/CMakeFiles/QmVk.dir/PhysicalDevice.cpp.o -MF src/qmvk/CMakeFiles/QmVk.dir/PhysicalDevice.cpp.o.d -o src/qmvk/CMakeFiles/QmVk.dir/PhysicalDevice.cpp.o -c /var/tmp/portage/media-video/qmplay2-9999/work/qmplay2-9999/src/qmvk/PhysicalDevice.cpp
> /var/tmp/portage/media-video/qmplay2-9999/work/qmplay2-9999/src/qmvk/PhysicalDevice.cpp: In member function ‘void QmVk::PhysicalDevice::init()’:
> /var/tmp/portage/media-video/qmplay2-9999/work/qmplay2-9999/src/qmvk/PhysicalDevice.cpp:41:89: error: call of overloaded ‘basic_string(vk::ArrayWrapper1D<char, 256>&)’ is ambiguous
>    41 |         m_extensionProperties.insert(static_cast<string>(extensionProperty.extensionName));
>       |                                                                                         ^
> In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/string:55,
>                  from /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/stdexcept:39,
>                  from /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/array:39,
>                  from /usr/include/vulkan/vulkan.hpp:30,
>                  from /var/tmp/portage/media-video/qmplay2-9999/work/qmplay2-9999/src/qmvk/PhysicalDevice.hpp:23,
>                  from /var/tmp/portage/media-video/qmplay2-9999/work/qmplay2-9999/src/qmvk/PhysicalDevice.cpp:19:
> /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/basic_string.h:552:7: note: candidate: ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’
>   552 |       basic_string(basic_string&& __str) noexcept
>       |       ^~~~~~~~~~~~
> /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/basic_string.h:525:7: note: candidate: ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’
>   525 |       basic_string(const _CharT* __s, const _Alloc& __a = _Alloc())
>       |       ^~~~~~~~~~~~
> /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/basic_string.h:448:7: note: candidate: ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’
>   448 |       basic_string(const basic_string& __str)
>       |       ^~~~~~~~~~~~
> ninja: build stopped: subcommand failed.
```

What is puzzling is, that my current running version 0bbb3f9c was built on "Wed Dec 16 11:57:11 2020" and the
affected source file did not change for months.

Also at the time of the successful building was mesa-20.3.0 installed and now it's mesa-20.3.2
And GCC in both cases is gcc-9.3.0 with a distro internal revision bump in between.

So the 2 components (Vulkan and GCC/libstdc++), I would suspect causing harm didn't change much.

Removing "static_cast\<string\>" makes it build an run again, but not understanding the code, it'll probably
break something.

**Comment by zaps166** [comment]
> Removing "static_cast<string>" makes it build an run again, but not understanding the code, it'll probably
break something.

Vulkan C++ header doesn't have stable API. QMPlay2 should use it from submodule which must compile, mesa version doesn't matter. What is your build script? Does it properly init/update git submodules?

**Comment by cbirchinger** [comment]
I've used a Gentoo live git ebuild. It appears to checkout a different header version somehow.:

zaps166_QMPlay2.git # git rev-parse HEAD
0e6950659ba861d4fad3f5a62e3dd9156d7b17c3

zaps166_QmVk.git # git rev-parse HEAD
b7d2af8ab67e9ff3d32e63a28c855c4c896123ed

KhronosGroup_Vulkan-Headers.git # git rev-parse HEAD
9efc4a631161eeea11082bbd16d605cca0b7a01e
```
And "git show" in the shows it's using HEAD in all the sub modules:
```
./
commit 0e6950659ba861d4fad3f5a62e3dd9156d7b17c3 (HEAD, refs/git-r3/media-video/qmplay2/0/__main__, refs/git-r3/HEAD)

./src/qmvk:
commit b7d2af8ab67e9ff3d32e63a28c855c4c896123ed (HEAD, master, refs/git-r3/media-video/qmplay2/0/src_qmvk/__main__, refs/git-r3/HEAD)

./src/qmplay2/vulkan/headers:
commit 0e57fc1cfa56a203efe43e4dfb9b3c9e9b105593 (HEAD, tag: v1.1.130, tag: sdk-1.1.130.0, sdk-1.1.130, refs/git-r3/media-video/qmplay2/0/src_qmplay2_vulkan_headers/__main__)
```

I see that "git rev-parse HEAD" source directory and the checked out build directory are different:
9efc4a631161eeea11082bbd16d605cca0b7a01e vs. 0e57fc1cfa56a203efe43e4dfb9b3c9e9b105593

I'm not really understanding why because the only SOURCE it uses is "https://github.com/zaps166/QMPlay2"
without freezing, locking or defining any fixed version.

But since it builds by manually fetching the source, it's clearly a distribution failure. I'm closing this bug.

**Comment by cbirchinger** [comment]
Just for the record. The build script uses "-DQMVK_FIND_VULKAN=true" and i didn't use that option
when building manually. Removing this from the build script fixes the compilation.

**Comment by zaps166** [comment]
> Removing this from the build script fixes the compilation.

Ok!

---

`QMVK_FIND_VULKAN` is disabled by default and should never be used for QMPlay2. I don't know why it has been enabled in script, especially that this option doesn't have any user description in CMake file.

**Comment by PhobosK** [comment]
Thanks very much @zaps166 for the info :)

I stumbled upon the same problem as the OP, and removing the option QMVK_FIND_VULKAN from the Gentoo build script fixes it + QmPlay2 works with vulkan perfectly well.
I had filed a bug report for fixing it: https://bugs.gentoo.org/766027

Thanks again. Great work :)
