### ISSUE TITLE
Why and how this occurs

### ISSUE THREAD

**Issue by tasty0tomato** [zaps166/QMPlay2#393]
![2021-02-01 16_45_33-QMPlay2 updates](https://user-images.githubusercontent.com/48764449/106434917-2357ab80-64ad-11eb-84a8-20c7034d0832.png)

**Comment by tasty0tomato** [comment]
I live in China. Maybe because of this?

**Comment by zo-shin** [comment]
Yes, the update info is stored at a domain name which is not available in your region most of the time.

**Comment by tasty0tomato** [comment]
I understood. Maybe I should update QMPlay2 manually.
