### ISSUE TITLE
No sound when use dxva

### ISSUE THREAD

**Issue by lunatichai** [zaps166/QMPlay2#396]
Window 10 x64, QMPlay2-Win64-20.12.16.exe
when I do as shown in the screenshot the sound disappears
![image](https://user-images.githubusercontent.com/37984586/108169082-4fa83480-7109-11eb-9af6-b7f2eb008cd0.png)
If i set "Software decoder" playing with software decoder and dxva not used, although dxva checkbox checked.

**Comment by zaps166** [comment]
Please don't disable the software decoder, because audio is a software decoder.
To make DXVA2 default, go to the "Playback settings", move DXVA2 as first on the list and press "Apply".
