### ISSUE TITLE
QMPlay2 segfault at startup in Plasma Full Wayland Session.

### ISSUE THREAD

**Issue by DarkWav** [zaps166/QMPlay2#397]
Recently, I have been experimenting with Plasma's full Wayland Session on openSUSE Tumbleweed with proprietary NVIDIA drivers and found QMPlay2 to crash on startup when trying to launch it inside a full Wayland session.
It doesn't happen on X11 or normal Wayland Session, maybe there's something wrong with the NVIDIA drivers?
Or does QMPlay2 need XWayland to function?

I tried to fetch a half-decent stacktrace, I hope it is at least somewhat useful:
[stacktrace.txt](https://github.com/zaps166/QMPlay2/files/6016474/stacktrace.txt)

**Comment by zaps166** [comment]
It crashes inside the `vkEnumeratePhysicalDevices` function, looks like a driver bug or loader is using wrong driver file. Please check if any other Vulkan applicaiton runs natively on Wayland (not XWayland).
Alternatively if Vulkan doesn't work there, change QMPlay2 renderer to OpenGL in Renderer settings on X11 and try again on Wayland.

**Comment by DarkWav** [comment]
Yep, OpenGL works completely fine, thanks!
Now this might be a case for NVIDIA or the openSUSE Vulkan Maintainers.
I think this isn't really related to QMPlay2 directly, closing.
