### ISSUE TITLE
QMPlay2 cannot start (win10 x64)

### ISSUE THREAD

**Issue by hooke007** [zaps166/QMPlay2#399]
https://github.com/zaps166/QMPlay2/issues/239#issuecomment-785822597

After installation, I just double clicked the exe file, no window showed and I checked the Task Manager, I could see it but nothing happened.
Sorry I do not know how to collect more related logs. Tell me and I will have a try.

**Comment by zaps166** [comment]
Weird issue, show me your computer configuration. I assume Windows 10 from screenshot. What GPU(s) do you have? Are your drivers up to date?

QMPlay2 is not verbose, but check logs and config files here: `%AppData%\QMPlay2`:
- `QMPlay2.log` - log file
- `QMPlay2.ini` - main config file

---

You can try to change manually renderer from Vulkan (default) to OpenGL (not recommended if Vulkan is working properly):
- edit `QMPlay2.ini` in notepad,
- in section `[General]`,
- set `Renderer` to `opengl`,

```
[General]
Renderer=opengl
```

Revert to `vulkan` if it doesn't fix your issue.

**Comment by hooke007** [comment]
RTX2070super(latest driver)
After first failure start, I killed it in the task manager, and `\QMPlay2\` is empty.

**Comment by zaps166** [comment]
Do you have other GPUs enabled (Intel, Radeon, SLI, etc.)?
Can you check any other Vulkan application?

**Comment by hooke007** [comment]
There is an intel integrated card in my device.

**Comment by zaps166** [comment]
I have confirmation that QMPlay2 runs on Windows 10 and Nvidia RTX 2070s, drivers are new I think.

**Comment by zaps166** [comment]
Can you stop freezed QMPlay2 on debugger and look at backtrace? Is it freezed inside QMPlay2 code or in Vulkan loader/drivers?

**Comment by hooke007** [comment]
Oh, I found the solution. Just force it to start by 2070s in win10OS and driver panel settings. Now it can use 2070s' Vulkan.
Maybe the two graphic cards made it confused, I guess.

**Comment by zaps166** [comment]
>  Maybe the two graphic cards made it confused, I guess.

It should work properly with two graphics, I tested it on Windows 10 a few months ago (Intel UHD 630 + 1080Ti).
I'm curious what is wrong :smile:, but no logs here, unfortunately.

There are to ways:
1. I'll send you verbose QMPlay2,
2. If you able to use a debugger, use GDB for Windows to attach to freezed QMPlay2 process and get backtrace.

**Comment by hooke007** [comment]
I choose (1). I do not know how to debug.

**Comment by zaps166** [comment]
Try this: https://github.com/zaps166/QMPlay2/releases/download/vkdebug/QMPlay2-Win64-vkdebug.exe

**Comment by hooke007** [comment]
![Snipaste_2021-03-07_02-17-32](https://user-images.githubusercontent.com/41094733/110216670-55fd2580-7eeb-11eb-85cf-9b18e0546d02.jpg)

**Comment by zaps166** [comment]
It is a QMPlay2 bug in GDI code, not in Vulkan code.

**Comment by zaps166** [comment]
I think I fixed it: https://github.com/zaps166/QMPlay2/releases/download/vkdebug/QMPlay2-Win64-vkdebug2.exe

Could you check once again? Look at console output, also check if you can see 2 GPUs on the list, first on the list should be your primary GPU.

**Comment by hooke007** [comment]
![Snipaste_2021-03-07_02-56-50](https://user-images.githubusercontent.com/41094733/110217756-d5412800-7ef0-11eb-8bd6-3939465e1539.jpg)
It doesn't affect the playback, everything is ok.

**Comment by zaps166** [comment]
Ok, thanks for test!
