### ISSUE TITLE
openSUSE:Factory — fatal error: libavutil/cpu.h: No such file or directory 

### ISSUE THREAD

**Issue by DAP-DarkneSS** [zaps166/QMPlay2#4]
openSUSE has added recently ffmpeg to official repo so QMPlay2 could be added too. However official ffmpeg packaging introduces some strange errors: "fatal error: libavutil/cpu.h: No such file or directory" etc.

Another project with similar issue: https://github.com/MaartenBaert/ssr/issues/327
Package files listing: http://pkgs.org/opensuse-factory/opensuse-multimedia-libs/libavutil-devel-2.6.2-6.1.x86_64.rpm.html

PS Also it should be raised at configuring time not build one, shouldn't it?

**Comment by zaps166** [comment]
I see that this package contains "cpu.h" in other directory than most distributions have. "cpu.h" is usually located in "include/libavutil" directory, but in this package, the file is in "include/ffmpeg/libavutil" directory. Probably I must change QMPlay2's project files to use PKGCONFIG to detect include directories.

**Comment by zaps166** [comment]
This issue should be fixed by this commit: "https://github.com/zaps166/QMPlay2/commit/3bfd4e34baf5f4796799278e4a71401964de568b".

**Comment by DAP-DarkneSS** [comment]
Works fine, thank you very much!
