### ISSUE TITLE
Youtube resolution control does not work.

### ISSUE THREAD

**Issue by MariasStory** [zaps166/QMPlay2#400]
I am getting HD 30FPS youtube video, although I selected FullHD 60FPS.
It does not happen with SMPlayer.

**Comment by zaps166** [comment]
Something has changed on YouTube recently.

**Comment by DarkWav** [comment]
Can confirm, probably some YouTube.com -> youtube-dl -> QMPlay2 interaction issue.
youtube-dl itself can still download stuff at max quiality just fine though.
