### ISSUE TITLE
[Feature request] add external audio

### ISSUE THREAD

**Issue by lunatichai** [zaps166/QMPlay2#402]
it may be useful to add external audio stream, like subtitles from file

**Comment by zaps166** [comment]
It is possible:
- press Ctrl+U,
- select "FFmpeg",
- set: `[/path/to/stream1][/path/to/stream2]`,
- play,
- choose audio/video stream on Information panel,

![Screenshot_20210310_190554](https://user-images.githubusercontent.com/6239090/110675854-a5856f00-81d3-11eb-86f7-8c196bcf154b.png)
