### ISSUE TITLE
Three questions

### ISSUE THREAD

**Issue by windf17** [zaps166/QMPlay2#404]
My computer OS is Linux mint, I have three questions：
1. I can't use fcitx in the input window.
2. How do I save the playback progress. Can I open the program to play automatically from the last progress?
3. When I add a playback file, I feel that the sort of file name is not logical，for example：
file01
file02
 ...
file09
file100
file101
file102
 ...
file109
file20
file21
...
file29

**Comment by zaps166** [comment]
1. I don't know.
2. Go to Playback settings, check ![Screenshot_20210313_131626](https://user-images.githubusercontent.com/6239090/111029695-52dbcb00-83fe-11eb-8e32-1de5ddc8ba52.png) and press apply.
3. Because it sorts just like `ls -1`. It can be a feature request. Or use `file001` instead.

**Comment by windf17** [comment]
I can't find "remember playback position"
![2021-03-13_21-24](https://user-images.githubusercontent.com/65995709/111031444-8ccec080-8442-11eb-8482-25b33298c59c.jpg)

**Comment by windf17** [comment]
![2021-03-13_21-27](https://user-images.githubusercontent.com/65995709/111031513-e59e5900-8442-11eb-9854-6c12d7fcc4ed.jpg)
I want to input chinese，but i can't load fcitx in that input window

**Comment by windf17** [comment]
I set the position and size.you can see the playlist widgets and the video widgets position and size is perfect.
![2021-03-13_21-29](https://user-images.githubusercontent.com/65995709/111031687-b9370c80-8443-11eb-8ab1-4cd99d57c148.jpg)
but when i close the application and i open it again，the position and size is bad.
![2021-03-13_21-35](https://user-images.githubusercontent.com/65995709/111031753-0d41f100-8444-11eb-8780-ac823bbbf715.jpg)

**Comment by windf17** [comment]
I really like this app more VLC、SMPlayer.
I hope the application can automatic remember set position and size and playback position.
keep it simple and stupid.
Thank you very much.

**Comment by zaps166** [comment]
> I can't find "remember playback position"

Scroll down and find the checkbox. Then check it and press apply.

>  I want to input chinese，but i can't load fcitx in that input window

It's first time I met `fcitx`. How did you install QMPlay2? Is it AppImage or is it installed from sources or from repository?

>  but when i close the application and i open it again，the position and size is bad.

I think you found a bug: set size of internal panels, hide to tray, close, open, close, open, restore from tray.
All other cases when maximized window closes and opens again works for me as expected - it keeps the layout.

**Comment by windf17** [comment]
1. thank you, I find "remember playback position" .

2. It's appimage.

**Comment by zaps166** [comment]
> It's appimage.

Maybe that's a problem for `fcitx`. You can try to unpack appimage and remove most libraries to use system libs. Or recompile QMPlay2 from sources. What linux distribution do you use?

**Comment by windf17** [comment]
> > It's appimage.
> 
> Maybe that's a problem for `fcitx`. You can try to unpack appimage and remove most libraries to use system libs. Or recompile QMPlay2 from sources. What linux distribution do you use?

I use Linux Mint, Thank you.
I have a good idea. I will send email to you. my email address is 40859419@qq.com

**Comment by zaps166** [comment]
I didn't get any email so far.

**Comment by windf17** [comment]
> I didn't get any email so far.

![2021-03-17_02-54](https://user-images.githubusercontent.com/65995709/111364615-6cb23200-86cc-11eb-805e-ae37c36064b5.jpg)
I am sure that I have sent the email.

**Comment by windf17** [comment]
> > It's appimage.
> 
> Maybe that's a problem for `fcitx`. You can try to unpack appimage and remove most libraries to use system libs. Or recompile QMPlay2 from sources. What linux distribution do you use?

I tried other distribution，i can input chinese on it。

**Comment by zaps166** [comment]
> I tried other distribution

AppImage on other distribution?

> I am sure that I have sent the email

Sorry, it is in SPAM :/

**Comment by windf17** [comment]
My computer use Linux Mint, I install the qmplay2 by AppImage, then i cann't use fcitx in input box.
But I use Linux Manjaro, I install the qmplay2 by yay -S qmplay2, then i can use fcitx in input box.

**Comment by zaps166** [comment]
>  But I use Linux Manjaro, I install the qmplay2 by yay -S qmplay2, then i can use fcitx in input box.

So probably something is missing in AppImage and/or it can't integrate with it. It is not QMPlay2 issue.

**Comment by windf17** [comment]
> > But I use Linux Manjaro, I install the qmplay2 by yay -S qmplay2, then i can use fcitx in input box.
> 
> So probably something is missing in AppImage and/or it can't integrate with it. It is not QMPlay2 issue.

I got it, thank you.

**Comment by zaps166** [comment]
> When I add a playback file, I feel that the sort of file name is not logical，for example：

Fixed, try: `yay -S qmplay2-git`

**Comment by zaps166** [comment]
Btw. I hate when app doesn't have a title bar. I rarely use Chrome, but if use it, always with a title bar.

**Comment by zaps166** [comment]
About tabs: nice, but too much work on it - do you mean tabs instead of multi processes?

**Comment by windf17** [comment]
> About tabs: nice, but too much work on it - do you mean tabs instead of multi processes?

We can set the video tag, which has two items: video and playlist;
We can also set up YouTube tags, which have three items: videos and comments and channels;
We can also set the web TV tags, which has two video and channel options inside.
And so on ...
It is not possible to list all the functions together, we can classify them by tags.
Everything can be customized, and the final choice is left to the user.

**Comment by windf17** [comment]
> About tabs: nice, but too much work on it - do you mean tabs instead of multi processes?

We need to save the state before the process is closed, so that it can be restored when it is opened again.

For example: I opened a video process, when it is closed, it should remember the current playing file and progress and which monitor and window size and location and other information.
at the same time I open a YouTube process, when it is closed, it should also remember the current playback record and which monitor and window size and location and other information.

If there is no label to classify and save, then we can only save the last closed process state.

If there are tags to classify and save, then we can remember the state of each independent process before it is closed.
When opened again, it can perfectly restore the way it was before closing.

**Comment by windf17** [comment]
> About tabs: nice, but too much work on it - do you mean tabs instead of multi processes?

With the tag function:
we can even use the command line "qmplay2 -v" to quickly start videos, "qmplay2 -y" to quickly start YouTube, "qmplay2 -m" to quickly start music, etc., 
of course, we can also bind shortcuts to them Key, so that one key can start the function we need.
