### ISSUE TITLE
Youtube search shows nothing

### ISSUE THREAD

**Issue by cipricus** [zaps166/QMPlay2#406]
Fedora 33 Plasma
Qmplay2 Appimage version 21.03.09

Youtube search shows suggestions but finds nothing:

![image](https://user-images.githubusercontent.com/3447868/113254103-7344ca00-92c6-11eb-9ae0-952f9580fe10.png)

Trying the [same version installed from rpm](https://rpmfind.net/linux/rpmfusion/free/fedora/updates/33/x86_64/q/qmplay2-21.03.09-1.fc33.x86_64.rpm) the same problem is there. The same when installing as said [here](https://github.com/zaps166/QMPlay2#installation) for Fedora.

The same problem when trying   `qmplay2-20.07.04-2.fc33.x86_64.rpm` for Fedora 33.

**Comment by zaps166** [comment]
Unfortunately, youtube is not scriptable in QMPlay2 (yet), so you have to compile QMPlay2 from git master (fixed, but not yet release).

It is because of new youtube consent page...
