### ISSUE TITLE
YouTube Search: Playlist are grayed out again.

### ISSUE THREAD

**Issue by DarkWav** [zaps166/QMPlay2#407]
Hello, I just tested the new YouTube search with commit cab6f598553722b252bd80cd313496a666ae583c.
For normal videos it works great, but Playlists seem to be grayed out yet again:
![Screenshot](https://user-images.githubusercontent.com/16162641/113276613-4a313300-92e0-11eb-9c95-df9461e14061.jpg)
Perhaps YouTube changed their API yet another time -_-

**Comment by zaps166** [comment]
Should be fixed now on current master. Obviously their new great consent page. I don't know how long setting the empty cookie will work and why empty works :smile:

**Comment by DarkWav** [comment]
Thanks, It works great (For now :) )
