### ISSUE TITLE
Ability to switch off display/suspend/screensaver whilst playing audio?

### ISSUE THREAD

**Issue by Chromace** [zaps166/QMPlay2#41]
Currently, QMPlay2 will prevent the display from turning off/suspend whilst playing videos. It would be nice to have the option to do this for audio too. This is mostly for aesthetics sake, for full-screen playback of audio with nice album art.

**Comment by zaps166** [comment]
For full screen audio playback only if it contains a cover image (+ maybe for full screen visualizations)?

**Comment by Chromace** [comment]
That sounds like a good idea. Making it by default off could work as well?

**Comment by zaps166** [comment]
Fixed, please test :smile:

**Comment by Chromace** [comment]
It even works with full-screen visualisations! Thank-you :)
