### ISSUE TITLE
QtSvg icon engine plugin does not exist

### ISSUE THREAD

**Issue by kellerleicheorig** [zaps166/QMPlay2#412]
During startup, I get this message:

QtSvg icon engine plugin does not exist.
QMPlay2 will not scale icons!

I have reinstalled: lib64qt5svg5 but it does nothing.
Version of qt5svg5 is 5.15.2
Listet in our rpm package is :
/usr/lib64/libQt5Svg.so.5
/usr/lib64/libQt5Svg.so.5.15
/usr/lib64/libQt5Svg.so.5.15.2
/usr/lib64/qt5/plugins/iconengines/libqsvgicon.so
/usr/lib64/qt5/plugins/imageformats/libqsvg.so

My system is PCLinuxOS, and up to date.
Kernel 5.11.12

The player works but it's annoying.

How do I get rid of this message ?
![qmplay](https://user-images.githubusercontent.com/24721541/114286022-abcd6c00-9a5b-11eb-9aa7-b2965edafcb8.png)

**Comment by DarkWav** [comment]
This has been fixed already with commit 7b2df68ba9bdec45271d9791a4b997f7031aef2b, your distribution probably has not incorporated this patch downstream yet.
The [required patch](https://aur.archlinux.org/cgit/aur.git/plain/7b2df68ba9bdec45271d9791a4b997f7031aef2b.patch?h=qmplay2
) can be found on the AUR.
The easiest way to fix this would probably be to build the latest QMPlay2 git master from source.
You could also try to use [openSUSE Tumbleweeds' RPM file](https://download.opensuse.org/repositories/openSUSE:/Factory/standard/x86_64/QMPlay2-21.03.09-4.1.x86_64.rpm) (it's patched), but it might have dependency issues.

**Comment by kellerleicheorig** [comment]
Okay Thanks for replay, 

I will add the  patch now.

**Comment by zaps166** [comment]
I didn't expected that another SVG icon engine (from KDE) can behave differently :smile:
