### ISSUE TITLE
youtube download crashes

### ISSUE THREAD

**Issue by Amaunator** [zaps166/QMPlay2#415]
when I am trying to download audio from youtube using latest qmplay2-git-21.03.09.r24.g550de0c7-1 it crashes
30 Apr 2021 17:53:41.960] QMPlay2 crashed (SIGSEGV)
fish: Job 1, 'QMPlay2' terminated by signal SIGSEGV (Address boundary error)

**Comment by zaps166** [comment]
Hmm, is backtrace possible?

**Comment by zaps166** [comment]
I haven't got any crashes. Anyway try with current master.
