### ISSUE TITLE
Feature Request Disable screen saver and stand by

### ISSUE THREAD

**Issue by Augusto7743** [zaps166/QMPlay2#419]
Any chance to implement an feature to disable screen saver and suspend stand by in Linux version ?

**Comment by zaps166** [comment]
I don't test this functionality often, but it should work for screen saver on X11 (full screen playback only).

**Comment by Augusto7743** [comment]
Linux only allow disable screen saver in full screen ?
Have another media player (SMPlayer) allow disable screen saver, but enabling not works.

**Comment by zaps166** [comment]
> Linux only allow disable screen saver in full screen ?

QMPlay2, not Linux.

---

QMPlay2 should disable screensaver on Linux(X11 only), Windows, macOS, Android:
- fullscreen audio playback
- video playback (fullscreen and windowed)

---

QMPlay2 use this on Linux/X11: https://tronche.com/gui/x/xlib/window-and-session-manager/XForceScreenSaver.html

**Comment by Augusto7743** [comment]
You is saying that QMPlay2 disable screensaver ? If yes here not works.
Is an good feature.

**Comment by zaps166** [comment]
> If yes here not works.

Do you have Ubuntu 21.04 and you use QMPlay2 AppImage? I installed Ubuntu 21.04 and NVIDIA proprietary drivers: disabling screen saver works for me.

Is it X11 or Wayland?

**Comment by Augusto7743** [comment]
Appimage good feature is all libraries are in same file, but in each start the appimage is extracted in /tmp writing in disk. For some users need enable tmpfs.
Thus I had figured for some softwares extract the appimage and copy to /opt. All run correctly without problem loading opengl , vulkan or with security.

Using the appimage in fullscreen the screensaver works, but not in windowed mode.
Using X11 and LXQT.

**Comment by zaps166** [comment]
> Appimage good feature is all libraries are in same file, but in each start the appimage is extracted in /tmp writing in disk.

AppImage is mounted, not copied (internally it is `squashfs`, mounted using `fuse` driver): https://docs.appimage.org/reference/architecture.html. It is similar to mounting a disk partition to a directory.

---

> Using the appimage in fullscreen the screensaver works, but not in windowed mode.

- blocking the screensaver in fullscreen works for audio and video
- blocking the screensaver in windowed mode works only for video playback if it is not paused

**Comment by Augusto7743** [comment]
test using appimage file using vulkan render in user folder in both full screen and windowed mode not disable screen saver

**Comment by zaps166** [comment]
> LXQT

Maybe LXQt doesn't respect `XForceScreenSaver` function. Linux is a bit fragmented OS, every desktop works on its own. Is it any way to block screensaver on LXQt? Is it a D-Bus interface for it?

**Comment by Augusto7743** [comment]
Thanks very much about information appimage mount.
The fix is use the script below
https://raw.githubusercontent.com/jamcnaughton/useful-linux-scripts/master/xscreensaver/xscreensaverstopper.sh
now screen saver not works in full screen :)

**Comment by zaps166** [comment]
OK!

**Comment by wcasanova** [comment]
- archlinux
- Plasma
- Wayland
- QMPlay221.06.07.r1.ga47371ac-1 +  OpenGL ( Vulkan does not work well ) Intel HD Graphics 620
I confirm that the same thing happens in full screen, do not deactivate the screen saver.

**Comment by zaps166** [comment]
Wayland screen saver suspending is not supported yet.

**Comment by zaps166** [comment]
#683
