### ISSUE TITLE
Feature Request Not add new files in playlist

### ISSUE THREAD

**Issue by Augusto7743** [zaps166/QMPlay2#420]
Playlist add each file manually started.
Several times need to remove all files.
An option to disable that feature avoid it.
Your software about using hardware is very good and need only few new features to be in list in default player for Linux.

Thanks very much for doing that software.
Have an nice week.

**Comment by zaps166** [comment]
Try this:

![Screenshot_20210507_131328](https://user-images.githubusercontent.com/6239090/117441652-044a3900-af36-11eb-84de-8424d2cc8f81.png)

It is on "General settings" tab - check it and press apply. It will cleanup your playlist when software quits.

**Comment by Augusto7743** [comment]
Thanks.
Have an nice week :)
