### ISSUE TITLE
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()

### ISSUE THREAD

**Issue by perfect7gentleman** [zaps166/QMPlay2#423]
This error occurs when trying to play video in wayland+vulkan.

**Comment by zaps166** [comment]
I think it is a Qt issue. Qt Wayland plugin is not complete and unstable AFAIK.

**Comment by perfect7gentleman** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1820923#c3 
>Qt doesn't consider this a bug in their stuff.
https://forum.qt.io/topic/90639/comparing-qt-widgets-app-under-gnome-wayland-using-platform-wayland-egl-to-xcb/7
"...This means your window tried to grab focus in the compositor, which is not allowed in wayland. Don't create a bug for it, there's nothing we can do."
