### ISSUE TITLE
Please fix / allow to specify URL type from the cmdline argument

### ISSUE THREAD

**Issue by masscream** [zaps166/QMPlay2#424]
Hello, 
I've recently found out that QMPlay2 can be started to open urls from the command line, however its functionality lacks one basic thing - the URL type specification as it can be done via the classic "Open" GUI. When I open the youtube links, it loads immediately  through gui, in case I specify the url as an argument (from the browser ext. and tested also manually), it can't be opened. As I see in the media history, it's because the yt url is being opened as a normal one and therefore it's not processed via youtube-dl I guess. At some point, trying to open the same URL all over again, the QMPlay2 has memorized it and then it was able to open it from the commandline as well, but I believe this kind of processing is not very perfect. Thank you for you effort and the whole project.
![Screenshot_2021-05-12_12-39-25](https://user-images.githubusercontent.com/11753248/117962649-c1b2a300-b31f-11eb-84f0-4f0d2fce2f24.png)
![Screenshot_2021-05-12_12-39-41](https://user-images.githubusercontent.com/11753248/117962670-c5462a00-b31f-11eb-95eb-3160330fefd1.png)

**Comment by parkerlreed** [comment]
For some clarification because I was also confused...

Launching from the command-line doesn't auto detect URL type

```
[parker@t495 Jitterbit Studio 10.34]$ QMPlay2 --open https://www.youtube.com/watch?v=FHh5ZjVdpg0
[19 May 2021 10:37:57.523] Cannot open: https://www.youtube.com/watch?v=FHh5ZjVdpg0
```

Having `--open` behave like auto-detect in the GUI would help here. Or maybe have its own option?

**Comment by zaps166** [comment]
Try this:
`QMPlay2 YouTube://{https://www.youtube.com/watch?v=FHh5ZjVdpg0}`
or 
`QMPlay2 --open YouTube://{https://www.youtube.com/watch?v=FHh5ZjVdpg0}`

**Comment by zaps166** [comment]
Anyway auto detect address can be nice feature in cmdline.

**Comment by parkerlreed** [comment]
Aha thanks yeah YouTube:// works

**Comment by masscream** [comment]
Yeah, works like a charm :) could be added into the man, page, if not already there.... Thanks :+1:

**Comment by parkerlreed** [comment]
@zaps166 Thanks, working great!
