### ISSUE TITLE
Search function no more working on Haiku 64bit nightly

### ISSUE THREAD

**Issue by Brunobasta** [zaps166/QMPlay2#425]
Haiku nightly 64bit newest.
I cannot search for YouTube files anymore. Was working some time (weeks or month) ago.
Playing the older (YouTube) files works.
Everything else works fine...

**Comment by zaps166** [comment]
Try to compile with current master branch. I'll rewrite YouTube to JS script to avoid issues.

#406
#411

**Comment by zaps166** [comment]
> Haiku nightly 64bit newest.

I don't know who build QMPlay2 for Haiku and I don't know which version is built for Haiku.

**Comment by zaps166** [comment]
You have to compile QMPlay2 from current master branch (or use patch mentioned [here](https://github.com/zaps166/QMPlay2/issues/426#issuecomment-841542352)). It's not a Haiku issue, it a Google's stupid behavior to add annoying consent page. :disappointed:
