### ISSUE TITLE
Import youtube playlist?

### ISSUE THREAD

**Issue by ghost** [zaps166/QMPlay2#430]
I have a playlist from youtube i'd like to import, how would you do this?

**Comment by parkerlreed** [comment]
```
youtube-dl -j --flat-playlist "https://www.youtube.com/watch?v=SlPhMPnQ58k&list=PL4o29bINVT4EG_y-k5jGoOu3-Am8Nvi10" | jq -r '.id' | sed 's_^_https://youtu.be/_' > playlist.txt
```

Well I found a way to export the URLs from the playlist only to realize I don't see an import option for bare URL list in QMPlay2

@zaps166 Is it possible to import a plain URL list?

**Comment by zaps166** [comment]
QMPlay2 can import youtube playlist from youtube browser.

> Is it possible to import a plain URL list?

M3U/PLS playlists only or add them from command line.
