### ISSUE TITLE
Missing "to system tray on colse"

### ISSUE THREAD

**Issue by hamedsbt** [zaps166/QMPlay2#433]
I'm using QMPlay2 as radio player on Linux and it may working for couple of hours so it's make better user-experience to ability  "to system try on colse"
Thank you developer(s)

**Comment by zaps166** [comment]
Hi, you can press "`" key to hide to system tray. Also clicking on the tray icon will hide to tray (if desktop environment allows it). There is also possibility to change key shortcuts in settings (Set key bindings in General settings).

**Comment by hamedsbt** [comment]
Thank you for your reply. but I'm using close button usually.
