### ISSUE TITLE
Embed video in QML

### ISSUE THREAD

**Issue by nejatafshar** [zaps166/QMPlay2#435]
Is there a way to have the video rendering in qml? Something like Qt multimedia `VideoOutput` item which renders in a qml item using OpenGL?

**Comment by zaps166** [comment]
> Is there a way to have the video rendering in qml?

No. What's the purpose?

---

In renderer settings, you can choose OpenGL to use pure OpenGL (Vulkan is default). Adding additional OpenGL output via QML's `VideoOutput` and requiring the entire QML/QtQuick engine just to display video is pointless.

**Comment by nejatafshar** [comment]
I am looking for a way to use QMPlay2 in a QML based application which needs to play video files. If the ui is not widget based, then it is not straightforward to use QMPlay2 rendering in qml. Maybe finding a way to embed rendering widget as a qml item? Any way some libs like QtAV have ability to render output both in widgets using QOpenGLWindow and qml using QQuickFramebufferObject which is a good thing as many applications are qml based especially the ones intended for mobile and touch screen devices.

**Comment by zaps166** [comment]
Currently QML is not supported. Only pure OpenGL, pure Vulkan and some legacy video outputs.

**Comment by zaps166** [comment]
It is possible to embed QML/QtQuick in widgets, it's like embedding `QOpenGLWidget` (not `QOpenGLWindow`) but for sure it will have performance impact and it needs a lot of work I think.
