### ISSUE TITLE
Allow seeking for HLS stream

### ISSUE THREAD

**Issue by Fortuna666** [zaps166/QMPlay2#456]
Some players allow users to seek in HLS media (e.g. audio and video m3u8's). Loading an HLS video URL would start playback from the current live position and there is not possible to seek backward in an HLS stream.
Can you add the ability for HLS streams to allow seeking during live broadcast?

**Comment by zaps166** [comment]
#627 - now you can seek within QMPlay2's buffer on keys or mouse wheel over the video.
