### ISSUE TITLE
expand streaming support to other sites other than Youtube

### ISSUE THREAD

**Issue by beew** [zaps166/QMPlay2#457]
Hi, this is a feature request.

Currently yt-dlp and youtube-dl support many sites beside youtube but it seems that QMPlay2 cannot stream from these sites. It would be nice if QMPlay2 can work for all sites that are supported by yt-dlp or youtube-dl.

Thanks.

**Comment by zaps166** [comment]
If you press Ctrl+U (Playlist->Add->Address) you can choose "youtube-dl" from the list and past URL supported by the yt-dlp.
