### ISSUE TITLE
[feature request] show description of YouTube videos

### ISSUE THREAD

**Issue by RJVB** [zaps166/QMPlay2#465]
I just realised that the json document you get with `yt-dl -j <url>` also contains the video `description`, i.e. the text YouTube shows under the player.

It would be great if QMPlay2 could display that info (I find that much more interesting than, say, the full content URL ;)). As it is, I often have to open the YT page because I want to read the description, which is a waste of time that could be avoided.

It could be shown in the video's properties window (in copy'able form) and/or in the Information panel. In that panel, it could be abbreviated in a similar way as YouTube does because the panel will typically not be wide/big enough, and shown in complete form in a popup.

**Comment by RJVB** [comment]
I've started looking into implementing this but it appears there is no generic metadata class that is accessible both from `YouTube::getYouTubeVideo()` and `DemuxerThr::emitInfo()` (which appears to be where the info panel content is generated)? Can 'YouTube::getYouTubeVideo()` get at the `demuxer` instance of the `DemuxerThr` class?

**Comment by zaps166** [comment]
Should it be visible in information panel or is enough to show it in YouTube panel?

**Comment by RJVB** [comment]
How would you show it in the YouTube panel?

There are 2 descriptions, which correspond to the initial description you see on the webpage and the additional text under "show more", and if memory serves me well those are available separately in the video's json data. If so, I guess the ideal would be to show the initial/short one in the YT panel (the popup?) but the full description is often long enough that it would make sense to use the additional space available in the Info panel.

**Comment by zaps166** [comment]
It can be displayed in Lyrics, but it's different module and it needs to be changed a lot. But good idea!

**Comment by RJVB** [comment]
>It can be displayed in Lyrics, but it's different module and it needs to be changed a lot. But good idea!

You already receive title and artist there, from what I've seen.  I haven't looked from where it's called (from a single location only, I'd presume) and how you'd get the `description` information available there, but it seems to me that it would be much less of an overhaul to add that information to the call into the Lyrics class. Or even to pass those parameters via a structure.
Then, you'd probably show the description first if one's available, followed by the result of the lyrics look-up(s).

**Comment by zaps166** [comment]
Already in master!
