### ISSUE TITLE
[Feature request] Spectrum FTT scrolling volume change

### ISSUE THREAD

**Issue by marczas** [zaps166/QMPlay2#470]
Please add scrolling volume change on spectrum FTT widget view.

**Comment by zaps166** [comment]
> scrolling volume change

spectrogram?

**Comment by marczas** [comment]
> spectrogram?
FTT Spectrum Widget (pl: konkretnie chodzi mi o to żeby w tej zakładce dało się zmieniać głośność kółkiem myszy tak jak w zakładce wideo)
![QMPlay2_vNIdx0aw81](https://user-images.githubusercontent.com/47288403/143964252-eb77e988-0610-4758-9453-fa96d7e03d25.jpg)

**Comment by zaps166** [comment]
> konkretnie chodzi mi o to żeby w tej zakładce dało się zmieniać głośność kółkiem myszy tak jak w zakładce wideo

Ok, teraz rozumiem. Myślałem, że może chodzi o dodanie spektrogramu do tego :smile: 

> A i mam jeszcze pytanie, gdzie mogę usunąć niepotrzebne profile?

Kliknij prawym na nazwę profilu z menu.
