### ISSUE TITLE
vdpau : video freezing with 25 fps stream

### ISSUE THREAD

**Issue by taktiker12** [zaps166/QMPlay2#478]
hi zapps 
just notice a freezing video when playing H264 25 fps stream from my enigma box , especially after the version qmplay2 19.12  . 
![test](https://user-images.githubusercontent.com/9823492/147385631-1dce7d73-9858-4c80-a983-1ac0cdc6cf8b.png)
thank You

**Comment by zaps166** [comment]
Hi, I need more information. QMPlay2 19.12.x is very old, please upgrade. Does it happen without VDPAU? Can you try CUVID on OpenGL or Vulkan (after QMPlay2 upgrade)?

**Comment by taktiker12** [comment]
the freezing happen with newer version ( from version 20.XX to 21.XX) .using cuvid , there is no freezing .
,

**Comment by zaps166** [comment]
> using cuvid , there is no freezing 

use CUVID instead of VDPAU.

> the freezing happen with newer version ( from version 20.XX to 21.XX)

Maybe because I removed VDPAU X11 surface which was a little bit faster than VDPAU + OpenGL. What is your Graphics card?

**Comment by taktiker12** [comment]
i use GTX1050Ti ..it is ok with CUVID option .
thank U zaps166
