### ISSUE TITLE
libmodplug: MixSoundBuffer size mismatch

### ISSUE THREAD

**Issue by arthurzam** [zaps166/QMPlay2#48]
When compiling QMPlay2 with [`-flto` flag](https://gcc.gnu.org/onlinedocs/gccint/LTO-Overview.html) (I really recommend using it when building the release builds), a warning is found:

```
/home/arthur/dev/QMPlay2/src/modules/Modplug/libmodplug/snd_dsp.cpp:102:12: warning: type of 'MixSoundBuffer' does not match original declaration
 extern int MixSoundBuffer[MIXBUFFERSIZE*2];
            ^
/home/arthur/dev/QMPlay2/src/modules/Modplug/libmodplug/fastmix.cpp:17:5: note: previously declared here
 int MixSoundBuffer[MIXBUFFERSIZE*4];
     ^
```

I guess this snippet explains the problem - mismatch in size of array. I guess the best solution would be change the size to `MIXBUFFERSIZE*4` in `snd_dsp.cpp:102`, but because I don't know what happens in libmodplug I think this is better for you to review it.

**Comment by zaps166** [comment]
> I guess (...)

Does it link properly if `extern` also have `MIXBUFFERSIZE*4` ?

**Comment by zaps166** [comment]
Aaah, this is only a warning... :smiley:
