### ISSUE TITLE
Qmplay issue with PKGBUILD

### ISSUE THREAD

**Issue by ghost** [zaps166/QMPlay2#486]
Issue with qmplay2 
"1 error generated.
[9/190] Building CXX object src/modules/Extensions/CMakeFiles/Extensions.dir/Downloader.cpp.o
ninja: build stopped: subcommand failed.
==> ERREUR : Une erreur s’est produite dans build().
    Abandon…

real	0m4,130s
user	0m7,853s
sys	0m0,734s
:: Unable to build qmplay2 - makepkg exited with code: 4
=>> Try again? [y/N]: "

- Works fine with qmplay2-git
- shaderc dependencies seems to be missing

**Comment by zaps166** [comment]
It should be fixed now!
