### ISSUE TITLE
M3U not interpreted correctly with Mac CR/LF format (<CR>)

### ISSUE THREAD

**Issue by acnapyx** [zaps166/QMPlay2#487]
If an M3U file is with old Mac CR/LF format (<CR>) is opened, it's interpreted only as single line, not as a playlist containing multiple lines. (If the file is saved as PC or Unix format, it works just fine.)

Steps to confirm:

1. Save the following file as M3U with Mac CR/LF format. 
```
#EXTM3U
 
#EXTINF:111, Sample artist name - Sample track title
C:\Music\SampleMusic.mp3
 
#EXTINF:222,Example Artist name - Example track title
C:\Music\ExampleMusic.mp3

```
Attaching also a [zipped example file](https://github.com/zaps166/QMPlay2/files/8149444/mac-cr-lf-format.zip) as GitHub doesn't allow M3U attachments.

2. Try to open it with QMPlay2.

Please fix.

**Comment by zaps166** [comment]
Done!
