### ISSUE TITLE
MyFreeMP3 browse stop working

### ISSUE THREAD

**Issue by unspacyar** [zaps166/QMPlay2#488]
Since some weeks ago, the search using MyFreeMp3 option (in MediaBrowser tab) stop working.  No error message, just every query get no items found.  I tried using the MyFreeMp3 site, and works, so I guess there was some change in the site API.

**Comment by zaps166** [comment]
Exactly, API or URL change.

**Comment by zaps166** [comment]
Fixed, please check now!

**Comment by unspacyar** [comment]
Thank you!  Is working now!
