### ISSUE TITLE
[regression] VAAPI.cpp expects VAProfileAV1Profile* in libva 2.6.1

### ISSUE THREAD

**Issue by RJVB** [zaps166/QMPlay2#490]
Hi,

My system is still at libva 2.6.1 and the build of `master` now fails because VAAPI.cpp expects the `VAProfileAV1Profile*` tokens to be defined. Something must be wrong with the VA version detection logic you use.

I get `VA_VERSION_HEX == 0x1060000` so this failure is to be expected.

`va_version.h` also defines a `VA_VERSION_CHECK` macro so I can solve this regression by checking with `#if VA_CHECK_VERSION(1, 7, 0)`. However, just above (line 500) the access to the `VAProfileVP9Profile2` token is protected with the same test of `VA_VERSION_HEX`, and I do have that token in my v2.6.1 (so that was introduced before libva 1.7.0).

**Comment by zaps166** [comment]
I don't get it why this library has 2 version numbers... Maybe move entire enum into QMPlay2 instead of ifdefs?

**Comment by RJVB** [comment]
On Sunday March 20 2022 07:33:24 Błażej Szczygieł wrote:
>I don't get it why this library has 2 version numbers... Maybe move entire enum into QMPlay2 instead of ifdefs?

What do you mean with 2 version numbers? I think there's a simple confusion with which version introduced what feature. Or maybe their way of calculating the hex version number changed at some point. We could end up in the current situation if they had done that such that the new VA_VERSION_HEX is always larger than the values calculated with the old algorithm *for the versions where that old algorithm was valid*. So if you calculate a hex version for, say, libva v2.7.0 with the old algorithm you'd get a value that's much too low. If this is what happened it must have been done with v1.6.0 at the latest because I already get a VA_VERSION_HEX that's much larger than the value the code is expecting.

I hope this is clear...

Folding the enum into QMPlay2 would circumvent this problem, but you'd end up thinking the AV1 profiles are supported by libva 1.6; I have no idea what the effect of that would be. I think it's better to use the version check macro because that should work with every version you want to support. You'd just have to verify exactly when `VAProfileVP9Profile2` was introduced (as said, 2.6.1 has it).

**Comment by zaps166** [comment]
Now it's independent of the header version, please try to compile now!

**Comment by zaps166** [comment]
There should be no problem, it's only an additional test whether codec is supported to not stat decoding it:
```
    // Optional check - FFmpeg opens VA-API when first frame is given to the codec,
    // so check here if codec is supported to not open VideoWriter unnecessarily.
```
