### ISSUE TITLE
Playback of mono recording in left channel only

### ISSUE THREAD

**Issue by RJVB** [zaps166/QMPlay2#496]
A strange issue: QMPlay2 is one of a small handful of applications that have an issue with playback of mono audio over my Behringer UMC204HD. When that device is connected via one of the USB3 ports on my Belkin Thunderbolt dock, mono content plays back over the left channel only (from the affected applications).

QMPlay2 is evidently not at fault here, but there's clearly something it could be doing differently; neither VLC nor Apple's own QT Player are affected (but the system volume control feedback sound *is* affected).

**Comment by zaps166** [comment]
I guess the problem is with mono playback on your device, it is playing mono over left channel (QMPlay2 and volume notification), but QuickTime and VLC probably mixes audio to stereo before playback.

I remember on Linux/Pulseaudio and 5.1 audio setup, mono was playing in center speaker only.

Try this setting: ![Screenshot_20220420_010046](https://user-images.githubusercontent.com/6239090/164114961-685d4339-a941-4913-a7b4-3fb808f8da03.png)

**Comment by RJVB** [comment]
On Tuesday April 19 2022 16:01:15 Błażej Szczygieł wrote:

>I guess the problem is with mono playback on your device, it is playing mono over left channel (QMPlay2 and volume notification), but QuickTime and VLC probably mixes audio to stereo before playback.

Most applications apparently do. The curious thing is that it doesn't happen when I connect the device to one of the USB2 ports in/on my Mac. I am also seeing assertion warnings coming from a system library, so something is definitely off somewhere. It's odd enough that it caught the interest of a Behringer support engineer ;)

>I remember on Linux/Pulseaudio and 5.1 audio setup, mono was playing in center speaker only.

That actually makes sense, even if it's not what you expected! The centre speaker is supposed to be for "voice content", and it's in fact a recorded voice message that made me discover the issue.

>Try this setting: ![Screenshot_20220420_010046](https://user-images.githubusercontent.com/6239090/164114961-685d4339-a941-4913-a7b4-3fb808f8da03.png)

Ah, that looks like exactly the kind of workaround I was going to suggest (and looked for, in vain). Except I was thinking of an up-sampling approach, not one that converts everything.

I actually looked around in the code but realised I don't know much about how the actual sound data has to be sent. I did see something that looks like support for filters, but there is no evidence of audio filter support in the GUI? A fun solution to this mono problem would be to apply an (optional) filter that adds a pseudo-stereo effect ;)

**Comment by RJVB** [comment]
On Tuesday April 19 2022 16:01:15 Błażej Szczygieł wrote:

>Try this setting: ![Screenshot_20220420_010046](https://user-images.githubusercontent.com/6239090/164114961-685d4339-a941-4913-a7b4-3fb808f8da03.png)

This works of course.

How about making it possible to force the number of channels upward only, so mono content gets promoted to stereo, but content with more than 2 channels does get changed? It doesn't look entirely straightforward to adapt the code in SettingsWidget.cpp to follow this, but for the actual conversion it shouldn't be too hard (if I can find where it is ^^). How about controlling this by making the ForceChannels checkbox a tri-state button?

R.

**Comment by RJVB** [comment]
Something else I noticed: the subwoofer channel from the testfiles here <https://www2.iis.fraunhofer.de/AAC/multichannel.html> doesn't sound on my Mac, even when I force a conversion to 2 channels.
