### ISSUE TITLE
Where is the full list of keyboard shortcuts?

### ISSUE THREAD

**Issue by formlessdao** [zaps166/QMPlay2#501]
Where is the full list of keyboard shortcuts? Can't find them anywhere.
Also can I change them so some are remapped to some of my mouse buttons?

**Comment by zaps166** [comment]
> Where is the full list of keyboard shortcuts?

Settings -> General Settings -> Set key bindings (scroll to the bottom).

> Also can I change them so some are remapped to some of my mouse buttons

No, you can change only "Mouse wheel action on video dock" in "Playback settings".

---

Additionally:
- mouse wheel click toggles pause, 
- shift + mouse left click + mouse move - moves video,
- ctrl + mouse left click + mouse move - moves subtitles,
- mouse left click + mouse right click - changes aspect ratio,
- mouse left click + mouse wheel click - resets video changes,

**Comment by formlessdao** [comment]
Thanks!
