### ISSUE TITLE
High CPU usage and YouTube search

### ISSUE THREAD

**Issue by UserNameJohnDoe** [zaps166/QMPlay2#506]
Hello! I have a low-end laptop and I have some problems.
**1) Very high CPU usage.**
When I watch youtube videos, cpu is almost loaded 100%. But when I open videos with mpv, cpu is loaded ~15%. But in mpv I change the video format with yt-dlp to avc1 codec.
I changed “Preferred video codec” in settings to h.264 instead of VP9, but it didn’t help.
How can I change the codec to avc1 as default for youtube videos in QMPlay2?

**2) Youtube search doesn’t work properly.** 
It doesn’t show all found videos and it doesn’t sort videos by date. When I want to sort videos by date it still shows them randomly.

**Comment by UserNameJohnDoe** [comment]
I have core i3 2350m. But I have reduced the CPU frequency to 1.78. The task manager always shows the maximum cpu usage as 78%, not 100% in any program. In this case youtube video loads cpu ~78% that is equal to 100% at the base CPU frequency. But mpv loads cpu ~25-27% with avc1 codec. With vp9 mpv also loads ~78%.

**Comment by UserNameJohnDoe** [comment]
I am using default player settings.
CPU usage with MPV
![mpvCPU](https://user-images.githubusercontent.com/93444428/168126265-e7683470-0e49-4309-afa4-f42b365493d7.png)

Maybe useful information from MPV
![mpvInfo](https://user-images.githubusercontent.com/93444428/168126297-9cfe83f3-8452-421c-95f1-0f62856da756.png)

AVC1 is one of available formats that I can chose with yt-dlp.
![youtubeFormats](https://user-images.githubusercontent.com/93444428/168126327-1de4b99b-3701-4e92-b1b5-4c15337f2473.png)
![QMplay2CPU](https://user-images.githubusercontent.com/93444428/168126364-eb303a49-5a0c-4015-82ee-1d5f4e74cdbf.png)

Can you close FFT and simple visualization and check CPU load again?
Nothing changed.

**Comment by zaps166** [comment]
Ah it's Windows. I guess MPV uses hardware decoding. QMPlay2 can do it (also on Windows), but it's disabled by default.

Go to "Playback Settings" and set decoders order like this and press "Apply":
- for NVIDIA:
![Screenshot_20220512_192001](https://user-images.githubusercontent.com/6239090/168132522-65aa0057-bf3e-454b-9ca6-ee204d3d8294.png)
- for Intel GPUs and AMD Radeon:
![Screenshot_20220512_192113](https://user-images.githubusercontent.com/6239090/168132731-099ea2c5-c5b1-4ab9-ad95-e6653d3947db.png)

**Comment by zaps166** [comment]
For best hardware decoding performance use VA-API with Vulkan on Linux (Intel and AMD Radeon only).

**Comment by UserNameJohnDoe** [comment]
Unfortunately, it didn't help( I use integrated GPU.

**Comment by UserNameJohnDoe** [comment]
Youtube with h264ify extension loads cpu ~50-60%.

**Comment by zaps166** [comment]
Do you use Vulkan or OpenGL? If Vulkan can't interoperate with D3D11VA, try OpenGL with DXVA (it can help if you have old drivers for old hardware).

**Comment by UserNameJohnDoe** [comment]
I use OpenGL. When I choose Vulcan in Render settings, after restart program returns OpenGL.

**Comment by zaps166** [comment]
I see, Vulkan not supported (too old hardware and driver). DXVA might not work, too.

QMPlay2 relies on Direct3D and OpenGL/Vulkan interoperation which requires newer driver (and newer GPU). The only solution is to keep CPU decoding (set software decoder as first) or try Linux with VA-API. Probably MPV use Direct3D 11 for rendering (no need to interoperate with OpenGL).

**Comment by UserNameJohnDoe** [comment]
Ok, thank you for help!

**Comment by formlessdao** [comment]
Why is hardware decoding disabled by default?

**Comment by zaps166** [comment]
> Why is hardware decoding disabled by default in Linux?

It's disabled on Windows, too.
Because of stability - hw decoding is dependent on drivers which can crash application or system in some cases, sometimes video can be decoded with graphical glitches, sometimes HW decoder is slower than CPU.
