### ISSUE TITLE
Ability to download YouTube videos as audio files?

### ISSUE THREAD

**Issue by Chromace** [zaps166/QMPlay2#51]
Currently, if one searches for a video in QMPlay2's YouTube widget, it can only be downloaded as a video. It would be nice to be able to download them as audio files as a means to save hard disk space.

Whilst this can be somewhat mitigated by attempting to search for the song on Prostopleer, some more obscure music can't be found there.

**Comment by zaps166** [comment]
YouTube and other similar websites will be improved in the future.

Currently you can download audio from YouTube:
- search on YouTube for a music,
- expand the tree,
- right click and "Download" one of YouTube audio (Vorbis, Opus or AAC),
- after download:
 - Vorbis and Opus are downloaded as MKV (WebM) format, you can repack it to OGG without a conversion: `ffmpeg -i file.webm -acodec copy file.ogg`
 - AAC is downloaded to `.mp4`, so change extension to `.m4a` for an audio extension.

Bit rate in description on YouTube search in QMPlay2 can differ from a real bit rate. Some of them can be missing.

For some video clips you must have `youtube-dl` installed.

There is no possibility to download MP3 from YouTube (I recommend Vorbis or even Opus; AAC for better compatibility with some hardware players). YouTube doesn't have MP3, so you must convert it - download best quality audio from YouTube and then convert it to MP3 (probably any other MP3 downloader from YouTube converts the audio, so except an additional quality loss). Manually you can do it from e.g. MKV(WebM; Vorbis/Opus): `ffmpeg -i file.webm -acodec libmp3lame -ab 160k file.mp3`. You can use `SoundKonverter` for batch conversion.

**Comment by Chromace** [comment]
Thank-you! Apologies, I did not see that. ^^;
