### ISSUE TITLE
GPU scaling algorithms

### ISSUE THREAD

**Issue by kkanungo17** [zaps166/QMPlay2#512]
Hi,

Would it be possible to implement a feature to scale on Intel GPUs? As apparently they have a good scaling algorithm in quicksync.

**Comment by zaps166** [comment]
Id it upscale od downscale?

**Comment by kkanungo17** [comment]
Both, as it seems. There's a scale_qsv filter equivalent in FFmpeg that can use it.

As an aside, is QMPlay2 color managed?

**Comment by zaps166** [comment]
Currently I don't plan to add custom scaling filters. I'm aware it's faster on Intel GPUs that GLSL filter (it's using VideoEnhance), but it's much harder to add and maintain. I can try to speedup and improve GLSL HQ scaling filter in the future.

---

How about the "color managed" question? Is it about applying e.g. Rec. 709, Rec .601 color spaces to video or applying display color space (xiccd/colord)?

**Comment by zaps166** [comment]
Rec. 601, Rec. 709, Rec. 2020 are applied to video (depends on metadata and frame size). HDR is not not currently supported at all (bad/weathered colors and bad luminance on both HDR and SDR screens).

Display color profile is not currently applied, however it [might work on macOS](https://github.com/zaps166/QMPlay2/blob/7eb796a4dc2495cf93802c4ab94877c816ffffa7/src/gui/Main.cpp#L614).

**Comment by kkanungo17** [comment]
Too bad about the quicksync scaling, seemed like a nice way to get HQ scaling without performance hit.

I was talking about applying display color profile on linux, with gamma adaptation (e.g. bt.1886 to 2.2).

**Comment by zaps166** [comment]
> Too bad about the quicksync scaling, seemed like a nice way to get HQ scaling without performance hit.

Is it available in VA-API? Maybe this:

```c++
/** Scaling flags for vaPutSurface() */
#define VA_FILTER_SCALING_DEFAULT       0x00000000
#define VA_FILTER_SCALING_FAST          0x00000100
#define VA_FILTER_SCALING_HQ            0x00000200
#define VA_FILTER_SCALING_NL_ANAMORPHIC 0x00000300
#define VA_FILTER_SCALING_MASK          0x00000f00

/** Interpolation method for scaling */
#define VA_FILTER_INTERPOLATION_DEFAULT                    0x00000000
#define VA_FILTER_INTERPOLATION_NEAREST_NEIGHBOR           0x00001000
#define VA_FILTER_INTERPOLATION_BILINEAR                   0x00002000
#define VA_FILTER_INTERPOLATION_ADVANCED                   0x00003000
#define VA_FILTER_INTERPOLATION_MASK                       0x0000f000
```

But it will be available only when decoding by VA-API and needs to be implemented in QMPlay2.

---

> I was talking about applying display color profile on linux, with gamma adaptation (e.g. bt.1886 to 2.2).

Not possible, I need help how to apply display color profile from ICC in GLSL.

**Comment by kkanungo17** [comment]
Yep, I was talking about those. I was wondering if those could be utilised even with software decode.

> Not possible, I need help how to apply display color profile from ICC in GLSL.

I see.

**Comment by zaps166** [comment]
> Yep, I was talking about those. I was wondering if those could be utilised even with software decode.

I think it's possible to upload CPU-decoded texture to VA-API, but QMPlay2 can't do it. For now, QMPlay2 can use HW deinterlacing filter in VA-API in some cases only (Intel with old `libva-intel-driver` driver). `intel-media-driver` and Radeon uses Yadif on Vulkan instead.

**Comment by kkanungo17** [comment]
I see. Hopefully it would be possible in the future.

**Comment by zaps166** [comment]
Could you open an issue for color profile?

**Comment by kkanungo17** [comment]
Sure.

**Comment by zaps166** [comment]
[I've changed the upscale algorithm](https://github.com/zaps166/QMPlay2/commit/f0a57d281608071a7421875f69064d8391b1a744).
