### ISSUE TITLE
Input Virtual allow

### ISSUE THREAD

**Issue by markosc** [zaps166/QMPlay2#516]
it is possible that the application can detect the virtual audio inputs, vlc detects it, and qm2play in windows also detects with "Port Audio" but in linux (arch / artix) it does not 
![image](https://user-images.githubusercontent.com/16872280/180627702-29d356ee-42fb-4977-98d5-71e89c82f9f0.png)
![image](https://user-images.githubusercontent.com/16872280/180627719-bb16d24a-f771-4f40-a512-ebcd456b3b2e.png)

**Comment by zaps166** [comment]
Virtual audio inputs or virtual audio outputs? What is the virtual sink? Is it PipeWire virtual output or ALSA virtual output or something else?

For ALSA try [this](https://github.com/zaps166/QMPlay2#alsa).
For PipeWire open `pavucontrol` or similar tool and change output device for QMPlay2 in `Playback` tab.

**Comment by RafaelLinux** [comment]
> Virtual audio inputs or virtual audio outputs? What is the virtual sink? Is it PipeWire virtual output or ALSA virtual output or something else?
> 
> For ALSA try [this](https://github.com/zaps166/QMPlay2#alsa). For PipeWire open `pavucontrol` or similar tool and change output device for QMPlay2 in `Playback` tab.

If it helps (I don't use PulseAudio yet, but Pipewire) this is what I think it means with "sink":
sink: device that can output digital audio stream from PulseAudio (typically speaker signal, headphone output, HDMI output, line out; may or may not be backed by actual audio hardware but PulseAudio will treat it as if it was real hardware).

I used it in some Linux-powered TVBoxes to redirect simultaneously audio to HDMI and headphones.
