### ISSUE TITLE
Maintain audio pitch when speeding up/down playback?

### ISSUE THREAD

**Issue by RJVB** [zaps166/QMPlay2#518]
Hi,

Am I overlooking an option to maintain audio pitch when slowing up or down playback speed?

If not, it'd be great to have such an option!

**Comment by zaps166** [comment]
#383

**Comment by zaps166** [comment]
@RJVB Do you prefer time domain or frequency domain algorithm? Is Rubberband ok?

**Comment by RJVB** [comment]
***@***.*** Do you prefer time domain or frequency domain algorithm? Is Rubberband ok?

TBH, whichever works over a reasonable range and (why not) is the easiest to implement. My use of this feature would not require the same hifi quality of sound as the original.

**Comment by zaps166** [comment]
Now I checked Rubberband again. The new Rubberband 3 has better sound quality than previous version, so it should be enough.

**Comment by RJVB** [comment]
Fine with me then!

**Comment by zaps166** [comment]
RubberBand >= 3.0 is required, please test!

`Playback->Keep audio pitch`

**Comment by RJVB** [comment]
Works, and audio/video sync seems to remain OK too, thanks!

I'm beginning to understand why you asked about quality; the slowed-down sound is indeed a bit strange. But that can just as well be because we don't notice those strange things when they sound at their normal speed. Not a problem though as far as I am concerned!

**Comment by zaps166** [comment]
Slowed-down sound is usually worse, but RubberBand is doing it much better than web browser on YouTube :smile:

**Comment by RJVB** [comment]
The only things that a web browser on YT does better at this point is taking up resources and showing comments... ;)
