### ISSUE TITLE
Unstable work in OS Haiku 64 bit hrev56350 and crashes.

### ISSUE THREAD

**Issue by kim1963** [zaps166/QMPlay2#519]
Unstable work in OS Haiku 64 bit hrev56350 and crashes.
![screenshot275](https://user-images.githubusercontent.com/111342660/184827608-83804f12-eb73-4c25-8193-bb2257c21b2c.png)
![screenshot268](https://user-images.githubusercontent.com/111342660/184827774-c9a38675-2df4-499f-8749-4ba809efd600.png)

**Comment by zaps166** [comment]
Can you open debugger and send a backtrace? How did you install QMPlay2?

**Comment by kim1963** [comment]
> Can you open debugger and send a backtrace? How did you install QMPlay2?

Can you open debugger and send a backtrace? --
No. I am only user.

How did you install QMPlay2?--
https://depot.haiku-os.org/#!/?bcguid=bc1-PHBA&repos=haikuports&arch=x86_64&viewcrttyp=FEATURED&srchexpr=qmplay2

**Comment by zaps166** [comment]
I can't see anything without backtrace. Haiku is not supported by me, please ask Haiku's package maintainer. Btw I don't know why nobody made a PR here.

**Comment by zaps166** [comment]
What do you do to crash it?

**Comment by kim1963** [comment]
> I can't see anything without backtrace. Haiku is not supported by me, please ask Haiku's package maintainer. Btw I don't know why nobody made a PR here.

https://github.com/haikuports/haikuports/issues/7106

**Comment by kim1963** [comment]
> What do you do to crash it?

Use my playlist from links to Videklips from the YouTube website.

Around a couple of hours, you will get freezing with a gray window and loading 1 core of the processor by 100 %. The screenshot of this is presented above.

The second option is a fall, the program window disappears spontaneously. In the log there are records of crash.
[00001.pls.zip](https://github.com/zaps166/QMPlay2/files/9349508/00001.pls.zip)

**Comment by zaps166** [comment]
> Around a couple of hours

It's a lot.

---

Do you use Vulkan or OpenGL or legacy video outputs or custom (community developed) output designed for Haiku?

I guess, gray windows is a main (GUI) thread freeze.

Have you tried it also on Windows or Linux?  Is it possible to attach `gdb` to QMPlay2 process when it freezes? Maybe in release build it can show useful info, too.

On Linux it's just open `gdb` and inside gdb `attach PID` - PID is a process ID of QMPlay2.

**Comment by nephele-gh** [comment]
> I can't see anything without backtrace. Haiku is not supported by me, please ask Haiku's package maintainer. Btw I don't know why nobody made a PR here.

I am not sure, QMPlay2 has been available in haikuports for quite some time.
You can see the patchset here: https://github.com/haikuports/haikuports/blob/master/media-video/qmplay2/patches/qmplay2-22.06.16.patchset

**Comment by kenmays** [comment]
See: https://github.com/zaps166/QMPlay2/issues/239

Tested FFmpeg 5.0.1 and QMPlay2 22.06.16 w/ user's playlist (4-hour test)
`I tested this on my Haiku system. Found a non-consistent bug when transitioning between videos - you get a thread that hangs and disrupts QMPlay2 overall functionality. No major CPU issues or application crashes on my yest system - and nothing shown in QMPlay2 log. No display issues (i.e. the grey screen)`

Resolution: 
`Tracked down pthread issue to FFmpeg. Bumped to FFmpeg 5.1. Reran user's playlist for 12 hours. No issues.`

Note: On Haiku, I left OpenGL enabled for QMPlay2 with no display issues... yet.

**Comment by zaps166** [comment]
#239 Is different issue, but similar. Good that's working, closing!

@kenmays 

 > Note: On Haiku, I left OpenGL enabled for QMPlay2 with no display issues... yet.

Is it software OpenGL? Is it possible on Haiku to use software Vulkan, too?
QPainter has less features, but it's faster than SW OpenGL.

**Comment by nephele-gh** [comment]
zaps166: Yes, Haiku uses llvmpipe to provide OpenGL currently.
