### ISSUE TITLE
Internal Update Not working + Youtube.dll missing

### ISSUE THREAD

**Issue by Csumidex** [zaps166/QMPlay2#520]
Win 7 Ultimate 32 bit
Usually using for IPTV , Youtube and Online Radio streams listening

Internal Update Not working , ruined the Youtube playback ..... the internal update made the player stopped responding 1 year ago too , but then reistalling . Error code .... Can Not be updated the player
The internal update is somehow not well coded .... made QM 2 not working

After 1 year hapened again still the same problem .... Internal Update not working + after a short time Error code .... Can not find the youtube.dll .... so Youtube links + IPTV .m3u8 links playback equal to zero

Desinstalled ..... downloaded an .exe from Softpedia

Worked correctly with Youtube playback only 1 day
The second day the player interface goes to updatae .
After finishing the internal update ... cant play the Youtube links again

**Comment by zaps166** [comment]
Hi

It was "youtube-dl", but now it's "yt-dlp" (it's not "Youtube.dll").

Could you please describe the problem more precisely? What exactly will happen when you start playing the video?

---

Maybe you have old and bugged Intel GPU driver, so the new Vulkan API isn't working and it's freezing the player. In this case, go to the "Options->Renderer settings", change the "Renderer" to "OpenGL" and press "Apply". If it doesn't help, you can stay with Vulkan if possible.

**Comment by Csumidex** [comment]
Hello

Here is the shoot
https://prnt.sc/dpssEG5HpKL1

The driver was updated 3 month ago . Using AMD GPU but Intel processor . Have no Vulkan

I have SM Player that using mpv engine but there is working
https://prnt.sc/gkHdt54NhebB

**Comment by zaps166** [comment]
Ok, I see it's not Vulkan issue. I have to check it on Win7 32-bit maybe...

**Comment by zaps166** [comment]
I found one issue with Vulkan on my laptop with AMD Radeon on Windows, but it's different (critical) issue.

---

I've installed QMPlay2 32-bit on my 64-bit Windows 10 (few years old OS, not updated) - YouTube works properly, `yt-dlp` is downloaded without any problems...

Can you just download [yt-dlp](https://github.com/yt-dlp/yt-dlp/releases/download/2022.08.14/yt-dlp_x86.exe) manually and put it into `%AppData%\QMPlay2` and try again?

**Comment by zaps166** [comment]
Well... 22.06.16 for sure is not compatible with Windows 7 and HTTPS, I blame new OpenSSL...

**Comment by zaps166** [comment]
It'll be fixed in next release soon, thanks for the bug report!

**Comment by zaps166** [comment]
Please upgrade to 22.08.21 and try again!
