### ISSUE TITLE
fix compilation with FFmpeg 5.1

### ISSUE THREAD

**Issue by kenmays** [zaps166/QMPlay2#521]
Build issue with FFMpeg/OggHelper.cpp and FFmpeg 5.1 (AV API/ABI changed vs 5.0):
* master/src/modules/FFmpeg/OggHelper.cpp

av_malloc not declared:
```
    if (avio_open2(&io, url.toUtf8(), AVIO_FLAG_READ, &interruptCB, nullptr) >= 0)
        pb = avio_alloc_context((quint8 *)av_malloc(4096), 4096, false, this, readPacket, nullptr, seekPacket);
```

av_free not declared:
```
OggHelper::~OggHelper()
{
    if (pb)
    {
        av_free(pb->buffer);
        av_free(pb);
    }
    if (io)
        avio_close(io);
}
```

**Comment by zaps166** [comment]
Missing include?

**Comment by kenmays** [comment]
I tested with FFmpeg 5.0.1 and it built fine. For FFmpeg 5.1, the includes and functions are there.

**Comment by zaps166** [comment]
Does it work for you, because you closed?

**Comment by kenmays** [comment]
Looking into the issue.
