### ISSUE TITLE
Screen goes to sleep mode while QMPlay2 on

### ISSUE THREAD

**Issue by erdibayrak** [zaps166/QMPlay2#526]
Hey, I am having an issue as explained in the title. The screen goes to sleeping mode while QMPlay2 is playing sth. Do we have any solutions for this? I am currently using W11 and had the same issue with a different device operated with W10.
Thanks.

**Comment by zaps166** [comment]
Is it similar to #359 ?

**Comment by erdibayrak** [comment]
> 

Yes, the same issue. I am having this trouble on 2 different Windows devices.

**Comment by zaps166** [comment]
I have to check it on Windows again. Last time I tested it, it worked on my Windows...

**Comment by zaps166** [comment]
Could you provide more information? Steps to reproduce, Windows configuration?

**Comment by zaps166** [comment]
@erdibayrak Do you play video or only audio?

**Comment by adeep** [comment]
> @erdibayrak Do you play video or only audio?

I have same issue on Windows 10
But my pc not turn of display just dim it. Like just  windows do before sleep screen. If i change "turn of display" setting never in power settings. It's not dim anymore.
I checked powercfg and see Qmplay2 not create process to prevent sleep like vlc etc. do. I think that is problem causing this.
VLC
![dA7MtI5hCB](https://github.com/zaps166/QMPlay2/assets/374042/c711be7e-4efc-4705-9fe9-cb751f7c62d2)
QmPlay2
![GzT5Bx1d0X](https://github.com/zaps166/QMPlay2/assets/374042/60c9e946-6e6a-41f6-bc4d-53fa71b9279d)

**Comment by zaps166** [comment]
Is it laptop?

**Comment by adeep** [comment]
> Is it laptop?

Yes it is a laptop (HP)

**Comment by zaps166** [comment]
I'll look at this again, maybe I have to check on laptop with screen dimming :smile:

**Comment by zaps166** [comment]
It really doesn't work if lockscreen is enabled with screen saver here: ![Zrzut ekranu_20240429_100237](https://github.com/zaps166/QMPlay2/assets/6239090/55ffd49c-0399-4358-8441-793ead4bcca8)

> I checked powercfg and see Qmplay2 not create process to prevent sleep like vlc etc. do. I think that is problem causing this.

Do you know how to do it? I found workarounds like simulating F15 key press every 59 seconds which looks bad... Does `powercfg` requires admin permissions?

**Comment by adeep** [comment]
> > I checked powercfg and see Qmplay2 not create process to prevent sleep like vlc etc. do. I think that is problem causing this.
> 
> Do you know how to do it? I found workarounds like simulating F15 key press every 59 seconds which looks bad... Does `powercfg` requires admin permissions?

I tried to disable screensaver setting and it is not sleep but still dimming the screen after 1 minutes.

I am not programmer but i guess it is about "screen wake lock api" or similar thing 
I use this web site when playing something on qmplayer2 to prevent sleep
https://nosleep.page/ It is using web api

**Comment by zaps166** [comment]
Documentation: https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-powersetrequest

I guess the previous solution was good for Windows 95/98/ME (without screen dim and without screen lock).
