### ISSUE TITLE
Add System Language Auto-detection

### ISSUE THREAD

**Issue by zo-shin** [zaps166/QMPlay2#529]
When the app runs for the first time, the system language auto-detection should be introduced, so users don’t have to set that in the app manually.

**Comment by zaps166** [comment]
This feature exists in QMPlay2. It always detects Polish language correctly.

**Comment by zo-shin** [comment]
I found since **v21.12.07**, the app fails to recognize simplified Chinese as system language. Maybe that’s because I changed the language file name from **zh.ts** to **zh_CN.ts**. Do you think there can be any solution?

**Comment by zaps166** [comment]
It's possible QMPlay2 can't detect languages with suffix in name. I'll check it later.
