### ISSUE TITLE
off new youtube-dl download update

### ISSUE THREAD

**Issue by YoshiKill** [zaps166/QMPlay2#531]
Hello, thanks for your great project. 
Now the question. How i can off auto-update\download the new version of youtube-dl every time? 
just in case i need solution for fresh version 22 and for old one 20.12.16 version. There is any way to off it?

**Comment by zaps166** [comment]
Hi, there's no such option.
You can download yt-dlp sources and change code to ignore `-U` parameter or block somehow the official executable...

Why is it needed to not check for updates?

**Comment by YoshiKill** [comment]
> Why is it needed to not check for updates?
youtube-dl has problem with speed some time, yt-dlp is better solution to use, or in old version 20.12 i use it for old PC and in this case i need to use some custom youtube-dl with speed fix, i change default youtube-dl.exe downloaded by qmplay for my custom youtube-dl to work youtube full speed, but every time i start qmplay it again download default slow version of youtube dl. 
I just need off any download of youtube-dl.

**Comment by zaps166** [comment]
If you have your custom youtube-dl, can't you modify it to ignore `-U` command?

**Comment by zaps166** [comment]
There's also possible to modify QMPlay2's DLL (20.12.16) to skip youtube-dl update - I guess you have to find [this](https://github.com/zaps166/QMPlay2/blob/92e6acf198655e5323890bda7ecc083709931ec9/src/qmplay2/YouTubeDL.cpp#L358) function in DLL and put:
```assembly
mov eax, 1 # set return value to true
add esp, 4 # cleanup stack (4 bytes for C++ implicit "this" pointer argument)
ret # return from function
````
but I don't know if above code written in web browser is correct.

**Comment by YoshiKill** [comment]
> If you have your custom youtube-dl, can't you modify it to ignore `-U` command?

i just overwrite some old file, i dont know how modify it to ignore -U command, its unknown magic for me :/ 
and any way qmplay check for latest version of youtube-dl and download latest version and overwrite old one 

>I guess you have to find [this](https://github.com/zaps166/QMPlay2/blob/92e6acf198655e5323890bda7ecc083709931ec9/src/qmplay2/YouTubeDL.cpp#L358) function in DLL and put:

thanks, i try it, its sounds like good solution. What software you recommend to use for edit dll?

**Comment by zaps166** [comment]
The code above is wrong, because it's Microsoft's fastcall, so:
```asm
mov eax, 1
ret
```

---

It's only for [this](https://github.com/zaps166/QMPlay2/releases/download/20.12.16/QMPlay2-Win32-20.12.16-nojs.exe) version!

Put `B8 01 00 00 00 C3` into `libqmplay2.dll` at offset `0x344A0` (replace old values, don't change file size).

---

I've prepared a file, you can download, unpack and replace it: [libqmplay2.dll-no-ytdlp-update.zip](https://github.com/zaps166/QMPlay2/files/9727582/libqmplay2.dll-no-ytdlp-update.zip), SHA-1 of DLL file is `1848cb69c408c444143958a4bcd4bca14e84dfb3`.

**Comment by zaps166** [comment]
@YoshiKill Does it work for you?

**Comment by YoshiKill** [comment]
> @YoshiKill Does it work for you?

Yes, this fix is work fine. Thanks a lot! Maybe in future version it be good to add some option to turn off auto download. And don't have sort of this problem.

**Comment by zaps166** [comment]
> Yes, this fix is work fine.

:+1:

> Maybe in future version it be good to add some option to turn off auto download.

Is configuration file only a good option?
