### ISSUE TITLE
Android yt-dlp

### ISSUE THREAD

**Issue by trimechee** [zaps166/QMPlay2#533]
Hello, in releases page : "yt-dlpl is not supported, so YouTube is disabled,.", it will be great , in order to make possible the support of yt-dlp in android, to add apk version outside the play store  or add QMPLAY2 to f-droid store where there is no censorship, thank you !

https://f-droid.org/en/

**Comment by zaps166** [comment]
`yt-dlp` can be installed in Termux, so QMPlay2 will have to launch it through Termux somehow and get the result.

I don't want to bother with this, too much work and I don't know if it'll finally work correctly.

It's more like Termux integration (https://github.com/termux/termux-app/wiki/Termux-Libraries).

Also QMPlay2 for Android doesn't support HW acceleration, so CPU decoding is the only option.

**Comment by zaps166** [comment]
> it seems seal has suceeed to integrate yt-dlp in android os :

I didn't say it's impossible. I'm not interested to do this here.

---

Maybe consider NewPipe application.
