### ISSUE TITLE
Deinterlacing and audio only youtube 

### ISSUE THREAD

**Issue by trimechee** [zaps166/QMPlay2#536]
Hello, I'm exploring the QMPlay2 settings and it's amazing, there are so many amazing options!

I see in the "renderer settings" section this option "use GPU deinterlacing for cpu decoded video", so if we uncheck this box, we can disable deinterlacing? and how can we completely deactivate the deinterlacing to save resources and preserve the battery please?

and I also see in the "modules/extension/youtube" section, that there is not in the "preferred quality" video resolutions lower than 480p, for example there is no resolution 360p, 240p , 144p, because it's useful when our internet connection is getting weak, so it will be great to add those resolutions below 480p please, also sometimes we just want to listen to the audio of the youtube video without watching the video, for example a podcast on youtube, so it will be great in order to save data and energy to add an "audio only" option and thus only download and use the audio stream m4a or opus or webm or ogg thus the screen of the computer will be off and we save data , thank you so much!

Some old videos in streaming sitse are in aspect ration 4/3, and i would to watch video in 16/9 aspect ratio to avoid black bands, how can we change the aspect ratio manually please?

and another million thanks for this amazing media player :) 🥇 💯

**Comment by arthurzam** [comment]
For the audio only part, you can use `audio` value for the additional value for Youtube entry.

**Comment by arthurzam** [comment]
> @trimechee 
> @arthurzam Thank you for your help :) please where exactly we can add value for youtube ? for exemple i copy and paste url adress of youtube video, how can we add or use audio only streams ?

So my flow is such: left click on the playlist, `Add` --> `Address` - a new dialog opens. In drop down list select `YouTube` and under it in left text box put the regular youtube URL, and in the right one put `audio`, and then click `OK`.
You can also edit properties of existing entry, and add in the righter text box `audio`.

**Comment by zaps166** [comment]
> I see in the "renderer settings" section this option "use GPU deinterlacing for cpu decoded video", so if we uncheck this box, we can disable deinterlacing? and how can we completely deactivate the deinterlacing to save resources and preserve the battery please?

Deinterlacing is enabled automatically only on interlaced videos, it's not used otherwise. To disable or configure it, go to "Video filters" tab and uncheck "Remove interlacing" and apply (not recommended). Additionally you can enforce it for all videos (not recommended, only for testing purpose) - "Automatically detect interlaced frames" checkbox. Best idea is to keep default settings :)
