### ISSUE TITLE
Disable video in audio mode 

### ISSUE THREAD

**Issue by trimechee** [zaps166/QMPlay2#542]
Hello, yesterday I downloaded a tv show via software and the video file obtained is in ".ts" format, I went to sleep and therefore I opened the file with foobar2000 audio player so that the screen of the computer is off but I can't move around in the video, so I tried to open the file with QMPlayer2 and managed to move around in the video, but I just prefer to listen to the audio because I was going sleep, so it will be great if QMPlayer2 adds a button or option to the main interface "disable video" so you can listen to the audio of the video with the screen off and it saves resources and battery .....vlc player has this option to turn off video but you have to click many times and hopefully QMPlayer2 will give us a quick simple option to turn off video and only decode audio , and maybe add option to QMPlayer2 in audio player mode to only decode youtube audio dash streams like m4a, opus, o gg.....so the audio player will only use audio streams from youtube videos and ignore video streams in order to save resources for example when listening to a radio or poscast on youtube, thank you very much!

**Comment by zaps166** [comment]
Hi, press `O` key to disable video (`Playback->Enable video`).
