### ISSUE TITLE
Wayland artifacts on both Gnome and KDE on playback bar

### ISSUE THREAD

**Issue by formlessdao** [zaps166/QMPlay2#545]
On Fedora 36 on both KDE and Gnome using Wayland, Qmplay has glitchy behavior and displays all kind of visual artifacts in the playback bar when moving the mouse on the playback bar while playing a video in Full Screen .

PS:Where are all the settings of the appimage stored? Although I installed a new version my playlist contains the old files I played.
How can I delete all traces of Qmplay so when I install it, it is truly a clean install?

**Comment by zaps166** [comment]
Hi, settings are stored in `$HOME/.config/QMPlay2` or `$HOME/.qmplay2` (old path).

Can you give screenshot? Do you use appimage on Wayland? Is it Vulkan or OpenGL?
