### ISSUE TITLE
Cuvid not loading after resume from suspend on Ubuntu

### ISSUE THREAD

**Issue by taktiker12** [zaps166/QMPlay2#548]
Hey Zaps166

when playing Qmplay2 after resuming computer from suspend i get this error :

08 nov. 2022 16:06:20.846] CUVID :: Unable to get function pointers
Set VDPAU_DRIVER_PATH to /usr/lib/x86_64-linux-gnu/vdpau

qmplay2 cannot find cuvid , but when restarting the computer it works .
 regards
Mounir

**Comment by zaps166** [comment]
Hi!

NVDEC/CUVID/CUDA and OpenCL - all these APIs have this issue on NVIDIA GPUs on Linux. You have to reboot the computer or reload the NVIDIA driver (reboot is faster and simpler). It's very old and annoying NVIDIA driver BUG, I can't do anything. I've already reported this bug to NVIDIA, but they probably never fix it :rofl: 

Example: Run Geekbench with CUDA, sleep, wakeup - the same issue:
```
$ ./geekbench5 --compute cuda
[1108/184942:WARNING:src/halogen/cuda/cuda_common.h(30)] CUDAError: cuInit(0) returned 999
Error: Compute API 'CUDA' is not available.
```
