### ISSUE TITLE
HDR→SDR

### ISSUE THREAD

**Issue by gergrege** [zaps166/QMPlay2#549]
Can you add a button？HDR to hdr！like potplayer！
Or automatically recognize HDR and convert to SDR! like VLC!!!!
on windows platform！！！
Thank you!!!

**Comment by zaps166** [comment]
Hi!

> Can you add a button？HDR to hdr！like potplayer！

No, adding just a button doesn't do anything :rofl: QMPlay2 needs to have the image conversion algorithm.

Currently HDR videos are not supported and will be displayed incorrectly. I'll change it in the future maybe.

**Comment by zaps166** [comment]
Currently I don't have knowledge about HDR videos.

**Comment by gergrege** [comment]
> 

Thank you so much, looking forward to that moment

**Comment by gergrege** [comment]
The World Cup is about to start，4k signals are mostly transmitted in HDR mode，So I can only use potplayer first.....

**Comment by gergrege** [comment]
> Do you know the theory how to convert it to SDR?
Sorry, I don't know the theory
The so-called HDR to SDR is realized by a renderer, such as madvr, mpcvr
Another ispotplayer：SMPTE2084/2086

**Comment by zaps166** [comment]
Thanks, I forgot about it :sweat_smile: It's working, especially with bt709 color primaries on QMPlay2.

**Comment by zaps166** [comment]
@Realex-fire Do you want to test if I some work to master?

**Comment by zaps166** [comment]
Done, please test :slightly_smiling_face: 

Only Vulkan is supported, shaders binaries are not yet updated, so please use GLSLC to compile them (`-DUSE_GLSLC=ON`) or just `qmplay2-git` from AUR!

**Comment by zaps166** [comment]
> do you plan to extend support for this feature to the OpenGL renderer

Currently not planning. Anyway OpenGL is poorly implemented in QMPlay2 for modern videos (no 10-bit support on CPU decoding - it's converted on CPU to 8-bit, unoptimized subtitles/OSD, no zero-copy decoding, etc...).

I'll try to add real HDR support on Vulkan, too.

> QMPLAY2_ALLOW_VULKAN_CPU

It can be added settings, but the performance of this is horrible :sweat_smile: 

---

Do you have PC w/o Vulkan?

**Comment by zaps166** [comment]
Software decoding is not the same as software YUV->RGB conversion with chroma planes interpolation and up/down scaling. This should done only on GPU.

CPUs can decode video pretty well, sometimes better than video decoders in GPUs (e.g. AMD Radeon 6900XT can consume more power when decoding on VA-API than decoding on Ryzen 7950X - both in power saving mode).

> At the moment (by default without QMPLAY2_ALLOW_VULKAN_CPU) QMPlay2 uses software (without hardware acceleration) OpenGL

llvmpipe OpenGL?

**Comment by zaps166** [comment]
`QMPLAY2_ALLOW_VULKAN_CPU` is to prevent running software by default Vulkan where hardware OpenGL might be available :smile:

**Comment by zaps166** [comment]
> OK, thanks. I just want "full" llvmpipe users and users without Vulkan hardware support to also be able to see the HDR improvements without setting an environment variable slightly_smiling_face

Done!

Btw. For me software Vulkan is much faster than software OpenGL + now you can optionally disable texture filtering for Vulkan.

**Comment by zaps166** [comment]
I'm aware of this issue. Doesn't play on Windows either. `ffplay` also can't handle the audio there, too. Looks like it works only on PipeWire (where I'm testing :sweat_smile:). Maybe there's a bug in FFmpeg, because it can't analyze audio and it reports 0 channels and 0 Hz samplerate at beginning.

**Comment by zaps166** [comment]
[Done](8288a79cf734b0ac540c055fe45375f35e314aac)

**Comment by zaps166** [comment]
> Maybe QMPlay2 needs some sort of smarter algorithm to increase the "probesize" and maybe "analyzeduration" for all containers if necessary

I think FFmpeg should handle it :smile: Maybe report it to FFmpeg with sample video?

---

Btw. Maybe I'll push HDR->SDR for OpenGL, too...

**Comment by zaps166** [comment]
Hi, zero-copy is experimental, not synchronized and probably doesn't work on newer hardware.

Do you know which function throws the exception?

**Comment by zaps166** [comment]
On my Intel zero-copy works fine on 3840x2160 HDR video.

**Comment by zaps166** [comment]
I'll check it soon, could you report as separate issues?

**Comment by zaps166** [comment]
- I have to check it, but zero-copy means it maps existing memory.
- Could you upload your video, I've got 10th gen laptop i7 to test?

**Comment by zaps166** [comment]
Usually 10-bit H.264 is non-standard and it's not supported by hardware decoders. I'll check the Windows code.

**Comment by zaps166** [comment]
> but start playing on Windows (D3D11VA, DXVA2) only if I revert the commits (https://github.com/zaps166/QMPlay2/commit/47cde5726e697c6b1dcaa84a04d3dc48c1c54b64, https://github.com/zaps166/QMPlay2/commit/6f2067d611d0aaf9b908b2055f0249b711741dca, https://github.com/zaps166/QMPlay2/commit/8056924aed0943973cdc4dc8c3af68eb71a569f4, https://github.com/zaps166/QMPlay2/commit/255789b2c9d4e321e2e3589c0fb74572ab8a27b9).

Both D3D11VA and DXVA2 or just DXVA2?

**Comment by zaps166** [comment]
Please check again with 6de222b7.

**Comment by zaps166** [comment]
> This works now, but the colors for HDR videos on SDR display with OpenGL and DXVA2 are the same as on legacy renderers, not "improved". 

Fixed.

**Comment by zaps166** [comment]
Please check zero-copy with 609d20f2a10e5050a1b2dfd3b22115a43e69aa27.

**Comment by zaps166** [comment]
zero copy requires less memory, because additional buffer is not needed.

**Comment by zaps166** [comment]
> Please also check the black screen on FFmpeg/DXVA2, DirectDraw

I know it's not working, I'll remove this possibility to play DXVA2 without OpenGL. Just waste of time for this 😅

**Comment by zaps166** [comment]
I don't have idea why zero-copy isn't working. Could you tell exactly which function throws exception? (add maybe some `qDebug()`)?

**Comment by zaps166** [comment]
Maybe I have to use `VK_KHR_dedicated_allocation`...? 🤔

**Comment by zaps166** [comment]
With zero-copy I've got 1 GiB GPU memory usage, without it's 1.4 GiB on 8k video, so it's a problem that it can't import DX11 texture to Vulkan (it's incompatible anyway, so it might work or might not like on AMD, Nvidia, newer Intel like 12gen).

To properly import it (if even possible) I have to create 2-plane image array on Vulkan side and import DX11 memory (including dedicated memory if required), but I don't want to do it right now...

Currently I'm calculating offset for decoded image in DX11 texture array and I'm trying to map it into two Vulkan images (one per plane - luminance plane and chrominance plane - NV12 format and similar for 10-bit).

**Comment by zaps166** [comment]
> Okay, but doesn't that work with`QPainter`?

Yes, it's pointless. Behavior is now the same as D3D11VA (but here is OpenGL-only). With DirectDraw there's more work to make it working, but also pointless, so removed (for both for easiness and consistency).

---

> Maybe also hide VDPAU

If it doesn't work with XVideo or causes other issues. VDPAU is first thing I want to remove, it's implementation is ugly in QMPlay2. I don't know if it's possible to interoperate with Vulkan (maybe not?).

---

609d20f2a10e5050a1b2dfd3b22115a43e69aa27 was wrong and didn't fix anything (already reverted) :sweat_smile: 

---

Thanks for the exception trace, I've looked at the code and I don't have knowledge how to properly do it. DirectX is hard to interoperate with other APIs and Vulkan is a bit bugged on Intel GPUs :sweat_smile: Maybe try to upgrade [GPU drivers](https://www.intel.com/content/www/us/en/download-center/home.html) as first? It's working on laptop with 10th gen Core i7 and Windows 10...

Btw. On Intel I'm not able to play real HDR (option in renderer settings), but it's working on Nvidia and AMD...

**Comment by zaps166** [comment]
Thanks fort testing :smile: 

---

Xorg/Xwayland crash - I can see `nouveau` - it's experimental driver, it can crash or fail everywhere. For me it looks like 99.9% driver bug.

---

> black background is not shown under visualization widgets

Fixed by painting black background on OpenGL + Wayland.

Wayland is a protocol without any fully working implementation. Currently Wayland compositors sucks, are incompatible and they can't properly handle mouse cursor without input lag (like Windows or X11 is doing). Every Wayland compositor is written differently and they have different bugs. Moreover Qt also have bugs (I had to workaround Qt crashes on Wayland already).

AMD Radeon here. I don't have any glitches with QMPlay2 on Sway, but `QOpenGLWidget` shows white screen on full screen on Weston. I remember on KDE there was one different problem, too. :rofl: 

Could you upload a screenshot with glitches?

> integrated GPU

Intel or AMD?

Again, cursor input lag is horrible there :angry: 

---

> On the latest versions of Fedora

I've never tested Fedora. Why they are doing it differently then all other OS?

**Comment by zaps166** [comment]
> The VDPAU is hidden in the list of decoders on Vulkan while it is still available in the FFmpeg module settings. I mean this inconsistency.

Fixed.

---

Also DXVA2 now works with DirectDraw 😅

**Comment by zaps166** [comment]
Did you try Qt 6.4 or Qt 5.15?

**Comment by zaps166** [comment]
> Vulkan validation layer not found

Maybe you're compiling QMPlay2 in Debug mode - in this case I use validation layers. Install `vulkan-validation-layers` (name on Arch Linux).

---

I've pushed one fix which fixes one  XWayland + Intel glitch.

---

Could you check if removing [this line](https://github.com/zaps166/QMPlay2/blob/0305fd7a6b48876c3ce194120ad002de96649d7b/src/gui/Main.cpp#L771) fixes some issues on Wayland or XWayland?

**Comment by zaps166** [comment]
> On XWayland with `OpenGL` in full screen mode I got [this](https://ibb.co/6XkJpQp) glitch with control buttons.

Yes, I can see this sometimes on Vulkan, too (with XWayland).

---

Let's keep Wayland "as is" :sweat_smile: Wayland + Qt works bad. Exotic platform like macOS doesn't have much problems, but Wayland is a disaster. Don't forget about cursor input lag on many (all?) Wayland compositors (maybe it also depends on settings and scaling) + Wayland implementation fragmentation.

XWayland allows to run X11 app under Wayland, so if an X11 app run correctly under X11, so it's XWayland or just Wayland compositor problem, not QMPlay2 problem.

Running QMPlay2 natively on Wayland is mostly Qt problem to me, but every Wayland compositor has different issues, so idk... I think Sway works best (after recent QMPlay2 fixes - no issues on my machines with native Wayland).

**Comment by zaps166** [comment]
Anyway is DXVA2 working good with DirectDraw now?

**Comment by zaps166** [comment]
> Maybe it's also worth adding export QT_QPA_PLATFORM=xcb to the AppImage

AppImage doesn't have Wayland support. Also PipeWire is not supported - I have to upgrade my build environment some day :sweat_smile: 

---

Maybe I don't have as many Wayland problems with QMPlay2 because I have 5.15.10+kde+r52-1 on Manjaro Linux :smile:

**Comment by zaps166** [comment]
> problem with QT 6.4 when trying to play any videos.

Fixed, strange issue, Qt 6.4 bug?

**Comment by zaps166** [comment]
> If you want, try the GitHub Actions with Docker to work with older LTS versions of Ubuntu. Maybe it will be more comfortable, but scripts are needed 😅

I've got local docker :smile:

> I have one question, is it okay that hardware acceleration for FFmpeg does not work for me on OpenGL and legacy renderers if DRI_PRIME and LIBVA_DRIVER_NAME point to different GPUs or is it a bug? This works on Vulkan. For example, if LIBVA_DRIVER_NAME points to Intel and NVIDIA is selected in the renderer device list, then VA-API (on Intel) applies only to FFmpeg.

Vulkan + VA-API should choose correct device. On OpenGL + X11 the device should also be correct, on OpenGL + Wayland idk (`FIXME` in code :sweat_smile:). Legacy should choose same as OpenGL (I don't care, it's rare use case anyway, but here any device can be used because there's no interoperation).

**Comment by zaps166** [comment]
> On OpenGL and Legacy I can get FFmpeg/VA-API, OpenGL 4.6 VA-API if Intel is chosen, and FFmpeg, OpenGL 4.6 if NVIDIA is chosen.

How do you choose Nvidia? I usually swap Xorg config files and restart `lightdm`, so now Nvidia is my primary GPU (even if boot GPU is Intel). I can turn off build-in display and use NVIDIA's HDMI/USB-C directly. In this case OpenGL + VA-API runs fully on Nvidia (https://github.com/elFarto/nvidia-vaapi-driver).

> if LIBVA_DRIVER_NAME points to Intel and NVIDIA is chosen, and FFmpeg, Vulkan if NVIDIA is chosen and LIBVA_DRIVER_NAME points to NVIDIA or not set.

Don't fully understand, but if you enforce by envvars, something might not work maybe. The most important is if it crashes due to QMPlay2 bug - if no crash and it fallbacks to CPU decoder, it's ok to me.

> Is that how it should be? OpenGL and Legacy don't support "cross combination", when VA-API is running on another device for FFmpeg only?

With Legacy, "cross combination" might work, image is downloaded from device memory to CPU memory (e.g. through PCI-Express). But I don't want to add device selector for this use-case :sweat_smile: Maybe using envvars can help in this case.

For Vulkan and OpenGL "cross combination" might work the same way as on Legacy, but it makes no sense (poor performance), so it's blocked.

**Comment by zaps166** [comment]
I don't use `DRI_PRIME`, so idk. I don't think it changes the default display device anyway on Xorg, it'll copy from one GPU to another to display the image even if window is on another monitor.

> It doesn't seem to block, but it doesn't work.

Not possible to map memory from one GPU in another GPU (not in methods I use). Does it switch to next decoder?

> I understand, then it's strange that for some reason it doesn't block for me on Vulkan and shows FFmpeg/VA-API, Vulkan

llvmpipe?

**Comment by zaps166** [comment]
> In this case, yes. It looks like such a trick possible only with this?

Yes, it's intentional: https://github.com/zaps166/QMPlay2/blob/ad6ad841f91384922b1855bfa90ec96f57048a55/src/modules/FFmpeg/FFDecVAAPI.cpp#L222

**Comment by zaps166** [comment]
>  I also get QMPlay2 crashes with QT 6.4 on GNOME and Weston

I thought I've workarounded it, it works to me now. It's Qt bug.

> Software Vulkan on my Intel is very slow

llvmpipe is very slow. It does much more things than CPU outputs like QPainter (it's also not fully optimized, but much faster). Especially when scaling to 4k full screen. It's good to enable "Low quality image scaling" for llvmpipe.

> "Video to audio sync"

Without this option video can desync even on fast machine.

> llvmpipe is faster than GPU

GPU can't be slower then CPU via llvpipe in case of image up/down scaling :sweat_smile: Intel (U)HD Graphics can be slower in compute workloads then CPU, but not in image scaling/interpolation/texturing :astonished: What GPU do you have and which drivers?

> Thank you very much for the new release and good luck with further QMPlay2 improvements 

Thanks!

**Comment by zaps166** [comment]
> I compiled QMPlay2 for QT 6.4.3. Maybe your workaround doesn't work for that old version?

"Fixed": 2847d4687880c7cc9f2653386a3c0e8ab6392926. Qt + Wayland = disaster :rofl: 

> has only one Intel i3 (7th Gen)

If llvmpipe is faster than GPU it sounds like opensource Nvidia NVK driver :sweat_smile: GPU can't be slower in image interpolation. You have corrupted drivers. Btw. how do you measure the speed?

```diff
diff --git a/src/qmplay2/vulkan/VulkanWindow.cpp b/src/qmplay2/vulkan/VulkanWindow.cpp
index 0521edd8..5739b965 100644
--- a/src/qmplay2/vulkan/VulkanWindow.cpp
+++ b/src/qmplay2/vulkan/VulkanWindow.cpp
@@ -589,10 +589,16 @@ void Window::render()
             m.commandBuffer->endRenderPass();
 
             m.queueLocker = m.queue->lock();
+
+            QElapsedTimer et;
+            et.start();
             m.commandBuffer->endSubmitAndWait(false, [&] {
                 m.swapChain->present(imageIdx, &suboptimal);
                 vulkanInstance()->presentQueued(this);
             }, move(submitInfo));
+            auto t = et.nsecsElapsed();
+            qDebug() << t / 1e6 << "ms";
+
             m.queueLocker.unlock(); // It is not unlocked in case of exception
         }
     }
```

Try this, but put your PC to performance mode (CPU governor, similar for GPU).

**Comment by zaps166** [comment]
> slows down considerably when the GPU is chosen in the Vulkan renderer settings and causes this problem... 

How CPU decoder can slow down the GPU on Vulkan only?? Could you check `vk-async` branch with and without the `WIP` commit (it's async, so not easy to measure time the way I gave you)?

**Comment by zaps166** [comment]
> The GPU doesn't slow down, it's just that `FFDec::decodeStep` is very slow for some very strange reasons if `Vulkan` on Intel GPU is chosen... The `vk-async` branch has no effect on this.

Aaah, memory cache. Could you remove entire `try`/`catch` (with code) from `FFDecSW::open`?

**Comment by zaps166** [comment]
> Can this somehow be related to the D3D11VA :: vk::Device::allocateMemory: ErrorOutOfDeviceMemory exception on Windows when using D3D11VA with zero-copy on Intel?

No, it's different code. This is about CPU decoder, D3D11VA is HW decoder.

> In both cases, the problem arises in the videos requiring a large memory for decoding.

No, zero-copy requires less memory.

> Maybe you need some way to check the correct support for zero-copy and make it possible to disable zero-copy in the settings?

Zero-copy in CPU decoder is used only when it can be used.
```c++
static_pointer_cast<QmVk::Instance>(QMPlay2Core.gpuInstance())->physicalDevice()->findMemoryType(
    vk::MemoryPropertyFlagBits::eHostVisible | vk::MemoryPropertyFlagBits::eHostCoherent | vk::MemoryPropertyFlagBits::eHostCached
);
```
this throws exception if host visible cached memory doesn't exits (if there's no cached memory, zero-copy will be many times slower). If driver reports host cached where it's not cached, it's a driver bug.

> In full screen on Intel, the exception Vulkan :: vkAcquireNextImageKHR: Timeout is now sometimes thrown and video playback stops.

It can't timeout, it's 2.5 sec. It indicates you have horrible drivers.

---

Could you upload `vulkaninfo` results as txt file?

**Comment by zaps166** [comment]
> Mesa 22.3.0

It's old, anyway, `.0` at end means first release = usually more bugs. 23.1.6 is the new stable release now.

> Yes, I know, but it doesn't affect OpenGL, where there is no zero-copy. Maybe make it user-managed for Vulkan?

Better to fix bug in driver instead of exposing weird options (maybe envvar for testing/debugging purposes). I never had issues with this, it was working also on Raspberry-Pi correctly (detected that zero-copy is not supported). I used it many times on Intels w/o issues.

Your driver reports: 
```
			MEMORY_PROPERTY_DEVICE_LOCAL_BIT
			MEMORY_PROPERTY_HOST_VISIBLE_BIT
			MEMORY_PROPERTY_HOST_COHERENT_BIT
			MEMORY_PROPERTY_HOST_CACHED_BIT
```
Just regular cached system memory visible by GPU. Idk why it doesn't work.

---

Are you sure compositor is bypassed on full screen? If you use KDE, you have to allow this in Kwin settings, or just disable it on hotkey. Otherwise testing doesn't make any sense. Best to test is to run `openbox --replace` and don't start any custom X11 compositors. Later you can try [my compositor](https://aur.archlinux.org/packages/qdre-compositor-git) + [it's autostart](https://aur.archlinux.org/packages/qdre-compositor-autostart) with openbox or xfwm4 or marco (xfwm4 and marco own compositor must be disabled manually!).

> Edit: After a reboot, I can't reproduce the full screen issue. It looks like it resolved itself...

As you see, your driver is bugged or compositor is doing weird things.

**Comment by zaps166** [comment]
> Maybe it is possible to detect this somehow and disable zero-copy? Additional options will not be needed 🙂

I'm doing it, detection is correct according to `vulkaninfo` output, zero-copy should be fast.

---

```diff
diff --git a/src/modules/FFmpeg/FFDecSW.cpp b/src/modules/FFmpeg/FFDecSW.cpp
index 1eba0bea..974263a1 100644
--- a/src/modules/FFmpeg/FFDecSW.cpp
+++ b/src/modules/FFmpeg/FFDecSW.cpp
@@ -770,6 +770,36 @@ int FFDecSW::vulkanGetVideoBuffer(AVCodecContext *codecCtx, AVFrame *frame, int
 {
     if (m_dontConvert)
     {
+        {
+            constexpr vk::DeviceSize dataSize = 4096;
+
+            QElapsedTimer et;
+
+            uint8_t cppData[dataSize] = {}; // Create initialized data on stack
+
+            const auto buffer = QmVk::Buffer::create(
+                m_vkImagePool->instance()->device(),
+                dataSize,
+                vk::BufferUsageFlagBits::eStorageBuffer,
+                vk::MemoryPropertyFlagBits::eHostVisible | vk::MemoryPropertyFlagBits::eHostCoherent | vk::MemoryPropertyFlagBits::eHostCached
+            );
+            const auto bufferData = buffer->map<uint8_t>();
+
+            for (int i = 0; i < 2; ++i) // First loop = warmup
+            {
+                et.start();
+                memcpy(bufferData, cppData, dataSize); // Upload data
+                auto t1 = et.nsecsElapsed();
+
+                et.start();
+                memcpy(cppData, bufferData, dataSize); // Download data
+                auto t2 = et.nsecsElapsed();
+
+                if (i > 0)
+                    qDebug() << t2 / t1;
+            }
+        }
+
         int w = frame->width;
         int h = frame->height;
         int linesizeAligns[AV_NUM_DATA_POINTERS] = {};
```

Show me results of this.

**Comment by zaps166** [comment]
> It's just horrible, I'm getting values ​​over 80... Do you need a full log?

It means it's not cached :sweat_smile: So the driver tricks you. This benchmark can detect and fallback to normal decoding, however driver must not report wrong values...

**Comment by zaps166** [comment]
> However, he does it... Even with llvmpipe I get values around 1 or less.

If CPU can use cache for memory, the value will be between 0 and 1 (same performance for C++ stack and Vulkan alocated CPU memory). If CPU can't use cache, the value will be high. Your driver reports it's cached, but looks like it's not cached - driver bug. If hardware is not able to use CPU cache with GPU access, driver must not report DEVICE_LOCAL together with HOST_CACHED.

**Comment by zaps166** [comment]
Intentional bug? Do you use any custom envvars or configs?

**Comment by zaps166** [comment]
> Are you sure you need to bypass the compositor in QMPlay2 on Vulkan by default?

Yes, compositors are bad - it's additional copy which increases power consumption and includes possible stuttering (also due to desync, sometimes due to very slow GPU) and disables FreeSync which is needed e.g. for smooth 50 FPS display on e.g. 60 FPS monitor.

Without compositor you're in MAILBOX mode when supported (MESA supports it, it's low latency, non-blocking tear-free mode) or you can fully check to enable FIFO mode (just V-Sync). It works correctly only if you have single monitor connected to X11's primary GPU. Linux drivers on X11 redirects fast, so no visible flickering like on Windows.
It temporarily replaces the compositor in page-flipping. It's highly recommended for games also.

> also on Openbox

Openbox doesn't have compositor, so this option doesn't have any effect there.

> I get a loop of multiple frames.

Driver bug. Probably three buffers in a loop. You really have weird GPU, IIRC even RaspberryPi is working correctly which has awfully slow GPU...

How about fullscreen game e.g. from Steam? How about compositor bypass in OpenGL?

**Comment by zaps166** [comment]
Just checked Intel HD 4000 (i7-3770k) + Nvidia as primary GPU, Intel is running Vulkan, Nvidia is displaying:

Nouveau:
- Xorg crash on Vulkan resize (driver bug)
- full screen looped buffers (driver bug, also on `vkcube`)
- Intel Vulkan host cached memory is working correctly,

Nvidia proprietary:
- no image on windowed and full screen mode (drivers bug)
- X11 and later PC freeze when switched from Intel to Nvidia Vulkan in QMPlay2 (drivers bug)

When I choose Nvidia Vulkan on Nvidia proprietary drivers when Nvidia is primary GPU with monitor connected, it's working good.

---

Tomorrow I'll check Intel-only (it requires default GPU in UEFI change + different monitor cable).

**Comment by zaps166** [comment]
Tested Intel HD 4000 without Nvidia, X11 modesetting driver, Vulkan:
- host cached memory is working correctly and fast,
- no issues on full screen without compositor or bypassed compositor,
- no X11 crash on resizing,
- VA-API is working with H.264 videos,

Just runs flawless on this old Intel GPU.

CPU is i7-3770k with Intel HD 4000 graphics, Mesa 23.1.6, kernel 6.4.12 (Manjaro), Pipewire.

---

Full screen with compositor increased GPU usage by 2-2.5x and I've got visible stuttering in some parts of video when decoding 4k VP9 HDR video from youtube. (Almost) no stuttering without compositor on full screen and much less GPU overhad.

---

Other thing I noticed (as always) is limited range (16-235) output which causes weathered colors, dark gray black and light gray white. I had to run `xrandr --output HDMI-2 --set "Broadcast RGB" "Full"` to get normal image. It's unfortunately normal with Intels also on Windows and needs to change manually on both OSes :disappointed: 

---

Some hints for Linux:
- avoid Nvidia if you don't need fast ray tracing or CUDA
- never use nouveau driver, proprietary is much better, use with `nvidia-drm.modeset=1`
- don't event try experimental Vulkan NVK driver for nouveau
- avoid connecting screen to non-primary GPU (configure Xorg properly to get primary GPU you have monitor connected)
- avoid using different GPUs - primary for display, secondary for rendering (the exception is laptop with 2 GPUs or pure compute workload, but for laptop I still suggest to swap primary GPU in Xorg config files).

---

I guess you have Nvidia nouveau as primary GPU, Intel as secondary GPU and Intel is rendering image in QMPlay2 and sends to Nvidia to display. Your Nvidia doesn't support Vulkan on nouveau. This is a disaster causing non-working full screen, lower performance and Xorg crash. You can't blame QMPlay2 for your setup, any/most other Vulkan apps will not work correctly there I guess. Your solution is to switch to OpenGL. You should avoid Vulkan on your setup.

---

Another thing is host cached memory on Intel - this is weird and I don't understand, mapped memory with flags host cached + host visible + host coherent should behave to the CPU as `malloc()` IMHO. Maybe try to report it on Mesa and they will tell you what's going on? Also check your UEFI settings, try to physically unplug or disable Nvidia if possible (or just blacklist it's all kernel drivers).

**Comment by zaps166** [comment]
> Thanks for the thorough investigation. I have expanded my understanding, but I already realized that Nouveau is bad for me and the best solution is not to use it or use it only with OpenGL on Nvidia 🙂

Nouveau doesn't support Vulkan yet (NVK is in early development), so Vulkan is rendered on Intel which is another GPU. This scenario is bad. OpenGL is probably rendered on Nvidia. In this config (Nvidia with nouveau first, Intel second), you should avoid Vulkan. Why not use proprietary driver?

---

> As I already wrote, this problem occurs on completely different PCs (including the physical absence of Nvidia), Intel generations and OSes (Linux). I understand correctly that you think that, in this case, the best solution is to also use OpenGL in QMPlay2 until the drivers are fixed? And no need to add workarounds to "fix" this and additional options in QMPlay2 Vulkan settings?

This benchmark will fix it for you, but I don't want this. Also option is a bad idea. I can add env var or hidden INI settings for this. I remember last year I was using it with 7th and 8th gen Intel and it was running correctly... 3rd 10th and 12th gen also running correctly now.

This behavior is abnormal, maybe you should open issue on Mesa GitLab?

What kernel do you use?

**Comment by zaps166** [comment]
Done: 5f3f50fb55d3a2b4d7880631639f4d8fe59357aa (`General` section of `FFmpeg.ini` file).

Please note it will increase CPU overhead on normally working PC.

**Comment by zaps166** [comment]
Redundant so far.

**Comment by zaps166** [comment]
I enabled Discussion, please now use it to talk :grimacing:

**Comment by zaps166** [comment]
> I hope my tests were useful 🙂

Yes, thanks! :slightly_smiling_face: 

---

Do you have Windows on these machines? Could you run QMPlay2 ant try there? And run `vulkaninfo` or [this](https://vulkan.gpuinfo.org/download.php) and show me memory info.

**Comment by zaps166** [comment]
Can't reproduce, I'll keep it as is. I know windows remote desktop can duplicate it.
