### ISSUE TITLE
Could you provide Flatpak package 

### ISSUE THREAD

**Issue by libreajans** [zaps166/QMPlay2#551]
Hi, Linux have very versatile and colourful community. We may have hundred different package format. Also there are some universal packages. AppImage, Flatpak and Snap.

I'm not a Qt developer. I use OBS Studio, Kate and Shotcut as a flatpak package from different sources (mostly from Flathub)

Could you consider providing a Flatpak package at least for development?

**Comment by zaps166** [comment]
Hi, currently I'm not planning to support another distribution however it can be done by other people!
