### ISSUE TITLE
[feature request] YouTube playlist support

### ISSUE THREAD

**Issue by RJVB** [zaps166/QMPlay2#553]
QMPlay2 has partial support for YT playlists in that it will create a playlist folder when you double click on a playlist hit in the YT search result list.

However, I see no way to do the same thing with a playlist URL (e.g. https://www.youtube.com/playlist?list=PLsgNPd9KTY_wCNDxthSW66zAzp5qy6imA), nor of a sure way to search for playlists via the YT search feature.

Those would be useful features to improve QMPlay2's status as a more efficient YT browser.

**Comment by zaps166** [comment]
It's working since [24.05.23](https://github.com/zaps166/QMPlay2/releases/tag/24.05.23).

**Comment by RJVB** [comment]
Did you change anything w.r.t. the searching for playlists function since I created this ticket?

I should have mentioned this in my OP, but it would be great if the original playlist URL were stored somewhere in the folder/group properties *), so it becomes possible to reload/update the playlist. IMHO there's no need for an automatic sync function - because I more often than not make changes to my local copy of the playlist.

*) Rather than a `√-Sync with file or directory : QMPlay2://YouTube Browser/Nate Lopez plays The Blue Guitar Collection.pls` which doesn't seem to correspond to anything I can find on disk, maybe (and to stick with the example in my OP)? ;)

**Comment by zaps166** [comment]
> Did you change anything w.r.t. the searching for playlists function since I created this ticket?

It was working in the past, they changed it, fixed.

**Comment by zaps166** [comment]
@RJVB 

Is it possible to update playlist on YouTube without changing ID?

**Comment by RJVB** [comment]
On Monday December 23 2024 03:20:35 Błażej Szczygieł wrote:

>Is it possible to update playlist on YouTube without changing ID?

Good question, I have no idea!

**Comment by zaps166** [comment]
> Good question, I have no idea!

Ok, let's keep it as-is. Not worth to do sync for now.

---

A few fixes were done, you can paste your URL from issue report, also you can open from YouTube browser. Opening same playlist from YouTube browser will update existing one.
