### ISSUE TITLE
CUVID+Vulkan+Turing/RTX+Linux rendering glitch

### ISSUE THREAD

**Issue by UnknownSuperficialNight** [zaps166/QMPlay2#554]
im getting this interesting glitch with vulkan when i try play any video i get green artifacts

![2022-11-16_07-46](https://user-images.githubusercontent.com/88142731/202002315-9c179672-6c96-4ee7-839d-3ca3a215cc18.png)

screenshot above

**Comment by DarkWav** [comment]
Do you happen to use CUVID with Vulkan? Because I have this same glitch with CUVID+Vulkan only.
If so, you can try giving FFMpeg a higher priority than CUVID to fix it.

**Comment by UnknownSuperficialNight** [comment]
> Do you happen to use CUVID with Vulkan? Because I have this same glitch with CUVID+Vulkan only. If so, you can try giving FFMpeg a higher priority than CUVID to fix it.

yep that was it thanks :)

**Comment by zaps166** [comment]
@UnknownSuperficialNight 

From README: `CUVID + Vulkan might not work properly on RTX devices.` - it's working on GTX on Linux and Windows. Also it's working on RTX only on Windows. I don't know what's wrong with RTX on Linux with CUVID.

**Comment by zaps166** [comment]
Fixed!
