### ISSUE TITLE
请教QMPlay2 标题栏颜色如何设置成深色？？？？

### ISSUE THREAD

**Issue by yirenxiaoyan** [zaps166/QMPlay2#555]
![微信图片_20221118143650](https://user-images.githubusercontent.com/53068295/202637150-0e6e077d-fa1b-4b16-b821-ce5a21c96726.png)
1、选的fusion 
2、选的QMplay_dark
请问，如何把3标题栏设置成深色。
版本号：22.10.23  系统：win11

**Comment by zaps166** [comment]
You can't in QMPlay2, the only way to set it is to change title bar theme in Windows.

Please use English!
