### ISSUE TITLE
A few paper cuts

### ISSUE THREAD

**Issue by ghost** [zaps166/QMPlay2#561]
Hi. Due to being split, I can't translate some strings very well. I couldn't find a proper document for KDE apps, but there should be something similar to [this guideline](https://wiki.gnome.org/TranslationProject/DevGuidelines/Never%20split%20sentences).

https://github.com/zaps166/QMPlay2/blob/master/src/gui/Main.cpp#L851
https://github.com/zaps166/QMPlay2/blob/master/src/gui/AudioThr.cpp#L98
https://github.com/zaps166/QMPlay2/blob/master/src/gui/AudioThr.cpp#L101

Also, do we really need to translate log entries? For example:

https://github.com/zaps166/QMPlay2/blob/master/src/modules/ALSA/ALSAWriter.cpp#L175
https://github.com/zaps166/QMPlay2/blob/master/src/gui/VideoThr.cpp#L279
https://github.com/zaps166/QMPlay2/blob/master/src/gui/VideoThr.cpp#L298

Missing question mark on this line.
https://github.com/zaps166/QMPlay2/blob/master/src/modules/FileAssociation/FileAssociation.cpp#L63

**Comment by zaps166** [comment]
Hi!

> Also, do we really need to translate log entries? For example:

As you wish :) You can fix them (combine) or keep them as-is.

---

Feel free to fix splitted sentences and missing question mark in your PR, I'll update Polish translation.

**Comment by libreajans** [comment]
I will fix a few of them soon. I have exams in two weeks. Also I need to
fix translation errors in Turkish.

Błażej Szczygieł ***@***.***>, 27 Kas 2022 Paz, 02:06
tarihinde şunu yazdı:

**Comment by zaps166** [comment]
@yakushabb

**Comment by yakushabb** [comment]
The first attempt wasn't successful: https://github.com/zaps166/QMPlay2/pull/693

Could you list the split sentences in another issue for someone else to work on?

I'll be busy updating the EOL runtimes for the next few months: https://discourse.flathub.org/t/eol-runtime-working-team/6627

**Comment by zaps166** [comment]
I see, ok. It's a lot of work: source code + all translations have to be updated...
I pinged you because you're ghost user here :smile:

**Comment by zaps166** [comment]
Could be improved, but user deleted account -> closing.
