### ISSUE TITLE
Nagrywanie transmisji

### ISSUE THREAD

**Issue by DajMiliona** [zaps166/QMPlay2#562]
Dobry wieczór
Prosze o dodanie opcji nagrywania transmisji video

**Comment by zaps166** [comment]
Hej, co to za transmisja? Jeżeli jest to zwykły internetowy stream, to można go pobrać (Rozszerzenia -> Pobierz) z menu kontekstowego. Aby zakończyć pobieranie należy je zatrzymać w zakładce "Pobieranie plików z Internetu".

**Comment by DajMiliona** [comment]
Nagrywanie transmisji live. Jakakolwiek transmisja live z FB,YT, Tvp stream itp

**Comment by zaps166** [comment]
#185
