### ISSUE TITLE
Odtwarzanie i nagrywanie video z Facebook

### ISSUE THREAD

**Issue by DajMiliona** [zaps166/QMPlay2#563]
Prosze o dodanie opcji
Odtwarzanie i nagrywanie video z Facebook

**Comment by zaps166** [comment]
Nie posiadam tam konta. yt-dlp nie ogarnia jak wkleisz adres (Ctrl+U, wybierz "youtube-dl")? Jeżeli to zadziała, mogę dodać do głównej opcji autowykrywania.

**Comment by zaps166** [comment]
#185
