### ISSUE TITLE
soporte NDI

### ISSUE THREAD

**Issue by playmepe** [zaps166/QMPlay2#571]
Es posible puedan implementar soporte de transmision por red por NDI, SRS, RTSP, HLS o RTMP? quisiera utilizar para hacer transmisiones en vivo o para complementar con OBS-STUDIO  https://obsproject.com/
Gracias por este gran software.

**Comment by zaps166** [comment]
Use English

**Comment by RafaelLinux** [comment]
haz las preguntas en inglés. Puedes usar la página web deepl.com/translator para traducir tus preguntas a inglés y viceversa. Si no lo haces, no conseguirás respuestas.   Un saludo.

**Comment by zaps166** [comment]
I know I can use deepl or google, but I prefer to read English or Polish here :smile:

**Comment by RafaelLinux** [comment]
> I know I can use deepl or google, but I prefer to read English or Polish here smile

I'm sorry, my comment was for playmepe ;)
