### ISSUE TITLE
Wygląd jak w VLC lub Media Player

### ISSUE THREAD

**Issue by DajMiliona** [zaps166/QMPlay2#573]
Prosze o wyglad taki intuicyjny jak w VLC oraz Mediaplayer (łatwiejsze otwieranie linków intrnetowych) tak jak w VLC.
Ponadtto prosze o opcje nagrywania tak jak w VLC jest. Nagrywanie przy pomocy Streamlink czy tez innej aplikacji.
Zmiana rozdzielczośći (odszukanie tej opcji oglądajac YT czy to inny materiał) to męczarnia. Też mozna by to uprościc.

![Wyglad](https://user-images.githubusercontent.com/39501742/209691394-0ac1ee5f-f72e-4ea9-bdb3-2d766596cc81.png)

**Comment by zaps166** [comment]
Jak wrócę do programowania QMPlay2 to zobaczę na to.

> Ponadtto prosze o opcje nagrywania tak jak w VLC jest.

To wymaga trochę zmian w programie. Tak jak już pisałem w innym Issue - stream internetowy można po prostu pobrać na dysk/SSD w QMPlay2 - jest to prawie to samo (tworzy drugie połączenie z serwerem, ale za to zapisuje bezstratnie takie same dane obrazu i dźwięku jak w streamie).

> Zmiana rozdzielczośći (odszukanie tej opcji oglądajac YT czy to inny materiał) to męczarnia.

Klikasz na drugą ikonkę w zakładce YouTube i wybierasz, tylko trzeba włączyć ponownie odtwarzanie. Jakieś pomysły na usprawnienie? Wiem na pewno, że ikony trzeba zmienić (w tym pod styl ciemny).

**Comment by DajMiliona** [comment]
Niestety ja nie odszukałem tego i nie potrafię nagrywać. Prosiłbym o uproszczenie tego.
Ponadtto dodanie opcji otwórz link a nie tworzenie playlist itp.

**Comment by zaps166** [comment]
> Niestety ja nie odszukałem tego i nie potrafię nagrywać.

Nie ma nagrywania, ale można pobrać stream.

> Nagrywanie transmisji live. Jakakolwiek transmisja live z FB,YT, Tvp stream itp

Działa dla YT i TVP Sport i dla wielu innych. Double-click na liście pobierania otwiera video.

https://user-images.githubusercontent.com/6239090/213795197-77ecfb42-ad91-4530-bb76-884de66f8a01.mp4

**Comment by DajMiliona** [comment]
U mnie nie ma pliku w katalogu z naganiamia z YT. Sama opcja jest tak nieintuicyjna.... Dlatego prosze o zmiane wygladu programu.

**Comment by zaps166** [comment]
Nagrywanie zostało dodane, streamlink też działał (jak sprawdzałem to dawno temu).

Wiem, że interface może być nieintuicyjny (zwłaszcza opcje), ale nie mam teraz czasu ani pomysłu, żeby przerobić to wszystko. Poza tym interface VLC dla mnie jest kiepski...

**Comment by zaps166** [comment]
I can agree UI/UX is not perfect (especially settings window and some context menus), but I'll not clone VLC or WMP design here.
