### ISSUE TITLE
Mediabrowser window usability: First column (Title)

### ISSUE THREAD

**Issue by RafaelLinux** [zaps166/QMPlay2#574]
I was mad about trying to change first column size in "MediaBrowser". Usually, when I place mouse pointer between two columns in common QT applications, it leave me to drag between any title column intersection. However, after trying a lot of ways, I found that to change "Title" size user must drag from "Artist" and "Lenght" columns intersection. To change this and let user drag between "Title" and "Artist" would be very usefull.  ;)

Anyway, I discovered your application today, after using "VLC", "QMMP" and "SMPlayer". But your application features are really what I was looking a long time ago. To add "YouTube" and "MediaBrowser" as part of your player is like you read my mind. I needed Opera to browse MyFreeMp3 pages (very slow downloading) but your application does it all. Goodbye Opera for visit that page and same for YouTube. 

YOUR WORK IS REALLY GREAT

THANK YOU

**Comment by zaps166** [comment]
Hey, thanks!

I locked the first column intentionally to adjust it to maximum size keeping Artist and Length as small as possible, but I'll try to unlock it.

**Comment by RafaelLinux** [comment]
Thank you!!! I love your application. It's "all in one" about media playing/searching. You had a really great idea and solved me a lot of work opening distinct pages in browser and distinct browsers (as I mentioned, only Opera can open myfree.... without issues.

I'll recommend QMPlay2 to anyone who needs a good player for Linux/Windows (I'm sorry about Mac users .... but it's supposed they can pay any player!!!!  XD )

**Comment by RafaelLinux** [comment]
Excellent. Thank you for your great great work. I discovered that even when I download files thru "mediabrowser", your application removes the "myfreemp3..." suffix inserted in filename. Another awesome feature.

Thanks!!
