### ISSUE TITLE
Inhibiting Screensaver whilst playing files?

### ISSUE THREAD

**Issue by Chromace** [zaps166/QMPlay2#58]
Usually, QMPlay2 will prevent the screen from turning off whilst it is playing files (video/URL + audio). However, this is currently not the case - after the designated screen switch-off time, the screen powers off, with the video/audio still playing.

**Comment by zaps166** [comment]
Probably because of this: https://github.com/zaps166/QMPlay2/commit/52df39677a37984f33af054f86b24f45737abd67

Tested only on `xset s 1` which sets screensaver to 1 second. With this works properly for me. Could you describe your screensaver and/or power management settings, your desktop environment and what have you done in QMPlay2 when screensaver starts when it shouldn't?

**Comment by Chromace** [comment]
I'll do my best. I'm using the Plasma Desktop on Arch, with the 'screen energy saving' option turned on to switch off the screen after 10 minutes on AC power and 5 minutes on battery power.

Experimentally, I toggled the switch off to 1 minute as to test QMPlay2's screensaver inhibiting ability, and played a YouTube video which lasted 10 minutes. The screen turned blank after the minute was up. This also occured for full-screen audio (with album art), which inhibited screen blanking in the past (thanks for that again ^^).

For the screen to turn blank, all I have to do is wait for the designated blank time - I don't touch the computer.

**Comment by zaps166** [comment]
Thanks, I'll try on Plasma Desktop soon.

One more thing, could you execute `xset s 1` in terminal - this will enable screensaver after one second. It is blocked by QMPlay2 for me properly (`xset s 0` to disable screensaver).

**Comment by Chromace** [comment]
Enabling the screensaver with xset (before + after disabling Plasma's screen blanking) results in the screensaver being triggered after one second even whilst playing videos or full-screen audio.

**Comment by zaps166** [comment]
Thanks, but weird :smile:
I assume that you have Qt 5.7.0, QMPlay2 uses Qt 5 and you open QMPlay2 and play YouTube video, right?

**Comment by Chromace** [comment]
Yes. I've also tested it with full-screen audio files as well as local video files - same results.

**Comment by zaps166** [comment]
Thanks! If I won't able to check what's wrong, so I'll send you something to test, OK?

**Comment by Chromace** [comment]
Sure! :)

**Comment by zaps166** [comment]
`xset s 1` on KDE 5 - properly blocked (you must set this before starting playback)
Screensaver from KDE 5 power management - not blocked

**Comment by Chromace** [comment]
Apologies - on trying again properly, I have the same results as you do.

**Comment by zaps166** [comment]
I don't want to use `XResetScreenSaver()` again, because it is bad and causes not smooth playback on some drivers (OpenGL is not smooth on entire X session, e.g. Intel+OpenGL Compositor+VSync).

Maybe KDE screen saver can't be disabled using `XSetScreenSaver()` or I'm using in incorrectly...

**Comment by zaps166** [comment]
Try also:
```sh
xset -dpms
xset s off
```

and later enable again:
```sh
xset dpms
xset s on
```

**Comment by Chromace** [comment]
Sure. What was the expected results?

With 'xset -dpms && xset s off', and Plasma power management turned on, the screen blanks even with full-screen audio files. However, video files work fine.

The computer does automatically suspend itself however, regardless of whether or not the screensaver is inhibited.

**Comment by zaps166** [comment]
> the screen blanks even with full-screen audio files. However, video files work fine.

Full-screen and video playback should have the same result. Please try without QMPlay2 (only commands in terminal), because it might override something, but I think that it won't work properly.

**Comment by zaps166** [comment]
Maybe I'll use command-line DBus for common desktop sessions, it should work.

**Comment by Chromace** [comment]
I've found that QMPlay2 does inhibit audio files. Interestingly enough, the screensaver appears for a second or two, then goes away.

**Comment by zaps166** [comment]
> the screensaver appears for a second or two

Exactly, event with `xdg-screensaver suspend {winid}` or `xdg-screensaver reset` in the loop doesn't work properly (the script uses dbus inside). Maybe it is also KDE bug after a recent update?

Could you try QMPlay2 16.09.04 for both: full-screen audio and next for video playback?

**Comment by Chromace** [comment]
Sure. Both full-screen audio and video playback in 16.09.04 inhibit the screensaver (1 minute threshold).

**Comment by zaps166** [comment]
Thanks, but can it also inhibit session lock (16.09.04)?

**Comment by Chromace** [comment]
Yes. Session locking and suspending is inhibited in 16.09.04.

**Comment by zaps166** [comment]
Ok, so the best solution is to reset screensaver in a timer like in previous QMPlay2 version, bu I'll do it better than before.

**Comment by zaps166** [comment]
Using DBus and other APIs (depends on Desktop Environment) is not good for me :smile:

**Comment by zaps166** [comment]
Thanks for the bug report!

Correct behavior for screen saver with timeout >= 30 sec:
- Full-screen mode should always inhibit during video/audio playback.
- Windowed mode should inhibit only non-paused video playback.

**Comment by Chromace** [comment]
Thank-you! The screen-saver is inhibited :)
