### ISSUE TITLE
Request: Smaller UI Menus

### ISSUE THREAD

**Issue by 0pLuS0** [zaps166/QMPlay2#580]
Hello,

First let me say, this is a really nice app, thank you very much for all your hard work, it's greatly appreciated!

I noticed with the UI menus, the space between the words, horizontally and vertically are spaced to far apart, creating really huge menus.

I'm running a 27" monitor at 1440p and I was really surprised at how huge the menus are.

I hope you can please make these like 50% smaller.

THANKS, keep up the great work! 👍 

![1  OMPlay2](https://user-images.githubusercontent.com/36190223/212624430-65dc1966-bf5a-45c7-b25a-901e31d95d2e.jpg)

![2  OMPlay2](https://user-images.githubusercontent.com/36190223/212624450-29a31280-e49e-4135-8373-db0bdfcbe74e.jpg)

**Comment by zaps166** [comment]
Maybe it should be reorganized instead? Qt and Qt style in your OS is determining the size, I use the default sizes.

**Comment by 0pLuS0** [comment]
I've never had any QT apps with menus this big. 

This is not my setup causing the huge menu, it's the app.

**Comment by zaps166** [comment]
> it's the app.

Not the app. I don't enforce the menu size. Which Qt style do you use? It's possible that some styles makes it larger because of icons in menu. Could you check on Fusion style? For me QMPlay2's menu looks like in other applications with icons in menu.
