### ISSUE TITLE
速度>=1.2X，声调变了，变尖，没有原声效果

### ISSUE THREAD

**Issue by Leadrive** [zaps166/QMPlay2#583]
加速播放时，声调变了。
同样的视频，采用PotPlayer就很正常

**Comment by Leadrive** [comment]
Windows 10, amd64

**Comment by zaps166** [comment]
English please

**Comment by Leadrive** [comment]
@zaps166
Thank you.
If the play speed >= 1.2, the people sound tone will change, not the normal.
You can play the same video via PotPlayer, it will play sound ok.

**Comment by Leadrive** [comment]
https://github.com/zaps166/QMPlay2/issues/518

**Comment by zaps166** [comment]
Thanks, as you noticed you can enable the option which keeps the audio pitch. I hope it works ok to you!
