### ISSUE TITLE
No voice channel sound with AAC 6 channels video

### ISSUE THREAD

**Issue by RafaelLinux** [zaps166/QMPlay2#584]
When I play a video with a AAC or AC3 6 channels encoded audio thru an stereo output (headset or 2.1 audio system), I can't listen voice channel. MPV plays all channels.

Do I need to change something to listen all audio channels in QMPlay2?

**Comment by zaps166** [comment]
I need file to check it.

**Comment by RafaelLinux** [comment]
https://we.tl/wRwJ3EJt32

You will (not) listen a sound each time a text appears in video (central channel I guess). Use mpv or VLC and you will listen difference.

Here https://thedigitaltheater.com/dolby-trailers/ you have more videos to try

**Comment by RafaelLinux** [comment]
I'm sorry I didn't reply sooner. Yes, I use Pipewire. I can't check fix cause latest AppImage is from october .... where I can download fixed version?

**Comment by zaps166** [comment]
For ArchLinux and Manjaro use AUR `qmplay2-git`, for others wait for new release or compile it.
