### ISSUE TITLE
cuda video filter enhancement 

### ISSUE THREAD

**Issue by taktiker12** [zaps166/QMPlay2#585]
hi zaps166
i discover that some video players are using yadif_cuda into video filters , is it possible to integrate this video filter in the cuvid box ?
regards and thank u

**Comment by zaps166** [comment]
Hi, QMPlay2 already uses Yadif filter on GPU. Use Vulkan and select both options:
![Screenshot_20230125_181838](https://user-images.githubusercontent.com/6239090/214634785-fd3d6a6c-0efa-45dd-95a6-3801bc8e94e1.png)
and press apply. It applies to CPU-decoded videos and to CUVID, VA-API, D3D11VA.

**Comment by taktiker12** [comment]
Thank u zaps166

Błażej Szczygieł ***@***.***> schrieb am Mi., 25. Jan. 2023,
18:20:
