### ISSUE TITLE
Vp9 profile2 video with opengl renderer has no vaapi acceleration

### ISSUE THREAD

**Issue by NaofumiHonda** [zaps166/QMPlay2#587]
I have several intel platform notebooks.
Both the vp9 profile 0 (AV_PIX_FMT_YUV420P ) and profile 2 (AV_PIX_FMT_YUV420P10 ) 
 videos with vulkan renderer are properly accelerated through vaapi.
However,  with opengl renderer , only the profile 0 video is hw-accelerated , 
and the other one is not.

I saw the related source code and found that if  we change the line 184 in  src/modules/FFmpeg/FFDecVAAPI.cpp
`
else if (pix_fmt != AV_PIX_FMT_YUV420P && pix_fmt != AV_PIX_FMT_YUVJ420P)
`
to
`
else if (pix_fmt != AV_PIX_FMT_YUV420P && pix_fmt != AV_PIX_FMT_YUV420P10 && pix_fmt != AV_PIX_FMT_YUVJ420P)
`
then both the videos are again  properly accelerated under the combination of vaapi and opengl.

Is there any reason to prevent an AV_PIX_FMT_YUV420P10 format video from being hw-accelerated under this combination?

**Comment by zaps166** [comment]
I can confirm it's working on Radeon, too. I'll add this, thanks!

**Comment by zaps166** [comment]
Btw. why OpenGL?

**Comment by NaofumiHonda** [comment]
> Btw. why OpenGL?

In my home,  all the machine share the same settings via NFS.

For some desktops with nvidia cards, contrary to the reported intel case,
vp9 profile2 video is ok with opengl renderer (through cuvid and vdpau)  but not good with vulkan (there are many green stripes in the scree).
So I wanted a common  renderer setting for which all the machines play the vp9 profile2 vidoes well.
And now opengl renderer becomes the desired one, THANKS!

**Comment by zaps166** [comment]
Ok!

> there are many green stripes in the scree

Nvidia RTX + Linux + CUVID (#554)?

**Comment by NaofumiHonda** [comment]
> Ok!
> 
> > there are many green stripes in the scree
> 
> Nvidia RTX + Linux + CUVID (#554)? 

The screen image in #554  is the same as the one in my case.
But my machine has NVIDIA GeForce GTX 1660/6GB.
(opengl + cuvid: OK,  vulkan + cuvid: NG).

**Comment by zaps166** [comment]
> But my machine has NVIDIA GeForce GTX 1660/6GB (with Linux!).

GTX 1660 is Turing like RTX 2xxx :smile: GTX 1080 and GTX 1080Ti (Pascal) are working!
Also newer Nvidia GPUs are working with CUVID + Vulkan on Windows.

I really don't know what's wrong, I've looked again at this few hours ago without luck. Maybe I did it wrong or it's a driver bug and I need to find other way of doing this.

**Comment by zaps166** [comment]
> The screen image in https://github.com/zaps166/QMPlay2/issues/554 is the same as the one in my case.

Can you test again it with current master branch?

**Comment by NaofumiHonda** [comment]
> > The screen image in #554 is the same as the one in my case.
> 
> Can you test again it with current master branch?

Oh!  Perfect!
Now vulkan renderer becomes the best choice for me.
I'm really appreciated for your effort.
