### ISSUE TITLE
Set video zoom to integer

### ISSUE THREAD

**Issue by notramo** [zaps166/QMPlay2#589]
Screen recordings appear blurry when viewed on a screen with different resolution.
E.g. when a 1280x720 screen recording is viewed on a full HD monitor, it is blurry. One may want to scale down and view it with an actual 1:1 zoom in a 1280x720 px size of the screen (probably centered). On a 4K monitor, the same 720p video may be viewed with a 2x zoom, to avoid interlacing.

VLC has this in the top menu: **Video** in top menu bar, then **Always fit window**. However, it doesn't support 2x or 3x scaling.

**Comment by zaps166** [comment]
I see, need to do :sweat_smile:

I understand it must be pixel-to-pixel independent of DPR.

**Comment by zaps166** [comment]
0ffd656249b7a19c3e1ee1084cf9ea53256d101c, fixed.

**Comment by zaps166** [comment]
Code refactor after some integer scaling tests :sweat_smile:

**Comment by zaps166** [comment]
Thanks for testing! AUR package is fixed already!
