### ISSUE TITLE
Problems with reading .srt subtitles

### ISSUE THREAD

**Issue by Ksiencha** [zaps166/QMPlay2#59]
Hello! I encountered some issues while playing video with .srt subtitles:

1. The player doesn't apply `<font color>` tags
[Screenshot 1](http://i.imgur.com/loDWqcB.png)

2. The second reply in dialogue had to start in a new line
[Screenshot 2](http://i.imgur.com/AaS2Xuz.png)

Is there anything that can be done to solve this?
Thanks :)

**Comment by zaps166** [comment]
@Ksiencha Thanks for bug report!

`<font color>` tag is not supported. Please upload the SRT file here (change file extension to *.txt) then I'll implement it :)

**Comment by Ksiencha** [comment]
@zaps166 Uploaded. Thanks again ;)
[The.Night.Manager.S01E01.HDTV.x264-TLA.txt](https://github.com/zaps166/QMPlay2/files/544332/The.Night.Manager.S01E01.HDTV.x264-TLA.txt)

**Comment by zaps166** [comment]
I hope SRT colors and line breaks will work properly now :)

**Comment by zaps166** [comment]
Fixed REG/Blue swapped colors in SRT.
