### ISSUE TITLE
Is there a way to stop yt-dlp automatic update?

### ISSUE THREAD

**Issue by beew** [zaps166/QMPlay2#591]
Hi,

The latest yt-dlp release (2023.03.03) breaks dash videos on Youtube.

https://github.com/mpv-player/mpv/issues/11392

On Qmplay2 all YT vidoes have resolution <= 1024x768

This change was made to solve a problem that doesn't exist for me (throttling apparently doesn't happen here)

So I would rather continue using the previous version 2023.02.17 instead of upgraded to  2023.03.03, but whenever I replace yt-dlp in ~/.config/Qmplay2 with the older version it is automatically updated again.

The only way I can restore the previous working behaviour is to build yt-dlp from nightly but replacing yt_dlp/extractor/youtube.py with the file from 2023.02.17 and then replace Qmplay2's copy with it. In this way it no longer update.

There is probably a way to stop yt-dlp from automatically updating but I couldn't find it.

**Comment by DarkWav** [comment]
I can confirm that the YouTube dash video quality is limited to 720p.
However, downloading a video manually with yt-dlp first and then opening the `.webm` file in QMPlay2 works just fine.

**Comment by zaps166** [comment]
Hi, set `SkipYtDplUpdate=true` in `QMPlay2.ini` file in `[General]` section to skip auto-update.

**Comment by zaps166** [comment]
Fixed typo: `SkipYtDplUpdate` -> `SkipYtDlpUpdate`.

**Comment by zaps166** [comment]
Please check if YouTube is working correctly :)

**Comment by DarkWav** [comment]
> Please check if YouTube is working correctly :)

For me it works fine, thanks for fixing.
