### ISSUE TITLE
YouTube "Audio only" option also plays/downloads videos?

### ISSUE THREAD

**Issue by Chromace** [zaps166/QMPlay2#592]
Hello! Currently, it seems like while using the YouTube widget > right-clicking a searched video > selecting "Audio only" > Play/Download will result in playing or downloading a regular video instead of just audio.

This can currently be worked around by using the youtube-dl/yt-dlp playback option as seen below, which does only play audio as expected:
![image](https://user-images.githubusercontent.com/16624211/224515419-c9324521-8036-422c-866e-99955c2043ee.png)

Unfortunately, using those same parameters using the regular YouTube option doesn't seem to work.

**Comment by zaps166** [comment]
#591 
Something has changed, I'll look at this.

**Comment by zaps166** [comment]
Please check if YouTube is working correctly :)

**Comment by Chromace** [comment]
The audio-only options (playing and downloading) now work as expected, thank you!
