### ISSUE TITLE
[FR]: Open in compact mode when opening video file

### ISSUE THREAD

**Issue by RafaelLinux** [zaps166/QMPlay2#593]
I searched in configuration options but didn't find any way to get QMPlay2 to start in only video mode ("Compact mode" or "Alt+V") when opening QMPlay or  - better - when opening a video file. Could you implement that feature???

Thank you

**Comment by ben2talk** [comment]
> I searched in configuration options but didn't find any way to get QMPlay2 to start in only video mode ("Compact mode" or "Alt+V") when opening QMPlay or - better - when opening a video file. Could you implement that feature???
> 
> Thank you

This certainly prevents me switching default for video from MPV.

**Comment by RafaelLinux** [comment]
I have even tried to achieve this using the "profiles". First I set QMPlay2 to "Compact View", then created a profile and saved it. When I open QMPlay2 again with that profile, it ignores that I saved it with "Compact View". I don't know what to try anymore.

**Comment by zaps166** [comment]
Do you want to compact mode to be restored after QMPlay2 restart?

**Comment by RafaelLinux** [comment]
Most than 3/4 time I use QMPlay is to play video, so yes, I want compact mode when I open a video.

**Comment by zaps166** [comment]
Sorry, forgot about it.
