### ISSUE TITLE
error while loading shared libraries: libavutil.so

### ISSUE THREAD

**Issue by ProfP30** [zaps166/QMPlay2#594]
Since around 10th March 2023 or so, launching QMPlay2 on Arch brings:

"error while loading shared libraries: libavutil.so.57: cannot open shared object file: No such file or directory"

Installed QMPlay2-package from AUR:
https://aur.archlinux.org/packages/qmplay2

**Comment by zaps166** [comment]
FFmpeg 6.0, new library file names, just recompile: `yay -S qmplay2`.
