### ISSUE TITLE
DVB-T1/T2 (terrestrial TV channels) teletext showed instead subtitles

### ISSUE THREAD

**Issue by RafaelLinux** [zaps166/QMPlay2#595]
When I play a DVB-T1/2 TV channel and enable subtitles (pressing N key), QMP2 shows teletext screens in a continuous loop thru ALL teletext pages, instead TV channel subtitles.

[vokoscreenNG-2023-03-20_02-12-02_VP9.webm](https://user-images.githubusercontent.com/13048959/226225119-48fcac57-09e0-42fd-a172-51e0dcee70a7.webm)

**Comment by zaps166** [comment]
Is it possible to change subtitles stream?

**Comment by RafaelLinux** [comment]
Each time I press "N", it only enables/disables Teletext.

**Comment by zaps166** [comment]
I think I've seen this bug before somewhere (maybe I tested it long time ago).
I need sample video file, but idk how it works (also in real TV I don't know how to use "feature" (teletext) :smile:).

**Comment by RafaelLinux** [comment]
Usually, there is a button named "Teletext" in remote controller. I'm not sure if Teletext content will be saved with video, cause Teletext is asynchronous, but I'll try.

**Comment by zaps166** [comment]
To do anything with this I need the file. I think you should be able to capture everything using ffmpeg from command line.

**Comment by RafaelLinux** [comment]
As it's saved as TS file, I can insert here, so I shared video in this link
https://file.io/f33shlyHra00
MPV plays correctly Teletext channel. VLC detect it as a Teletext channel and show typical buttons in interface (blue, yellow, green and black buttons on remote control).

**Comment by zaps166** [comment]
On your file:
VLC detects, buttons are visible, but teletext doesn't work (buttons do nothing).
MPV doesn't works either.
QMPlay2 doesn't show anything, subtitles track is not selected and not possible to select it.

**Comment by RafaelLinux** [comment]
Curiously, only QMP2 it's not working for me same way.  Among those players, only QMP2 begin to show ALWAYS Teletext layer just when I open the stream or the recorded file. As you told, teletext buttons in VLC doesn't work (I personally, I don't need Teletext), however, VLC is the only only that recognices "DVB Subtitles" and shows it!!!. MPV shows subtitles correctly )slowly, not accelerated as QMP2) but they are not interactive. You can see the three players playing live same DVB-T stream with subtitles enabled in attached link.

Resume:

- QMP2 ALWAYS enable (for me) Teletext, independently if I closed QMP2 with or without subtitles enabled and reopen the stream or file. Teletext layer always is showed. It's really anoying .
- QMP2 doesn't detect "DVB Subtitles". Only VLC is able to identify and show stream subtitles (they are even colored).

https://file.io/EQ9hZ52pc6lp

**Comment by zaps166** [comment]
You don't have to show me the comparison, I know about it. QMPlay2 doesn't support DVB-T, but to try to avoid this issue (don't display teletext), I need captured stream with working teletext. [this](https://file.io/f33shlyHra00) doesn't work in any of three players, unfortunately.

**Comment by zaps166** [comment]
Try to capture MPEG stream using ffmpeg command line using stream copy (audio, video, subtitles).

**Comment by RafaelLinux** [comment]
Just copied as is with 
`ffmpeg -i "http://192.168.1.11:9981/stream/channel/7159c961dd4920e9633297f32f9ab8e7" -map 0:v:0 -map 0:a:0 -map 0:s -c copy -y -f mpegts test.ts`

https://file.io/slZuwZjT4A1I

**Comment by zaps166** [comment]
I can see teletext on VLC, but I can't enable this stream on QMPlay2, so still can't reproduce your issue :sob: The `dvbsub` stream is enabled by default, `dvb_teletext` can't be enabled.

Btw. your videos don't work on VA-API on Radeon RX 6900 XT (but they work on AMD Radeon Vega 8 VA-API). Could you report it [here](https://gitlab.freedesktop.org/mesa/mesa/-/issues) and link your video (I can see the issue on MPV, VLC, QMPlay2)?

Look  :rofl: 

https://user-images.githubusercontent.com/6239090/228329948-0c6f0f16-f6c9-469b-9987-8657bfc1175a.mp4

**Comment by RafaelLinux** [comment]
Really annoying !!! ;) 
I'm using openSUSE Tumbleweed with Nvidia propietary drivers. In my system, that issue doesn't happen!!! Plays fine like in the live stream. Llike in my firstposted video, when I open this file with QMP2, "accelerated" Teletext is enabled by default, till I press "N". 
However, I really don't know what do you want me to say in that forum ...

**Comment by DarkWav** [comment]
I believe NVIDIA currently does not support VA-API in any applications except Firefox (and even that is experimental), so a VA-API exclusive bug will not show up when using NVIDIA hardware. It is indeed very hard to report a bug you can't even reproduce on your own system.

Asides that, for openSUSE TW I currently employ these build options:
```
%define __builder Ninja
  -DCMAKE_C_COMPILER=clang \
  -DCMAKE_CXX_COMPILER=clang++ \
  -DCMAKE_C_FLAGS="${CFLAGS:-%optflags} -gdwarf-4" \
  -DCMAKE_CXX_FLAGS="${CXXFLAGS:-%optflags} -gdwarf-4" \
  -DSOLID_ACTIONS_INSTALL_PATH="%{_datadir}/solid/actions" \
  -DUSE_LINK_TIME_OPTIMIZATION=ON \
  -DUSE_PCH=ON \
  -DUSE_GIT_VERSION=OFF \
  -DCMAKE_INSTALL_PREFIX=%{_prefix} \
  -DCMAKE_INSTALL_LIBDIR=%{_libdir} \
  -DUSE_GLSLC=ON \
  -DUSE_PORTAUDIO=ON \
  -DUSE_PIPEWIRE=ON \
  -DUSE_RUBBERBAND=ON \
  -DUSE_UPDATES=OFF
```
Meanwhile, the AUR version uses these:
```
  -G Ninja \
  -DCMAKE_C_COMPILER=clang \
  -DCMAKE_CXX_COMPILER=clang++ \
  ../QMPlay2-src-${pkgver} \
  -DCMAKE_INSTALL_PREFIX=/usr \
  -DCMAKE_INSTALL_LIBDIR=lib \
  -DUSE_CHIPTUNE_SID=ON \
  -DUSE_LINK_TIME_OPTIMIZATION=OFF \
  -DUSE_PCH=ON \
  -DUSE_GLSLC=OFF \
  -DUSE_GIT_VERSION=OFF
```
Any differences that could cause the differences in behavior?

**Comment by RafaelLinux** [comment]
> Can I use your video file and report a driver bug?
I have no objection to that!!!

**Comment by RafaelLinux** [comment]
> I believe NVIDIA currently does not support VA-API in any applications except Firefox (and even that is experimental), so a VA-API exclusive bug will not show up when using NVIDIA hardware. It is indeed very hard to report a bug you can't even reproduce on your own system.
> 

But, I'm not sure about how that is related to my reported issue. I'll try to test issue in another Linux without Nvidia card, but suspect is not related.
> Asides that, for openSUSE TW I currently employ these build options:
> 
> ```
> %define __builder Ninja
>   -DCMAKE_C_COMPILER=clang \
>   -DCMAKE_CXX_COMPILER=clang++ \
>   -DCMAKE_C_FLAGS="${CFLAGS:-%optflags} -gdwarf-4" \
>   -DCMAKE_CXX_FLAGS="${CXXFLAGS:-%optflags} -gdwarf-4" \
>   -DSOLID_ACTIONS_INSTALL_PATH="%{_datadir}/solid/actions" \
>   -DUSE_LINK_TIME_OPTIMIZATION=ON \
>   -DUSE_PCH=ON \
>   -DUSE_GIT_VERSION=OFF \
>   -DCMAKE_INSTALL_PREFIX=%{_prefix} \
>   -DCMAKE_INSTALL_LIBDIR=%{_libdir} \
>   -DUSE_GLSLC=ON \
>   -DUSE_PORTAUDIO=ON \
>   -DUSE_PIPEWIRE=ON \
>   -DUSE_RUBBERBAND=ON \
>   -DUSE_UPDATES=OFF
> ```
> 
> Meanwhile, the AUR version uses these:
> 
> ```
>   -G Ninja \
>   -DCMAKE_C_COMPILER=clang \
>   -DCMAKE_CXX_COMPILER=clang++ \
>   ../QMPlay2-src-${pkgver} \
>   -DCMAKE_INSTALL_PREFIX=/usr \
>   -DCMAKE_INSTALL_LIBDIR=lib \
>   -DUSE_CHIPTUNE_SID=ON \
>   -DUSE_LINK_TIME_OPTIMIZATION=OFF \
>   -DUSE_PCH=ON \
>   -DUSE_GLSLC=OFF \
>   -DUSE_GIT_VERSION=OFF
> ```
> 
> Any differences that could cause the differences in behavior?

**Comment by DarkWav** [comment]
> > I believe NVIDIA currently does not support VA-API in any applications except Firefox (and even that is experimental), so a VA-API exclusive bug will not show up when using NVIDIA hardware. It is indeed very hard to report a bug you can't even reproduce on your own system.
> 
> But, I'm not sure about how that is related to my reported issue. I'll try to test issue in another Linux without Nvidia card, but suspect is not related.

I's only related to the VA-API bug @zaps166 discovered with their 6900XT, it has nothing to do with the original issue.

**Comment by zaps166** [comment]
And for the original issue: files deleted 😔 But I should have it on another computer

**Comment by RafaelLinux** [comment]
> And for the original issue: files deleted pensive But I should have it on another computer

Here you have it again. I can't attach here cause it's 32MiB and you want to keep original stream, so can't convert to webm  ;)
https://file.io/QUEBcZDou2HU

**Comment by zaps166** [comment]
1. Bug [reported](https://gitlab.freedesktop.org/mesa/mesa/-/issues/8740).
2. When I select 2nd stream with teletext it doesn't work at all, I can't select second stream at all (Manjaro/Arch and QMPlay2 for Windows and [AppImage](https://github.com/zaps166/QMPlay2/releases/download/23.02.05/QMPlay2-23.02.05-1-x86_64.AppImage)). Do you use the newest version and do you use any custom compilation of FFmpeg/QMPlay2? Could you try my AppImage?

**Comment by RafaelLinux** [comment]
This is my version:
![imagen](https://user-images.githubusercontent.com/13048959/228629830-938d373a-c1ef-49e9-bd33-050c4462a92f.png)

Anyway, your AppImage crashed when trying to open my TS file:
[29 mar. 2023 20:10:55.393] CUVID :: Unable to get function pointers
Set LIBVA_DRIVERS_PATH to /usr/lib64/dri
libva info: VA-API version 1.17.0
libva info: Trying to open /usr/lib64/dri/nvidia_drv_video.so
libva info: Found init function __vaDriverInit_1_15
[29 mar. 2023 20:10:55.446] QMPlay2 crashed (SIGSEGV)
fish: Job 1, './QMPlay2-23.02.05-1-x86_64.App…' terminated by signal SIGSEGV (Address boundary error)

**Comment by RafaelLinux** [comment]
It doesn't crash priorizing FFMPEG. It doesn't work as in my installed version. It appears selected the first channel but if I select the second one, and I  access again to select channel, last clicked one (second one) in not selected!!! No Teletext in any way.

Second channel appears like "not selected" even after it let me select it previously:
![imagen](https://user-images.githubusercontent.com/13048959/228634038-b1018dbc-8acf-427f-92af-ac4ffa4c5fd8.png).

But I consider this workaround is enough. At least, Teletext is not enabled by default (second channel) so I don't mind if they are played "accelerated" or not   ;)

**Comment by zaps166** [comment]
@RafaelLinux @DarkWav 

- Please don't use `nvidia_drv_video.so` - it can crash any VA-API software on Linux on NVIDIA drivers (QMPlay2, OBS, etc.). This driver is obsolete and should never be installed (`libva-vdpau-driver` on Arch Linux)! You can uninstall it and try again without changing decoders priority.

@RafaelLinux 
- `CUVID :: Unable to get function pointers` - interesting... Did you put your computer to sleep before running QMPlay2 maybe?

---

> It doesn't work as in my installed version. It appears selected the first channel but if I select the second one, and I access again to select channel, last clicked one (second one) in not selected!!! No Teletext in any way.

I have the same, that's why I can't reproduce.

**Comment by DarkWav** [comment]
> Please don't use nvidia_drv_video.so - it can crash any VA-API software on Linux on NVIDIA drivers (QMPlay2, OBS, etc.). This driver is obsolete and should never be installed (libva-vdpau-driver on Arch Linux)! You can uninstall it and try again without changing decoders priority.

Alright, thanks for the heads up, the AppImage indeed doesn't crash any more once I uninstall that faulty driver.

**Comment by RafaelLinux** [comment]
> @RafaelLinux @DarkWav
> 
>     * Please don't use `nvidia_drv_video.so` - it can crash any VA-API software on Linux on NVIDIA drivers (QMPlay2, OBS, etc.). This driver is obsolete and should never be installed (`libva-vdpau-driver` on Arch Linux)! You can uninstall it and try again without changing decoders priority.

I didn't know it was obsolete. Really I don't know if it is installed automatically or I installed it to get some acceleration. I uninstall it now (it's the libva-vdpau-driver library in openSUSE).

> @RafaelLinux
> 
>     * `CUVID :: Unable to get function pointers` - interesting... Did you put your computer to sleep before running QMPlay2 maybe?

Yes!!!! I always prefer to sleep my PC. My data is in a mechanical HD and takes a lot to Plasma to load my desktop configuration, so I usually sleep my PC (I can't hibernate a long time ago since I changed my SSD with BTRFS to compressed mode). You know a lot about my system  XD

**Comment by RafaelLinux** [comment]
As a Linux user, it's my fault for continue buying Nvidia graphic cards. In fact, I use official Nvidia (for openSUSE) repository to get propietary drivers, but as you showed me, that doesn't solve Nvidia issues on Linux systems.

You have really done a lot of research and know the ins and outs of Nvidia and its failures much better than I do. For years, I've kept thinking "they'll fix it" and I see that they won't. I'm not.

Thank you

**Comment by zaps166** [comment]
> As a Linux user, it's my fault for continue buying Nvidia graphic cards.

:sweat_smile: Nvidia is good on Linux for CUDA and other professional usage (e.g. Blender OptiX Cycles render) if you don't put your PC to sleep. It has also better video encoder and better error handling. That's all. All other is better in Radeon (RX 6000 series are most stable at the moment). Radeon powersaving is too aggressive by default for gaming (on some games), but it is highly configurable (e.g. in CoreCtrl application) and can save a lot of power on web browsing, etc. comparing to Nvidia. I switched to AMD and everything is better for my use-case: V-Sync, FreeSync, gaming, X11 is working better (no stuttering with V-Sync, faster Vulkan window creation, etc), better power management, easy undervolting, better suspend/resume ([but still not perfect](https://gitlab.freedesktop.org/mesa/mesa/-/issues/8676))...

**Comment by zaps166** [comment]
> I used precisely CUDA for Blender, but openSUSE repositories version have not enable GPU acceleration, so I needed to install standalone one and was really faster than CPU ;)

Yes, GPUs render faster than CPUs (usually). However Blender renders fast on Ryzen 7950X.
My BMW27 results on Blender 3.5: CPU (Ryzen 7950X) 50 sec, GPU (AMD HIP, RX 6900 XT) 20 sec :smile: 

---

Your video is [fixed](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/22485) on AMD drivers.

**Comment by zaps166** [comment]
I see one download URL here, but file no longer exist.

**Comment by zaps166** [comment]
Thanks! This video plays subtitles as `dvbsub`. The only thing I can do is to select this stream automatically instead of trying to select `dvb_teletext` which doesn't work.

**Comment by zaps166** [comment]
> Can't it be [extracted](https://trac.ffmpeg.org/wiki/ExtractSubtitles) or converted to SRT and played?

No. FFmpeg requires to be compiled with zvbi to use `dvb_teletext`. On Arch Linux FFmpeg is not compiled with it. Only custom FFmpeg compilation will allow this (e.g. AppImage or custom FFmpeg builds).

---

Compiled FFmpeg (Arch PKGBUILD + zvbi) - the `dvb_teletext` just works (maybe a little too large, but can change subtitles scale to fit on screen).

**Comment by zaps166** [comment]
> Then this issue can probably be closed if everything works correctly. Thanks.

I still don't understand what was wrong with this: https://github.com/zaps166/QMPlay2/issues/595#issue-1631214383 :sweat_smile:

**Comment by zaps166** [comment]
> Subtitles on page 150.

No chance to know on which page is it? I don't want to add UI for this (except settings which is inconvenient)...

**Comment by RafaelLinux** [comment]
> > Then this issue can probably be closed if everything works correctly. Thanks.
> 
> I still don't understand what was wrong with this: [#595 (comment)](https://github.com/zaps166/QMPlay2/issues/595#issue-1631214383) 😅

The problem is that QMPlay, when a user opens a channel with teletext, IMMEDIATELY shows teletext pages continuously without stopping and in a loop. This happens in QMPlay until the user presses the "N" key.

This behavior is not normal for a player when playing channels with teletext, not even when viewed on a SmartTV. The usual practice is for the user to enable teletext (which we have already discussed that QMPlay does not support).

Therefore, the solution would at least be NOT TO ENABLE the display of teletext data if there is any.

**Comment by zaps166** [comment]
1. Teletext contains subtitles, too.
2. Teletext is not enabled in Windows builds. AppImage, Flatpak, Arch Linux FFmpeg, so teletext is a rare case in QMPlay2.

**Comment by zaps166** [comment]
I want to make it disabled by default with possibility to select this stream and set page in settings.

**Comment by RafaelLinux** [comment]
> I want to make it disabled by default with possibility to select this stream and set page in settings.

As a exIn VLC, Teletext enabled streaming have 3 options in "Subtitles" menu: 
- "Disabled" (by default)
- "Teletext"
- "Subtitles"

![image](https://github.com/user-attachments/assets/a76e6213-2955-44e3-b2e4-3eefbb53742f)

**Comment by zaps166** [comment]
The "Disabled" in VLC is when you press "N" in QMPlay2 (deselects the "Playback->Enable subtitles").

---

After fixing this issue (current master branch), the teletext is not selected by default, so your issue will not happen anymore automatically (you have to select the teletext stream manually as in VLC). Additionally, in QMPlay2's FFmpeg module settings you can specify the teletext page (sometimes it contains subtitles).

**Comment by zaps166** [comment]
> I learned that this is the key in QMPlay2 precisely because of the chaos that happens when displaying teletext in such a strange way (visible in the video I attached as an example).

It'll not happen again with upcoming QMPlay2 release (fixed) :tada: 

> I use the one from the official openSUSE repositories, and subtitles are always disabled by default.

So how did you get  [this](https://github.com/zaps166/QMPlay2/issues/595#issue-1631214383) by default?

**Comment by RafaelLinux** [comment]
> It'll not happen again with upcoming QMPlay2 release (fixed) 🎉

THANKSSSSSS 

> So how did you get [this](https://github.com/zaps166/QMPlay2/issues/595#issue-1631214383) by default?

Before I started recording , I pressed "N" to deactivate the teletext, to clearly reflect that the overlaid text was not part of the video broadcast and to clearly understand what was happening when the subtitles were activated. I also had muted the sound, which was also not significant.

I explained how QMP2 worked in that thread, a little further down https://github.com/zaps166/QMPlay2/issues/595#issuecomment-1481931563 you probably didn't remember it ;)

**Comment by zaps166** [comment]
Ok, I couldn't reproduce, because zvbi is not used in FFmpeg in my AppImage and in Arch Linux. Now it doesn't matter - fixed in QMPlay2 :smile:

**Comment by zaps166** [comment]
> Hello @zaps166, Maybe, also add a `txt_transparent` [option](https://www.ffmpeg.org/ffmpeg-codecs.html#Options-10) to the GUI? A black background is good, but sometimes you need a transparent one. Thanks.

Yes, you can do a PR.
