### ISSUE TITLE
Configuration window remains behind main window when "Always over" is enabled (Plasma desktop)

### ISSUE THREAD

**Issue by RafaelLinux** [zaps166/QMPlay2#597]
I always enable "Always on top" feature on my video players. When I open new windows (as context menu windows) from these applications, those windows are over main video player window.

However, QMP2 configuration window opens behind main window (and should not!!).

Please, could you check it and fix?

Thank you

**Comment by DarkWav** [comment]
AFAIK I's not even exclusive to QMPlay2, e.g. the Help > Help window in VLC Media Player glitches out the exact same way for me.

**Comment by RafaelLinux** [comment]
Yes, that's how "Help" window works in VLC. But in VLC (or SMPlayer) "Preferences" window (Ctrl + P) is over VLC main window (even "About" window too). I think it's only necessary for "Options" or "Preferences" window, cause usually user need to do changes "on the fly" without leaving full screen or disabling "Always over" feature and enable it again after changes :(

**Comment by zaps166** [comment]
Works ok on xfwm4, hmm.

**Comment by DarkWav** [comment]
> Works ok on xfwm4, hmm.

Yes, xfwm4 seems to work, however, it's still broken on Kwin5 for me. Is it a KWin bug then?

**Comment by zaps166** [comment]
kwin 5.27.3

**Comment by DarkWav** [comment]
So I found out something interesting. 

- If go and tell KWin to *permanently* remember that it should keep the *entire* QMPlay2 application on top, it will work 100% fine.
- If go and tell KWin to *permanently* remember that it should keep only the "QMPlay2" window on top, it will not work at all.
- Simmilarly, if I only right click on the panel icon and check the "Always on top" checkbox temporarily, it will not work either.

Is that how it is intended to work?

**Comment by DarkWav** [comment]
I'm stuipd - I tried to set the "Always on Top" property via KWin the entire time, when I can literary set it right inside of QMPlay2 😆 in the "Window" menu.
If I use the "Always on Top" option in the "Window" menu from QMPlay2, it does work 100% fine.
Sorry for the inconvenience.

**Comment by zaps166** [comment]
Ah you're right, it works only from QMPlay2 menu. Looks like Qt is not refreshing `windowFlags()` when you do it from WM directly. I don't want to use XCB directly to check if WM set the flag properly, so let's use QMPlay2's function for now :)

**Comment by DarkWav** [comment]
@RafaelLinux I backported the fix for openSUSE Tumbleweed, the fixed version should arrive in Tumbleweed repos in 2-3 days:
https://build.opensuse.org/request/show/1075704

**Comment by RafaelLinux** [comment]
> So I found out something interesting.
> 
>     * If go and tell KWin to _permanently_ remember that it should keep the _entire_ QMPlay2 application on top, it will work 100% fine.
> 
>     * If go and tell KWin to _permanently_ remember that it should keep only the "QMPlay2" window on top, it will not work at all.
> 
>     * Simmilarly, if I only right click on the panel icon and check the "Always on top" checkbox temporarily, it will not work either.
> 
> 
> ~Is that how it is intended to work?~ I run kwin 5.27.3, too.

I was wondering why you did it that way :P   till you find there was an option in QMP2  ;)

**Comment by RafaelLinux** [comment]
> @RafaelLinux I backported the fix for openSUSE Tumbleweed, the fixed version should arrive in Tumbleweed repos in 2-3 days: https://build.opensuse.org/request/show/1075704

Great!!! That's a quick fix!!! Thank you!!

**Comment by DarkWav** [comment]
QMPlay2 `23.02.05-5.1` has landed in TW repos, it contains the fix.

**Comment by RafaelLinux** [comment]
It works!!! Curiously, now "About" window stay always behind, but it's not so important  

Thank you

**Comment by DarkWav** [comment]
I'm glad it works for you, too!
> Curiously, now "About" window stay always behind, but it's not so important

That would require more code changes from @zaps166, unfortunately.
I think it should be fine as it is now, apps like VLC also don't do it for every low-priority (e.g. "Help") window.

**Comment by zaps166** [comment]
Settings window has different parameters here than in VLC. VLC has modal window, QMPlay2 does not (intentional behavior).

> It works!!! Curiously, now "About" window stay always behind, but it's not so important

Done (for consistency).

**Comment by DarkWav** [comment]
@RafaelLinux I backported the fix for the about window as well, but it will take another 2-3 days until that arrives in repos:
https://build.opensuse.org/request/show/1076771

**Comment by RafaelLinux** [comment]
Not a priority at all, configuration it's window was really more important.
Thank you!!

**Comment by DarkWav** [comment]
Fix for the about window should have arrived in TW repos as well now (`23.02.05-6.1`).

**Comment by RafaelLinux** [comment]
It appears like QMPlay2-23.02.05-187.1.x86_64 and fixed perfectly issue!!!

Thank you again!!!
