### ISSUE TITLE
MyFreeMP3: Something happening - No results at all

### ISSUE THREAD

**Issue by RafaelLinux** [zaps166/QMPlay2#598]
Hi!!

Don't know why, but just today MyFreeMp3 search is not giving results. However, at console, in each new search, it shows:
`[31 mar 2023 00:29:50.522] MediaBrowser: file:040-MyFreeMP3.js:58 SyntaxError: JSON.parse: Parse error`

Is it an external issue???

Thanks

**Comment by zaps166** [comment]
I need to update the script again

**Comment by RafaelLinux** [comment]
I was wondering it ... more tasks ... sorry :(

**Comment by RafaelLinux** [comment]
Thanks zaps166!!!
