### ISSUE TITLE
[Feature request] Load external subtitles that are in sub-directories

### ISSUE THREAD

**Issue by Yasand123** [zaps166/QMPlay2#599]
At least by default, external subs are only loaded when they're in the same directory as the video being played. I looked in the settings for an option to enable parsing through sub-directories but it seems there's no option for it.

I'm not sure if this is already implemented, but if not I think it would be a nice addition to this awesome media player. This is mainly useful for organization purposes. It's especially needed on Linux for obvious reasons.

Thank you

**Comment by zaps166** [comment]
Hi, could you give more details about directory hierarchy? For example I can't recursively search for subtitles :smile:

**Comment by Yasand123** [comment]
> Hi, could you give more details about directory hierarchy? For example I can't recursively search for subtitles smile

Hey! Of course. Something like this:
```
Root folder/
├─ Episode 1.mp4
├─ Episode 2.mp4
├─ Subtitles/
│  ├─ Episode 1.srt
│  ├─ Episode 2.ass
```
So just 1 level deep, not recursively. The point is not to "search", the point is to read from a predetermined sub-directory that contains the subtitle files.

Mpv has this feature and it allows you to add multiple patterns for possible folder names: `sub-file-paths=ass:srt:sub:Sub:subs:Subs:subtitles:Subtitles` -- This means any sub folder with any of these names will be searched for subtitles.

You could allow us to add such patterns manually, or you could simply use this list in the example as I think it covers the possible names people would typically use.

**Comment by zaps166** [comment]
Done!

**Comment by Yasand123** [comment]
That was crazy fast 👀 Tysm!
