### ISSUE TITLE
Opensubtitles.org

### ISSUE THREAD

**Issue by procobain** [zaps166/QMPlay2#600]
Hi, I saw that you answered another request about creating an opensubtitles.org download tool, but that was in 2018, I believe I forgot, and with only a single request, it gets even more discouraging, right?

So, lo and behold, in 2023 we completed two requests to create an opensubtitles.org download tool.

My absolute favorite player is yours, but when I have to download subtitles, it messes me up a bit, hugs...

**Comment by zaps166** [comment]
Relates to #162

**Comment by zaps166** [comment]
Full downloader or just shortcut which will redirect you to website with video name?
