### ISSUE TITLE
How to watch rtsp links?

### ISSUE THREAD

**Issue by procobain** [zaps166/QMPlay2#601]
How to watch rtsp links? I create files in .strm format and put the rtsp line like this:

rtsp://MYUSER:MYPASSWORD@192.168.1.150:554/cam/realmonitor?channel=1&subtype=1

But I can't get it, any ideas?

**Comment by procobain** [comment]
I managed to watch the rtsp, but just opening it with the shortcut ctrl + U, I would like to create a shortcut on the desktop as if it were a regular file, double click and watch, does anyone know how to do this?

**Comment by zaps166** [comment]
Hi, you can create a playlist (`.pls` file) which is associated with QMPlay2:

```
[playlist]
NumberOfEntries=1
File1=rtsp://MYUSER:MYPASSWORD@192.168.1.150:554/cam/realmonitor?channel=1&subtype=1
```
