### ISSUE TITLE
Subtitle settings are confusing/not working as intended

### ISSUE THREAD

**Issue by Yasand123** [zaps166/QMPlay2#603]
Hello!

I have been messing with the subtitle settings for the last couple days but for some reason it's not working as one would expect and/or it's somewhat bugged? I will list the issues separately so it's easier to follow/reference.

### A) Font size for subtitles is not consistent across different videos, if `Fonts and spacing` is checked
If I wanted to change the fonttype (ex. from default to Tahoma) I pick it from the drop-down menu at the very top, and check both `Apply for ASS/SSA subtitles` and `Fonts and spacing`.

While it affects the font type, this makes the subtitles way too small, so I increase the font size at the top to around 90. This works nicely for that specific video, but in other videos the subtitles would be way too large at the same font size. So I either get too large or too small depending on the video, and I'd have to keep changing it in the settings.

What's the difference between these videos? Well, there are 2 possibilities, first, embedded vs external, I noticed embedded subtitles would look too small at 30 for example, while external ones look just fine.
Another possibility is the file type, embedded subs are usually ssa, while external ones ass. I doubt this is the issue however, since I tried one external ssa file after converting it.

A way to get around this is to de-couple "size" and "font type" so size would have its own checkbox.`Fonts and spacing` should not include font the size setting imo.

However, some might want to change the size as well, so fixing the core issue is needed here.

### B) If `Margin and alignment` is checked, text on signs, episodes titles, etc, are moved to the bottom
These aren't dialogue subtitles, they're purposefully not at the bottom. These are usually on top of the original text on street signs, or next to the episode title.

This setting if checked turns these into regular subtitles. I think what happens here is that when the setting is checked QMPlay2 does 2 things, first reset the position and 2nd apply the new values. So that means even these are reset into the position of regular dialogue subtitles.

Maybe there's a way to exclude these? I don't know. But mpv somehow does it. Perhaps there's a specific flag in the subtitle file for these? Maybe if the subtitle line has a custom position that usually means you shouldn't mess with it? It's an interesting problem but I think the idea of making an exception for these lines is a good start.

### C) Finally, this is more of a feature request, missing "Bold" option
This is needed because not all fonts have bold variant that is selectable from menus

I apologize if this is long, but I wanted to include details as they might be useful in debugging.
Thank you for your time, and for this awesome media player!

**Comment by zaps166** [comment]
Do you apply everything to ASS subtitles only? It's mostly for SRT and other simple formats. ASS has their own style, QMPlay2 can override some of them, but not all. Overridden ASS styles will not display as in style.

There's too much text without examples :sweat_smile: I need sample file and settings which doesn't work (I don't use "Apply for ASS/SSA subtitles" because it's pointless for most ASS subs).

**Comment by zaps166** [comment]
Hmm, tested it briefly now with regular subtitles. Idk what spacing is doing (don't remember, can't see any difference). When changing alignment I have to restart video to apply on all texts.

---

Could you upload screenshot what's exactly wrong? Do you use Shift+R / Shift+T to scale subtitles without touching these settings?

**Comment by zaps166** [comment]
If Shift+R / Shift+T doesn't work, it means your subtitles are bitmap subtitles (pgssub, dvdsub, etc.) - settings from "Subtitles" tab doesn't apply there.

> it's a normal sub file embedded in the movie I'm watching right now not an ass or some other pgssub.

Hmm, could you put screenshot of Information panel (at least Subtitles streams)?

**Comment by zaps166** [comment]
I can see names: `jacosub`, `xsub`, `dvbsub`, `pgssub`, `mpsub` when grepping FFmpeg code, can't find just `sub` codec name...

> I'll upload whatever information you want in the morning.

Ok! Also if possible - URL where can I download sample file (can be send via email).

**Comment by zaps166** [comment]
Well, `dvdsub` are not text subtitles, they're bitmap subtitles. Scaling is not supported, so it's rather a feature request.

**Comment by zaps166** [comment]
They are scaling with video only, so need to handle scaling subtitles, too.

**Comment by zaps166** [comment]
I'll add scaling of bitmap subs for next version.

**Comment by zaps166** [comment]
> Finally, this is more of a feature request, missing "Bold" option

Added.

**Comment by zaps166** [comment]
> Idk what spacing is doing (don't remember, can't see any difference).

Fixed (typo in settings access...).

**Comment by zaps166** [comment]
> Font size for subtitles is not consistent across different videos, if Fonts and spacing is checked

Maybe will be better now!

> If Margin and alignment is checked, text on signs, episodes titles, etc, are moved to the bottom

Fixed!

**Comment by zaps166** [comment]
Is it working correctly now? :smile:
