### ISSUE TITLE
Make vaapi glx support optional at compile time.

### ISSUE THREAD

**Issue by DarkDefender** [zaps166/QMPlay2#604]
Hello!
As most vaapi applications now seem to prefer EGL, I helped out with the removal of the vaapi GLX backend for Gentoo.
However some users poked me and reported that QMPlay2 still requires GLX support at compile time.

As the preferred backend here also is EGL, I solved this issue temporary by removing the GLX module from the build scripts:
https://905453.bugs.gentoo.org/attachment.cgi?id=861121

However I'm guessing that here in upstream this might not be the preferred solution.
So my question before I open up a pull request, is if removal is preferred or if I should simply make it optional by splitting the `pkg_check_modules` into two where the GLX module check is allowed to fail.

**Comment by zaps166** [comment]
`libva-glx` is not needed, can be removed

**Comment by DarkDefender** [comment]
Awesome, thank you! :)
