### ISSUE TITLE
Can't use Wayland if Vulkan is merely installed

### ISSUE THREAD

**Issue by IslandC0der** [zaps166/QMPlay2#611]
Due to 75730d9, xcb is forced just because Vulkan exists on the system, even if it isn't being used as the renderer. This causes a variety of graphical glitches, especially when using fractional scaling, as well as decreased performance.
Instead, I suggest disabling the Vulkan renderer option when using Wayland: users could still use Vulkan if they don't mind the tradeoff, simply by launching the application with xcb.
Alternatively, we could still force xcb automatically, but only when the Vulkan backend is actually enabled, not if it's merely available.
Both options would still prevent #566.

**Comment by zaps166** [comment]
> Alternatively, we could still force xcb automatically, but only when the Vulkan backend is actually enabled, not if it's merely available.

This is more complicated, first option sounds better.

> as well as decreased performance.

QMPlay2 with OpenGL on Wayland uses RTT to prevent issues with docking native windows on Wayland (QtWidgets itself probably, too, but don't remember), which is not optimized on Qt's side (for both CPU and GPU). With XCB, OpenGL is running directly on window. Are you sure about it?

**Comment by IslandC0der** [comment]
> This is more complicated, first option sounds better.

I could be missing something here, but wouldn't it be as simple as toggling XCB on _only_ when the user enables Vulkan in Renderer Settings -> Renderer? Perhaps also prompting for an application restart.

> QMPlay2 with OpenGL on Wayland uses RTT to prevent issues with docking native windows on Wayland (QtWidgets itself probably, too, but don't remember), which is not optimized on Qt's side (for both CPU and GPU). With XCB, OpenGL is running directly on window. Are you sure about it?

I haven't done any exhaustive testing, but I've noticed that when using QMPlay2 with VA-API and OpenGL on Wayland,  both the `Video` and `Render/3D` engines are being used when probing with `intel-gpu-top`; whereas in XCB, the whole load goes to `Render/3D`, which suggests the hardware video decoder isn't being used properly.

**Comment by zaps166** [comment]
Vulkan on Wayland with Qt6 (tested on 6.5.1) will work properly.

**Comment by zaps166** [comment]
> QMPlay2 with OpenGL on Wayland uses RTT to prevent issues with docking native windows on Wayland

Fixed, obsolete info.
