### ISSUE TITLE
Youtube Subscription

### ISSUE THREAD

**Issue by parduspanteri** [zaps166/QMPlay2#612]
Can you add a feature,  we can track our youtube subscriptions?

**Comment by zaps166** [comment]
You can try new option to import cookies from browser which allows you to open content allowed on your account:

![Zrzut ekranu_20241211_085737](https://github.com/user-attachments/assets/cdc0cf72-7063-43bf-8f75-ddb427b8d9ab)

---

YouTube subscription plan here - I don't know, I don't use official API for YouTube, so for now - not.
