### ISSUE TITLE
Youtube live video

### ISSUE THREAD

**Issue by GHbasicuser** [zaps166/QMPlay2#614]
Hello,

I have a problem to report since the last update (23.06.04), I can no longer play live video channels on Youtube, ie: 

- France Info : https://www.youtube.com/watch?v=gxG3pdKvlIs  or https://www.youtube.com/c/franceinfo/live
- France 24 : https://youtu.be/gxG3pdKvlIs or https://www.youtube.com/watch?v=gxG3pdKvlIs
- Euronews : https://www.youtube.com/watch?v=NiRIbKwAejk
- Sky News: https://www.youtube.com/watch?v=9Auq9mYxFEE

I use these links with the "Internet radios" widget, and when they work I very often get interruptions during playback. Isn't there a way to fix this ? 😐

Thank you very much 🙂

**Comment by zaps166** [comment]
Caused by 11e491356900d633d25fb12494a6fb827e9214cf

**Comment by zaps166** [comment]
Fixed: e1dfb228d10a7d79072e4d2f8c18eba92168abeb

Idk why GitHub can't link issue with a commit :thinking: 

Thanks for the bug report! Are you able to test it?

**Comment by GHbasicuser** [comment]
Thanks for the fix and your responsiveness ! 🙂

But sorry, I don't have the right environment to compile and run these tests at the moment. 

For the playback problem with these Live videos, is there a setting that can be made so that the playback is smooth for a long time ? (even if it means lowering the resolution of the video being played)

I don't know if the problem really comes from the "buffer"... The speed of my internet connection isn't great (less than 1 MB/s) but in general playback from the Youtube site goes well... it's with QMPlay2 that there are regular interruptions.. perhaps Youtube doesn't encourage playback via external applications. 🤔

In any case, thanks for the fix, I'll test it in the next version. 😉

**Comment by zaps166** [comment]
> is there a setting that can be made so that the playback is smooth for a long time ? (even if it means lowering the resolution of the video being played)

Yes. In YouTube tab, click the second icon and choose the lowest and (re)start YouTube playback. It should play in 480p.

> less than 1 MB/s

1MB/s or 1Mb/s? The 480p stream of link you provided me is about 1Mb/s (about 0.125MB/s).

> But sorry, I don't have the right environment to compile and run these tests at the moment.

If Windows I can build it quickly :smile:

**Comment by GHbasicuser** [comment]
>Yes. In YouTube tab, click the second icon and choose the lowest and (re)start YouTube playback. It should play in 480p.
>1MB/s or 1Mb/s? The 480p stream of link you provided me is about 1Mb/s (about 0.125MB/s).

1MB/s. (On Youtube, I don't usually have any problems playing Full HD videos.)

Here I had set it to 1080p, I'm going to test 720p. But I'd almost forgotten that I also have this problem with other Live video sources, like this local TV channel which isn't in very high resolution (720p) but which freezes (very) regularly with QMPlay2 : 
- https://streamtv.cdn.dvmr.fr/TVR/ngrp:tvr.stream_all/master.m3u8

For your tests, this is perhaps the most interesting link. 

I had also tested different settings in the "Playback setting" more than a year ago, but it hadn't improved anything. 😑

![](https://i.postimg.cc/G2kv4Hzm/qmplay2-buffer-01.jpg)

>If Windows I can build it quickly 😄

Yes, currently under Windows. 😅

Thank you very much !

**Comment by zaps166** [comment]
One problem can be due to QMPlay2 buffering is not very good for HLS. It can be easily workarounded by pausing for a few seconds (let it wait for next chunk of data). But the real problem is that I've got:
```
[mpegts @ 0x7f546025d840] PES packet size mismatch
[mpegts @ 0x7f546025d840] Packet corrupt (stream = 1, dts = 2446612096).
[hls @ 0x7f5468002b40] Packet corrupt (stream = 1, dts = 2446608496).
```
which destroys the playback completely making video to freeze and audio skips, too.

**Comment by zaps166** [comment]
I've made some fixes, it should freeze less and shorter, but packet corrupt still happens even if I change user agent. It happens also in `ffmpeg` command line and in MPV, but didn't happen (so far) in `ffplay` tool, strange...

QMPlay2 now respects "Start playback internet stream if it's buffered" for HLS streams.

[Here](https://drive.google.com/file/d/13UCjitdXZWESDoU-oBxQcRn2Pq4R1s3N/view) is the fixed unofficial release to test :slightly_smiling_face:

**Comment by zaps166** [comment]
> Try to automatically reconnect live streams on error

I does nothing here. I've checked many FFmpeg's HTTP/HLS options for this stream and nothing helped :disappointed: Other software has the same issue as QMPlay2 (which relies on FFmpeg: MPV, `ffmpeg` and `ffplay` command line tools). I think FFmpeg is doing something wrong with some HLS streams like TVR or this stream is weird and needs special handling :smile:

**Comment by GHbasicuser** [comment]
Thank you very much for your time and the fix. 🙂  

I don't know if this will lead to the beginning of a "solution" (for Live videos) but the "-re" parameter ("Read input at native frame rate") seems to have a positive impact when I test it this way :
`ffmpeg -fflags +discardcorrupt -re -i https://streamtv.cdn.dvmr.fr/TVR/ngrp:tvr.stream_all/master.m3u8 -c copy "d:\output.mp4"`

Without this "-re" parameter I have quite a few "PES packet size mismatches" and none when I use it... (on a few 3-5 minute tests)

(https://stackoverflow.com/questions/48479141/understanding-ffmpeg-re-parameter)

There may be a link with the speed at which ffmpeg retrieves the stream. 😐

**Comment by zaps166** [comment]
Maybe that's why reproducing the issue on `ffplay` is much harder than on `ffmpeg` or QMPlay2. `-re` seems to be a workaround to improve stability of the stream, because FFmpeg waits for the next HLS chunk in `av_read_frame`, hmm. Maybe server doesn't like opening most recent chunk too early?

**Comment by zaps166** [comment]
It's working when I set "Network buffer size (A/V packet count)" to 125 :sweat_smile: 
Maybe I should enforce small values to HLS...?

**Comment by GHbasicuser** [comment]
Yes, it seems to work on my side too by setting the "Network buffer size (A/V packet count)" to a small value. 😀

I made 2 tests of 10 mn, because the one at 125 presented errors (6:39 -> 7:10, 7:19 -> 7:30, 8:09 -> 8:20, 9:59 -> 10:10), for the second one I set to 100 and everything seemed OK. 🧐

Yesterday I did a quick test of other hls (French) TV streams, which had the same problem as TVR. I couldn't find the source of the list I downloaded yesterday, but I did find something equivalent that might interest you for testing : https://iptv-org.github.io/

**Comment by zaps166** [comment]
> Edit : The problems reappeared with "NBS" set to 100 after 25-30 min... it's probably not the right setting yet.

It can appear, but it's rare comparing to default settings, right?

---

I'll change how QMPlay2 buffers data - packets are useless, better to set seconds in UI and split live streams and networks known-length streams.

**Comment by zaps166** [comment]
Could you test [this](https://drive.google.com/file/d/16w7lxqTVlSAt7yzXFsTonM91gGly27ik/view?usp=sharing)?

**Comment by GHbasicuser** [comment]
>It can appear, but it's rare comparing to default settings, right?

Yes, it's much (much) better 😄, but it's strange that the cuts frequently come back after ~25mn (with TVR). 🤔

1st test of ~33mn with "NBS" set to 100 and TVR : 
25:11->25:30
30:59->31:02
31:29->32:00
32:09->32:20
32:59->33:10

2nd test of ~40mn with TVR and QMPlay2 "hls beta 2" :
24:59->25:10
25:19->23:31
25:59->26:10
32:59->33:10
33:29->33:50
34:19->34:30
35:09->35:20
25:49->36:00
38:39->39:00

Another link that might be interesting to follow, this time in full HD, with QMPlay2 "hls beta 2" it doesn't work well, with FFplay (or FFmpeg with "-re") it looks fine 😐 :
- TF1 : https://live-tf1-hls-dai.cdn-1.diff.tf1.fr/out/v1/c2e382be3aa2486e8753747e7bb6157e/index.m3u8

**Comment by zaps166** [comment]
How about https://live-tf1-hls-dai.cdn-1.diff.tf1.fr/out/v1/c2e382be3aa2486e8753747e7bb6157e/index.m3u8 in previous versions of QMPlay2?
Btw. unfortunately this stream contains a few other streams with different video sizes, but all are downloaded, one is played :disappointed:

**Comment by GHbasicuser** [comment]
It was (quite) similar. There are indeed several streams. 😕 (contrary to what I thought, the one taken into account is probably not full HD).

But this latest version of QMPlay2 is already a nice improvement 🙂👍, and for most of the hls links I watch from time to time, it looks good. 🧐

I've rediscovered the page with downloadable IPTV channel lists (by country, language, etc.) 😅 :  
- https://mawuen.github.io/2020/05/12/regardez-plus-de-8000-chaines-tele-dans-votre-lecteur-video/

**Comment by zaps166** [comment]
Fixed, now QMPlay2 should download only selected streams, [download link](https://drive.google.com/file/d/13ldRKKGbV_1pYw3-lv0gGgq2z5jPAtSn/view?usp=sharing) (except first chunk on open).

**Comment by GHbasicuser** [comment]
It's great to be able to choose the stream when the broadcaster offers this choice. 🙂

Unfortunately, with TF1, whatever the stream (even low quality, ie 416x234px), the buffer (set to 5 sec) fills up and empties almost as quickly, and the video freezes while the buffer fills up again... 😕 (https://i.postimg.cc/v80jnmWG/2023-06-12.png)

**Comment by zaps166** [comment]
>  The resolution is not shown in the menu

Yes :sweat_smile:

> Unfortunately, with TF1, whatever the stream (even low quality, ie 416x234px), the buffer (set to 5 sec) fills up and empties almost as quickly, and the video freezes while the buffer fills up again...

How long did you wait? First chunk is downloaded for all streams, later it should download only selected. Wait a bit longer. Could you also test with D3D11VA or software decoder? For me your link plays smoothly.

**Comment by GHbasicuser** [comment]
I had anticipated your request 😅... I've tried lots of buffer settings and also tested Cuvid/FFmpeg D3D11VA/FFmpeg decoders... but alas, nothing better on any setting. 😐

In my tests (lasting several minutes), the 5s buffer (or whatever its value is) only fills up, empties (with almost no attempt to fill it up) and once at 0, fills up only to empty again... the video is impossible to follow.  (a sample : https://www.sendspace.com/file/1ydokn)
I just tried again (1280x720px + FFmpeg D3D11VA) : I get 15s of video then ~10s of cut, the video resumes for ~15s, then stops for ~10s, resumes for 15s then overlaps for 10s, and it keeps repeating. 
>For me your link plays smoothly.

I get (fairly) smooth playback with FFplay (or FFmpeg + "-re") but not with QMPlay2... it's rather odd. 🤔

**Comment by zaps166** [comment]
Ye, I've added a condition after my tests which was not tested and it's not working now :sweat_smile:

**Comment by zaps166** [comment]
Try [this](https://drive.google.com/file/d/1QkiGzCK0-4MSd8MSrG7y8hZK50DwZ5MR/view?usp=sharing) :smile:

**Comment by GHbasicuser** [comment]
I'll try to test more tomorrow (with other channels, etc), but right now it works great with TF1 (10mn test)! Well done ! 😀👍

**Comment by GHbasicuser** [comment]
I've run a few more tests. 😅 (essentially with TF1 + TVR)

Yesterday evening I noticed problems again in the first few minutes with TVR (including 1 very long freeze shortly after launch, and 1 that hadn't stopped after 2 minutes) + a few cuts (of 10s) with TF1 at various times (but rare). 😐

Then I had the idea of testing another "decoder", I switched from "CUVID" (which I had been using until then) to "FFmpeg D3D11VA / Vulkan" and since then I've noticed no problems (except possible oversights) over long periods (30mn to 1h !). 😄

I don't know if there really is a link, but seeing nothing negative in the use of "FFmpeg D3D11VA", I'm going to continue with the latter as everything now seems to work fine. 😎🤞

Thanks again for this new version of QMPlay2 !!! 😀

_Ideas for a future version 😜 :_ 
- _an easy-to-access button for recording a stream during playback._ 
- _create a "IPTV" module using the https://iptv-org.github.io/ source. (like the "Internet Radios" module using Radio-Browser)_ 
  - https://github.com/iptv-org/
  - https://mawuen.github.io/2020/05/12/regardez-plus-de-8000-chaines-tele-dans-votre-lecteur-video/

**Comment by zaps166** [comment]
> an easy-to-access button for recording a stream during playback.

It was requested already. Maybe I'll add it in the future :smile: For now use "Download". It's almost the same, but it opens another connection to the server.

---

> Thanks again for this new version of QMPlay2 !!! :grinning:

:smile: :tada: 

> I don't know if there really is a link, but seeing nothing negative in the use of "FFmpeg D3D11VA"

D3d11VA should be better and more stable, speed is similar (both performs one copy in GPU memory, unfortunately). I'll remove CUVID, but don't know when yet :smile: CUVID is more bugged and old. Nvidia has new NVDEC API, supperted by FFmpeg, maybe I'll add it. However Vulkan is now adding HW decoding via Vulkan, it should be the best (I hope)!

**Comment by GHbasicuser** [comment]
Thank you ! 😄🎉

Perhaps other interesting links to look at as the problems may be related to the number of frames per second 🧐 (FFplay is also struggling to keep up with my internet connection) :

- France2: http://livetv.ktv.zone/4/play.m3u8 -> the buffer empties faster than it fills up. After 5s, everything is paused until it fills up again, and then it starts all over again... (but it's full HD)
- TF1: http://livetv.ktv.zone/3/play.m3u8 (idem)
- LCI: http://livetv.ktv.zone/28/play.m3u8 -> problems with interlacing that I "solved" by unchecking "Video filters -> double the numbers of reams per second".

I don't know the service used to broadcast these channels, but depending on the day (especially in the evening) the flow seems to be disrupted, which must explain most of the outages for LCI (not HD).

**Comment by zaps166** [comment]
> http://livetv.ktv.zone/4/play.m3u8

This stream is corrupted, it can't play on any player on CPU and GPU. Moreover corrupted H264 data crashes AMD driver on hardware decoding on Linux :rofl: VLC and QMPlay2:

```
amdgpu 0000:03:00.0: amdgpu: [mmhub] page fault (src_id:0 ring:24 vmid:5 pasid:32783, for process vlc pid 4485 thread vlc:cs0 pid 4500)
amdgpu 0000:03:00.0: amdgpu:   in page starting at address 0x000080010bbfb000 from client 0x12 (VMC)
amdgpu 0000:03:00.0: amdgpu: MMVM_L2_PROTECTION_FAULT_STATUS:0x00501A31
amdgpu 0000:03:00.0: amdgpu: 	 Faulty UTCL2 client ID: VCN1 (0xd)
amdgpu 0000:03:00.0: amdgpu: 	 MORE_FAULTS: 0x1
amdgpu 0000:03:00.0: amdgpu: 	 WALKER_ERROR: 0x0
amdgpu 0000:03:00.0: amdgpu: 	 PERMISSION_FAULTS: 0x3
amdgpu 0000:03:00.0: amdgpu: 	 MAPPING_ERROR: 0x0
amdgpu 0000:03:00.0: amdgpu: 	 RW: 0x0
amdgpu 0000:03:00.0: amdgpu: [mmhub] page fault (src_id:0 ring:24 vmid:5 pasid:32783, for process vlc pid 4485 thread vlc:cs0 pid 4500)
amdgpu 0000:03:00.0: amdgpu:   in page starting at address 0x000080010bbf8000 from client 0x12 (VMC)
amdgpu 0000:03:00.0: amdgpu: MMVM_L2_PROTECTION_FAULT_STATUS:0x00000000
amdgpu 0000:03:00.0: amdgpu: 	 Faulty UTCL2 client ID: unknown (0x0)
amdgpu 0000:03:00.0: amdgpu: 	 MORE_FAULTS: 0x0
amdgpu 0000:03:00.0: amdgpu: 	 WALKER_ERROR: 0x0
amdgpu 0000:03:00.0: amdgpu: 	 PERMISSION_FAULTS: 0x0
amdgpu 0000:03:00.0: amdgpu: 	 MAPPING_ERROR: 0x0
amdgpu 0000:03:00.0: amdgpu: 	 RW: 0x0
```

```
amdgpu 0000:03:00.0: amdgpu: [mmhub] page fault (src_id:0 ring:24 vmid:1 pasid:32782, for process QMPlay2 pid 3276 thread QMPlay2:cs0 pid 3293)
amdgpu 0000:03:00.0: amdgpu:   in page starting at address 0x0000800106ff8000 from client 0x12 (VMC)
amdgpu 0000:03:00.0: amdgpu: MMVM_L2_PROTECTION_FAULT_STATUS:0x00105631
amdgpu 0000:03:00.0: amdgpu: 	 Faulty UTCL2 client ID: VCN0 (0x2b)
amdgpu 0000:03:00.0: amdgpu: 	 MORE_FAULTS: 0x1
amdgpu 0000:03:00.0: amdgpu: 	 WALKER_ERROR: 0x0
amdgpu 0000:03:00.0: amdgpu: 	 PERMISSION_FAULTS: 0x3
amdgpu 0000:03:00.0: amdgpu: 	 MAPPING_ERROR: 0x0
amdgpu 0000:03:00.0: amdgpu: 	 RW: 0x0
amdgpu 0000:03:00.0: amdgpu: [mmhub] page fault (src_id:0 ring:24 vmid:1 pasid:32782, for process QMPlay2 pid 3276 thread QMPlay2:cs0 pid 3293)
amdgpu 0000:03:00.0: amdgpu:   in page starting at address 0x0000800106ffb000 from client 0x12 (VMC)
amdgpu 0000:03:00.0: amdgpu: MMVM_L2_PROTECTION_FAULT_STATUS:0x00000000
amdgpu 0000:03:00.0: amdgpu: 	 Faulty UTCL2 client ID: unknown (0x0)
amdgpu 0000:03:00.0: amdgpu: 	 MORE_FAULTS: 0x0
amdgpu 0000:03:00.0: amdgpu: 	 WALKER_ERROR: 0x0
amdgpu 0000:03:00.0: amdgpu: 	 PERMISSION_FAULTS: 0x0
amdgpu 0000:03:00.0: amdgpu: 	 MAPPING_ERROR: 0x0
amdgpu 0000:03:00.0: amdgpu: 	 RW: 0x0
amdgpu 0000:03:00.0: amdgpu: [mmhub] page fault (src_id:0 ring:24 vmid:1 pasid:32782, for process QMPlay2 pid 3276 thread QMPlay2:cs0 pid 3293)
amdgpu 0000:03:00.0: amdgpu:   in page starting at address 0x0000800106fff000 from client 0x12 (VMC)
amdgpu 0000:03:00.0: amdgpu: MMVM_L2_PROTECTION_FAULT_STATUS:0x00000000
amdgpu 0000:03:00.0: amdgpu: 	 Faulty UTCL2 client ID: unknown (0x0)
amdgpu 0000:03:00.0: amdgpu: 	 MORE_FAULTS: 0x0
amdgpu 0000:03:00.0: amdgpu: 	 WALKER_ERROR: 0x0
amdgpu 0000:03:00.0: amdgpu: 	 PERMISSION_FAULTS: 0x0
amdgpu 0000:03:00.0: amdgpu: 	 MAPPING_ERROR: 0x0
amdgpu 0000:03:00.0: amdgpu: 	 RW: 0x0
amdgpu 0000:03:00.0: amdgpu: [mmhub] page fault (src_id:0 ring:24 vmid:1 pasid:32782, for process QMPlay2 pid 3276 thread QMPlay2:cs0 pid 3293)
amdgpu 0000:03:00.0: amdgpu:   in page starting at address 0x0000800106ffb000 from client 0x12 (VMC)
amdgpu 0000:03:00.0: amdgpu: MMVM_L2_PROTECTION_FAULT_STATUS:0x00000000
amdgpu 0000:03:00.0: amdgpu: 	 Faulty UTCL2 client ID: unknown (0x0)
amdgpu 0000:03:00.0: amdgpu: 	 MORE_FAULTS: 0x0
amdgpu 0000:03:00.0: amdgpu: 	 WALKER_ERROR: 0x0
amdgpu 0000:03:00.0: amdgpu: 	 PERMISSION_FAULTS: 0x0
amdgpu 0000:03:00.0: amdgpu: 	 MAPPING_ERROR: 0x0
amdgpu 0000:03:00.0: amdgpu: 	 RW: 0x0
amdgpu 0000:03:00.0: amdgpu: [mmhub] page fault (src_id:0 ring:24 vmid:1 pasid:32782, for process QMPlay2 pid 3276 thread QMPlay2:cs0 pid 3293)
amdgpu 0000:03:00.0: amdgpu:   in page starting at address 0x0000800106ffc000 from client 0x12 (VMC)
amdgpu 0000:03:00.0: amdgpu: MMVM_L2_PROTECTION_FAULT_STATUS:0x00000000
amdgpu 0000:03:00.0: amdgpu: 	 Faulty UTCL2 client ID: unknown (0x0)
amdgpu 0000:03:00.0: amdgpu: 	 MORE_FAULTS: 0x0
amdgpu 0000:03:00.0: amdgpu: 	 WALKER_ERROR: 0x0
amdgpu 0000:03:00.0: amdgpu: 	 PERMISSION_FAULTS: 0x0
amdgpu 0000:03:00.0: amdgpu: 	 MAPPING_ERROR: 0x0
amdgpu 0000:03:00.0: amdgpu: 	 RW: 0x0
amdgpu 0000:03:00.0: amdgpu: [mmhub] page fault (src_id:0 ring:24 vmid:1 pasid:32782, for process QMPlay2 pid 3276 thread QMPlay2:cs0 pid 3293)
amdgpu 0000:03:00.0: amdgpu:   in page starting at address 0x0000800106ff8000 from client 0x12 (VMC)
amdgpu 0000:03:00.0: amdgpu: MMVM_L2_PROTECTION_FAULT_STATUS:0x00000000
amdgpu 0000:03:00.0: amdgpu: 	 Faulty UTCL2 client ID: unknown (0x0)
amdgpu 0000:03:00.0: amdgpu: 	 MORE_FAULTS: 0x0
amdgpu 0000:03:00.0: amdgpu: 	 WALKER_ERROR: 0x0
amdgpu 0000:03:00.0: amdgpu: 	 PERMISSION_FAULTS: 0x0
amdgpu 0000:03:00.0: amdgpu: 	 MAPPING_ERROR: 0x0
amdgpu 0000:03:00.0: amdgpu: 	 RW: 0x0
[drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring vcn_dec_0 timeout, signaled seq=144, emitted seq=146
[drm:amdgpu_job_timedout [amdgpu]] *ERROR* Process information: process QMPlay2 pid 3276 thread QMPlay2:cs0 pid 3293
```

I think I should capture this stream and report a bug in Mesa.

**Comment by zaps166** [comment]
> http://livetv.ktv.zone/3/play.m3u8

Also doesn't play, corrupted H264 data

> http://livetv.ktv.zone/28/play.m3u8

Also doesn't play, corrupted H264 data. What about the interlacing? Double the framerate is better, why it fixes your problem?

**Comment by zaps166** [comment]
I need working interlaced stream to check it. If it's interlaced, with doubling the framerate you should achieve TV-like 50Hz framerate (it's much more smooth) if you have 50 Hz monitor or you have enabled FreeSync/GSync :smile: 

Thanks for corrupted streams, I've already reported AMD bug :smile:

**Comment by GHbasicuser** [comment]
These regional TV channels seem to work and use interleaving 🧐 : 
- http://livetv.ktv.zone/216/play.m3u8
- http://livetv.ktv.zone/227/play.m3u8
- http://livetv.ktv.zone/226/play.m3u8

When the options indicated above are active (at least the doubling of the lines) I have constant interruptions... in 25i/s it's (much) better (although the speeds are a bit high for my connection, there are interruptions but they seem to be more linked to a buffer problem. 🤔)

**Comment by zaps166** [comment]
Tried all 3 streams: no issues with 50 FPS - with FreeSync smooth as in real TV :grin: 
Do you still use CUVID? Can you check: CUVID, D3D11VA and software decoder? Restore interlacing settings on video filters tab to default first. Could you check these options (in all combinations)? First option should work for software decoder, second for CUVID. On D3D11VA both should not make a difference.
![Screenshot_20230615_191438](https://github.com/zaps166/QMPlay2/assets/6239090/8ca5ea4a-5d4a-4b92-8f6e-3eecab360910)

**Comment by GHbasicuser** [comment]
I stopped using Cuvid a few days ago and switched to "FFmpeg/D3D11VA, Vulkan (D3D11VA)". 😉

The "Force Vulkan Yadif deinterlacing for all hardware decoders" option seems to have had a positive impact on stability at 50i/s. 🙂 

Now what's affecting good stream playback is the buffer, which empties without really trying to fill up; it only fills up once it's empty and the video is stopped for ~10s. 😐

Tests over 2 minutes (all options active, 50i/s, etc):
- With Cuvid: cuts out at around 30s then 1mn05s then ~1mn40s ( + sound sync problem after 1mnxxs) 
- With D3D11VA: cut-off around 30s, then 1mn05s, then 1mn39s and after that it didn't recover well. 
- With FFmpeg (vulkan active): cut-off around 32s, then 1mn08s, then 1mn50s... didn't seem to recover well afterwards.  

Now in 50i/s or 25i/s it seems quite similar, the buffer problem is present in both cases, followed by a more or less good recovery (sound sync, number of frames/s indicated).

I noticed that as the 2-minute test approached, recovery was getting worse and worse, and was no longer possible (with 14i/s for example, as opposed to a relatively stable 50i/s previously).

I'd overlooked the "Force Vulkan Yadif deinterlacing for all hardware decoders" option, thanks for the info ! 🙂

**Comment by zaps166** [comment]
> "Force Vulkan Yadif deinterlacing for all hardware decoders"

It shouldn't make any difference on D3D11VA.

---

If decoder produces corrupted frames with wrong timestamps, doubling the frame rate might have issues, because it will not know which time stamp should the new frame have.

No issues on Linux, but stream is sometimes corrupted on Windows, just like it can't properly download the data :rofl:

**Comment by GHbasicuser** [comment]
I think most of my tests last night were with D3D11VA, but I may be wrong. Disabling 50i/s seemed very effective (over 2-3 tests) with the LCI channel ("ktv.zone" version), which isn't HD and didn't have (too) many buffer problems (if none).. if I remember correctly. 😐 (I can't try again tonight, the channel is completely unresponsive. 😂)

Now with the 3 regional channels in full HD (interlaced), it seems mainly a buffer problem... (also linked with the speed and/or quality of my internet connection 😕)
