### ISSUE TITLE
Provide universal/apple silicon support dmg

### ISSUE THREAD

**Issue by superusercode** [zaps166/QMPlay2#617]
Current dmg prompts for rosetta on apple silicon macs

**Comment by zaps166** [comment]
Because Qt6 (which supports ARM there) is not yet deployed on macOS

**Comment by zaps166** [comment]
Qt6 support on Linux was added recently. Later will be macOS.

**Comment by RJVB** [comment]
I'm pretty certain you can find a Qt5 version supporting Apple silicon in MacPorts.

**Comment by RJVB** [comment]
>Maybe, but it's still a lot of work to prepare it. Qt6 shouldn't be a problem, because QMPlay2 already supports it.

Is it? That's a rhetorical question, I'm not going to buy a silicon Mac just to see for myself ;)

NB: Qt are very quick in dropping older OS support, so please don't drop Qt5 support (I'm already backporting to Qt 5.9 ...)

>Btw. I'm curious if MoltenVK can handle Vulkan in QMPlay2 :grin: 

I would expect so, if you don't do anything outside of Qt's Vulkan glue and that isn't supported...

**Comment by zaps166** [comment]
> so please don't drop Qt5 support (I'm already backporting to Qt 5.9 ...)

I still support 5.10. 5.9 requires code changes, yes. I will not drop Qt 5 for very long time (Qt6 doesn't work on Windows 7 AFAIK). I can drop all older than 5.15.2 later, but not very soon ofc :smile: Also Qt5 works better for me now with QMPlay2, especially Qt 6.5 which is doing something wrong with styles on inactive windows.

Isn't it possible to compile 5.10.x on your macOS somehow? And isn't it possible to upgrade macOS?

> I'm not going to buy a silicon Mac just to see for myself ;)

I have access to such machines, so I can test, but I have to build it from my PC, so I have to prepare new VM and compile universal binaries.  I already compiled universal binaries for ARM+x64, so I know what to do, but I have to do it for QMPlay2 now... :sweat_smile:

> I would expect so, if you don't do anything outside of Qt's Vulkan glue and that isn't supported...

And if Qt will not do anything wrong as it does sometimes :rofl:

**Comment by RJVB** [comment]
>Isn't it possible to compile 5.10.x on your macOS somehow?

I have already done that backporting for 5.9, which didn't really make me very eager to repeat the endeavour.

>And isn't it possible to upgrade macOS?

Oh, yes, to 10.13 on my hardware, or even 10.15 with a bunch of hacks. But I still remember how much time it took to get 10.9 to work the way *I* want after upgrading from 10.6 (which I did in a Paragon VM because I had a license for that). I have this stupid little premonition that my Mac will die just about when I finally have everything as well as possible the way I want it... ;)

>And if Qt will not do anything wrong as it does sometimes :rofl: 

There's that...

**Comment by zaps166** [comment]
I hope it's working, tested once when I had access to Arm64 machine.
