### ISSUE TITLE
Combined streaming separate video and audio links

### ISSUE THREAD

**Issue by RJVB** [zaps166/QMPlay2#621]
It'd be nice to be able to specify separate links for streamed audio and video content, for instance to watch content from arte.tv

E.g. https://www.arte.tv/fr/videos/076591-003-F/cuisines-des-terroirs/
->
https://arte-cmafhls.akamaized.net/am/cmaf/076000/076500/076591-003-F/230526071128/medias/076591-003-F_v1080.m3u8
https://arte-cmafhls.akamaized.net/am/cmaf/076000/076500/076591-003-F/230526071128/medias/076591-003-F_aud_VF-FRA_3.m3u8

**Comment by zaps166** [comment]
Just add: `FFmpeg://{[https://arte-cmafhls.akamaized.net/am/cmaf/076000/076500/076591-003-F/230526071128/medias/076591-003-F_v1080.m3u8][https://arte-cmafhls.akamaized.net/am/cmaf/076000/076500/076591-003-F/230526071128/medias/076591-003-F_aud_VF-FRA_3.m3u8]}` :grin:

**Comment by RJVB** [comment]
Magic!

(I knew there had to be some incantation already ;) )

**Comment by zaps166** [comment]
Easier way (don't have to remember syntax): Choose `FFmpeg` and add `[https://arte-cmafhls.akamaized.net/am/cmaf/076000/076500/076591-003-F/230526071128/medias/076591-003-F_v1080.m3u8][https://arte-cmafhls.akamaized.net/am/cmaf/076000/076500/076591-003-F/230526071128/medias/076591-003-F_aud_VF-FRA_3.m3u8]`.

---

You can combine any streams, but results might not be good for all possibilities :smile:

**Comment by RJVB** [comment]
>You can combine any streams, but results might not be good for all possibilities :smile: 

You can simulate LSD then, playing back audio as video or vice versa? :))

**Comment by zaps166** [comment]
>> You can combine any streams, but results might not be good for all possibilities 😄

> You can simulate LSD then, playing back audio as video or vice versa? :))

Audio is audio, video is video, but you can mix local audio with youtube video, etc :stuck_out_tongue: 

If you want to see audio: https://www.youtube.com/watch?v=ECLWihsF_PA - nice to have osciloscope for this :smile:  ([this](https://github.com/zaps166/DSPBlocks) might handle it, too :smile: )
