### ISSUE TITLE
Play streaming videos from russian sites ok.ru/video and rutube.ru and video.sibnet.ru

### ISSUE THREAD

**Issue by trimechee** [zaps166/QMPlay2#629]
Hello, yt-dlp support the russain sites ok.ru/video and rutube.ru and video.sibnet.ru, we hope our beloved QMPLAY2 will be able to play video drom these important popular sites, thank you so much !

i have idea : may be QMPLAY2 could download in background temporarily a small part of the streaming video then delete it when you leave the media player, thank you!, thank you !

https://ok.ru/video/529769433747

https://rutube.ru/video/c71a722e6f74234eba54043ca507572b/

https://video.sibnet.ru/video5128213-Dead_Mount_Death_Play_01_VF/?utm_source=player&utm_medium=video&utm_campaign=EMBED

**Comment by zaps166** [comment]
Hi!

Add->Address (Ctrl+U), choose youtube-dl and paste URL to the website with a video :smile:

**Comment by trimechee** [comment]
Yes ! I remember THAT IHAVE doing that but if my memory IS right, I couldn't play the videos from the russian sites.....I don't know, maybe because my graphics card is old and dated from 6 years ago....I will try with the new version of QMPLAY2 and i will try to disable hardware acceleration  :)

**Comment by trimechee** [comment]
Hello @zaps166 , i tried with the last version of  QMPLAY2 and last version of yt-dlp to play videos from ok.ru/video and rutube.ru but QMPLAY2 says that it can"t play the video.s...i tried with smplayer and mpc -qt in windows 10 and i can play videos from ok.ru and rutube, we hope there will be a fix, thank you :)

**Comment by zaps166** [comment]
Do you paste URL as youtube-dl? ![Screenshot_20230717_220552](https://github.com/zaps166/QMPlay2/assets/6239090/ead220b4-0380-4890-83c6-204011569768)

**Comment by trimechee** [comment]
No ! i didn't know that there s all these options ! i play video with "auto detect address" ! I just tried it and it works perfectly! QMPLAY2 can play Russian sites ok.ru and rutube .ru! this is very awesome beautiful wonderful, thank you so much ! 🥇 💯 


I just tried it and it works perfectly! QMPLAY2 can read Russian sites ok.ru and rutube .ru! this is stunningly beautiful, thank you so much!

I have a question please, I see 'youtube-dl' in playback options and not 'yt-dlp', does QMPLAY2 use youtube -dl or yt-dlp? and I think it will be great if QMPLAY2 uses yt-dlp by default and not auto detect address....


I also noticed directx and cuvid are enabled by default so hardware decoding is enabled by default in mods section while in QMPLAY2 description, QMPLAY2 says "Hardware acceleration is disabled by default", so please how can we easily disable hardware acceleration? Thanks again for this wonderful great media player :)

**Comment by zaps166** [comment]
Use Vulkan if it's working on your PC. For hardware acceleration on Windows try D3D11VA. If it's working, you'll see `Vulkan (D3D11VA)` in information panel.

**Comment by trimechee** [comment]
Great awesome !! Thank you so much for your precious help :) 💯 🥇
