### ISSUE TITLE
Volume Normalization?

### ISSUE THREAD

**Issue by Chromace** [zaps166/QMPlay2#63]
It would be nice if QMPlay2 had the ability to use audio normalization (i.e. making quiet parts louder, louder parts quieter).

This would allow for listening to media files with a high variation of dynamics without having to adjust the media player's volume manually (e.g. action movies, classical music, etc.), or listening to multiple media files which all have different levels of dynamics from each other.

**Comment by zaps166** [comment]
Does e.g. "Dyson Compressor" LADSPA plugin will be enough ?

**Comment by Chromace** [comment]
That should be fine :)

**Comment by zaps166** [comment]
I've got Dyson Compressor code on my local GIT repo, currently it needs refactoring, fixing, etc. If you want to test, I can push it :)

**Comment by Chromace** [comment]
It's alright - please take your time, thank-you :)

**Comment by zaps166** [comment]
Done, check the "AudioFilters" settings page :)

**Comment by Chromace** [comment]
Thank-you! :smile:

Do you know what the different compressor options do?

**Comment by zaps166** [comment]
These four options in AudioFilters settings? Ah it doesn't have a description :D First is max peak in percent (similar to volume), second is hard to say for me, but I can notice the minor difference... (see ladspa description), third and fourth are compretion ratio (according to labels - fast and overal) - compress more or less. Set two last sliders to max to get maximum level of effect. This is not my algorithm, I've never written compressor before, so I don't know details :D

**Comment by Chromace** [comment]
That's alright - I should be able to test it out.

Thank-you! ^^
