### ISSUE TITLE
in "QMPlay2" not work "CUDA"  ( CUVID decoder )

### ISSUE THREAD

**Issue by n0bzeR** [zaps166/QMPlay2#634]
From what I know for sure, on this version "CUDA" works
QMPlay2-22.10.23-1-x86_64 (its .appimage version)

On latest version not work.
- Just black screen  (not see video, but see decoder usage cuda, and hear audio)
video card is : nvidia gtx 570

**Comment by zaps166** [comment]
OpenGL, right?

**Comment by n0bzeR** [comment]
> OpenGL, right?

Yes, OpenGL
Just no have video. black screen.

**Comment by n0bzeR** [comment]
> OpenGL, right?

in Windows TOO not work CUDA with latest version ; (
Can fix it? Wanna use CUDA CORE`s on my GPU

**Comment by zaps166** [comment]
I have to check it on different PC, I no longer have Nvidia on my main PC.

> Wanna use CUDA CORE`s on my GPU

CUVID uses CUDA API, but video is decoding on Nvidia's video decoder, not CUDA cores, same as DXVA2 and D3D11VA.

**Comment by n0bzeR** [comment]
> I have to check it on different PC, I no longer have Nvidia on my main PC.
> 
> > Wanna use CUDA CORE`s on my GPU
> 
> CUVID uses CUDA API, but video is decoding on Nvidia's video decoder, not CUDA cores, same as DXVA2 and D3D11VA and VDPAU.

Okay, im wait fix CUVID decoder, for old nvidia card (pss, my video card have driver 390 - its maximum for gtx 570)

It turns out that the cuda decoder is not used even when it is written that it is used ?
There is no action of cuda cores?
I was always sure that by activating the cuda decoder, I would activate it.
It turns out that it was all a lie?

**Comment by n0bzeR** [comment]
> I have to check it on different PC, I no longer have Nvidia on my main PC.
> 
> > Wanna use CUDA CORE`s on my GPU
> 
> CUVID uses CUDA API, but video is decoding on Nvidia's video decoder, not CUDA cores, same as DXVA2 and D3D11VA and VDPAU.

![Screqenshot_2023-07-29_02-14-05](https://github.com/zaps166/QMPlay2/assets/104155535/37bcbac0-7128-4dca-94d6-fbd6e57ee303)

But, CUVID decoder work on " XVideo ".. Why only on that cuda not have black screen ? What a Bugged? What damaged?

**Comment by zaps166** [comment]
Using it outside opengl and vulkan is copying the data to host memory and uploading again to gpu memory. Very inefficient, might be sometimes slower than CPU decoding.

**Comment by zaps166** [comment]
I can confirm the issue, I'll fix it.
