### ISSUE TITLE
no video playback on intel gpu / opensuse leap 42.2

### ISSUE THREAD

**Issue by ahjolinna** [zaps166/QMPlay2#64]
I installed the recently arrived [openSUSE leap 42.2](https://news.opensuse.org/2016/11/16/optimal-release-for-linux-professionals-arrives-with-opensuse-leap-42-2/) -KDE on my old [Acer Aspire S7 191](http://www.linlap.com/acer_aspire_s7-191) ultrabook, and when I tried for example this [k-pop youtube video](https://www.youtube.com/watch?v=yghPuQnny24) (using youtube-dl in the player) I only got audio and no video playback, and if downloaded the video nothing happens and it won't play it at all.
I tried many different settings and nothing helped, and I didn't see any errors when I run it in gdb

-----
I'm using the packman (community) repo version, currently the version is 16.11.01-1.1
it also installed some QMPlay2-kde-integration pkgs?

**Comment by ahjolinna** [comment]
seems to be a opensuse problem...or intel...or both, because VLC or bomi-player doesn't work either

**Comment by zaps166** [comment]
`QMPlay2-kde-integration` is only a shortcut for AudioCD.
Also openSUSE doesn't have some codecs, use QMPlay2 and FFmpeg from [packman repository](http://packman.links2linux.org/mirrors).

**Comment by ahjolinna** [comment]
well I did install the ffmpeg 3.1.3-3-1 from packman now and some missing codecs I found, and for some reason ffmpeg wasn't installed at all :S ?! but it still doesn't work..sigh... I wonder what codec's are needed? I don't know who maintains the pkgs in packman but it would be nice if the pkgs would include all the needed codec pkgs

**Comment by ahjolinna** [comment]
I haven't used opensuse in years so I cant remember if there is somekind of multimedia metapkgs that would install all this (1-click install?)

**Comment by ahjolinna** [comment]
okay now it works, when I installed the ffmpeg (packman version) it seems it didn't install/upgrade all the codecs that was in packman repo, I so I had to do zypper dup so it would change all the pre-installed codecs to the packman version...sigh, fuck how hard can these simple stuff be -_-
