### ISSUE TITLE
Program Doesn't Start, Affects Performance Poorly

### ISSUE THREAD

**Issue by fosforoglu** [zaps166/QMPlay2#642]
Although I have been using the player for a long time, there was nothing wrong with it until a couple of months ago. I don't know if it is something about an update, but all of a sudden, I can not open the program (the interface does not appear at all). When I check the task manager, it is shown in the background processes with a high CPU usage (maybe it is normal but %10 seems high to me). What is stranger is that trying to open it affects my computers performance so much so that even my keyboard inputs become lagged, everything slows down until I stop the process in task manager. 
Below you can see task manager. 

![image](https://github.com/zaps166/QMPlay2/assets/93059423/52658aea-1608-4e7f-bfa1-3933aed03cd6)

**Comment by zaps166** [comment]
@fosforoglu Is it working?

**Comment by zaps166** [comment]
Please check the 23.08.08 version and re-open this issue if it still can't run.

**Comment by fosforoglu** [comment]
I checked it and it works nicely so far. Thanks for the replies.

Błażej Szczygieł ***@***.***>, 8 Ağu 2023 Sal, 18:18
tarihinde şunu yazdı:
