### ISSUE TITLE
[BUG]: With some videos, only red channel is visible

### ISSUE THREAD

**Issue by RafaelLinux** [zaps166/QMPlay2#644]
Since a month or two ago (I guess after an update) some videos only show the red channel (as seen in the screenshot). I've tried switching from Vulkan to XRender, but that doesn't solve the problem. Everything I've tried, fails to fix it.

I thought it was with some formats or codecs, but I can't find any relation. In fact, in one of these videos that is not seen correctly, when moving with the left-right slider, suddenly, it was seen correctly, but when closing and reopening, again the same problem.
I attached a video with this issue (cropped by size limit reasons).

![imagen](https://github.com/zaps166/QMPlay2/assets/13048959/1f5f4552-b89f-43ba-8931-eda9bbb01e14)

https://github.com/zaps166/QMPlay2/assets/13048959/0daa42cf-7adf-4b30-939c-9d8b7097a5b9

**Comment by zaps166** [comment]
Could you give more info (hw accel, ffmpeg version, QMPlay2 version, are you able to play it on older QMPlay2 version, is it AppImage, etc.)? Does the MP4 from GitHub (download it) plays incorrectly to you?

**Comment by RafaelLinux** [comment]
QMPlay2: lastest version (and tried as you suggested with older version, QMPlay2-21.12.24-1-x86_64)
Kdenlive: 23.04.3
MLT: 7.16.0
Qt: 5.15.10 (built against 5.15.10 x86_64-little_endian-lp64)
Frameworks: 5.108.0
System: openSUSE Tumbleweed
Kernel: linux 6.4.6-1-default
CPU: x86_64
ffmpeg: 6.0

Tested downloaded video (maybe you suggested cause can be recoded) and same result. Only red channel.
However, Firefox (like VLC) shows video correctly.

I even tried disabling "Use GPU deinterlacing for CPU ..." and and interchanging QPainter to XVideo  but same result.
Changing Vulkan to OpenGL results in a black image. Legacy, works (I could let it, but I think performance could be lower).

After a lot of changes, I find out what's not working well in my configuration: In "Options, Play values" under "Decoders priority" if I choose "FFmpeg VA-API decoder", the issue appears. If I chosse "FFmpeg dedocer" or "CUVID decoder", issue is gone.

```
~> vainfo
Trying display: wayland
Trying display: x11
libva info: VA-API version 1.19.0
libva info: User environment variable requested driver 'nvidia'
libva info: Trying to open /usr/lib64/dri/nvidia_drv_video.so
libva info: Found init function __vaDriverInit_1_0
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.19 (libva 2.19.0)
vainfo: Driver version: VA-API NVDEC driver [direct backend]
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain12             : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD

```

So, I think issue is related to non-offical VA-API [nvidia-vaapi-driver](https://github.com/elFarto/nvidia-vaapi-driver) driver for Nvidia cards I installed some months ago. Maybe I should ask developer about it. As your software is (luckily) so so flexible, after I installed that driver, I changed to it in QMPlay2, but as only some videos are affected, I didn't noticed why that happened.

Maybe I should notify it to that driver developer.

**Comment by zaps166** [comment]
> Maybe I should notify it to that driver developer.

Yes :slightly_smiling_face: 

Btw. are you able to reproduce the issue in Firefox with VA-API enabled (use EGL in Firefox + enable `media.ffmpeg.vaapi.enabled`)?

**Comment by RafaelLinux** [comment]
It's enabled (I enabled it after install the driver) but no issues, but I would bet that Firefox is not using it (at least for this video) cause when I play it, `nvtop` only shows CPU load increase to 20%, not GPU, despite I configured all things I read was neccesary to enable it in Firefox using VA-API.

![imagen](https://github.com/zaps166/QMPlay2/assets/13048959/a90a8dbf-87ab-48a0-84b3-f3b0dc444a9d)

In fact, I have all this modified:
    • gfx.webrender.all → true  (WebRender)
    • layers.acceleration.force-enabled → true (OpenGL)
    • media.ffmpeg.vaapi.enabled → true
    • media.ffmpeg.vaapi-drm-display.enabled →  true  (doesn't exist, must be created)
    • media.ffvpx.enabled → false
    • media.av1.enabled → false
    • media.rdd-vpx.enabled → false
    • media.navigator.mediadatadecoder_vpx_enabled → true
