### ISSUE TITLE
[FR] Add an option to disable cover arts caching

### ISSUE THREAD

**Issue by Realex-fire** [zaps166/QMPlay2#645]
Hello,
Please consider adding an option to disable caching of cover arts while still being able to view them, including from LastFM (e.g. In `DemuxerThr::updateCover`, perhaps you can simply set the save condition to a file). At the moment, all cached covers are stored in the  "Covers" folder and can only be cleared manually.

Thanks.

**Comment by zaps166** [comment]
In General settings there's a button "Clear covers cache".

**Comment by zaps166** [comment]
Is a hidden setting in INI file better?

**Comment by zaps166** [comment]
Added to `QMPlay2.ini` file.
