### ISSUE TITLE
where to find webradio station list

### ISSUE THREAD

**Issue by ahahahaah** [zaps166/QMPlay2#649]
hello
just installed qmplay2 to use it as a radio application, but when i clic the radios tab, there is no prelist.
where to find a qmplay2radio compatible list?
thanks

**Comment by zaps166** [comment]
Write a name in search bar and press enter. No prelist so far.

**Comment by ahahahaah** [comment]
> Write a name in search bar and press enter. No prelist so far.

OMG!!! THANK YOU SIR!!
i had a headache, and were frustrated to have nothing :p
