### ISSUE TITLE
in the radio list when you  increase the size of a column, then the name/icon column is shrinked and you cant resize it

### ISSUE THREAD

**Issue by ahahahaah** [zaps166/QMPlay2#651]
i mean, if for example i enlarge the "tags" column then the "country" and "stream info" columns keep the same size but not the "name" column which is automatically shrinked.
the horizontal bar doesn't help, and even if you try to resize the "name" column with your mouse (**after** it is automatically shrinked) then it doesnt work also.
so i wonder why other columns are not automatically resized whereas the "name" column size changes automatically and we can't "control" it
![image](https://github.com/zaps166/QMPlay2/assets/69671446/d431cee2-b44c-43ee-8a59-c59a035d02c9)
i don't know if you see what i mean.

**Comment by zaps166** [comment]
I'll try to improve it

**Comment by ahahahaah** [comment]
> I'll try to improve it

thanks :D
