### ISSUE TITLE
QMPlay2 can not open video files named in Arabic

### ISSUE THREAD

**Issue by 0azizi0** [zaps166/QMPlay2#655]
The videos will not work unless renamed in English. Also the Arabic names will not show in the playlist. I use Linux on x86-64 processor.

**Comment by zaps166** [comment]
Could you give me example file name which doesn't work?

**Comment by zaps166** [comment]
I tested random Arabic text found in Google, set as file name and song title - I don't have any issue with this. Do you use AppImage from my GitHub?

**Comment by zaps166** [comment]
I used your file name and QMPlay2 AppImage - it works to me.

**Comment by zaps166** [comment]
Good to hear it's working there! I also use Manjaro.

Maybe check your `/etc/locale.gen` and run `sudo locale-gen` and/or try to install some other fonts?
