### ISSUE TITLE
Impossible to play videos from https://my.mail.ru/video 

### ISSUE THREAD

**Issue by trimechee** [zaps166/QMPlay2#657]
Hello, I use the last version of QMPLAY2 and last version of yt-dlp, and sadly i can't play video from this important and famous streaming website, we hope our beloved QMPLAY2 will fix it, thank you so much ! 

https://my.mail.ru/v/sienduk/video/35/707.html

**Comment by trimechee** [comment]
Yes ! Thank you @parkerlreed :) I have tried with mpc be, mpc hc, mpc qt, moon player, smplayer and this video doesn't play....


I remember that I spoke to the developer of Grid player who solved the problem, but yt-dlp and streamlink seem to be out of date, which is why I am currently looking for another media player that can play videos from Russian sites. ..

so I tried "3DYD Youtube Source" with mpc-be and potplayer while disabling yt-dlp in the media players to avoid any conflicts and it works,

https://ys.3dyd.com/home/


but we hope our beloved QMPLAY2 which has so many rare and unique revolutionary features and we prefer to use it will be able to find a solution to play videos from this Russian site please which hosts a lot of streaming videos this is why we like to use a media player to see these videos without the need for a web browser which can be heavy....
the magnificent QMPLAY2 can play videos from the Russian sites like rutube.ru, and ok.ru and we hope it will also be able to play videos from this site, thank you very much !

**Comment by trimechee** [comment]
Hello @parkerlreed I have idea, QMPLAY2 is capable of downloading videos, so when there is a playback problem with a streaming site supported by yt-dlp, for greater speed and simplicity, especially since using yt-dlp on the command line is difficult and complicated to choose the video quality for example,  it will be great if QMPLAY2 will be able to download the video in the background and then play it automatically, so what do you think  Mr @parkerlreed ? Is it technically possible ?

**Comment by zaps166** [comment]
@trimechee Are you able to compile and test?

**Comment by trimechee** [comment]
Excuse me Mr @zaps166 , I don't konw any thing about compiling because I am not developer :( 

but what i can confirm is a lot of media players which can use yt-dlp like moon player, kikoplay, smplayer, mpc qt.....can't play videos from mail. ru, i have may be solution, see the source code or contact the developer of the magnificent GridPlayer which can play mail.ru videos, because I contacted him last year and he solved the problem and we can watch the videos from https://my.mail.ru/video with GridPlayer, and also with using "3DYD Youtube Source" with mpc-be mpc-hc and potplayer, so maybe the wonderful Grid Player developer Mr vzhd1701 could help !

https://github.com/vzhd1701/gridplayer/issues/54

https://ys.3dyd.com/

**Comment by trimechee** [comment]
It's strange, I'm almost certain I made an issue about the version of yt-dlp used in QMPLAYR2 but the issue disappeared....

so I ask the question again please: is it possible that QMPLAYR2 uses the 64bits version of yt-dlp and not the yt-dlp_x86 version ?

**Comment by zaps166** [comment]
> It's strange, I'm almost certain I made an issue about the version of yt-dlp used in QMPLAYR2 but the issue disappeared....
> 
> so I ask the question again please: is it possible that QMPLAYR2 uses the 64bits version of yt-dlp and not the yt-dlp_x86 version ? @zaps166

Done.

**Comment by zaps166** [comment]
New version is released, could you confirm it's working now?

**Comment by trimechee** [comment]
Ohh totally incredible sensational titanic revolutionary! the video works perfectly! which makes our beloved QMPLAYER2 the most powerful media player in the whole world! 💯 🥇 

 it is indisputable!

We are very grateful to you for all your hard work in inventing and developing and continuing to improve this magnificent media player, an exceptional jewel of technology ! Thank you so much Mr @zaps166
