### ISSUE TITLE
Difference between the "video" widget and the shortcut "o" which disable video

### ISSUE THREAD

**Issue by trimechee** [zaps166/QMPlay2#659]
Hello, when I sleep, I like to listen to YouTube video and I like to listen just to the audio dash without decoding the video part to save the battery, and I noticed that when you disagree the "video" widget, the video disappears But does this option just hide the video or also deactivates video decoding? And what is the difference between deactivating the "Video" widget and clicking on the "O" key that also disable the video or the 2 options are the same ? Thank you !

**Comment by zaps166** [comment]
You should use "O" key - it doesn't decode video and (if possible) doesn't download it.

---

You shouldn't close the Video widget - video is still downloaded and decoded, but not displayed. The widget will appear again on next video play (depends on settings "Automatically open video window"). Closing it can be useful to music-only profile.

---

How to check it? On "Information" panel you can see video stream underlined with decoder information - it means video is decoded. If it's not underlined and doesn't have decoder information - it's not decoded (and not downloaded if possible).

**Comment by trimechee** [comment]
Ohh very very interesting and instructive ! Thank you so much for your precious advices Mr @zaps166 :) 💯
