### ISSUE TITLE
inode/directory

### ISSUE THREAD

**Issue by Chamrosh** [zaps166/QMPlay2#66]
Please delete "inode/directory" of Mimetype in QMPlay2_enqueue.desktop and QMPlay2.desktop

This is an additional option and unworkable

**Comment by zaps166** [comment]
For me it works fine and it is convenient especially for `QMPlay2.desktop`:
![inode/directory](https://cloud.githubusercontent.com/assets/6239090/20647362/10d67168-b493-11e6-83bf-13a60b543621.png)
Kaffeine also has this feature.

Does it cause any problems, on which desktop?

**Comment by Chamrosh** [comment]
I've installed elementary os
In the pantheon does not work and when I use, tries to open the files irrelevant even Pictures

**Comment by zaps166** [comment]
> In the pantheon does not work and when I use

I can't see any problems on Elementary OS. Directories are open using "Files" by default, additionally I can load directory with music or videos in QMPlay2 using popup context menu (works properly).

> tries to open the files irrelevant even Pictures

If you have problems with default file browser (the OS shouldn't change the default after installing a new software), go to system settings and set "Files" as a default directory browser.

![spectacle m17532](https://cloud.githubusercontent.com/assets/6239090/20648925/aef8cdf8-b4b3-11e6-97f8-dc5c37806333.png)

**Comment by zaps166** [comment]
I assume that everything work now properly :)
