### ISSUE TITLE
yt-dlp failing

### ISSUE THREAD

**Issue by ben2talk** [zaps166/QMPlay2#661]
![dl-youtube](https://github.com/zaps166/QMPlay2/assets/6983154/0ceef29b-12a5-463d-ac11-cda575971ee5)
![Error](https://github.com/zaps166/QMPlay2/assets/6983154/6f480aac-bf27-457d-b0c1-117c23add878)

Browsing the Youtube tab, juz trying to grab a video brings a fair wait (assuming that yt-dlp is doing it's thing) and then a useless dialog window.

There's no issue doing this via Youtube, grabbing the url and using it directly in yt-dlp though.

**Comment by zaps166** [comment]
No problem in QMPlay2 either, also Manjaro: ![Screenshot_20231014_101948](https://github.com/zaps166/QMPlay2/assets/6239090/342a3df1-4ebc-4bd4-9eba-3b8ddfc2671d)

**Comment by ben2talk** [comment]
https://i.imgur.com/XkArXGu.png

**Comment by zaps166** [comment]
Can't reproduce, please reopen if issue still happens.
