### ISSUE TITLE
Full dark mode theme even in the top bar

### ISSUE THREAD

**Issue by trimechee** [zaps166/QMPlay2#665]
Hello, thank you fir the new amazing awesome version of QMPLAY2 media player ! 

I have request please : dark theme helps preserve energy and our eyes by minimizing blue light, that's why I enabled dark mode in our beloved QMPLAY2, and I notice the top bar remains white despite it being the dark mode theme, we hope that QMPLAY2 will adopt full dark mode even in the top bar, thank you very much !

We also hope that the space in the middle of QMPLAY2 when the media player is idle will also be completely dark without a logo, thank you ! 
![Capture](https://github.com/zaps166/QMPlay2/assets/76402212/7b84a1bb-45f6-4a1d-8b48-6021a3b258ce)

**Comment by zaps166** [comment]
> eyes by minimizing blue light

I guess it's Windows - reduce blue light in Windows display settings :slightly_smiling_face:

---

It'll be changed in next release (only for main window), but as temporary solution, edit `qt.conf` file which is in QMPlay2 installation directory and replace:
`WindowsArguments = fontengine=freetype` 
to:
 `WindowsArguments = fontengine=freetype,darkmode=1`

**Comment by trimechee** [comment]
Great ! Thank you so much @zaps166 :) yesss it's windows haha 👍
