### ISSUE TITLE
Changing volume control while a video is playing crashes app

### ISSUE THREAD

**Issue by kenmays** [zaps166/QMPlay2#669]
QMPlay2 23.10.22 crashes if changing volume control while a video is playing. Doesn't crash if changing volume control and video not playing. No application crash when tested with QMPLay2 22.08.21.

Tested platform: Haiku R1B4 x86_64 w/ QMPlay2 23.10.22.

Error:
```
terminate called after throwing an instance of 'std::system_error'
  what(): Resource deadlock
Abort
```

**Comment by zaps166** [comment]
Strange, nothing changed about volume. Can you use debugger and show where it crashes?
It shows OSD in video, cold you try to zoom in/out video to see if it display OSD properly?

**Comment by zaps166** [comment]
Aaah now I noticed it's 22 not 23. Please show me backtrace.

**Comment by kenmays** [comment]
I noticed a difference between the releases. I ran a video with subtitles enabled. 
1. QMPlay2 22.08.21 - play video without issue.
2. QMPlay2 23.10.22 - crashes when video is about to display subtitles and no audio.

When I disabled subtitles:
Result: QMPlay2 23.10.22 - plays video without audio issues. Still crashes if video control is clicked.

I ran strace and Debugger. Will review further.

**Comment by zaps166** [comment]
Hmm, I didn't touch Haiku code except whitespace and `NULL`->`nullptr` changes. Also I don't have Haiku to test it.

You can catch the exception in debugger and see where the deadlock happen.

**Comment by kenmays** [comment]
Note: This issue has something to do with QMPlay2 libass interaction on Haiku. I traced it back to the QMPlay2 22.10.23.
I've attach the Haiku build file showing previous code build of libass 0.17.1 with QMPlay 22.10.23 before QMPlay2 23.02.05.

[qmplay2-22.10.23_libass-0.17.1_haiku.txt](https://github.com/zaps166/QMPlay2/files/13335918/qmplay2-22.10.23_libass-0.17.1_haiku.txt)

**Comment by zaps166** [comment]
Do you use Vulkan or OpenGL for testing?

**Comment by kenmays** [comment]
We use OpenGL. I enabled OpenGL which ran a little slower in video playback due to OpenGL software rendering. No other issues.
Runs A/V optimal with no other issues otherwise.

**Comment by zaps166** [comment]
Software Vulkan (mesa's lavapipe) should perform better than Software OpenGL in QMPlay2. Also subtitles works differently with Vulkan - maybne worth to try?

Is libass working stable with other software?

**Comment by kenmays** [comment]
OK. I switched to Vulkan which seems smoother. No major issues. I'll research the libass issue a bit - possibly Haiku specific.

**Comment by zaps166** [comment]
Good that Vulkan is working better.

But strange issue with libass. I'm aware it'a s lot of work, but yould you find which commit caused this issue with libass?

**Comment by kenmays** [comment]
Reviewing: https://github.com/zaps166/QMPlay2/commit/0c9cd8d433645049c75b23faa975e20799efae1d
- "Improve ASS subtitles sync"
 
I think the new code commit tickles a resource deadlock mutex handling condition on Haiku R1B4.  I'll research it more when time permits as I think this a Haiku R1B4 issue - not QMPlay2 22.10.23 at the moment.

**Comment by kenmays** [comment]
1. I noticed the other players did'n;t show the subtitles o this test file.
2. Using Haiku's Debugger/gdb, QMPlay2 shows the initial subtitle line, then there is a A/V sync break in which the audio track still plays fine but the video frame iis locked showing the video display and initial subtitle line. (i.e. this is the point of error). Application seems fine (i.e. video bitrate/buffer status info is progressing) until you try to use GUI menu commands.

**Comment by zaps166** [comment]
Could you send the test file? Or it happen on any video files?

**Comment by kenmays** [comment]
Test file: https://youtu.be/mPnl1aazs98?si=JNJALp1NJaUJT0hH

**Comment by zaps166** [comment]
Hmm, this video doesn't have subtitles, only auto-generated which doesn't work in QMPlay2. How do you see subtitles there?

**Comment by kenmays** [comment]
Ok. The subtitles for this video was something that appeared and worked  using the older QMPlay2. I'll upload a snapshot.
.

**Comment by zaps166** [comment]
I don't have any idea so far...

**Comment by kenmays** [comment]
@zaps166 - We can close for now. The feature is not of high use yet on Haiku. Otherwise, QMPlay2 seems stable on Haiku. Thanks.
