### ISSUE TITLE
Radio Station Icons Missing

### ISSUE THREAD

**Issue by ehamminga** [zaps166/QMPlay2#671]
Version QMPlay2-Win64-23.10.22-portable

When searching for radio stations I noticed that some of them have their icons missing even though they show up correctly at radio-browser.info. 

For instance, when searching in QMPlay2 for "FIP Metal", no icon shows, while radio-browser shows 2 matches, both with their respective icons, one in png format and the other in webp. Hitting the search button a few times in QMPlay2 does however render the png icon for one of the results, but this happens intermittently. When hitting the search button a few times again, the png icon dissapears again.

**Comment by zaps166** [comment]
This is the Radio Browser problem, same in Firefox when hitting F5: https://www.radio-browser.info/search?page=1&order=clickcount&reverse=true&hidebroken=true&name=fip%20metal
