### ISSUE TITLE
FFmpeg 4 build broken

### ISSUE THREAD

**Issue by RJVB** [zaps166/QMPlay2#677]
https://github.com/zaps166/QMPlay2/blob/41da371d47099cd486c748887826489456ee20ab/src/modules/FFmpeg/FormatContext.cpp#L366

This call (introduced in #d58ce60d35097663d1901f375643201554f5b5e9) breaks the build against FFmpeg 4.4 .

It looks like the commit above only introduces support for tags not supported before, correct?

I'd really like to see FFmpeg 4 continue to be supported because in my testing it is significantly faster than 6.1.1 on my Linux rig. Getting a good 2x parsing+decoding speed-up for relevant videos vs. just over 1.5x represents enough of a safety margin for not dropping frames when actually rendering the content.

**Comment by RJVB** [comment]
With this patch it builds but I have no test case:

```
diff --git a/src/modules/FFmpeg/FormatContext.cpp b/src/modules/FFmpeg/FormatContext.cpp
index a5c45496..8e14b5d8 100644
--- a/src/modules/FFmpeg/FormatContext.cpp
+++ b/src/modules/FFmpeg/FormatContext.cpp
@@ -363,7 +363,11 @@ QList<QMPlay2Tag> FormatContext::tags() const
         else
         {
             // check for all fields starting with "lyrics-" because libavformat's ID3v2 code adds lyric fields like that
+#if LIBAVUTIL_VERSION_MAJOR >= 58
             for (const AVDictionaryEntry *avTag = av_dict_iterate(dict, nullptr); avTag; avTag = av_dict_iterate(dict, avTag))
+#else
+            for (const AVDictionaryEntry *avTag = av_dict_get(dict, "", nullptr, AV_DICT_IGNORE_SUFFIX); avTag; avTag = av_dict_get(dict, "", avTag, AV_DICT_IGNORE_SUFFIX))
+#endif
             {
                 if (!std::strncmp(avTag->key, "lyrics-", sizeof("lyrics-")) && !(value = getTag(avTag)).isEmpty())
                 {
```

**Comment by zaps166** [comment]
Thanks! I've made it much more simple now.

Tested with `id3v2 --USLT asd a.mp3`. @Martchus
