### ISSUE TITLE
Establish compatibility with taglib 2.0

### ISSUE THREAD

**Issue by Martchus** [zaps166/QMPlay2#680]
The taglib 2.0 release removed some deprecated functions. I tried to build QMPlay2 against it (as taglib 2.0 is currently in Arch Linux' testing repository) but it failed. I suppose it shouldn't be hard to port QMPlay2 to taglib 2.0 while still supporting older versions of taglib.

**Comment by zaps166** [comment]
I removed support for 1.10, too, because I wanted to get rid of very old ifdef's :grin: I hope nobody uses 8 years old library.

**Comment by Martchus** [comment]
Thanks!
