### ISSUE TITLE
Screensaver appears when playing media fullscreen on Wayland

### ISSUE THREAD

**Issue by sibwaze** [zaps166/QMPlay2#683]
**Specs:** KDE Plasma 6
Manjaro Linux
Kernel: 6.8.0-1-Manjaro
QMPlay 23.10.22

**Issue:** While playing any media in fullscreen mode the screensaver appears and then i need to unlock my lockscreen with password again to watch media or turn on preventing screensaver in power settings
Any chance to fix this behaviour?

**Comment by zaps166** [comment]
#344, but KDE

It's not implemented on Wayland. I doubt Wayland has any protocol to do it. If you find specification how to do it, I can implement it.

**Comment by mar04** [comment]
> I doubt Wayland has any protocol to do it. If you find specification how to do it, I can implement it.

there is a dbus interface:
https://people.freedesktop.org/~hadess/idle-inhibition-spec/re01.html
and a wayland protocol for apps that don't want to depend on dbus:
https://wayland.app/protocols/idle-inhibit-unstable-v1
supported by kde and gnome, mpv uses it
