### ISSUE TITLE
24.03.16 Update flag as trojan/virus by Bitdefender

### ISSUE THREAD

**Issue by adeep** [zaps166/QMPlay2#688]
Qmplayer try to update to latest version (24.03.16) but when installing Bitdefender quarantine it because of malware/trojan.
I uninstall and download setup from github and tried again clean install but still same.
I upload setup.exe to virustotal and it flags for trojan.
Maybe iti is because exe signature unknown but antivirus not let me install it.

[Virustotal Link](https://www.virustotal.com/gui/file/804d616e4373e13da529775926fa3831bc28c2c7e67ea2021402eedde1a3b366?nocache=1)

![seccenter_POpaKBMsfq](https://github.com/zaps166/QMPlay2/assets/374042/3dd6f64f-8878-4d1f-a3c1-d4f2b3b2bf69)
![seccenter_PwphGm7Q83](https://github.com/zaps166/QMPlay2/assets/374042/b5329a59-5c49-438a-a944-ead2b32e189f)

**Comment by zaps166** [comment]
File is unsigned, so antivirus can show everything. Virustotal shows it's clean (bitdefender).

**Comment by adeep** [comment]
> File is unsigned, so antivirus can show everything. Virustotal shows it's clean (bitdefender).
Yes Virustotal Bitdefender Engine not flag it but on my pc it quarantine it.
İnteresting, i downloaded QMPlay2-Win64-24.03.16-portable.zip and Bitdefender not warn me and i scan folder and it is clean.
I guess installer has something that trigger Bitdefender.

![ODScanLogViewIE_w5Af8WwnLg](https://github.com/zaps166/QMPlay2/assets/374042/c3609269-6226-49b0-bf08-ded38a998aae)

**Comment by zaps166** [comment]
Yes, antivirus might detect false-positive.

**Comment by zaps166** [comment]
Both `QMPlay2-Win64-24.03.16.exe` and unpacked `QMPlay2Installer.exe` can be detected as trojan, because some of these antivirus software are just dumb. `QMPlay2Installer.exe` is generated by NSIS under Linux.

At least I can try to switch installer to InnoSetup, but idk if it helps.

**Comment by zaps166** [comment]
I changed how the NSIS installer is launching, we'll see next update.
