### ISSUE TITLE
Add speech synthesizer to subtitles for visually impaired viewers / dubbing subtitles voiceover with natural voices of yandex : Convert subtitles to speech with tts reader to add speech synthesizer to subtitles for visually impaired viewers by using rare feature of natural voices of this surprising open source rare tool vot-cli and extension Voice-over-translation ! 

### ISSUE THREAD

**Issue by trimechee** [zaps166/QMPlay2#691]
Hello, thank you very much for the new awesome fantastic wonderful new version of oour beloved QMPlay2 media player !! 💯 🥇 

Please i have request : we can download anime in Japanese from streaming sites which have 700 episodes which can be tiring to read the subtitles and we can find the subtitles easily so we hope for the addition of a speech synthesizer to "experience video in a whole new way with  "Speech Synthesizer" feature into streaming videos subtitles, reading them aloud through a sophisticated speech synthesizer that closely mimics the human voice. Choose from acclaimed voices like Ivona or the built-in Windows narrator voices such as Microsoft Paulina, Julie,  Zira, or Adam (standard in Windows 11).

This feature is perfect for those who prefer listen audio of pdf books and prefer listening over reading, or for visually impaired viewers, adding an extra dimension to your video-watching experience to enjoy videos in a way that suits us best, only with QMPlaye2 :) "

and also please if possible add  "Revolutionary AI-Powered Voice-Over Feature" : 

Add an innovative AI-powered voice-over feature, changing the way viewers experience videos. Utilizing advanced artificial intelligence technology for voice generation, the AI Voice-over provides a unique experience comparable to a real human narrator to enjoy videos without the need to read subtitles while still listening to the authentic voices of actors.

AI Voice-over is for those who dislike movie dubbing that destroys the true voice and authenticity of actors.
For visually impaired individuals who have difficulty reading subtitles.
For those who like to play movies in the background while doing other tasks and don't want to focus on reading subtitles.
Perfect for lovers of original soundtracks who also seek support in understanding dialogues. This function, developed by ElevenLabs.io - a world leader in this field, we hope it will be available to all QMPlay2 users to offer the innovative AI Voice-over technology enriches the film experience, combining the comfort of listening with the authenticity of the original performance." 

Thank you so much !

UPDATE : 

Mr @zaps166 , may be it can help : 

I suggest this featur to mpv based player developer, here his response :

"Please use the mpv script to implement the function you need, or download the script that has already implemented this function from the Internet. These scripts can usually also be used directly in mpv based player."

 and here the result of my research about voice synthesizer , maybe it can help : 

https://github.com/vincemann/Subtitle-Buddy

https://github.com/carsonip/Penguin-Subtitle-Player

edit : and
https://sourceforge.net/projects/subsplayer/

here the best synthesizer : 

https://www.cross-plus-a.com/balabolka.htm

This application that seems can read subtitles in the background while we watch a movie, so users can focus on the action, not on the subtitles:

https://www.softpedia.com/get/Multimedia/Audio/Other-AUDIO-Tools/Titlespeak.shtml

and :
https://alternativeto.net/software/subtospeech/about/

UPDATE GREAT NEWS :

Hi , just to inform that recently i discover this revolutionary amazing open source tool, maybe it can help to have reader speaker subtitles with natural voices please !
Thank you so much :)

https://github.com/FOSWLY/vot-cli

based on :

https://github.com/ilyhalight/voice-over-translation/blob/master/README-EN.md

developers have developed web browser extension ans tools to allow us the use of great rare Yandex Browser features even if we do not use Yandex Browsers !!

for example: the tools developed by Mr FOSWLY:

https://github.com/FOSWLY

"Video translation and dubbing
The browser can translate video:

into russian - from english, french, german, spanish, italian, chinese, japanese and korean;

into kazakh - from russian and english.

Men speak in a male voice and women in a female voice.

To watch the video in russian or kazakh:

Hover your mouse over the video.

Click on Translate and Voice or . The video will continue to be narrated in your language."

More informations about this unique rare
yandex feature :

translation and video dubbing :

https://browser.yandex.com/help/ru/search-and-browse/translators-settings#videos

Also i discover accessibility tools tHAT improve the tts readers, voice over, synthesizer.....

for example the great NVDA-IBMTTS-Driver :

https://github.com/davidacm/NVDA-IBMTTS-Driver

and also :

This repo contains the pico-tts for NVDA and TTS binaries,
This add-on implements NVDA compatibility with the svox-pico synthesizer

https://github.com/davidacm/PicoTTS-NVDA

Also if QMPlay2 plan to keep or enhance the great feature : search and add subtitle to streaming video from opensubtitle website, the problem is opensubtilte . org site imposes a limit of 5 subtile per day , maybe the recommendations and advices of Mr Bizilizi can help to fix this limit problem, thank you very much !

Missing Authorization header

https://github.com/plussub/plussub/issues/78

**Comment by zaps166** [comment]
I see on this website that the free version is limited (10min/month). Also I guess it always requires network.

**Comment by trimechee** [comment]
Yes in Allplayer, we have 10 or 20 free offers then you have to make a microtransaction to pay if you use this offer in the long term, and what distinguishes the AI voice is a more natural voice than the tts voice....but I tried with potplayer's tts synthetic tts voices and the result is pleasant, we can follow and clearly understand the plot in the anime....
In the changelog of Allplayer, they say : "In this version, LektorAI remains disabled. We have reduced the amount of information in the program about the voice-over feature. We are actively working to reintroduce LektorAI in some form in future releases....."

**Comment by trimechee** [comment]
@zaps166 , may be it can help : 

I suggest this featur to mpv based player developer, here his response :

"Please use the mpv script to implement the function you need, or download the script that has already implemented this function from the Internet. These scripts can usually also be used directly in mpv based player."

 and here the result of my research about voice synthesizer , maybe it can help : 

https://github.com/vincemann/Subtitle-Buddy

https://github.com/carsonip/Penguin-Subtitle-Player

here the best synthesizer : 

https://www.cross-plus-a.com/balabolka.htm

This application that seems can read subtitles in the background while we watch a movie, so users can focus on the action, not on the subtitles:

https://www.softpedia.com/get/Multimedia/Audio/Other-AUDIO-Tools/Titlespeak.shtml

and :
https://alternativeto.net/software/subtospeech/about/
