### ISSUE TITLE
Key binding for Show/Hide Playlist

### ISSUE THREAD

**Issue by ArchieA** [zaps166/QMPlay2#694]
First of all, thank you for QMPlay2. It is impressive and quite frankly, I find it better than Qute.

I personally don't use the mouse too much when it comes to watching videos. To me, it's a small distraction.  QMPlay2 has all well-thought of key shortcuts from Next, Stop, Previous, Compact View, Fullscreen, etc. However, one very essential action is missing on Option>Settings>Set key bindings is Show/Hide Playlist.

If you can add the Action and assign a key - preferably "P" and bind Keep audio pitch to another key - so there won't be a need to use the mouse to show/hide Playlist, I'm sure me along with a lot of other QMPlay2 users will  greatly appreciate it.

Thank you for your attention, and keep up the great work.

**Comment by zaps166** [comment]
Only playlist? Isn't compact mode enough (Alt+V)?

**Comment by ArchieA** [comment]
Only Playlist. Right now the only way to show or hide the Playlist is right-click the window > Widgets > Playlist.

Compact mode (Alt+V) won't display/hide Playlist.

**Comment by zaps166** [comment]
How about Ctrl+Alt+P or Shift+P?

**Comment by zaps166** [comment]
I've decided to use Shift+P. You can change it in key binding settings (general settings page, scroll to the bottom).

**Comment by ArchieA** [comment]
Thank you. It's truly appreciated.
