### ISSUE TITLE
Video adjustment custom saturation, hue, brightness, contrast, sharpness and other parameter values cannot be saved.

### ISSUE THREAD

**Issue by zhouxinghong** [zaps166/QMPlay2#699]
Video adjustment custom saturation, hue, brightness, contrast, sharpness and other parameter values cannot be saved.

Video adjustment custom saturation, hue, brightness, contrast, sharpness and other parameter values cannot be saved.

Steps to reproduce:
1. Customize parameters such as saturation, hue, brightness, contrast, sharpness;
2. Apply and exit the player;
3. Open the player again to play the video. At this time, you will find that all the parameters you set are lost.

Windows 10
QMPlay2 24.04.07

**Comment by zaps166** [comment]
Options->Playback settings->Remember video equalizer settings->Apply

**Comment by zhouxinghong** [comment]
![image](https://github.com/zaps166/QMPlay2/assets/54253524/51fadeef-24af-4489-9bed-322100ecb4ac)

**Comment by zhouxinghong** [comment]
thank you very much! 🎉👍🍦

**Comment by zhouxinghong** [comment]
Hello! Where does this skin come from? I can't find it in the appearance settings?
https://raw.githubusercontent.com/zaps166/GitHubCommonContents/master/Screenshots/QMPlay2.webp

**Comment by zhouxinghong** [comment]
Thank you very much! 🍦👍😜
