### ISSUE TITLE
Please support custom modification of the color of the area marked with the red arrow to make the theme fully customizable

### ISSUE THREAD

**Issue by zhouxinghong** [zaps166/QMPlay2#700]
Hello friends! Please support custom modification of the color of the area marked with the red arrow to make the theme fully customizable.

The color of the area marked with arrows cannot be customized
![image](https://github.com/zaps166/QMPlay2/assets/54253524/ec5ffa85-6b79-4424-bb00-203a0d74df22)

**Comment by zhouxinghong** [comment]
![image](https://github.com/zaps166/QMPlay2/assets/54253524/0b42e535-63b9-4c87-8435-033c6b388f4b)
If the colors of these areas could be customized, this player would be the most perfect visual tool in the world.

**Comment by zhouxinghong** [comment]
the background color of the drop-down list
![image](https://github.com/zaps166/QMPlay2/assets/54253524/7aa5d7f9-b1eb-4ea9-a5c0-a70a69426460)
the background color of the subtitle panel
![image](https://github.com/zaps166/QMPlay2/assets/54253524/bdfd5d50-39ca-4334-b2b9-96139a0cf37a)



In addition, the background color of the button will cover the background color of the drop-down list, the background color of the subtitle panel, and the background color of the OSD panel.

It is hoped that these areas can have separate background colors and not be related or coupled to each other. Thank you so much! 🍦👍

In this way, the entire theme will look more harmonious and friendly. 😜

**Comment by zhouxinghong** [comment]
![image](https://github.com/zaps166/QMPlay2/assets/54253524/453c340e-7e22-4864-ab8d-1bf4cea8635e)
The color of the vertical dividing line cannot be modified

**Comment by zhouxinghong** [comment]
I used to use PotPlayer all the time but when I learned about this player from a friend a few days ago, I fell in love with this beautiful video rendering tool and I hope that this video player will develop more and more! And many thanks to the developers for their hard work and effort! 💗🎉👏🌹👍🏆😜

**Comment by zhouxinghong** [comment]
Hello friends! Please support custom modification of the color of the area marked with the red arrow to make the theme fully customizable.

**Comment by zhouxinghong** [comment]
Hello friends! Can this error be fixed in the near future? I can help you with functional testing at any time after the problem is fixed.😜

**Comment by zaps166** [comment]
[Improved](https://github.com/zaps166/QMPlay2/commit/9654a2dfc610e4e73b43d7b49628a51dc154373d) it a bit, but still can't adjust every color. I will not work on this to make every pixel customizable.
