### ISSUE TITLE
Trigger keyboard D Can't turn on audio after turning off audio

### ISSUE THREAD

**Issue by zhouxinghong** [zaps166/QMPlay2#703]
Trigger keyboard D Can't turn on audio after turning off audio

![image](https://github.com/zaps166/QMPlay2/assets/54253524/61593d6c-6f0b-4941-a46a-811e0a566c6b)

During video playback, when you trigger keyboard D to turn off the audio Audio off and trigger keyboard D again, the audio cannot be turned on.
Windows 10

**Comment by zhouxinghong** [comment]
Thank you very much again for providing this unparalleled video player. I wish you a happy life and all the best! 🏆🍦😜

**Comment by zhouxinghong** [comment]
Computer operating environment:
Windows 10 19044
QMPlay2 24.04.07

**Comment by zaps166** [comment]
It's working to me.

**Comment by zhouxinghong** [comment]
I know, when you trigger the D keyboard to mute Audio off for the first time, and then trigger the D keyboard to unmute Audio on for the second time, you need to wait 2~3 seconds for it to take effect.

**Comment by zaps166** [comment]
2-3 seconds is not "cannot be turned on" - it just works as expected.
Use "M key instead to mute.

**Comment by zhouxinghong** [comment]
I didn't know the cause of this problem before, and I just discovered it after testing again. Thank you very much for your careful help! 👏👍🍦😜 I wish you a happy life!
