### ISSUE TITLE
Remember the selected video stream

### ISSUE THREAD

**Issue by blzos** [zaps166/QMPlay2#704]
Thanks for the wonderful player. Optimization of the player on old hardware is excellent!

I encountered the following issue:
Step by step:
1. I open an m3u file from a certain web page
2. It contains 4 video streams with different quality (360p, 480p, 720p, 1080p)
3. By default, • Program 3 (1080p) opens
4. I select • Program 1 (480p) [in the information panel]

However, if I open this or a similar link the next time, it opens again in program 3. In fact, the player always selects the latest stream, the best in quality.

Attention question:
Is it possible to make it so that when I open an external link, it takes stream 2 (480p) [or the program that was selected last time] from the m3u file by default?

I dug through all the settings, but did not find such a function.
Thank you!

**Comment by zaps166** [comment]
It's about HLS stream, right? I'll try to add this feature.

> Is it possible to make it so that when I open an external link, it takes stream 2 (480p) [or the program that was selected last time] from the m3u file by default?

Not possible now. When I (re)store previously selected streams, it'll be only for this stream. Every new stream will be open with defaults.

**Comment by blzos** [comment]
Yes, this is an HLS stream, which can be obtained, for example, from any TV channel on the Internet through the Developer Tools in the browser. Typically these files are named index.m3u or playlist.m3u

> Not possible now. When I (re)store previously selected streams, it'll be only for this stream. Every new stream will be open with defaults.

This will be good, since right now there are channels with a 4K stream, which the player selects it, which slows down the loading and wastes traffic if, for example, I need a 480p stream.

Perhaps in the future there will be a way to do this as it is implemented for YouTube using the settings Preferred quality in:
Extensions.ini
[YouTube]
QualityPreset=720p

Can create setting: QualityPresetHLS=1 (selects program 1 by default)

For example, Default Program setting: 

|Select default program |🡻|  (Selects the best quality)
Program 0 (QVGA)
Program 1 (SD)
Program 2 (HD)
Program 3 (FHD)
Program 4 (QHD)
Program 5 (4K)

In addition, it works, for example. I'm run a stream (it opens in program 3), select program 1 (playback is in progress), I will go to Options > Playback settings Change parameter "Keep zoom" (On or Off doesn't matter), click Apply. The QMPlay2 restarts the stream in program 1, and not program 3 how she launched this stream for the first time!!! Those it turns out that the code is already able to select the desired program!

**Comment by zaps166** [comment]
So instead of selected stream remember I can do preferred video size in settings. Is it ok?

Example combo box in settings:
```
- Default
- FullHD
- HD
- SD
```

**Comment by blzos** [comment]
> So instead of selected stream remember I can do preferred video size in settings. Is it ok?

This will be correct, since video streams can be described in 5 categories:
- Default (Opens stream in best quality [like now])
- QVGA (144p, 240p) - _This resolution is no longer relevant, so this value can be ignored_
- SD (480p) + _For low speed networks_
- HD (720p) + _For laptop screens 1366x768_
- FHD (1080p) + _For standard monitors, and a stable Internet connection_
- 4K (2160p) - _This will be the default value, as the highest possible quality, so this value can be ignored_

make it a dropdown list

**Comment by zaps166** [comment]
Yes, 144p and 2160p can be ignored. Default will take place of 2160p. Maybe I'll add it when there will be 4320p streams popular :smile:

**Comment by zhouxinghong** [comment]
@zaps166 You may also want to consider adding the 4320p 60 FPS now!

**Comment by zaps166** [comment]
> You may also want to consider adding the 4320p 60 FPS now!

Select "Default" instead, it *should* use highest possible.

**Comment by zaps166** [comment]
+ It' not for YouTube, because it reads only single video stream selected elsewhere.

**Comment by zhouxinghong** [comment]
@zaps166 Is there support for reading streaming links from the clipboard?

**Comment by zaps166** [comment]
Yes

**Comment by zaps166** [comment]
And improved it now for all combobox entries.

**Comment by zaps166** [comment]
So it selects audio stream from different program that video stream and it demuxes both programs?

**Comment by blzos** [comment]
> So it selects audio stream from different program that video stream and it demuxes both programs?

It looks like it. But in this case the load would be greater, there are some other processes taking place during such decoding, but you described the essence correctly. Now streams are taken from different programs (let's say video stream 2 is from program 1, audio stream 1 is from program 0). The load on the processor increases by 15-20% every 4-5 seconds, even if the audio bitrate in all streams is of the same quality.

**Comment by zaps166** [comment]
Fixed. Which installer do you use on Windows?

**Comment by blzos** [comment]
> Fixed. Which installer do you use on Windows?

[QMPlay2-Win64-24.05.23-qt5-portable.7z](https://github.com/zaps166/QMPlay2/releases/download/24.05.23/QMPlay2-Win64-24.05.23-qt5-portable.7z)

**Comment by zaps166** [comment]
Could you check it? (replace file) [QMPlay2.exe.zip](https://github.com/zaps166/QMPlay2/files/15445098/QMPlay2.exe.zip)

**Comment by blzos** [comment]
> Could you check it? (replace file) [QMPlay2.exe.zip](https://github.com/zaps166/QMPlay2/files/15445098/QMPlay2.exe.zip)

Yes, now it works perfectly.

✓ The required program is selected (taking into account the quality of the stream in the settings)
✓ The load on the CPU has stabilized

**Comment by zaps166** [comment]
> Yes, now it works perfectly.

Ok!
