### ISSUE TITLE
Streaming performance improvements

### ISSUE THREAD

**Issue by zhouxinghong** [zaps166/QMPlay2#705]
Streaming performance improvements

**Business Description:**
When I play streaming media for the first time, QM2 will automatically load the remote server resource for playback, but when I play the remote server resource again, QM2 will load the remote server resource again, and this process will cause excessive consumption of network traffic resources.

**Solution:**
When I play streaming media for the first time, QM2 will automatically load the remote server resource to play, as long as the user does not quit or close the QM2 player process, it will be able to play the streaming media resource that has been loaded before without reloading the remote server resource automatically.

**Implementation idea:**
1 . Will the first time you play a stream QM2 will automatically load a cache of remote server resources to local disk, after which QM2 automatically loads resources from local disk;
2. the first time you play a stream, QM2 automatically loads the remote server resource cache into local memory, after which QM2 automatically loads the resource from local memory;
3. Support streaming media cached to local disk and local memory in two ways by the user to choose.

**Design Thinking:**
Friend! Which of the above two options do you think is better? Or is there any other better implementation ideas?

Windows 10

**Comment by zaps166** [comment]
This requires to add cache for any non-live network stream. Generally it's not a problem if you don't use mobile network.

Alternatively you can increase "Network buffer length" in playback settings to not re-download on e.g. repeat listen of the same music/video.

**Comment by zhouxinghong** [comment]
Currently mpv has implemented both of these options, and its real-time streaming is almost as good as local media playback.

**Comment by zhouxinghong** [comment]
test link
`https://www.youtube.com/watch?v=ggIj7ur1-gk`
