### ISSUE TITLE
[Question] How to turn off the highlighting of alternate rows in the table

### ISSUE THREAD

**Issue by zhouxinghong** [zaps166/QMPlay2#706]
Hello friends! How to turn off the highlighting of alternate rows in the table?
![image](https://github.com/zaps166/QMPlay2/assets/54253524/69df51b4-63b1-4de7-9663-446fca2ae709)

**Comment by zaps166** [comment]
If you can't do it in QMPlay2 color settings, you generally can't.

Closing because of #700.

**Comment by zhouxinghong** [comment]
I'm using the default theme. Not a custom theme.

**Comment by zhouxinghong** [comment]
I'm using the default theme. Not a custom theme.

**Comment by zaps166** [comment]
It should be gray (lighter and darker), but it's gray/blue due to Qt bug on Windows in Fusion style (I'm aware of this and I'll report it to them later).

**Comment by zhouxinghong** [comment]
Thank you for your help! 🍦👏😜

**Comment by zaps166** [comment]
https://bugreports.qt.io/browse/QTBUG-124563

**Comment by zhouxinghong** [comment]
Thank you for your help! 🍦👏😜
