### ISSUE TITLE
Qt 6.7.0 separator color bugged

### ISSUE THREAD

**Issue by parkerlreed** [zaps166/QMPlay2#707]
Top: AppImage 24.04.07
Bottom: Locally compiled 1e8342072d84efee182e6880da11ec8c745b5bab

OS: Arch Linux
Theme: Breeze Dark Qt6

Separators become a light grey, not matching with the theme.

![image](https://github.com/zaps166/QMPlay2/assets/841440/1cf375b5-7e2a-46f0-9780-c15cc0077bee)

**Comment by zaps166** [comment]
I have "Breeze" only and it's dark and it looks completely different :smile: 
How to use "Breeze Dark"?

**Comment by parkerlreed** [comment]
That's what I meant. Dark variant of Breeze.

How is it looking for you? Also on At 6.7.0?

**Comment by zaps166** [comment]
Breeze in QMPlay2 (Qt 6.7.0):

![Zrzut ekranu_20240418_220100](https://github.com/zaps166/QMPlay2/assets/6239090/f0e27602-4117-43b5-9f98-3378ba3f83c3)
