### ISSUE TITLE
Desktop files needs to be fixed for flatpak

### ISSUE THREAD

**Issue by yakushabb** [zaps166/QMPlay2#710]
"Desktop files needs to be fixed anyway. Actions of main file doesn't work either. It can be done later."

_Originally posted by @zaps166 in https://github.com/zaps166/QMPlay2/issues/695#issuecomment-2070395608_

**Comment by zaps166** [comment]
The problem is that MPRIS doesn't work. I can't see MPRIS controls in flatpak's QMPlay2 at all (including xfce4-pulseaudio-plugin).

**Comment by yakushabb** [comment]
It was a productive day for us :+1:
