### ISSUE TITLE
[Question] Friends! How can I display the lyrics when playing a song?

### ISSUE THREAD

**Issue by zhouxinghong** [zaps166/QMPlay2#712]
[Question] Friends! How can I display the lyrics when playing a song?

**Comment by zaps166** [comment]
Click on Lyrics tab. If it will not display after a while - it's not available for this song or you're missing some metadata.

**Comment by zhouxinghong** [comment]
I use local *.mp3+*.lrc

**Comment by zhouxinghong** [comment]
![image](https://github.com/zaps166/QMPlay2/assets/54253524/f50736bb-fcc3-493c-9213-0705418e9e17)

**Comment by zaps166** [comment]
Lyrics included in MP3 files are supported, but not from separate file. Open issue and upload example.

**Comment by zaps166** [comment]
#356
