### ISSUE TITLE
Custom audio cannot be switched

### ISSUE THREAD

**Issue by zhouxinghong** [zaps166/QMPlay2#714]
Custom audio cannot be switched
![image](https://github.com/zaps166/QMPlay2/assets/54253524/11b51408-58b4-47c2-bfdd-881a9ef89629)
Windows 10

**Comment by zhouxinghong** [comment]
Hello friends! Can this error be fixed in the near future? I can help you with functional testing at any time after the problem is fixed.😜

**Comment by zaps166** [comment]
I don't understand.

**Comment by zhouxinghong** [comment]
Clicking Bass or Rock separately does not switch from Bass to Rock. Conversely, it is not possible to switch from rock to bass.

**Comment by zaps166** [comment]
I don't have this issue, this menu works correctly.

**Comment by zhouxinghong** [comment]
How did you set up the audio?

**Comment by zhouxinghong** [comment]
Maybe I'm setting it up incorrectly.

**Comment by zaps166** [comment]
I created two profiles with different equalizer settings. When I change to another, it's set to another.

Set equalizer to values you want and create profile. There are no default presets (see #298).

**Comment by zhouxinghong** [comment]
Thank you very much! 👍👍👍😜
