### ISSUE TITLE
App does not launch after updating python to 3.12

### ISSUE THREAD

**Issue by sibwaze** [zaps166/QMPlay2#716]
After updating the python package from 3.11 to 3.12, I face the issue: `QMPlay2: error while loading shared libraries: libpython3.11.so.1.0: cannot open shared object file: No such file or directory`
If I downgrade to 3.11, then I can normally use QMPlay2 as usual. Same happens with my plasmoids on KDE Plasma, so I need to use 3.11
Don't know if i need to report this issue here or on python repo

**Comment by zaps166** [comment]
I don't know how did you install QMPlay2. Usually for this error you have to recompile software (QMPlay2) with new dependencies.

You should give more information.

Btw. QMPlay2 doesn't use Python directly, so idk why it needs it to launch.

**Comment by sibwaze** [comment]
> I don't know how did you install QMPlay2. Usually for this error you have to recompile software (QMPlay2) with new dependencies.
> 
> You should give more information.
> 
> Btw. QMPlay2 doesn't use Python directly, so idk why it needs it to launch.

Actually I use yay to build packages from source (aur packages)
I don't know for sure why QMPlay2 needs that lib, but it actually fails to launch, if python package is v.3.12, not 3.11
Maybe it looks for some libs to launch and there are only 3.12s

**Comment by sibwaze** [comment]
Probably this issue is caused by arch partial update, so i'll see if it fixes soon after packages being updated

**Comment by zaps166** [comment]
I see. For these errors you can always use `lddtree /bin/QMPlay2` (from `pax-utils`). On my Linux `libpython3.11.so.1.0` is dependency of `libvapoursynth-script.so.0` (`vapoursynth` package) which is dependency of `libavformat.so.60` (`ffmpeg` package).

I guess all FFmpeg applications should stop working on your Linux now and even more applications which links to Python 3.11 library.

It's because other system dependencies links to `libpython3.11.so.1.0`, so you cannot use Python 3.12 for entire system.

**Comment by zaps166** [comment]
> Probably this issue is caused by arch partial update, so i'll see if it fixes soon after packages being updated

Yes, never do partial update. It breaks dependencies.

**Comment by sibwaze** [comment]
> I see. For these errors you can always use `lddtree /bin/QMPlay2` (from `pax-utils`). On my Linux `libpython3.11.so.1.0` is dependency of `libvapoursynth-script.so.0` (`vapoursynth` package) which is dependency of `libavformat.so.60` (`ffmpeg` package).
> 
> I guess all FFmpeg applications should stop working on your Linux now and even more applications which links to Python 3.11 library.
> 
> It's because other system dependencies links to `libpython3.11.so.1.0`, so you cannot use Python 3.12 for entire system.

Yep, you are right, ffmpeg and dependent packages don't work
