### ISSUE TITLE
17.01.08 ai-radio.org tags not updated at track change

### ISSUE THREAD

**Issue by Amaunator** [zaps166/QMPlay2#72]
http://listen.ai-radio.org:8000/44.flac?cc=GB&now=1482770379.88& Flac stream won't show current title/artist/album. need to start over listening (tagi w nie są odświeżane na bieżąco podczas odtwarzania strumienia flac)

**Comment by zaps166** [comment]
Does the version number in title mean that it worked before?

Btw. Są jeszcze jakieś inne strumienie Flac? Chętnie bym posłuchał :D

**Comment by Amaunator** [comment]
Has never worked before. Other stations (if broadcast tags) got it working well. 
Flac radios: http://89.223.45.5:8000/progressive-flac
http://89.223.45.5:8000/space-flac
http://amp1.cesnet.cz:8000/cro-d-dur.flac

**Comment by zaps166** [comment]
FFmpeg doesn't update title/artist, so QMPlay2 doesn't show new tags. Looks like FFmpeg bug, maybe nobody predicted that Flac will be streamed with tags :)

**Comment by zaps166** [comment]
Problem is when FLAC is inside OGG container. [FLAC-only streams](https://chiru.no:8081/stream.flac) works properly.
