### ISSUE TITLE
我感觉QMPlay2在网络处理方面存在问题，有待加强。

### ISSUE THREAD

**Issue by 4yt1k** [zaps166/QMPlay2#724]
我的系统是Windows 10。

代理用v2rayN的情况下，QMPlay2设置好代理IP和端口，可以播放油管直播频道，比如像下面这样的网址：
【凤凰资讯】https://www.youtube.com/watch?v=a3WZVssKlAI
效果跟直接播放一个m3u8直播源一样，特别赞！！！

但把节点放到路由器上面，就打不开了，还有很多本来可以播放的国外m3u8源【如NBC、BBC、CNN】都打不开了，同样的网络环境，Potplayer却可以打开。

当然，象上面【凤凰资讯】，m3u8源嵌在网页里面的网址，Potplayer一直都不支持，不管节点部署在路由器还是在本地，但Potplayer播放国外m3u8源却不需要额外设置代理，不管节点在本地还是在路由器上面都正常播放。

对了，路由器的SSR Plus我设的国外IP都走代理。

**Comment by zaps166** [comment]
English?
