### ISSUE TITLE
Make RadioBrowser Connection Error Optional

### ISSUE THREAD

**Issue by zo-shin** [zaps166/QMPlay2#727]
Users may not expect to be interrupted at app start up, so it’s better to make it optional. In fact, the old API **all.api.radio-browser.info** has been outdated for a while and should be updated according to **http://api.radio-browser.info/**.

**Comment by zaps166** [comment]
What do you mean about "interrupted at app start up"?

**Comment by zo-shin** [comment]
I sometimes play local music files offline with the app. When I start it every time, it shows the radio browser connection error message. I have to click OK to continue. Of course, I can hide the internet radio widget, but I don’t want to do so.
