### ISSUE TITLE
[Feature Request] Madlib MP3 decoder support

### ISSUE THREAD

**Issue by Amaunator** [zaps166/QMPlay2#73]
Would be nice to have option to use http://www.underbit.com/products/mad/ Madlib instead of mpg123 used by default by ffmpeg. Similar approach as VLC in it's settings. ffmpeg if I'm not mistaken got it built in just need setting to pick it instead of mpg123 (chciałbym się pobawić w porównanie jakości dekodowania libmad vs mpg123. oba dekodery są w ffmpeg, brakuje tylko opcji by użyć zamiast. mógłbym użyć VLC ale QMPlay2 to mój ulubiony odtwarzacz w tej chwili i nie chcę wracać do VLC bez potzeby...)

**Comment by zaps166** [comment]
Jak to odpalić w VLC (nie widzię tam takiego kodeka audio) ? W FFmpeg to zobaczę, czy to tam jest. Jeżeli nie, to trzeba w przyszłości napisać nowy moduł.

**Comment by Amaunator** [comment]
Właśnie odpaliłem VLC i sam nie mogę teraz znaleźć. Najnowsza wersja VLC usunęła możliwość wyboru. Sorry.

**Comment by zaps166** [comment]
Ok!
Jeżeli faktycznie jest różnica w jakości - to warto. Jeżeli nie słychać jej, lub jej nie ma, to czy ma sens pisanie dodatkowego modułu? Czym mogę to przetestować nie pisząc własnego programu używając tej biblioteki?

**Comment by Amaunator** [comment]
podobno jest wolniejszy i bardziej zasobożerny ale MOŻE mieć lepszą jakość, słowo kluczowe MOŻE.... na jakiej platformie chcesz przetestować? linux czy windows? na linuxie jest deadbeef player co to ma wbudowane, wiem że są inne ale nie pamiętam. na Archu są z AUR nakładki. winamp na windowsie miał wtyczke pamiętam,foobar2000 też. chyba szkoda czasu na to tracić....

**Comment by zaps166** [comment]
Chyba nie warto pisać tego - różnicy zapewne nie będzie. Jak chcesz lepszą jakość, to lepiej użyć FLAC albo ze stratnych to Opus/Vorbis. MP3 128kbps brzmi tak samo źle na FFmpeg jak i na libmad (deadbeef na arch'u) :smile:

Widzę, że VLC wymaga libmad `:: vlc: removing libmad breaks dependency 'libmad'`, więc może jednak z tego korzysta?
Także przy Audacity widzę zależność od `libmad`. Porównałem widmo eksportu do WAV z  FFmpeg i Audacity - jest jakaś minimalna różnica, ale które lepsze?

**Comment by zaps166** [comment]
Jeżeli usłyszysz gdzieś różnicę między dekoderem libmad i tym z FFmpeg, to możesz otworzyć issue uploadując tu próbki MP3 :)
