### ISSUE TITLE
HDR function support (ARIB STD-B67)

### ISSUE THREAD

**Issue by jacky9682** [zaps166/QMPlay2#731]
Is it possible to add a function similar to Potplayer to simulate HDR video display on non-HDR monitors?

**Comment by jacky9682** [comment]
This feature is very important for monitors that do not support HDR color hardware.

**Comment by jacky9682** [comment]
For monitors that do not support HDR, after turning on the hdr function in potplayer, HDR movies can display colors normally, but on qmplay2 the colors are dim and cannot be adjusted. The graphics card is NVIDIA, and no matter which decoding method is used, it cannot restore HDR colors.

**Comment by zaps166** [comment]
Vulkan and OpenGL supports HDR on non-HDR displays (if smpte2084 is detected correctly from metadata).

Additionally on Vulkan (need to select option) is able to use HDR on HDR displays (Nvidia and AMD are working, Intel probably doesn't).

Show me your information panel screenshot?

See #549

**Comment by jacky9682** [comment]
![image](https://github.com/zaps166/QMPlay2/assets/170976477/329a84fd-7531-4c3e-a614-a1fdae7899e1)

**Comment by zaps166** [comment]
Ok, it's different format. How can I watch it?

**Comment by jacky9682** [comment]
http://193.123.236.118:7878/4k/index.m3u8
Please copy it quickly and I will delete this address. I don’t want others to see this link. Please reply after copying it.

**Comment by zaps166** [comment]
Ok, I have on email.

**Comment by jacky9682** [comment]
Thanks

**Comment by zaps166** [comment]
I will read about this format and try to implement it.

**Comment by jacky9682** [comment]
Thanks

**Comment by jacky9682** [comment]
![9](https://github.com/zaps166/QMPlay2/assets/170976477/6068113f-ce6f-4bc8-90a8-28fd7c8109fe)

**Comment by zaps166** [comment]
Mostly I fixed colors, maybe it'll be good enough.
