### ISSUE TITLE
can not open a playurl

### ISSUE THREAD

**Issue by momo1994123** [zaps166/QMPlay2#733]
https://025365.xyz:8082/zh.php?url=https://025365.xyz:8082/upload/002.php
this url can not open ,but i can play with iina or others
php use header('Content-Type: application/x-mpegURL');
how can i play this url

**Comment by momo1994123** [comment]
https://025365.xyz:8082/zh.php?url=https://025365.xyz:8082/upload/002.php
this url can not open ,but i can play with iina or others
php like  header('Content-Type: application/x-mpegURL');
how can i play this url

**Comment by zaps166** [comment]
Can't play either `http://122.96.52.25:8080/gitv_live/G_CCTV-1-CQ/G_CCTV-1-CQ.m3u8: Server returned 404 Not Found`

or

`https://livednow.com/migu/626065193?sign=gAAAAABmZNRlpPMyXofSh0LAINA2UpYUm1CUJyZ_x3IIujcCwR6af8hIrfLbWRNlvnGa7KNIPL3Rv1F-jZArMT1FALMqLh7PGg30Jz0v0ygIeqS4qTI90ZBAkXEJ7xTOk_IxlAJ_uOsPaE5NUnIcGUOUuCnYsTAm7wbaUn06MphKkmVpsBU_rL5bKzQKtdbjBmHaFLOZ05b38_NjxFl4dMFJsXXBR6hxEw%3D%3D: Server returned 403 Forbidden (access denied)`

Server not found or rejects. Looks like I can't play it from my IP.

Just download this file from URL and open it in QMPlay2.

**Comment by momo1994123** [comment]
Do you mean that all the content of M3U must be accessible in order to open it, but the M3U I downloaded can be opened and accessed, and some URLs of M3U can only be accessed through specific internal networks

> Can't play either `http://122.96.52.25:8080/gitv_live/G_CCTV-1-CQ/G_CCTV-1-CQ.m3u8: Server returned 404 Not Found`
> 
> or
> 
> `https://livednow.com/migu/626065193?sign=gAAAAABmZNRlpPMyXofSh0LAINA2UpYUm1CUJyZ_x3IIujcCwR6af8hIrfLbWRNlvnGa7KNIPL3Rv1F-jZArMT1FALMqLh7PGg30Jz0v0ygIeqS4qTI90ZBAkXEJ7xTOk_IxlAJ_uOsPaE5NUnIcGUOUuCnYsTAm7wbaUn06MphKkmVpsBU_rL5bKzQKtdbjBmHaFLOZ05b38_NjxFl4dMFJsXXBR6hxEw%3D%3D: Server returned 403 Forbidden (access denied)`
> 
> Server not found or rejects. Looks like I can't play it from my IP.
> 
> Just download this file from URL and open it in QMPlay2.



> Can't play either `http://122.96.52.25:8080/gitv_live/G_CCTV-1-CQ/G_CCTV-1-CQ.m3u8: Server returned 404 Not Found`
> 
> or
> 
> `https://livednow.com/migu/626065193?sign=gAAAAABmZNRlpPMyXofSh0LAINA2UpYUm1CUJyZ_x3IIujcCwR6af8hIrfLbWRNlvnGa7KNIPL3Rv1F-jZArMT1FALMqLh7PGg30Jz0v0ygIeqS4qTI90ZBAkXEJ7xTOk_IxlAJ_uOsPaE5NUnIcGUOUuCnYsTAm7wbaUn06MphKkmVpsBU_rL5bKzQKtdbjBmHaFLOZ05b38_NjxFl4dMFJsXXBR6hxEw%3D%3D: Server returned 403 Forbidden (access denied)`
> 
> Server not found or rejects. Looks like I can't play it from my IP.
> 
> Just download this file from URL and open it in QMPlay2.

Do you mean that all the content of M3U must be accessible in order to open it, but the M3U I downloaded can be opened and accessed, and some URLs of M3U can only be accessed through specific internal networks

**Comment by momo1994123** [comment]
https://025365.xyz:8082/zh.php?url=https://025365.xyz:8082/upload/0021.txt 

this url can not open too ，but download it then open canplay

**Comment by zaps166** [comment]
It can't play playlist inside playlist, etc. Currently need to download playlist and open it.
