### ISSUE TITLE
Some questions about downloading

### ISSUE THREAD

**Issue by jacky9682** [zaps166/QMPlay2#737]
I hope the next version will restore the function of selecting video quality when downloading.
On some computer equipment with relatively poor hardware, downloading and watching the highest video quality will cause the computer to freeze. At the same time, if some HDR videos are only downloaded at the highest image quality, After downloading, there will be a problem that it is not an HDR video.
Even a lot of not-so-bad hardware can't hard-decode AV1-encoded videos, but currently there are a lot of AV1-encoded videos out there if you can only download them at the highest quality possible.
Therefore, it is important to restore the ability to select video quality when downloading.

**Comment by zaps166** [comment]
Download from YouTube has same quality as selected for playback. In settings you can choose H.264 codec and select lower quality.

In General settings you have "Default quality" for yt-dlp, you can set `worst` there for other URLs processed by yt-dlp.

In Playback settings you have "Desired video stream quality" for HLS streams.

---

Don't forget to press "Apply" button on every settings page!
