### ISSUE TITLE
Windows Xp v20.12.16 minor update for youtube-dl

### ISSUE THREAD

**Issue by YoshiKill** [zaps166/QMPlay2#739]
Hello, and thanks a lot for your great work.
I have some not trivial request (My tastes are very...singular) 
I use old Xp version 20.12.16 for my retro Pc, its work great i even can watch youtube with youtube-dl until this day. Now youtube change there stuff and only video source is 360p, all other is in DASH. 
So my request is ask for update, for this old version, to add chose DASH source of video + audio for youtube-dl, if its possible. 
It will be great support for retro PC enthusiasts.     

![IMG_20240623_221222_jpg](https://github.com/zaps166/QMPlay2/assets/46250788/94238630-fb79-459c-9fcd-dac62f46820e)

![IMG_20240623_221328_jpg](https://github.com/zaps166/QMPlay2/assets/46250788/9c289a0e-0ab0-44de-bd8b-79490164289a)

**Comment by zaps166** [comment]
It must be something else, not DASH. Is it possible to run newer version of youtube-dl there?

**Comment by YoshiKill** [comment]
> It must be something else, not DASH. Is it possible to run newer version of youtube-dl there?

(Sorry for long answer, have a big problem with electricity now. )

Some enthusiasts compile mod version of new YouTube-dl and yt-dlp for old PC, yes it's work fine. 
I make some screen from -F output 
![IMG_20240716_175708.jpg](https://github.com/user-attachments/assets/b591260e-e4c0-4906-b430-533089053a00)

![IMG_20240716_175654.jpg](https://github.com/user-attachments/assets/f6855c37-965d-4845-92e7-c9b36e764a1b)

**Comment by YoshiKill** [comment]
@zaps166
Hello, any news for this not trivial request? There is any chance add Dash support for this XP version?

**Comment by zaps166** [comment]
Windows XP is not supported anymore, I don't have any tools already for this.

**Comment by YoshiKill** [comment]
> Windows XP is not supported anymore, I don't have any tools already for this.

What tools is needed for compile Qmplay2  in xp? Or modern code don't support work in XP any way? I can try install all software to compile it. If you help me. But if you don't have any interest I understand.

**Comment by zaps166** [comment]
You have to use [Qt 5.6](https://github.com/zaps166/QMPlay2/tree/qt5.6) branch, Install/compile Qt 5.6.3.

Also verify which version of MinGW/GCC compiler supports Windows XP and compile all needed dependencies (requires older FFmpeg 4.x maybe - don't remember version exactly).

You can try to take DLLs from last QMPlay2 Windows XP release, but you have to have header files and try to link to these DLLs w/o `.a` files (maybe MinGW can handle it).

**Comment by zaps166** [comment]
I don't have tools for Windows XP anymore, I don't want to build environment for 23 years old operating systems, sorry :disappointed: You can do it on your own, also see #776 .

**Comment by barracuda156** [comment]
@YoshiKill If you have 20.12.06 with Qt5, it should be fairly trivial to backport a fix for HD YT streaming. This commit fixes it: https://github.com/zaps166/QMPlay2/commit/2f9281bb1026afd55650f4c33fdd3f3b91deee85
(Depending on whether it applies cleanly, you may need to backport something else too, but again, if you start from 20.x, this is likely easy.)

**Comment by YoshiKill** [comment]
> @YoshiKill If you have 20.12.06 with Qt5, it should be fairly trivial to backport a fix for HD YT streaming. This commit fixes it: https://github.com/zaps166/QMPlay2/commit/2f9281bb1026afd55650f4c33fdd3f3b91deee85
> (Depending on whether it applies cleanly, you may need to backport something else too, but again, if you start from 20.x, this is likely easy.)

Okey, thanks for idea. I try it 🤝

**Comment by barracuda156** [comment]
If you have some modern fast hardware, it is not hard to bisect to find a fix you are interested in, as long as you do not need to backport or fix a lot of stuff on the go. YouTube playback issues are largely platform-agnostic, so you can probably bisect and test on a modern system to determine what is needed for a legacy one.
(No guarantee that there are no platform-specific issues in addition to generic ones, of course, but perhaps worth trying. Running multiple rebuilds on arm64 with Qt5 saved me a lot of time in debugging this for PowerPC with Qt4.)
