### ISSUE TITLE
[Feature Request] notification to include Album Art

### ISSUE THREAD

**Issue by Amaunator** [zaps166/QMPlay2#74]
Would be nice to see song change Notification with AlbumArt picture like Clementine does it. They use Native notification, nothing fancy..

**Comment by zaps166** [comment]
@arthurzam is it possible to add pictures to notifications? :)

**Comment by arthurzam** [comment]
@arthurzam is it possible to add pictures to notifications? :)

Yes, I think. I will work on it.

**Comment by arthurzam** [comment]
@zaps166 
From where can I get the album art during an `updatePlaying` event?

**Comment by zaps166** [comment]
@arthurzam
`coverDataFromMediaFile()` gives you raw image (e.g. png).

**Comment by zaps166** [comment]
@arthurzam
Look at `MPRIS2.cpp`, `void MediaPlayer2Player::coverDataFromMediaFile(const QByteArray &cover)`
