### ISSUE TITLE
Help in selecting Multi files to send to Top or Bottom of very long playlists? Cheers to the developer on the great work on this player.

### ISSUE THREAD

**Issue by yaba1** [zaps166/QMPlay2#741]
**Hot addtl Superhot requests to make this player 5 Star Top Tier: 
*any way to [select in playlist, multiple files at a time, & quickly] send to top or bottom of playlist order? This option saves a huge amount of time in organizing large video & audio playlists.
*any poss to [search for duplicate files] to help clean up very long playlists?
*Any way to poss with [player or transition effects] to get my Music videos playlists
To use superhot [Crossfade effect], like a DJ, when go to next file. 
Currently they stop abruptly, b4 going to next. 
*any way poss to add a [very basic post Download Editor & video cropper option], to remove ugly black bars or logos, & to simply Pre-trim & cut unwanted parts of files before or at least after video downloading?  

Thank you. Cheers to all the hardwork on this great player!

**Comment by zaps166** [comment]
Thanks for the feedback!

---

> any way to [select in playlist, multiple files at a time, & quickly] send to top or bottom of playlist order? This option saves a huge amount of time in organizing large video & audio playlists.

Ctrl + click or Shift + arrows and drag and drop or Ctrl+C->Ctrl+V + delete. Currently no plans do improve.

Moving selection to the bottom could be added some day, but please do separate issue for this, but I don't understand the use-case.

> any poss to [search for duplicate files] to help clean up very long playlists?

Could be added some day, but please do separate issue.

> Any way to poss with [player or transition effects] to get my Music videos playlists

No plans.

> any way poss to add a [very basic post Download Editor & video cropper option], to remove ugly black bars or logos, & to simply Pre-trim & cut unwanted parts of files before or at least after video downloading?

It's just a player. Too much work to me.
