### ISSUE TITLE
The background does not blur when enlarging small covers...

### ISSUE THREAD

**Issue by IPeluchito** [zaps166/QMPlay2#743]
By enabling Blur Background and Enlarging Small Covers at the same time, the enlarged Small Cover returns to its original size...

**Comment by zaps166** [comment]
How to reproduce?

**Comment by IPeluchito** [comment]
Open an audio file with embedded cover, enable "Enlarge small covers" the embedded cover becomes larger...now enable "Blurred covers as background" the enlarged embedded cover returns to its original size...

Full Window Player with Player Widgets Enabled:
Hide menu bar
Video
Playlist
FFT Spectrum
Main toolbar
Lock widgets

**Comment by zaps166** [comment]
I see different problem. Enlarge small covers doesn't work when blur is disabled - it's always large. When blur is enabled it works as expected - covers are larger.

**Comment by IPeluchito** [comment]
https://github.com/zaps166/QMPlay2/assets/64821708/64a2a7be-e71f-4abc-8d56-0f2cb84382c3

**Comment by zaps166** [comment]
It's already large, so "Enlarge...." option is not doing anything. It leaves borders for blur. It's working as expected.

**Comment by IPeluchito** [comment]
Ok I thought that by enabling "Enlarge small covers" it would look the same size as when disabling "Blurred covers as background"... :S

**Comment by zaps166** [comment]
No, because there's margin for blur.

But if your cover is smaller, it will be larger with some margins with that option.

**Comment by IPeluchito** [comment]
Well that's all...Thanks for the clarification...
