### ISSUE TITLE
Question? Spanish translation...

### ISSUE THREAD

**Issue by IPeluchito** [zaps166/QMPlay2#746]
I have just reviewed the Spanish translation and I see that there are some texts missing and some are not well translated.... I would like to correct and translate the missing texts... is it possible that I can do it? I already did the same before with MPC-BE...

Thanks in advance!

**Comment by zaps166** [comment]
Yes, you can download [this](https://github.com/zaps166/QMPlay2/blob/master/lang/es.ts) and edit it in almost any text editor. Or you can use Qt Linguist tool to edit this file in convenient way (available in any Linux distribution repository or [here](https://www.qt.io/download-open-source)).
When you finish, open Pull request or upload it here, so I'll attach it.
