### ISSUE TITLE
Impossible to play youtube videos with QMPlay2 32 bits yt-dlp 32 bits VC Redist 32-bit  installed

### ISSUE THREAD

**Issue by trimechee** [zaps166/QMPlay2#749]
EDIT UPDATE : the good news is that i tried to play other video from famous russian site ok.ru/video and i can playback the video from ok.ru ! 💯 🥇 

Hello, thank you again for the awesome great QMPlay2 media player ! 💯 🥇 

Please there is a problem, my laptop recently broke down so I came back to use my old laptop from 2012 which has a Windows 7 pack 1 32 bit OS but the streamng reading is very jerky and laggy despite the fact that I use updated web browsers compatible with Windows 7 like supermium, thorium legacy, catsxp web browsers probably because my OS is old or weak or old processor.....

The only solution is either to download which is annoying because the download can get low because my sister uses hdmi a lot, or I use our beloved QMPlay 2 and I was happy relieved that there is a version of QMPlay 2 for windows 7 32 bit, thank you very much!

The problem is despite the fact that I updated yt-dlp of QMPlay2, installed VC Redist 32-bit, changed the video render settings....QMPlay2 displays a message "QMPlay2 cannot play this video" when I try to play a youtube video, we hope this problem will be solved please in order to save my old laptop, tahnk you so much :)

Let's specify that  i compared and I installed potplayer 32 bits for windows 7, the video is unreadable i.e. there is sound but the video image is scrambled but I have a tip and that it is necessary to change the default parameters of potplayer: filter control / video decoders : MPEG1, MPEG2 . .....from "integrated decoder" to "integrated system decoder", and by activating the dxva hardware decoding, and by installing the 3DYD Youtube plugin Source:

https://ys.3dyd.com/

which integrates with potplayer by adding yt-dlp to potplayer and I can play YouTube videos without problem with potplayer 32 bit for windows 7, also I can play YouTube videos and local videos media players version 32 bit windows 7 of vlc ,kmplayer, , mpc hc (sometime there is black screen and i should wait and exit full screen and enable full screen to video work), smplayer (the video in smplayer has weird colors but I fixed the problem by changing the output driver from 'default' to 'direct3d'!).

So we hope please our beloved QMPlay 2 will fix youtube playback with yt-dlp in windows 7 32 bit os, thank you so much!

**Comment by zaps166** [comment]
Go to: `%appdata%\QMPlay2` and check if the `yt-dlp.exe` can launch by 2x click?

**Comment by zaps166** [comment]
I don't have Win7 32-bit, but I have Win 8.1 32-bit and it's working without problems.

> "yt-dlp_x86.exe: error: do not double-click the executabe, instead call it from a command line .

It means 32-bit yt-dlp is working.

---

Do you have any message box in QMPlay2 when you want to play youtube video?

**Comment by trimechee** [comment]
Hello Mr @zaps166 , i find these softwares, may be they can help to fix the error message of Qmplay2 with youtube videos "Qmplay2 can't use youtube-dl", what is strange is that Qmplay2 32 bits  has succeeded to playback the streaming videos of other sites, but the bug only occurs in youtube !



https://github.com/commandcontrolQ/VxKex 

https://github.com/i486/VxKex 

https://news.ycombinator.com/item?id=41032479


https://msfn.org/board/topic/186333-vxkex-extended-kernel-project-dissapeared/
