### ISSUE TITLE
Add option to choose worst video quality ou best video quality in sites other than youtube

### ISSUE THREAD

**Issue by trimechee** [zaps166/QMPlay2#755]
Hello, in facebook : 

https://fb.watch/tHhh1ttHk3/

and other sites, the difference in weight between 360p and 1080p video is huge on mail.ru site and I tried to play this streaming video with QMPlay2 but my laptop is old low cpu and low internet connection so I deduce that QMPLay2 chose the best quality 1080p and we hope QMPlay2 will give us the choice to choose 360p quality please, thank you very much!

https://my.mail.ru/mail/muzioladd/video/_myvideo/3171.html?from=videoplayer

**Comment by zaps166** [comment]
I'll try to add it somehow, but later.

Currently you can set `sd` parameter, see:
![Zrzut ekranu_20240815_220633](https://github.com/user-attachments/assets/6659ce12-0d8e-4ece-9f3f-93cb52693d7c)

**Comment by trimechee** [comment]
Thanks for the new important  commit of video quality ! we hope QMPLay2 please will add and highlights sponsor donate button via paypal, buymecoffe, patreon.....at startup of QMPlay2 or in github page of the project  ( or even maybe show some not heavy ads)  to encourage users to donate to help the development of the project and to show thanks and gratitude fr the great generous developer Mr Błażej because I dare say it : QMPlay2 becomes the best media player Number 1 in the world ! 💯 🥇

**Comment by zaps166** [comment]
> Thanks for the new important commit of video quality ! we hope QMPLay2 please will add and highlights sponsor donate button via paypal, buymecoffe, patreon

I'll think about it!

---

I can do a pre-release and upload windows packages for manual download, do you want?

**Comment by trimechee** [comment]
Pre release for the future stable version ? thank you very much ! 💯  me personaly,  i prefer not to tire you Mr Zaps166 i think it's better i would wait like everyone else for the release of the future new stable version in sha Allah §  and for the moment, if i playback mail ru vdeo, i would simply add the worst parameter :)

**Comment by zaps166** [comment]
Ok, so if you don't use new one, no need to release.

**Comment by trimechee** [comment]
I really appreciate your great generosity and really if it was urgent, I would have asked you, but really it's easy to add the word worst and QMPlay2 playback acutually the video in SD quality without any problem ! and so I don't want to tire you without an urgent need, you have already helped me a lot by giving me the solutions to this problem thank you very much :)
