### ISSUE TITLE
Add support of cookies arguments commands of yt-dlp "--cookies-from-browser firefox" to play restircted videos of twitter

### ISSUE THREAD

**Issue by trimechee** [zaps166/QMPlay2#756]
Hello, yesterday i tried to play twitter videos because videos on twitter are very heavy and lag freeze even lowest quality in my old laptop, i tried with Qmplay2, smplayer, potplayer with 3DYD Youtube Source plugin, mpc hc, mpc be, qmplay2...all these players fails to pay twitter videos and have message that i should add cookies commands like --cookies-from-browser firefox....

i am not expert, i tired to add --cookies-from-browser firefox to the yt-dlp engines of these media players but no video playback :(

my idea please is that media player allows to support or add cookies yt-dlp commands arguments --cookies-from-browser firefox --cookies-from-browser chrome --cookies-from-browser r3dfox ........to video stream detected so we can avoid possible bugs and we could playback restirctid videos of twitter in vlc or potplayer or smplayer...thank you very much!

**Comment by zaps166** [comment]
Hello, could you try this:

```diff
diff --git a/src/qmplay2/YouTubeDL.cpp b/src/qmplay2/YouTubeDL.cpp
index fd4a5d24..c64eb6d1 100644
--- a/src/qmplay2/YouTubeDL.cpp
+++ b/src/qmplay2/YouTubeDL.cpp
@@ -63,6 +63,7 @@ QStringList YouTubeDL::getCommonArgs()
     QStringList commonArgs {
         "--no-check-certificate", // Ignore SSL errors
         "--user-agent", Functions::getUserAgent(),
+        "--cookies-from-browser", "firefox",
     };
 
     const char *httpProxy = getenv("http_proxy");
```

?

**Comment by trimechee** [comment]
Sorry I didn't understand well, i.e. I click on ctrl+u and I put all that?

before doing that, I try with a link of a normal youtube video because I suceeded to watch bein sport live channel during the olympics games with QMPlay2 but I didn't try with a normal youtube video and it works !!!

Our so bloved QMPlay2 can playback youtube video in my windows 7 SP1 32 bits without the need of comand cookies-from-browser firefox chrome !!!!
I don't know what changed, maybe new version of yt-dlp, also recently I uninstalled python (installed by elephant extension of FDM).....

I just proposed this idea of ​​being able to add this command cookies-from-browser firefox in case there would be a future playback problem in the future, in addition I recently read a thread that advises against adding this command cookies-from-browser firefox chrome because youtube will block the video so cookies-from-browser firefox seems to have the opposite effect !!

a user said this command cookies-from-browser firefox can work provided that we are not connected and if we are  logged out of our youtube account......

but we still hope, in case youtube complicates things in the future, to be able to easily add custom command please, maybe that will solve some possible problems, for the moment I close my issue of the problem of youtube playback in windows 7 32 bits, and it's up to you to decide Mr Zaps166 if this issue of adding custom command argument should be closed or left open.....

from what I've read, youtube seems to censor only ip addresses that download or use youtube too much.....a trick I found is it seems when we use aria2c and yt-dlp together, and I even added the argument cookies-from-browser firefox, we can download youtube videos and bypass possible blocking, I have used this beautiful downloader which allows us to add custom argument command and allows to add aria2c extension and combine it with yt-dlp to prove this theory :

https://github.com/mhogomchungu/media-downloader

Thanks a lot !

**Comment by RJVB** [comment]
> Hello, could you try this:

>          "--user-agent", Functions::getUserAgent(),
> +        "--cookies-from-browser", "firefox",

Hah, I was just going to suggest this because it actually works (provided you're logged in to YT in firefox I presume):

```
> yt-dlp  "https://www.youtube.com/watch?v=thx-HKhb-X8"
[youtube] Extracting URL: https://www.youtube.com/watch?v=thx-HKhb-X8
[youtube] thx-HKhb-X8: Downloading webpage
[youtube] thx-HKhb-X8: Downloading ios player API JSON
[youtube] thx-HKhb-X8: This video is age-restricted; some formats may be missing without authentication. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[youtube] thx-HKhb-X8: Downloading tv embedded player API JSON
[youtube] thx-HKhb-X8: Downloading mweb player API JSON
ERROR: [youtube] thx-HKhb-X8: Sign in to confirm your age. This video may be inappropriate for some users.
Exit 1
```

```
> yt-dlp --cookies-from-browser firefox "https://www.youtube.com/watch?v=thx-HKhb-X8"
Extracting cookies from firefox
Extracted 1537 cookies from firefox
[youtube] Extracting URL: https://www.youtube.com/watch?v=thx-HKhb-X8
[youtube] thx-HKhb-X8: Downloading webpage
[youtube] thx-HKhb-X8: Downloading ios player API JSON
[youtube] thx-HKhb-X8: Downloading mweb player API JSON
[youtube] thx-HKhb-X8: Downloading player 76c7a082
[youtube] thx-HKhb-X8: Downloading m3u8 information
[info] thx-HKhb-X8: Downloading 1 format(s): 135+140
[download] Destination: Differences of Alternate, Scalpel and Sarod Picking [thx-HKhb-X8].f135.mp4
[download] 100% of   75.46MiB in 00:00:10 at 7.20MiB/s
[download] Destination: Differences of Alternate, Scalpel and Sarod Picking [thx-HKhb-X8].f140.m4a
[download] 100% of   13.31MiB in 00:00:04 at 3.14MiB/s
[Merger] Merging formats into "Differences of Alternate, Scalpel and Sarod Picking [thx-HKhb-X8].mp4"
Deleting original file Differences of Alternate, Scalpel and Sarod Picking [thx-HKhb-X8].f140.m4a (pass -k to keep)
Deleting original file Differences of Alternate, Scalpel and Sarod Picking [thx-HKhb-X8].f135.mp4 (pass -k to keep)
```

(very curious to have an age-limit on a video about guitar picking...)

**Comment by RJVB** [comment]
On Tuesday October 29 2024 12:04:21 trimechee wrote:
>Try with these tools : 

Is the `--cookies-from-browser` option not enough?

QMPlay2 uses its own yt-dlp copy so installing a plugin is probably going to be (much) more work than just adding an argument to its invocation!

**Comment by RJVB** [comment]
FWIW, if the `--cookies-from-browser` option suffices there could be an additional simple choice in the Extensions/YouTube settings, e.g. a drop-down list with the known-supported browsers plus "none".

**Comment by xinghongzhou** [comment]
`https://rdx369h.cloudatacdn.com/u5kj7nej5hclsdgge6to2naflccyc6z2iih2vpiy73whybghcs4x6d2rz6ba/fuukpy0cid~MKlMvLWPf9?token=bslts3zrvx4dbkjq9abcplv7&expiry=1731032487249`
![image](https://github.com/user-attachments/assets/507530c3-7d2b-4c14-9240-720b27054efb)

![image](https://github.com/user-attachments/assets/5330ce32-1a7b-4cc8-b746-5196344d1780)
![image](https://github.com/user-attachments/assets/00c87153-251f-4f4b-b561-618790ecc39a)

```
Windows 10 21H2
yt-dlp 2024.11.04
[QMPlay2 24.06.16](https://github.com/zaps166/QMPlay2/releases/tag/24.06.16)
```

**Comment by zaps166** [comment]
I'll add this option, seems to be useful.

**Comment by zaps166** [comment]
> windows 7 os 32 bits

It's super obsolete and unsupported by upstream. You can put alternative youtube-dl manually (QMPlay2 can prevent auto-updates, I'll add it normally to settings instead of INI-only).

**Comment by zaps166** [comment]
![Zrzut ekranu_20241130_121258](https://github.com/user-attachments/assets/8d6e50f3-e051-4385-952b-cf0180fcd011)

How about this prototype?

**Comment by RJVB** [comment]
> How about this prototype?

LGTM - unless those are the default options? ;)

Looks like I'll be having to refactor my local tweak to unpack the compressed `yt-dlp` "bundle" and use that instead of having to wait for the decompression every time you use the script. I suppose you're still not very interested in merging that?

**Comment by zaps166** [comment]
> unless those are the default options

Not default ofc :smile: 

> Looks like I'll be having to refactor my local tweak to unpack the compressed yt-dlp "bundle" and use that instead of having to wait for the decompression every time you use the script.

IMHO yt-dlp should do it automatically if has permissions to write to directory (or use TEMP until system restart)...

With custom commands user can do it manually, too.

---

Btw. Is your solution automated and respects auto-updates and cleans up after update?

**Comment by RJVB** [comment]
On Saturday November 30 2024 04:51:10 Błażej Szczygieł wrote:
>Not default ofc :smile: 

In fact, if you know of a way to detect the user's default browser you could set the cookies-from-browser option accordingly as it will *probably* be what most users will want to use...

>IMHO yt-dlp should do it automatically if has permissions to write to directory (or use TEMP until system restart)...

Never noticed that it does, but I agree with the principle. And the yt-dlp devs could equally rightfully state that Python should do this automatically with all compressed application bundles - it could use its own cache directories for the byte-compiled scripts for instance.
 
>Btw. Is your solution automated and respects auto-updates and cleans up after update?

Not sure what you mean with "cleans up" (I leave the downloaded executable in place ATM) but otherwise, yes. It also does a simple check if the procedure succeeded. Of course, I'dd add ^^
https://github.com/RJVB/macstrop/blob/master/multimedia/qmplay2/files/patch-ytdlp-unpack.diff

You'll see that I only implemented it for Unix though, basically because I can't test it on MSWin.

**Comment by zaps166** [comment]
Ok, you use `unzip` :smile: Maybe some day, but not for upcoming release. How about Windows - it requires to bundle `unzip.exe` I guess...?

**Comment by RJVB** [comment]
On Saturday November 30 2024 05:15:53 Błażej Szczygieł wrote:
> How about Windows - it requires to bundle `unzip.exe` I guess...?

I suppose it should be possible to write an unzip utility in Python, or possibly even to leverage the MSWin/Explorer native support for zip files somehow. Or just consider that the unpacking overhead is really not the bottleneck on that platform anyway O:^)

**Comment by zaps166** [comment]
Ah on Windows it's in EXE file, so it's more work (and maybe requires to install/bundle entire Python...) :sweat_smile: 

Why this tool isn't written in modern C++ with some network tool or maybe use Qt? :sob: Could be like 100x faster :smile: 

---

I want to prevent auto-downloading this tool for custom path, but is it wise to allow auto-updates for custom path?

**Comment by zaps166** [comment]
I have to be logged in to youtube to make it work from firefox.

**Comment by zaps166** [comment]
Too much for now. Isn't streamlink not sufficient?

**Comment by RJVB** [comment]
On Saturday November 30 2024 06:12:54 Błażej Szczygieł wrote:
>I have to be logged in to youtube to make it work from firefox.

Anything else doesn't really make  sense as far as I can see...

**Comment by RJVB** [comment]
I just upgraded, and had to look for the cookies option - I expected it with the other YouTube options... :D

**Comment by zaps166** [comment]
> I expected it with the other YouTube options

YouTube options are for YouTube panel. I added them in general settings, because it also affects adding any customs URLs as `youtube-dl`.

**Comment by RJVB** [comment]
On Sunday December 08 2024 12:42:21 Błażej Szczygieł wrote:

>YouTube options are for YouTube panel. 

But the cookies are for accessing YouTube unless I really misundertood something ^^

**Comment by zaps166** [comment]
> But the cookies are for accessing YouTube unless I really misundertood something ^^

I don't know :smile: Maybe yt-dlp (now or in the future - didn't read documentation/their code) can use them for other websites, too?

**Comment by zaps166** [comment]
> @zaps166, you gave a thumbs up to rtizer-9's insulting message, me I have never disrespected you, you gave a thumbs up to a message that defames and insults me while I am trying to help the project, ok don't support me but stay neutral and fair, this is not fair and it is disappointing, I ask you to delete your thumbs up from rtizer-9's insulting message [#793 (comment)](https://github.com/zaps166/QMPlay2/issues/793#issuecomment-2527544094)

It was to the last paragraph about using windows + I don't want do do disk cache for now.
