### ISSUE TITLE
flatpak update

### ISSUE THREAD

**Issue by 03tekno** [zaps166/QMPlay2#758]
I would appreciate if you update the flatpak version. Thanks

**Comment by zaps166** [comment]
I forgot about this :sweat_smile: I don't own the Flatpak package, first I have to take over it.

**Comment by 03tekno** [comment]
I am using the Turkman Linux distribution. Unfortunately we don't have it in our warehouse. I have to use flatpak or appimage. :)

**Comment by cultx7191** [comment]
I really love using qmplay2 as my default video/audio player, It would be pretty sweet if it was added to Flathub so it'd automatically get integrated into the system menu rather than having to use gear lever

**Comment by zaps166** [comment]
I have to take over this package first, I'll do it soon.

**Comment by zaps166** [comment]
In meantime you can compile for Flatpak: https://github.com/zaps166/QMPlay2?tab=readme-ov-file#build-for-flatpak

**Comment by zaps166** [comment]
I've send email according to [this](https://docs.flathub.org/docs/for-app-authors/submission/#someone-else-has-put-my-app-on-flathubwhat-do-i-do), but no reply so far.

**Comment by zaps166** [comment]
It'd be nice if anybody else could maintain it on Flatpak. It has already flatpak file here in repo, so updating versions should be easy task anyway...

**Comment by zaps166** [comment]
Update flatpak file and readme needed to self-compilation.

**Comment by zaps166** [comment]
I followed this (2nd point): https://github.com/zaps166/QMPlay2/pull/695#issuecomment-2071043819. Sent email, no feedback since few months... Any ideas @yakushabb :smile:

**Comment by yakushabb** [comment]
@bbhtt might know better than me.

**Comment by bbhtt** [comment]
Easiest would be to open an issue on flathub/flathub. I've sent you an invite to have write access now.

**Comment by zaps166** [comment]
Thanks!

**Comment by zaps166** [comment]
Updated on master branch!

**Comment by zaps166** [comment]
Thank you for your help, QMPlay2 it's up-to-date in Flatpak!
