### ISSUE TITLE
[Feature Request] CUE Sheet support

### ISSUE THREAD

**Issue by Amaunator** [zaps166/QMPlay2#76]
Proszę o obsługę plików CUE które zawierają informacje o utworach audio zawartych w jednym dużym pliuku czy to flac czy ape czy innych. może by program sam szukał pliku CUE o tej samej nazwie co plik audio i żeby nie dublować pokazywał tylko poszczególne ścieżki np. z duzego flac pliku zamiast pl;iku flac? np: jak wczyta album1.flac by szukał album1.cue i tylko pokazał jego zawartość zamiast album1.flac?

**Comment by zaps166** [comment]
As a workaround: Mount CUE in cdemu and play it as a normal AudioCD.

**Comment by Amaunator** [comment]
some media files have CUE sheet embedded inside flac or wv and separate CUE don't exist
