### ISSUE TITLE
Does QMPlay2 support FreeBSD?

### ISSUE THREAD

**Issue by ghost** [zaps166/QMPlay2#760]
I can't find it in freshports, so I guess FreeBSD is not supported. Please add support for FreeBSD. Thank you.

**Comment by zaps166** [comment]
It "should" compile, however I haven't checked FreeBSD for many years. Could you try to compile it from GitHub sources?

**Comment by zaps166** [comment]
At least I can check whether it compiles and runs (and fix when necessary), but I'll not maintain QMPlay2 on freshports.

**Comment by vmz9poa5** [comment]
I don't mind having to compile from source. But it needs to be possible to compile first.

**Comment by zaps166** [comment]
> I don't mind having to compile from source. But it needs to be possible to compile on FreeBSD first.

Could you try and let me know whether it works? If not, I can guide you or install FreeBSD and fix it.

**Comment by vmz9poa5** [comment]
I have not yet tried to compile and run QMPlay2 in FreeBSD.

**Comment by zaps166** [comment]
QMPlay2 is compiling and working on FreeBSD 14.1. You have to install required packages to compile and run the software: `pkg install cmake ninja qt6 pkgconf taglib rubberband portaudio`. Compilation: 
- `cmake -B build -S. -DCMAKE_BUILD_TYPE=Release -G Ninja -DUSE_PCH=ON`
- `ninja`
- `ninja install/strip`

For yt-dlp, install `python3`.
