### ISSUE TITLE
Disaster : yt-dlp dropping support for Python 3.8, our beloved QMPlay2 will no longer support windows 7 32 bits os ? or QMPlay2 will use alterantive yt-dlp made by Mr Nicolaasjan for 32 bits version ?

### ISSUE THREAD

**Issue by trimechee** [zaps166/QMPlay2#767]
Hi, I am sad to discover this Announcement: Dropping support for Python 3.8 ::

This will increase the minimum required Windows version to Windows 8; the yt-dlp release executables will no longer support Windows 7 or Windows Server 2008 R2.

Users on Windows 7 and Windows Server 2008 R2 will need to consider alternative options such as @nicolaasjan['s unofficial builds](https://github.com/nicolaasjan/yt-dlp/releases) if upgrading your operating system is not possible.

https://github.com/yt-dlp/yt-dlp/issues/10086

is our beloved QMPlay2  going to drop the 32-bit version for windows 7 os ?

we hope that windows7 os will continue to be supported please!
I use windows 7 and probably many people still have old laptops that are still functional, thank you!

**Comment by zaps166** [comment]
`yt-dlp` is external tool, it's out of scope.

I doubt the [unofficial builds](https://github.com/nicolaasjan/yt-dlp/releases) will be supported for long time.

---

You can manually replace the yt-dlp `exe` file in `%AppData%\QMPlay2` (rename unofficial exe if needed to replace existing file) directory with the unofficial version and it should follow the unofficial updates.

**Comment by nicolaasjan** [comment]
> You can manually replace the yt-dlp `exe` file in `%AppData%\QMPlay2` (rename unofficial exe if needed to replace existing file) directory with the unofficial version and it should follow the unofficial updates.

Unfortunately the unofficial updates can't be invoked with `-U`.
They have to be manually updated from [Releases](https://github.com/nicolaasjan/yt-dlp/releases).

> I doubt the unofficial builds will be supported for long time.

I will do my best, but I'm not so young any more...
Besides that, I have to build the Windows XP version with a lower PyInstaller version (5.13.2) and I don't know how long that will work.

**Comment by nicolaasjan** [comment]
> and having the immense generosity to add a 32-bit Windows 7 version while you are using Windows XP!

(offtopic)

Actually I'm using Linux Mint 21.3 64bit on an old Intel Core i5-4670 with Intel Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics.

The Windows machines are all virtual, but run fast on SSD. :)
The Windows XP machine starts up to a usable desktop in ~10seconds.

![Schermafdruk op 2024-10-19 20-23-10](https://github.com/user-attachments/assets/56de8048-c553-44f5-9bd5-c0e6826c527b)

**Comment by zaps166** [comment]
> but fortunately I found 3 rare software that allow us to easily disable the windows 11 antivirus and I hope to test them if I get a new laptop windos 11 in sha Allah!

Try to run safe mode and do it in regedit with instruction from network. Better to avoid any software :smile: Also don't forget to disable some telemetry.
