### ISSUE TITLE
Commit a6c0170 broke showing of album covers online radio

### ISSUE THREAD

**Issue by SergDL** [zaps166/QMPlay2#770]
Commit a6c0170 from April 28 broke showing of album covers online radio. On the screenshot QMPlay 06.24.16, on the left without this commit, on the right the appimage version.
![2024-10-29 22-56-39](https://github.com/user-attachments/assets/57b13393-d65f-474d-9f8f-0d83ddb2289b)

**Comment by zaps166** [comment]
Strange, mentioned commit for sure breaks it, but 259516221a8dbd9d9cb0aa102e0cf4e4176c8d7b is to fix it in different attempt.

**Comment by zaps166** [comment]
Aaaa, covers, not lyrics :sweat_smile:

**Comment by SergDL** [comment]
Everything works, thanks.
