### ISSUE TITLE
Hello, may I ask how to compile executable files for Windows?

### ISSUE THREAD

**Issue by wankaiming** [zaps166/QMPlay2#771]
Is there a tutorial on cross compiling using the arch operating system?
Or a tutorial compiled on the Windows operating system using mingw64?

**Comment by zaps166** [comment]
Cross compilation is similar to Linux native compilation.

Install/compile all required dependencies for mingw-w64 (e.g. from AUR, however you may modify them to not compile unneeded dependencies) and run (example, adjust parameters if not working for you):
```
x86_64-w64-mingw32-cmake -S . -B build-win64 -DCMAKE_BUILD_TYPE=Release -GNinja -DCMAKE_INSTALL_PREFIX="$PWD/install" -DCUSTOM_LIBQMPLAY2_LIBRARIES="libass.dll.a" -DCUSTOM_AUDIOCD_LIBRARIES="libcdio.dll.a libcddb.dll.a" -DCUSTOM_PORTAUDIO_LIBRARIES="libportaudio.dll.a" -DCUSTOM_CHIPTUNE_LIBRARIES="libgme.dll.a libsidplayfp.dll.a" -DCUSTOM_GUI_LIBRARIES="libtag.dll.a" -DTAGLIB_STATIC_LINK=OFF
ninja -C build-win64 install/strip
````

Next copy needed files from `/usr/x86_64-w64-mingw32` into `$PWD/install` and run (see my Windows packages as reference).

**Comment by zaps166** [comment]
Compilation instruction for Windows on Windows is here: https://github.com/zaps166/QMPlay2/wiki/Compilation-on-Windows-x86-64 (a bit obsolete for now, but still more-or-less relevant for Qt 6.x).

**Comment by wankaiming** [comment]
@zaps166  Thank you very much for your reply. I will refer to the tutorial again and try again
