### ISSUE TITLE
Weird downloaded media filenames

### ISSUE THREAD

**Issue by RafaelLinux** [zaps166/QMPlay2#778]
I usually download mp3 files from "Media browser" without issues. However, when I was looking for that files in the folder where QMP2 download files, I didn't find my recently downloaded files by their names. The, I noticed the names assigned are not as usually:

![image](https://github.com/user-attachments/assets/b37e5bf1-5bc4-4900-bb25-17f7cd7997b7)
![image](https://github.com/user-attachments/assets/27e5f9dd-2167-4c84-83c1-971ecb75c1e4)
Any suggestion?

**Comment by zaps166** [comment]
It takes part of URL as a name.

**Comment by RafaelLinux** [comment]
What do you mean? That always worked fine. Maybe is a change in myfreemp3.

**Comment by zaps166** [comment]
Looks like Qt 6.8.0 bug (didn't check 6.7.3 yet) or they intentionally changed behavior making software works differently after Qt update?

**Comment by RafaelLinux** [comment]
So, will it be fixed in next release?

**Comment by zaps166** [comment]
Yes. Temporarily you can use older Qt.

**Comment by RafaelLinux** [comment]
Reverting to previous versions of QT is becoming increasingly complicated because some databases (like akonadi or digikam) change structure and there is no backward compatibility, so I will have to wait for your next version.

Thank you very much for resolving it so quickly.

**Comment by zaps166** [comment]
Ok!

**Comment by zaps166** [comment]
I think it's because of Qt 6.8.0 QML change mentioned in change log:

> 14bb25f69c QJSEngine: Treat empty string literals as non-null, empty QStrings Assigning an empty JavaScript string to a property of type QString now produces only an empty QString, not a null QString.

I was checking for null QString - this behavior has been changed in 6.8.0, so it changes application behavior. Bad from Qt side to do such things. IMHO they should do it for Qt 7.0.0 and communicate this change better...

**Comment by zaps166** [comment]
I see :sweat_smile:

**Comment by zaps166** [comment]
KDE is based on Qt, Qt is developed mostly by different people, but they has similar problems with breaking things (even if it is maybe better now - breaks compatibility with just an update, not major version change).

KDE removed ksysguard, but luckily there's a Qt6 fork available on AUR which works maybe better than official Qt5 app :smile:

**Comment by zaps166** [comment]
It should be working correctly in Qt 6.8.x and 24.12.06!
