### ISSUE TITLE
D3D11VA: Black screen when WMV1 and WMV2 video decoding

### ISSUE THREAD

**Issue by Realex-fire** [zaps166/QMPlay2#779]
Hello,
When trying to decode any `WMV1` or `WMV2` video using `D3D11VA` decoder, a black screen appears. `WMV3` decodes successfully by `D3D11VA`, but other decoders are skipped. Tested on my Intel and NVIDIA cards.

Probably related issue: `DXVA2` decoder with legacy renderers is not skipped when decoding `WMV1` or `WMV2` video and does not work correctly.

Could you please check this?
Thank you.

**Comment by zaps166** [comment]
Hello, could you link URLs for these videos or send via email?

**Comment by zaps166** [comment]
I don't know why, I blocked them, so software decoder will be used.

**Comment by zaps166** [comment]
WMV1 and WMV2 fallbacks to software decoder on DXVA2. D3D11VA is fixed on master branch (also will fallback to software decoder).

How to check WMV3 videos?

**Comment by zaps166** [comment]
Thanks, fixed!

**Comment by zaps166** [comment]
WMV1 and WMV2 are skipped in DXVA2, WMV3 works with OpenGL now.

**Comment by zaps166** [comment]
Fixed, thanks!

**Comment by zaps166** [comment]
So many weird codecs from MS :sweat_smile:

**Comment by zaps166** [comment]
Allowed for supported codecs only, thanks.
