### ISSUE TITLE
Add quick easy feature "add external audio' to video only file 

### ISSUE THREAD

**Issue by trimechee** [zaps166/QMPlay2#781]
Hi, when I use the extension:

https://github.com/chandler-stimson/live-stream-downloader

to donwload anime streaming videos,

sometimes there is streaming platform, maybe to make more difficult to donwload their streams, they seperate the stream in 2 independent streams: audio only file and video only file, actually the extension Live stream donwnloader can only dnwload the seperate streams audio only and videos only files but can't merge them internally and the developer advises me to use ffmpeg to merge audio only  and video only  streams or use vlc player that has feature ti add external audio to video only stream.....

i don't like to wait for ffmpeg merge and i don't even know how to merge audio and video with ffmpeg commad lines..... also i have old weak cpu eee pc , i try the option add external audio of Vlc player,  it works but it is too long process difficult to add external audio to video only file, so we hope please our beloved QMPlay2 will add quick easy feature to add external audio to video only file, maybe with keyboard or mouse shortcut, thanks!

**Comment by xinghongzhou** [comment]
It is better to provide a command line parameter to load external audio, just like --input-slave in VLC, so that all problems are solved. The loaded content can be in the form of a local file or a remote audio stream, such as: http://xxxx.mp3, etc.

**Comment by xinghongzhou** [comment]
It is better to provide a command line parameter to load external audio, just like --input-slave in VLC, so that all problems are solved. The loaded content can be in the form of a local file or a remote audio stream, such as: http://xxxx.mp3, etc.

Like the following:
```
QMPlay2.exe --audio=C:\Users\Name\Audio\test.mp3
QMPlay2.exe --audio=https://github.com/zaps166/QMPlay2/test.mp3
```

**Comment by zaps166** [comment]
You can do:

- select `FFmpeg`
- write every path in brackets `[]`

![Zrzut ekranu_20241211_083942](https://github.com/user-attachments/assets/5840ca1e-a68f-4010-8795-e7da32b8843c)

The path can be http(s) URL to direct stream or path to local file like `C:\whatever.mp3`. You can see more streams in information panel, so you can switch them there.

**Comment by DomoMKT** [comment]
you can easily merge those separate streams into a single file without waiting for ffmpeg commands by checking out [www.nemesyslabs.com](https://www.nemesyslabs.com) and using their high-quality text-to-speech conversion with extremely low latency.
