### ISSUE TITLE
Audio Pitch Changes When Increasing Video Speed

### ISSUE THREAD

**Issue by Evren-os** [zaps166/QMPlay2#783]
**Description**  
When increasing the playback speed in QMPlay2 (`qmplay2-git` from AUR) on CachyOS, the audio pitch changes noticeably. For example, male voices become high-pitched, resembling a child's voice.  

**Steps to Reproduce**  
1. Open QMPlay2.  
2. Play any video.  
3. Increase the playback speed.  
4. Notice the audio pitch changes with speed.  

**Expected Behavior**  
The playback speed should increase without altering the audio pitch.  

**System Information**  
- **OS:** CachyOS  
- **Package:** `qmplay2-git` (AUR)  

**Troubleshooting Attempts**  
- Tested with multiple videos.  
- Reviewed configuration settings, but no solution found.  

Any insights or fixes would be greatly appreciated!

**Comment by zaps166** [comment]
"Playback->Keep audio pitch" (`P` hotkey to toggle via keyboard) :smile_cat:

The default option is to not keep the pitch, just select this option from menu or use hotkey.
