### ISSUE TITLE
Videos cannot be played in the command line.

### ISSUE THREAD

**Issue by xinghongzhou** [zaps166/QMPlay2#786]
Videos cannot be played in the command line.

Hi everyone! I am planning to integrate QM2 into other applications, but I found that I cannot play videos, for example:
```
QMPlay2.exe 'https://www.youtube.com/watch?v=-SdVnhLupRs'
```

**Comment by zaps166** [comment]
Please give me more details. It's working correctly on my Linux.

**Comment by xinghongzhou** [comment]
Oh! I forgot, I use Windows 10 19044 with QMPlay2 24.06.16

**Comment by zaps166** [comment]
Checked on Windows, it's working, too. Just use `"` instead of `'`.

**Comment by xinghongzhou** [comment]
I just tried it and it works, maybe it’s a network problem.

**Comment by xinghongzhou** [comment]
So I turned it off.
