### ISSUE TITLE
Panel size restores to default

### ISSUE THREAD

**Issue by Digitalone1** [zaps166/QMPlay2#788]
Hello, thanks for this player.

If I change the size of the main panel (i.e. increasing the video widget and reducing the playlist) and close the application, when I reopen the player, the panel is restored to the default size.

Is this behaviour intended or am I doing something wrong?

My system is Gnome Wayland on Arch Linux.

**Comment by zaps166** [comment]
Hello!

It's not correct, I use Xfwm4 on Xorg and it persists settings. Could you check XCB backend `QMPlay2 -platform xcb`?

**Comment by zaps166** [comment]
Quickly checked Wayland backend on Weston - it works correctly. Maybe Gnome is doing something weird with window when launching application?

**Comment by zaps166** [comment]
Also works correctly on Sway.

**Comment by zaps166** [comment]
I don't have GNOME installed, but I have KDE, but can't test there, because since few months I just can't launch KDE in Wayland - it just hangs and do nothing. I have to kill a few processes to unlock system and launch Xfce4 again. I don't know what's going on with my KDE (KDE Xorg session runs) :rofl:

**Comment by Digitalone1** [comment]
I run `QMPlay2 -platform xcb` and the panel is not restored either. But I understood which is the problem. 

I launched the app normally and closed it not maximized. At the next startup the panel is restored at the previous position. The problem is that if I close it maximized, the panel returns at the default position (or maybe not the real default, but still not at the previous one).

The issue is not Wayland. Maybe the app restores the size before applying the maximized state?

**Comment by zaps166** [comment]
It's not Wayland, it's more like GNOME is doing unneeded resizing while launching application which changes the layout.

Do you have any other DE than Gnome to test? It also should keep panel sizes when you close it maximized. I also checked on Windows 10 now - no issues (closed maximized or not).

**Comment by Digitalone1** [comment]
> It's not Wayland, it's more like GNOME is doing unneeded resizing while launching application which changes the layout.
> 
> Do you have any other DE than Gnome to test? It also should keep panel sizes when you close it maximized. I also checked on Windows 10 now - no issues (closed maximized or not).

Please, read my update above, the same is happening when I run `QMPlay2 -platform xcb`. The app does no retain the panel position when resized/maximized.

**Comment by Digitalone1** [comment]
> It's not Wayland, it's more like GNOME is doing unneeded resizing while launching application which changes the layout.

I don't think that Gnome has the power to change the position of the panel when a Qt app is maximized/reduced.

**Comment by zaps166** [comment]
> The app does no retain the panel position when resized/maximized.

That's true. But when you don't manually resize/maximize window and you set panel size and you will go full screen and back or just close/open application - panels size are retained.

The only idea is that GNOME resizes window when closing/launching application, so it can't retain panels sizes...

> Please, read my update above, the same is happening when I run

I thought to check outside GNOME (if Wayland, try maybe: KDE, Sway, Weston) - does it work for you as expected there?

**Comment by Digitalone1** [comment]
> The only idea is that GNOME resizes window when closing/launching application, so it can't retain panels sizes...

Yes, maybe this is the reason. After various attempts, I managed to restore the panel size in maximized state. 

1. I stretched the window to cover the entire screen (like if it was maximized, but not in maximized state), then closed the app.
2. At the next reopen, the panel is in the right position in the maximized window (maybe because Gnome sees it covering the entire screen and maximizes it automatically).

So Gnome saves the size of the window prior to maximize it and, at the next reopen, it restores that size and then maximize.

Anyway, this issue could be resolved if the panel retains the same aspect ratio when the window is manually resized or maximized.

**Comment by zaps166** [comment]
> I can't check outside Gnome.

Ok.

> Anyway, this issue could be resolved if the panel retains the same aspect ratio when the window is manually resized or maximized.

Sure, but it looks complicated - Qt manages `QDockWindow` somehow automatically when resizing a window.

> So Gnome saves the size of the window prior to maximize it and, at the next reopen, Gnome restores that size and then maximize.

Looks like it's true. Maybe workaround is possible, but I have to install GNOME and see what's going on there... Are there any possibility to tell GNOME to don't apply any logic on window (QMPlay2 manages window geometry itself)?

**Comment by Digitalone1** [comment]
> Are there any possibility to tell GNOME to don't apply any logic on window (QMPlay2 manages window geometry itself)?

I don't think so.

Anyway this seems an issue affecting another use case. I have two monitors and the app is maximized on the first one. If I move it on the second monitor which has a different resolution, the app should resize and the aspect ratio of the panel will change.

So, if I want to retain the same proportion, I should adjust the video widget every time I move the app from a monitor to another.

**Comment by zaps166** [comment]
> So, if I want to retain the same proportion, I should adjust the video widget every time I move the app from a monitor to another.

That was never possible (except moving to another monitor is without resizing window).

Qt is doing it automatically, idk what can be done about it. I have to look at this some day.

**Comment by Digitalone1** [comment]
If Qt does not offer a way to set the position of the separator between the video and the info/playlist sidebar, this will never be solved.

Ideally, you could save the proportion of the video width related to the width of the main window. If Qt let you do something on window resizing (maybe with signals), you could get the new window width and calculate the new video width using the saved proportion, then apply it to retain the same aspect ratio. Obviously, on every video resize, you should calculate a new updated proportion and save it.

**Comment by zaps166** [comment]
> If Qt does not offer a way to set the position of the separator between the video and the info/playlist sidebar, this will never be solved.

I can resize panels, so it should be possible somehow. But when window is resizing, Qt is doing it automatically, so I have to block it somehow, recalculate and put my sizes.

I'll take a look at this some day :smile:

**Comment by zaps166** [comment]
Checked quickly possibility to maintain panels sizes, looks like it's not easy.

**Comment by zaps166** [comment]
I launched GNOME on Wayland, but I can't reproduce - panels (re)stores sizes on QMPlay2 restart :thinking:

**Comment by Digitalone1** [comment]
> I launched GNOME on Wayland, but I can't reproduce - panels (re)stores sizes on QMPlay2 restart 🤔

Indeed, as I pointed out in a previous comment, this happens when you close and restart the app in the maximized state (I noticed it because I mainly use the app maximized).

Maybe this happens because, in the normal state, Gnome saves the size. In the maximized state, instead, Gnome saves only the maximized state and retains the previous size. When you close and restart, Gnome shows the app in the previous saved size and then maximize (this leads to a redraw).

I don't see this redraw happening, but somehow the internal panel loses its position. The workaround is to have the app in the normal state and expand it to cover all the the screen (except the top panel). Then close and restart, so you have it already maximized, without redraw and with the previous panel size.

Anyway, saving the proportion is not only good for this Gnome use case, but also when you move the app from a monitor to another, when it redraws and loses the panel size on every desktop.

**Comment by zaps166** [comment]
> this happens when you close and restart the app in the maximized state

Oh I missed maximized state on GNOME, sorry! But in non-maximized state QMPlay2 launches in top-left corner on GNOME, which is also bad...

> Anyway, saving the proportions is not only good for this Gnome use case, but also when you move the app from a monitor to another (with different resolutions), when it redraws and loses the panel size on every desktop.

I'm aware, but it's a bit hard to tame panel sizes (no idea so far) :sweat_smile:

**Comment by Digitalone1** [comment]
XWayland? Isn't the app using the native Wayland?

**Comment by zaps166** [comment]
> > Oh I missed maximized state on GNOME, sorry! But in non-maximized state QMPlay2 launches in top-left corner on GNOME, which is also bad...
> 
> Yes, I think that's because Gnome saves the size, but not the position. As far as I know, the feature to restore also the position may be available in Gnome 48: https://www.phoronix.com/news/Mutter-XDG-Session-Management

QMPlay2 saves and restores entire window geometry using `QWidgtet::setGeometry()`. If GNOME overrides it, for me it's a GNOME bug (or at least Qt bug).

**Comment by zaps166** [comment]
> Hello @zaps166, Some time ago, I also noticed that the position of the vertical separator between widgets in maximized state QMPlay2 could get lost on a Wayland session of GNOME. It would be nice if you could fix it if possible.
> 
> PS: The AppImage build on GNOME regularly displays a message that the application has frozen and asks for a force close, although the application has not frozen. It's easy to get around this by disabling such messages. Is there probably some kind of XWayland bug?
> 
> Thanks.

Does it work correctly on anything except GNOME?

**Comment by zaps166** [comment]
@Digitalone1 Could you test dock resizing on branch `dock-resize`?

**Comment by Digitalone1** [comment]
> QMPlay2 saves and restores entire window geometry using `QWidgtet::setGeometry()`. If GNOME overrides it, for me it's a GNOME bug (or at least Qt bug).

I don't know into details how it works, but maybe under Wayland it's the compositor doing this things and Gnome sets the geometry in its way. Maybe in other compositors the app starts already maximixed while under Gnome it's restored in the previous saved size and then maximized...

> @Digitalone1 Could you test dock resizing on branch `dock-resize`?

I will try it. But how can I install the executable in a specific directory without conflicting on the AUR build?

**Comment by zaps166** [comment]
@Digitalone1 Starting maximized should be "fixed" on master branch (AUR: `qmplay2-git`)

> I will try it. But how can I install the executable in a specific directory without conflicting on the AUR build?

```sh
git clone https://github.com/zaps166/QMPlay2
cd QMPlay2
git submodule update --init
git checkout origin/dock-resize
cmake -B build -S . -GNinja
ninja -C build
build/src/gui/QMPlay2
```

> > Does it work correctly on anything except GNOME?
>
> Maybe yes, but GNOME is used by a lot of people... It seems to me that the GNOME developers think they are doing everything right 😅

Every software has bugs including FFmpeg, Qt, GNOME.

On GNOME:
- the `localsearch-extractor-3` is using 100% of my CPU core (???)
- Xorg: QMPlay2 on full screen has screen tearing - if 24-bit depth window fill entire screen area and is unredirected and compositor is not repainting and MAILBOX or FIFO is enabled - it's impossible to have screen tearing :astonished: 
- Xorg: "Bypass compositor in full screen" option is not working (still screen tearing), but when context menu is open - in this case GNOME's compositor is painting video
- Wayland: Mouse cursor has latency (latency when moving mouse is random (sometimes lower, sometimes higher), sometimes cursor stutters on screen)
- window positioning is different in GNOME Xorg and GNOME Wayland
- Wayland: Sometimes I have visual glitches when toggling full screen (make Qt bug, maybe GNOME - I don't know)

**Comment by Digitalone1** [comment]
> * Wayland: Sometimes I have visual glitches when toggling full screen (make Qt bug, maybe GNOME - I don't know)

I saw this one too. I'm using mpv and the fullscreen toggling has no issues. It could be also Vulkan since I suppose qmplay uses it while mpv by default still uses OpenGL.

Regarding mouse latency, I don't notice it. Maybe I'm used to it and just don't care. Which is you're graphic card. I'm on AMD.

**Comment by Digitalone1** [comment]
> @Digitalone1 Starting maximized should be "fixed" on master branch (AUR: `qmplay2-git`)

Very nice. I will try it.

Meanwhile, I tested the `dock-resize` branch and it fixes the issue.

https://github.com/user-attachments/assets/6e9f62f4-491b-4eb8-bbca-0f8f781512e9

Thanks @zaps166

**Comment by Digitalone1** [comment]
> @Digitalone1 Starting maximized should be "fixed" on master branch (AUR: `qmplay2-git`)

Tested it. I confirm it's working. :+1:

**Comment by zaps166** [comment]
> I saw this one too. I'm using mpv and the fullscreen toggling has no issues. It could be also Vulkan since I suppose qmplay uses it while mpv by default still uses OpenGL.

I have visual glitches on OpenGL and QPainter output (which is the simplest and doesn't create native windows inside), so it looks like Qt+Wayland has a bug and/or GNOME doesn't send events to Qt to update UI. I don't know, but maybe it's out-of-scope bug (on Weston it's going black instead of visual glitch, on Sway it's working correctly)... Maybe consider using XWayland? I want to test on KDE, but it still can't launch on Wayland (idk what's wrong).

**Comment by Digitalone1** [comment]
> Maybe consider using XWayland?

Honestly I don't even know if I'm using Wayland even if I'm on the Wayland session. But judging from the sharpness of the fonts and the `qt6-wayland` package installed, I shouldn't be on XWayland  (I'm using the fractional scaling and the fonts on XWayland are blurry). But, anyway, this is not a big issue to me, it does not happen always.

**Comment by zaps166** [comment]
> Meanwhile, I tested the dock-resize branch and it fixes the issue.

Nice! I can see one issue - Qt changes panels height a bit when resizing window after panels resize. I'll add it as an non-default option for now.

**Comment by zaps166** [comment]
> Honestly I don't even know if I'm using Wayland even if I'm on the Wayland session. But judging from the sharpness of the fonts and the qt6-wayland package installed, I shouldn't be on XWayland (I'm using the fractional scaling and the fonts on XWayland are blurry). But, anyway, this is not a big issue to me, it does not happen always.

Ok. I don't know much about XWayland, but on Xorg I have (pseudo)fractional scaling 170% - no issues with font sharpness or UI size (Qt and GTK3).

**Comment by zaps166** [comment]
> > Oh I missed maximized state on GNOME, sorry! But in non-maximized state QMPlay2 launches in top-left corner on GNOME, which is also bad...
> 
> Yes, I think that's because Gnome saves the size, but not the position. As far as I know, the feature to restore also the position may be available in Gnome 48: https://www.phoronix.com/news/Mutter-XDG-Session-Management

It's about session recovery :thinking: 

But as long as Wayland doesn't support moving windows outside compositor it's bad for some applications. The question is: Does Wayland support moving windows or just Qt didn't implement it? Also see [this](https://gitlab.xfce.org/panel-plugins/xfce4-whiskermenu-plugin/-/issues/112).

**Comment by Digitalone1** [comment]
> It's about session recovery 🤔

Indeed. To recover the session I suppose you save the position. But maybe I'm wrong and they will recover the session reopening all the apps on random positions and workspaces...

**Comment by zaps166** [comment]
Update UI is a bad idea. I already have a lot of workarounds for Qt event bugs, so no more workarounds for not my bugs - it "works" (remember, it's Wayland - it's like beta). I think it's better to see what is wrong and report bug to Qt or some Wayland compositors.

**Comment by zaps166** [comment]
> It would be nice if this beta wasn't used by default almost everywhere...

Not my decision to push Wayland as default for some DE...

**Comment by zaps166** [comment]
Even if it's Qt bug, also not my decision to use Wayland by default. I keep what Qt chose and some users wants this behavior, too.

**Comment by Digitalone1** [comment]
> It would be nice if this beta wasn't used by default almost everywhere...

I think this is a misunderstanding. Wayland is just a set of protocols. If something is wrong in this case, it's likely Qt, Vulkan or the compositor (the implementation of the protocols).

**Comment by zaps166** [comment]
> I think this is a misunderstanding. Wayland is just a set of protocols.

Yes, Wayland protocol implementations. It's weird that every compositor implements protocol from scratch and partially does job which should be done by "driver" (like Xorg's `xf86-video-xyz`). Finally users have different bugs and different features on every desktop environment + missing universal tools like `xrandr`, `xinput`, `xgamma`, `xwininfo` :sob: .

> If something is wrong in this case, it's likely Qt, Vulkan or the compositor (the implementation of the protocols).

I can say, it's not Vulkan  - same happens on legacy QPainter output (no Vulkan, no native window here).

Works OK on Sway, so no idea... :roll_eyes: 

On Weston when you're in compact mode and you go back from full screen - entire screen is black until QMPlay2 refreshes...

**Comment by zaps166** [comment]
Need to check KDE, maybe on USB stick will run finally

**Comment by zaps166** [comment]
I don't understand Wayland protocol, so the question is: Is it possible to move window and Qt just didn't implement it?

https://wayland-book.com/xdg-shell-in-depth/interactive.html

**Comment by zaps166** [comment]
Moreover Qt has a lot of bugs especially for more complicated UI full of docks and resizing/hiding widgets. I already have a lot of workarounds in 0ms timers for various missing events...

**Comment by Digitalone1** [comment]
> I don't understand Wayland protocol, so the question is: Is it possible to move window and Qt just didn't implement it?
> 
> https://wayland-book.com/xdg-shell-in-depth/interactive.html
Why do you want to move the window? I think the compositor and the user should be the ones to move the window. Then there's the issue that the position is not remember, but there should be a a protocol for that too (don't know if it's already merged and implemented). 

> Yes, Wayland protocol implementations. It's weird that every compositor implements protocol from scratch and partially does job which should be done by "driver" (like Xorg's `xf86-video-xyz`). Finally users have different bugs and different features on every desktop environment + missing universal tools like `xrandr`, `xinput`, `xgamma`, `xwininfo` 😭 .

Yes, that sucks, but a good DE would implement them anyway.

**Comment by Digitalone1** [comment]
> Moreover Qt has a lot of bugs especially for more complicated UI full of docks and resizing/hiding widgets. I already have a lot of workarounds in 0ms timers for various missing events...

Gtk and libadwaita have also their bugs. Nothing is perfect. I was testing the port of Easy Effects on Kirigami and all of a sudden the dark mode in not working anymore.

**Comment by zaps166** [comment]
> Gtk and libadwaita have also their bugs. Nothing is perfect.

Ofc.

> I was testing the port of Easy Effects on Kirigami and all of a sudden the dark mode in not working anymore.

I have all Qt apps in dark mode (I use Xfce4), but Spectacle (KDE) is mixed and I have dark background and black fonts and white buttons :sweat_smile:

**Comment by Digitalone1** [comment]
> I have all Qt apps in dark mode (I use Xfce4), but Spectacle (KDE) is mixed and I have dark background and black fonts and white buttons 😅

Till a few weeks ago, Kirigami apps had working dark mode on Gnome while Qt apps were showing light. After the update of both Qt and Kirigami, Qt apps have been fixed and the dark theme is correctly loaded while Kirigami apps are now broken and dark mode is not working. 😂

**Comment by zaps166** [comment]
> > Does it work correctly on anything except GNOME?
> 
> Hello [@zaps166](https://github.com/zaps166), I have determined what this bug is related to. It is `libX11-xcb.so.1` library in your AppImage. Versions prior to 1.7 cause freezes on the latest Fedora with GNOME and XWayland.
> 
> Maybe you can try adding a library `libX11.so.6` related to your library `libX11-xcb.so.1` from Ubuntu 16.04? You can also try updating `libX11-xcb.so.1` to the [version](https://packages.ubuntu.com/en/jammy-updates/libx11-xcb1) from Ubuntu 22.04 (recompile on Ubuntu 16.04).
> 
> But why don't you just add `libX11.so.6` to your AppImage? Thanks.

If it works on Xorg, but not on XWayland, isn't it XWayland or GNOME issue? How about KDE for example?

**Comment by zaps166** [comment]
It's unrelated to "Panel size restores to default" issue. It's unrelated to QMPlay2 source code. Does it work on GNOME Xorg session?

**Comment by zaps166** [comment]
> Yes, I can't reproduce it on GNOME Xorg session. For me it only happens on GNOME with XWayland.

I don't know. AppImage uses old libraries, but I don't see any issues except this.

I think `libX11.so.6` is mandatory system library and shouldn't be bundled here...

Maybe remove `libX11-xcb.so.1`? It's also system library which should be everywhere?

First - GNOME is weird. Second - AppImage may have issues due to old/incompatible libraries - it's common case, unfortunately (e.g. if older libstdc++ is used from AppImage and other system libs newer version).

**Comment by zaps166** [comment]
> The official [Krita](https://download.kde.org/stable/krita/5.2.6/krita-5.2.6-x86_64.appimage) AppImage does not contain these libraries, but the official [Inkscape](https://inkscape.org/release/inkscape-1.4/gnulinux/appimage/dl/) AppImage contains libX11.so.6 only.
These AppImages do not contain libX11-xcb.so.1.

AppImage packaging is messy sometimes and missing some libraries or providing (enforcing) others which shouldn't be there or should be optional (if no / too old in system). I can't be suggested by any other AppImage.

One question - do removing `libX11-xcb.so.1` fixes GNOME issue?

**Comment by zaps166** [comment]
> Can you upload an AppImage with -2 suffix or will that be for the next release?

You know how to launch it anyway, so not needed to upload new package.

**Comment by zaps166** [comment]
I finally managed to run Plasma Wayland (yeah, qt6ct...). I can confirm QMPlay2 runs OK natively (much better than on GNOME), but running through XWayland is perfect (can see screen tearing on vsync off, VRR works better, no issues when resizing panels with Vulkan video, no issues with displaying panels on full screen). In both backends (XWayland and native) I don't see graphical glitches like in GNOME.

**Comment by zaps166** [comment]
We were talking about Wayland here, I've opened a pinned issue about know issues there.

**Comment by Realex-fire** [comment]
> You know how to launch it anyway, so not needed to upload new package.

Hello @zaps166,
I still need to manually modify the AppImage for GNOME. I've tested this on the latest version of Fedora, and the GUI freeze bug is still present (GNOME, XWayland, and AppImage). Is it "out of scope"?

**Comment by zaps166** [comment]
Maybe I forgot to remove this file

**Comment by Realex-fire** [comment]
Yes, your AppImage still contains `libX11-xcb.so.1` file. I thought it was intentional 🙂

**Comment by zaps166** [comment]
I'll remove it for next release, but I'll stop releasing AppImage soon.

**Comment by Realex-fire** [comment]
> I'll remove it for next release

Thanks!

> I'll stop releasing AppImage soon

Maybe increase the minimum Ubuntu (glibc) version and update Qt instead, or is that too much work?

**Comment by zaps166** [comment]
> Maybe increase the minimum Ubuntu (glibc) version and update Qt instead, or is that too much work?

Too much work to keep AppImage builds (packaging on Linux is a pain, you never know which library should be included, which will be missing and which will conflict in the future, also another platform to compile dependencies, etc.). There's no problem on Arch Linux (AUR), some distributions provides QMPlay2 package, otherwise you can use Flatpak.
