### ISSUE TITLE
QMPlay2 24.12.06 generates excessive TGAHandler log entries

### ISSUE THREAD

**Issue by DarkWav** [zaps166/QMPlay2#789]
Every time when opening any video/audio file or YouTube Video with QMPlay 24.12.06, it outputs the message
```TGAHandler::canRead() error while reading the header```
to the logs, but otherwise works fine. Is this intended behavior?

**Comment by zaps166** [comment]
It's unrelated to 24.12.06 release, the same happens on 24.06.16. Maybe it's about recent KDE changes? If I have `kimageformats`  installed, QMPlay2 shows this log when tries to decode an image from empty data.

**Comment by DarkWav** [comment]
Thanks, the fix works!
