### ISSUE TITLE
Great amazing new versin but what should we put in the cookies from browser new section?

### ISSUE THREAD

**Issue by trimechee** [zaps166/QMPlay2#790]
Hi, thank you so much for the new awesome version Mr @zaps166 and specialy the great support of windows 7 os 32 bits  ! 💯 🥇 

so i explore with pleasure the new sensational features of QMPlay2 and i see new section of youtube dl : " cookies from browser " !

it's great ! tahnks ! i tried to put the famous cookies command of yt-dlp :

--cookies-from-browser firefox

but only a part of this command is displayed in the corresponding box, what exactly should we put in this box please ? just the name of the web browser firefox ? without quotes ?

**Comment by zaps166** [comment]
If you use Firefox, just put `firefox` text and press "Apply" button on the bottom of the window.

For more information, see README from: https://github.com/yt-dlp/yt-dlp

**Comment by trimechee** [comment]
Great ! Thank you for your precious help :) 💯 🥇
