### ISSUE TITLE
QMPlay2 doesn't choose SD video quality : QMPlay2 automatically chooses the higher video quality 1080p stream instead of the standard 360p stream despite having chosen the setting: desired video stream quality = SD

### ISSUE THREAD

**Issue by trimechee** [zaps166/QMPlay2#791]
Hi, I try to playback this video, I notice that the playback lags jerk, it's surprising and I discover that QMPlay2 has chosen the highest video stream quality  1080p despite I went to QMPlay2 settings / desired video stream quality and i chose "SD":

https://my.mail.ru/v/goal_net_ru/video/28/1264.html

this video stream has a standard video quality 360p suitable for my old weak eee pc windows 7 OS 32 bits yet QMPlay2 has chosen to playback the HQ stream 1080p which causes me lags jerks, we hope this problem will be solved please, maybe by adding the preset "worst" or "worst video" to the commands sent to yt-dlp, thanks!

**Comment by zaps166** [comment]
Select H264 in youtube settings?

**Comment by zaps166** [comment]
360p is not in preset (I doubt it's really needed), but 480p is available. You should use H.264 codec for slower hardware. Press the "settings" icon on YouTube tab and set accordingly (don't forget to press "Apply" button):

![Zrzut ekranu_20241208_090950](https://github.com/user-attachments/assets/b6802c73-1d9d-4e2a-97f6-e0d6c6d4b83f)

I tested it and it's working to me with up-to-date yt-dlp software.

**Comment by trimechee** [comment]
yesterday When QMPlay2 started choosing me 1080p quality of mail ru video instead of 360p quality, I started to suspect an interference a conflict between the setting desired video stream and module/extension / youtube, yesterday I chose 480p youtube preferred quality leaving default vp9 codec but QMPlay2 still chooses 1080p quality, but I will follow your advice and choose H264 codec, and I will tell you the result, thanks for yout help !

**Comment by zaps166** [comment]
Settings for YouTube are not related to custom URLs.

**Comment by zaps166** [comment]
I didn't notice it's custom URL. I posted a solution somewhere already (I remember it was you). Could you try to find?

**Comment by trimechee** [comment]
So Mr @zaps166 , thanks for your help !

I did new tests, at first I followed your first advice: I choose youtube quality 480p and H264 codec but QMPlay2 continues to choose the 1080p quality of https://my.mail.ru/v/goal_net_ru/video/28/1264.html ,

but the good news, by following your second advice and adding the preset worst and put worst parameter , QMPlay2 finally chooses the 360p quality of mail ru video !!! 💯 🥇

thanks for your help :)

yes exactly Mr Zaps166, I already told you about the video quality problem mail ru video months ago and you answered me that I have to manually add the "worst" parameter while waiting for you to find a way to add this parameter automatically:

https://github.com/zaps166/QMPlay2/issues/755#issuecomment-2292125658

so we hope please that QMPlay2 will offer us an easy way to permanently change the yt-dlp config to add the worst or worst video preset, or modify the setting: "desired video stream" so that it works with custom URLs and urls different from youtube, moreover sometimes the youtube playback works, sometimes QMPay2 tells me it can't use yt-dlp, I think youtube may be blocking QMPlay2, or maybe because I'm using an old eee pc, or maybe because i enable cookies settings, or maybe because change fr legacy rendering.....

anyway we hope please the great vital QMPlay2 will be able to automatically select the worst video stream if we select SD in the desired video stream setting, or maybe add a new "worst" parameter in the setting: "desired video stream" to make things even easier and faster thanks!

**Comment by zaps166** [comment]
Ok, thanks for the link to original issue.

**Comment by trimechee** [comment]
💯 👍
