### ISSUE TITLE
Please add a permanent persistent option to disable aspect ratio to get rid of annoying black bars in my small 10 inch screen !

### ISSUE THREAD

**Issue by trimechee** [zaps166/QMPlay2#792]
Hi, i playback this video:

https://my.mail.ru/v/goal_net_ru/video/28/1264.html

i notice there are black bars at the top and bottom, it is vital for me to get rid of these black bars please because every pixel counts in my small 10 inch screen of my old eee pc, i searched and when i go to the aspect ratio/disable section, the black bars disappear! but the problem when i close QMPlay2 and open a new video, the annoying black bars reappear again so it seems QMPlay2 does not save our preferences regarding the aspect ratio and we hope that there will be a permanent persistent option to disable the aspect ratio in order to remove the black bars permanently, thank you!

**Comment by zaps166** [comment]
Options->Playback settings

Select "Keep aspect ratio". If you want it permanent after restarting QMPlay2, select "Store aspect ratio and zoom in config file". Press "Apply" button.

**Comment by trimechee** [comment]
Great ! Thanks ! 💯
