### ISSUE TITLE
Don't autostart the video if "Remember Playback Position" is checked.

### ISSUE THREAD

**Issue by Rtizer-9** [zaps166/QMPlay2#794]
There are dedicated options given for remembering the accurate playback state like time,audio/video/subtitle stream, zoom, aspect ratio settings and so on but if you use that - specifically the "Remember Playback Position", whenever you open qmplay the first moment it starts autoplaying that local video or starts opening the stream.

I think user should be in control of what  happens first when you open the player and then if you click on that url or local file from recent menu/playlist then only it should start resuming from that exact position with that exact state in which it was being played before the player was closed.

**Comment by zaps166** [comment]
> "Remember playback position for each playlist entry"

It should work. You need longer files (maybe like 10 minutes or more) to trigger this and you must not stop at early begin/end of the playback. Don't remember constrains exactly (need to look at code).

Once you stop playback (let's say, stop > 10 min in the middle), when you resume, you'll notice that icon before the seek slider is available - clicking it will restore playback.

**Comment by zaps166** [comment]
Context menu is Player->Continue playback (or `C` hotkey). Example how it works:

https://github.com/user-attachments/assets/90e743be-80cf-4bc9-9f91-bc107230ae1a

**Comment by zaps166** [comment]
> Don't autostart the video if "Remember Playback Position" is checked

"Remember Playback Position" is designed for autostart. So the "Remember playback position for each playlist entry" is what you really wanted.

Is the issue report still relevant?

**Comment by zaps166** [comment]
> normally a user is going to expect same UI as other players online/offline we see.

It makes no sense cloning another player UI here. It's a different player. I only know how it works in VLC and I don't enjoy this idea at all with appearing annoying top bar asking whether to continue or not :smile: 

---

Added tooltip, renamed this checkbox, thanks!

**Comment by zaps166** [comment]
> Awesome, Happy to be of help. I think it's probably because English is not your native afaik so it's perfectly understandable

Yes, but also "Remember Playback Position" is a very old option. The "Remember playback position for each playlist entry" is a new option which sounds similar, which is misleading, so I changed the old option text. I have now: "Continue last playback when program starts".

> No it's not about cloning, what I simply meant here is that the UI should be intuitive in a manner that users shouldn't have hard time figuring out very simple things like this because we figure out things like this easily only when it's similar just like play/pause/stop button are 99% of the time going to be same icons with similar order in almost all players and similary you'd find "resume" function almost near the playback option.

It means I have to do more research by looking at different software. As I said, I checked only VLC and I didn't enjoy their solution :smile: The minimum length and 1% margins was to prevent storing position for every clicked URL (prevent spam in settings files when user will just listen to the short music or just press next button on various files). The persistent icon in the bottom bar is to not make UI "jumping" like in VLC for example when you get the top bar asking what to do.
