### ISSUE TITLE
tags duplicated

### ISSUE THREAD

**Issue by Amaunator** [zaps166/QMPlay2#80]
![issue](https://cloud.githubusercontent.com/assets/8012951/22196885/47fc4920-e147-11e6-8890-d74aae907ee4.png)

duplicated tags in a playlist and in notifications

**Comment by zaps166** [comment]
Tags are duplicated in FLAC file, so FFmpeg shows all using ";" separator. Tag editor (taglib) unifies them.

It is not a bug, but it doesn't look fine :(

---

In FLAC you can have ID3v1, ID3v2 and native FLAC tags. If you want to cleanup FLAC tags, you can de-duplicate them in tag editor (taglib should leave only native FLAC tags):
- do a change in tags (e.g. add space in title), because QMPlay2 must know that something has been changed,
- press OK,
- open tag editor again and revert the change,
- press OK again.

**Comment by zaps166** [comment]
@Amaunator Does it work properly for you 😄 ?

**Comment by Amaunator** [comment]
nie działa. skompilowałem z githuba przed chwilą
![issue](https://cloud.githubusercontent.com/assets/8012951/22267292/2c7a86fa-e27b-11e6-851d-60f540c3083a.png)

**Comment by zaps166** [comment]
Możesz gdzieś podesłać jeden z tych plików ?

**Comment by Amaunator** [comment]
https://dl.dropboxusercontent.com/u/96123248/03.%20The%20Last%20Shadow%20Puppets%20-%20Calm%20Like%20You.flac

**Comment by zaps166** [comment]
U mnie działa poprawnie po wczorajszym commicie:
![spectacle h16164](https://cloud.githubusercontent.com/assets/6239090/22268319/6038a074-e287-11e6-93ed-d2b8d9af8bc9.png)
Na pewno został skompilowany poprawnie z GITa?

---

Nowy QMPlay2 z tym commitem powinien odświeżyć wpis na playliście po rozpoczęciu odtwarzania. Można też przeładować cały katalog klikając na niego i wciskając "Shift+F5".

**Comment by Amaunator** [comment]
nadal kiszka. kompilowałem z gita z godzinę temu. jak sprawdzic jaki commit był ostatni? może by zacząć podawać w change log jak u Clementine jest?

**Comment by zaps166** [comment]
> może by zacząć podawać w change log

myślałem o dopisaniu short-sha1 do wersji kompilowanej z GIT'a. Ja commit wrzuciłem wczoraj, 23h temu, więc jeżeli kompilowałeś godzinę temu to musi być. Podbiję wersję i przekompiluj jeszcze raz.

**Comment by zaps166** [comment]
> Podbiję wersję

gotowe

**Comment by Amaunator** [comment]
ok. działa. dzięki. 
 przeładowałem liste potem zrestartowałem program i znów przeładowałem. w cache musiał mieć...

**Comment by zaps166** [comment]
:+1:
Po zainstalowaniu nowej wersji trzeba uruchomić program ponownie :) Ja nie pisałem cache, przeładowanie listy musi od razu odświezyć. Odtworzenie piosenki powinno od razu odświeżyć dany plik.
