### ISSUE TITLE
Relative vs Absolute Paths for Portable Version

### ISSUE THREAD

**Issue by TaxicabMessiah** [zaps166/QMPlay2#800]
On windows 11 using the portable version of QMPlay2 I have changed my downloads folder to be internal to the portable folder itself, this way everything is self contained.  But it looks like the program uses the absolute path and not a dynamic or relative path.  This means when I move the folder my downloads will no longer work because they can't find the path.  Just wanted to point this out unless I'm doing something incorrect.

**Comment by zaps166** [comment]
So it should be: If you chose path to the portable directory, it's should keep the relative path.
