### ISSUE TITLE
subtitle problem

### ISSUE THREAD

**Issue by kozroS** [zaps166/QMPlay2#804]
when watching via any online video link, the subtitles disappear when I fast forward. , it's fixed when you turn the subtitle off and on again.

**Comment by zaps166** [comment]
I need more info. You can also send video link via email.

**Comment by zaps166** [comment]
Thenks @Realex-fire 

It looks like a different issue. FFmpeg doesn't demux subtitles from this stream, but when I put paths manually (test as Direct Address):
```
FFmpeg://{[https://mtoczko.github.io/hls-test-streams/test-vtt-ts-segments/720p/2.ts][https://mtoczko.github.io/hls-test-streams/test-vtt-ts-segments/text/1.vtt]}
```
it works correctly. QMPlay2 uses FFmpeg to demux HLS, so maybe it should be reported there?

**Comment by zaps166** [comment]
I see in logs: `[hls @ 0x7f5a00006dc0] Can't support the subtitle(uri: text/main.m3u8)`

**Comment by zaps166** [comment]
Pushed a change which forces it. Not perfect at video start, but works at least.

**Comment by zaps166** [comment]
>  (there is another sample here, but there are a lot of streams and everything freezes for me 😅)

Maybe my change is to revert? Without today's change it plays after longer while, now doesn't play at all (downloading subtitles all the time).

HLS in FFmpeg seems to be very poor for more complicated streams. I don't want to re-implement it for now, hmm... I hope FFmpeg will fix it some day :sweat_smile:

**Comment by kozroS** [comment]
I don't know, but now my problem seems to have been solved a little bit for me. has a change been made?

**Comment by zaps166** [comment]
> I don't know, but now my problem seems to have been solved a little bit for me. has a change been made by you?

I did nothing about it so far. Did you compile from sources? How did you install QMPlay2? @kozroS 

> For me, there are no special differences from the latest release version. Probably something else on my side, but WebVTT works now with basic samples.

Compiled from sources just now? @Realex-fire

**Comment by kozroS** [comment]
probably because I changed the source provider. ffmpeg DXVA2 Decoder priority. my problem seems to be solved for now, I hope it will not cause problems in the future.

**Comment by zaps166** [comment]
> probably because I changed the source provider. ffmpeg DXVA2 Decoder priority. my problem seems to be solved for now, I hope it will not cause problems in the future. opengl may also have solved the problem.

Hmm, it shouldn't make any difference for subtitles. Also Vulkan (with D3D11VA) is preferred and faster as long as you don't have driver issues.

If you think it's a bug there, I can fix, but I need your stream/file to test.

**Comment by zaps166** [comment]
> Yes, but I haven't tested it in detail.
> Maybe then it would be possible to dynamically turn off the subtitle stream if the wait is too long?

I don't know if I can control it, because it's in `avformat_open_input()` function. Maybe I can add it as experimental checkbox (in FFmpeg it's as experimental anyway).

**Comment by zaps166** [comment]
Added checkbox :smile:

**Comment by zaps166** [comment]
I usually watch offline videos with subtitles or load them from text file - no issues here.

About network URLs - I need to check them. Are these URLs use text subtitles or bitmap subtitles? Could you give more details?

**Comment by zaps166** [comment]
:thinking: Checked with YouTube - I have subtitles there, not disappearing when seeking, working normally.

There must have been something else.

**Comment by zaps166** [comment]
Also checked some bitmap subtitles samples (pgssub/dvdsub) - no issues.

**Comment by zaps166** [comment]
Without URL to stream and/or file and configuration (which QMPlay2 package and version used, other QMPlay2 settings like decoder, hwaccel, renderer, etc.) I can't do anything.

**Comment by zaps166** [comment]
It's normal (subtitles appears before the dialog, so if you rewind before dialog in video, but after subtitles packet is delivered, you'll not see them). You have to rewind a bit more. But it's like 1-2 sentences (few seconds, not 3-5 minutes).

> They may not appear.

Do subtitles appear soon later (few seconds / next sentence)?

**Comment by zaps166** [comment]
If it's "this" case, I don't know if it can be fixed easily.

**Comment by zaps166** [comment]
Tried various files (also some from your email @Rtizer-9) - all are playing good (also on Windows). Cannot reproduce, sorry.

Maybe if you could send me the file which doesn't work, because I've never seen such issue...

**Comment by zaps166** [comment]
> It's probably because of that cache issue (rewinding to a point where the cache is already deleted).

Yes, it discards everything on seek, so the stream must provide it again. Usually you can notice zero or one (sometimes two) missing dialog(s). Just need to seek a few more seconds :smile: 

> and fast forward then subtitle disappears completely and maybe sometimes come back after like ~3-5 minutes and sometimes not.

This is the most interesting :thinking:

**Comment by zaps166** [comment]
> If anything happens then I'll report here again. For now everything works as expected.

Ok!
