### ISSUE TITLE
Free stretch and extrastereo

### ISSUE THREAD

**Issue by flandriai** [zaps166/QMPlay2#815]
It would be great if the free stretch option (that is present both in MPC-HC and MPC-BE) would be available. This gives you the possibility to stretch a video as you like, both horizontally and vertically in realtime (with the numpd keys), and there is an added option that makes it possible to also move the video image (up-down-left-right) within the player window. It's very useful with a content that uses a non-standard aspect ratio. 
Mplayer's extrastereo filter support would also be great. It provides an awesome surround effect.

**Comment by zaps166** [comment]
> and there is an added option that makes it possible to also move the video image (up-down-left-right) within the player window

You can do this by pressing Shift key and mouse click + mouse move.

**Comment by zaps166** [comment]
> Maybe, also add a custom aspect ratio (user value, keyboard input) in the current context menu?

I've been thinking about this for several years :sweat_smile:

**Comment by zaps166** [comment]
I don't know what extrastereo filter has to do with custom aspect ratio -> another issue.

> Maybe this is already implemented or you don't want to complicate your code with this feature?

Better to implement FFmpeg filters instead, so all can be used, but it's separate issue.

**Comment by flandriai** [comment]
> I don't know what extrastereo filter has to do with custom aspect ratio -> another issue.
> 
> > Maybe this is already implemented or you don't want to complicate your code with this feature?
> 
> Better to implement FFmpeg filters instead, so all can be used, but it's separate issue.

You are absolutely right @zaps166 ! Thank you for pointing it out and sorry for the misunderstanding. I opened a separate issue for the extrastereo filter.

**Comment by zaps166** [comment]
@Rtizer-9 

Example:
```
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
cmake --fresh -GNinja -B build -S . -DCMAKE_BUILD_TYPE=Release -DUSE_PCH=ON -DCMAKE_INSTALL_PREFIX=/usr/local
ninja -C build
sudo ninja -C build install/strip
```

**Comment by zaps166** [comment]
If it'll use old version or can't run due to version difference:

```
export LD_LIBRARY_PATH=/usr/local/lib
/usr/local/bin/QMPlay2
```
