### ISSUE TITLE
Extrastereo filter support

### ISSUE THREAD

**Issue by flandriai** [zaps166/QMPlay2#819]
Adding Mplayer extrastereo filter would be great. It provides an awesome sorrund effect.

**Comment by zaps166** [comment]
Maybe it's better to add all FFmpeg audio filters (libavfilter)?

**Comment by flandriai** [comment]
> Maybe it's better to add all FFmpeg audio filters (libavfilter)?

Yeah libavfilter would be even better. I did not think of that. It not only contains the extrastereo filter but many other filters too.
