### ISSUE TITLE
First instance of a file that won't display the content

### ISSUE THREAD

**Issue by TaxicabMessiah** [zaps166/QMPlay2#820]
When trying to play this movie file I get audio output but the display is my thumbnail instead of the film.  All other movies in my collection have worked so far and this file plays in other media players.  It's an H.265 codec inside a matroska container.  It has a standard resolution size (1080p) and framerate.  It has a standard audio format (aac) and a standard aspect ratio (16:9).  Not sure if there are settings I could try tweaking.  Using Vulkan on Windows 11.

![Screenshot 2024-12-23 035847](https://github.com/user-attachments/assets/08e325e9-5b54-44ea-bda6-5b54a1be0c48)

**Comment by zaps166** [comment]
What will happen if you press `O` key?

**Comment by TaxicabMessiah** [comment]
It looks like the movie is the black box behind the thumbnail that won't display.  Pressing O cycles between that blank movie box and the thumbnail.  Also using the seekbar breaks the movie and won't move the audio forward.  Strange behavior all around.

![Screenshot 2024-12-23 042106](https://github.com/user-attachments/assets/78a7357a-e1a9-4289-94ec-8143b17e68f0)
![Screenshot 2024-12-23 042130](https://github.com/user-attachments/assets/940f3117-eaa4-4115-ba80-ec2fefb315d2)

**Comment by zaps166** [comment]
I need `Information` panel screenshot.

You can try re-pack file using: https://mkvtoolnix.download/downloads.html#windows

Or re-pack using FFmpeg (try using `ffmpeg.exe` from QMPlay2 directory):
```
ffmpeg.exe -i "your file.mkv" -c copy "new file.mkv"
````

if this will not help, cut the video and send me, e.g.: 
```
ffmpeg.exe -i "your file.mkv" -c copy -t 10 "new file.mkv"
```

**Comment by TaxicabMessiah** [comment]
Oh good idea.  I looked at the logs and this is the error:
[16 Dec 2024 06:22:14.206] qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
[16 Dec 2024 06:22:14.208] qt.gui.imageio: libpng warning: iCCP: cHRM chunk does not match sRGB
[16 Dec 2024 06:23:20.717] qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
[16 Dec 2024 06:23:20.718] qt.gui.imageio: libpng warning: iCCP: cHRM chunk does not match sRGB

**Comment by TaxicabMessiah** [comment]
Logs offer no errors.  My goal isn't really to have the file play in QMPlay2 but more to understand why it isn't playing in the first place.  I'm just not sure what to look into for that.
![Screenshot 2024-12-23 052015](https://github.com/user-attachments/assets/0c07c0be-c038-4266-89e1-3369ab195af4)

**Comment by zaps166** [comment]
"Information" panel (Shift+I).

**Comment by TaxicabMessiah** [comment]
Oh, the widget itself.  I think I've already offered you all of this data in the first post but here it is.
![Screenshot 2024-12-23 060230](https://github.com/user-attachments/assets/2ca3957d-204c-4cac-abb2-33d147c34db3)
![Uploading Screenshot 2024-12-
![Screenshot 2024-12-23 060310](https://github.com/user-attachments/assets/329a2c60-2e7e-4848-9949-e586004318bc)
23 060245.png…]()

**Comment by zaps166** [comment]
Click on "Stream 1" (or Playback->Video streams" menu).

**Comment by TaxicabMessiah** [comment]
Holy shit you nailed it.  It split the thumbnail and the video into 2 different streams and defaulted to the thumbnail.  Whoa

**Comment by zaps166** [comment]
I don't know why it chose second stream (thumbnail) :sweat_smile: It shouldn't, but I need sample file.

**Comment by TaxicabMessiah** [comment]
I extracted a 1 minute sample of the movie to send to you but I wanted to test it first.  This clip has no issue - there is no thumbnail stream in the 1 minute clip - it acts perfectly normal.  Only the intact file has this issue.

**Comment by zaps166** [comment]
Yes, because this command copies one stream...

Try this:
```
ffmpeg.exe -i "your file.mkv" -c copy -map 0 -t 10 "new file.mkv"
```

**Comment by TaxicabMessiah** [comment]
Got it.  Here's the DL link: https://sendgb.com/jr0KCncRfmM
Also this new clip has ALMOST the same problem with a minor change.  Cycling through the 'o' option will still give me the same error but it wont reproduce the thumbnail over the black box error specifically.  Hopefully this is enough to diagnose however.  The 2 video issue is still here and the thumbnail is video 1 just like the full movie file, howerever.

**Comment by zaps166** [comment]
This video works correctly - just plays, only `mjpeg` streams manually selected - not (this is not important).

Maybe your video has incorrectly set the default stream to cover? I think you can check video from https://github.com/zaps166/QMPlay2/issues/820#issue-2755582068 with https://mkvtoolnix.download/downloads.html#windows and see which video stream is default.

**Comment by zaps166** [comment]
"Fixed", but not 100% sure if it's this case.

**Comment by zaps166** [comment]
Looks like a corrupted stream in file, but maybe "mjpeg" doesn't have to be default. If it'll cause other problems, I'll revert it in the future.
