### ISSUE TITLE
Add support for RTL direction

### ISSUE THREAD

**Issue by badrazizi** [zaps166/QMPlay2#824]
Currently, RTL languages are supported but not in the correct direction, which breaks the text if it is mixed with English.

for example:

currently displayed as:
<p dir="ltr">إجبار إلغاء تشابك Vulkan Yadif لكل أنواع فك التشفير المسرعة بوحدة المعالجة الرسومية</p>

where it should be as:
<p dir="rtl">إجبار إلغاء تشابك Vulkan Yadif لكل أنواع فك التشفير المسرعة بوحدة المعالجة الرسومية</p>

**Comment by zaps166** [comment]
It's correct here, could you add more info (system, Qt version, etc.?):

![Zrzut ekranu_20241225_002101](https://github.com/user-attachments/assets/bae78f04-1e66-4b8f-9022-2dee5b87646c)

**Comment by badrazizi** [comment]
System: Windows 10 22H2 Build 19045.5247
version 24.12.23_QT6
![QMPlay2_QT6](https://github.com/user-attachments/assets/bb3c14a6-a0d9-4c43-996d-eb2c287e8093)
version 24.12.23_QT5
![QMPlay2_QT5](https://github.com/user-attachments/assets/b629a46f-329e-4aa0-b0b2-ad698ad18ebb)
- both are the portable version

Test it on both windows display language English and Arabic

**Comment by zaps166** [comment]
It's a problem with package. Running compiled on Windows looks correct.

**Comment by zaps166** [comment]
I'll be fixed in next release, thanks!

**Comment by zaps166** [comment]
Yes
