### ISSUE TITLE
Text obfuscated by background

### ISSUE THREAD

**Issue by TaxicabMessiah** [zaps166/QMPlay2#826]
Some of the HUD doesn't have a dark background as an option and relies on contrast with the wallpaper itself.  It would be nice if we had the option for this text to have an outline or shadow with a color of our choosing to allow it to stand out.  Screenshot below highlights this type of text.  The example on the bottom right illustrates the problem - you cannot see the time on this background.

![Screenshot 2024-12-25 103429](https://github.com/user-attachments/assets/1e05076a-8ea4-4118-86f7-db77d63f998e)

**Comment by zaps166** [comment]
AFAIK to paint shadow I need move 1px and paint text with different color or use drop shadow effect on every label. I doubt if I can just set parameter to entire window for all texts.
