### ISSUE TITLE
Crash on (VkVideo, CUVID -> D3D11VA) fallback

### ISSUE THREAD

**Issue by Realex-fire** [zaps166/QMPlay2#828]
Hello @zaps166,
I noticed that QMPlay2 crashes when I manually switch the playing first video to the second in the playlist e.g. by double click:

1. https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/1080/Big_Buck_Bunny_1080_10s_1MB.mp4
2. https://test-videos.co.uk/vids/bigbuckbunny/mp4/h265/1080/Big_Buck_Bunny_1080_10s_1MB.mp4

This happens when the first video is decoded by VkVideo or CUVID, and for the second video a fallback to D3D11VA occurs.

If you play only the second video or wait until the end of the first for automatic switching, then the crash does not occur.
You can also manually stop the first video and play the second video, but then the crash does not occur too.

It will likely require special hardware to reproduce this when HEVC is only supported by D3D11VA.
Thanks!

**Comment by zaps166** [comment]
There's easier way to reproduce, but yes, it crashes 😭

**Comment by zaps166** [comment]
> Thanks a lot @zaps166 and Merry Christmas! 🙂

Thanks, Merry Christmas, too!
