### ISSUE TITLE
[FR]: Scaling improvements

### ISSUE THREAD

**Issue by Realex-fire** [zaps166/QMPlay2#829]
Hello @zaps166,
The current non-integer zoom step (0.05) does not allow accurate scaling at the edge of the screen (without black bars).
I suggest you improve the current scaling behavior as follows (this is an example for 1:1 video (e.g. 500x500) on FHD screen):

 - new_zoom_point_1 = screen_height / video_display_height = 1080 / 1080 = 1.00 (there can be many decimal places here)
 - new_zoom_point_2 = screen_width / video_display_width = 1920 / 1080 = 1.7(7)
 - add_zoom_point = new_zoom_point_1 or new_zoom_point_2 (the choice depends on what is taken as 1.00 zoom point)
 - zoom_points = [..., 1.00, 1.05, ..., 1.75, add_zoom_point, 1.80, 1.85, ...]

For screen size, you can take the current size of the video widget. This should fit well into the current scaling system with enabled aspect ratio. Is that possible?
Thanks!

**Comment by zaps166** [comment]
> Maybe. If you do this, will it be possible to set the accuracy to 3 or 4 decimal places in the input dialog?

Yes, I think 3 decimals is enough. If not - do a PR.

**Comment by zaps166** [comment]
>  I want to be able to "hook" onto the edges of the screen. But it's probably not easy to implement 🤔

Easier to do a dialog.

**Comment by zaps166** [comment]
Now it's consistent with playback speed. And who normally need 3-4 decimal for zoom? :astonished: If you crop few pixels, what's the difference? :sweat_smile:

**Comment by zaps166** [comment]
It can go into submenu, both options. But it'll be the last change in this :sweat_smile:

**Comment by zaps166** [comment]
And how  about input dialog which will update live when you use up/down arrows?

**Comment by zaps166** [comment]
GNOME again? Just switch to anything except GNOME and will be fine :rofl:

**Comment by zaps166** [comment]
>  I hope GNOME and Wayland will fix this someday 🙂

Yeah.

**Comment by zaps166** [comment]
I pushed changes, could you test it?

**Comment by zaps166** [comment]
Done

**Comment by zaps166** [comment]
I don't have problems on Xorg, Windows, macOS, but only on Wayland. Something is wrong with Wayland protocol in general.

**Comment by zaps166** [comment]
> Thanks a lot. I also see https://github.com/zaps166/QMPlay2/commit/7ff07eb0d2a3187d48a90e5e7f9a5dfee36a2a65, this fixes freezing on GNOME (Wayland) for QInputDialog.

It doesn't fix Weston behavior - also freezes with this.

**Comment by zaps166** [comment]
> PS: Do you want to swap "Toggle aspect ratio" and "Aspect ratio" lines in the context menu for better UX? Or is the current order better? 🙂

Done.

**Comment by zaps166** [comment]
Why this is needed?

**Comment by zaps166** [comment]
> This is used for videos like [this](https://www.youtube.com/watch?v=b1Fo_M_tj6w). For example, you might have a list with timestamps and a very long video file. Some people probably prefer to enter the time manually 🤔

I don't fetch chapters from YouTube. I don't know why it doesn't work same way as in MKV files... Maybe (if possible) it's a better idea to add them as "Chapters" as it's working in MKV files?

> I don't know how often this is used, but it is used 🙂

I think it's a rare case. I never used it. I can use seek bar which displays time in status bar or tool tip and click there.

> QMPlay2 also ignores it for now.

It's parameter for YouTube, not for QMPlay2.

---

Anyway it's not related to scaling improvements.
