### ISSUE TITLE
[Feature Request] drag& drop changing tabs

### ISSUE THREAD

**Issue by Amaunator** [zaps166/QMPlay2#84]
usage scenario:
I'm in file manager. want to play a folder or a file. I drag it to the player window but playlist is not an active tab so:
- nothing happens. 
- expected outcome: tab becomes active (switched into) and I can drop files/folders. saw it many places elsewhere working this way - very convenient. 

Don't want to open a new one: can seek bar slider show (like in case of youtube tab) buffer state when playing internet audio streams too? Actually, local files too if possible (can have option to disable) : often if usb disk is busy and I want to play video/flac file: it skips and I wander: is file corrupted or usb hdd isn't coping with demand?

**Comment by zaps166** [comment]
> Don't want to open a new one: can seek bar slider show (like in case of youtube tab) buffer state when playing internet audio streams too? Actually, local files too if possible (can have option to disable) : often if usb disk is busy and I want to play video/flac file: it skips and I wander: is file corrupted or usb hdd isn't coping with demand?

This is not related question, so in the future I won't be able to find it...
Local files has smaller buffer and different buffering method than network streams. Try to adjust it in settings (second tab). If it doesn't help - open a new issue.
