### ISSUE TITLE
[feature request] ability to scale simple visualisation peak meter

### ISSUE THREAD

**Issue by Amaunator** [zaps166/QMPlay2#87]
I keep my music files normalized at 89dB. when I play them back Simple visualisation shows peak level bar that goes up to only max 40% of its full height. like if full scale was at 150dB. Is the level meter logarithmic? files if I amplify them (very distorted) by +20dB reach full scale. can 89dB be 89% of the full graph please?

**Comment by zaps166** [comment]
Currently it is [RMS](https://github.com/zaps166/QMPlay2/blob/32f32d75c071042f354db8c78b70e725dcc3effe/src/modules/Visualizations/SimpleVis.cpp#L95).

So it must be adjustable in settings - everyone wants something else :D

**Comment by Amaunator** [comment]
Radia z Polskiejstacji czy pozostałe też "idą" do 1/3ciej, max 40% wysokości paska poziomu
