### ISSUE TITLE
[Feature request] Images support

### ISSUE THREAD

**Issue by parkerlreed** [zaps166/QMPlay2#88]
I have some panorama images that I haven't been able to find a decent viewer for. I remembered your project had a nice spherical OpenGL renderer. Tried adding some images to the playlist but it doesn't seem to support them at all. Would be a nice feature to have.

**Comment by zaps166** [comment]
Currently QMPlay2 doesn't support images (it is blocked), because images are treated as single-frame movie - I must do fake length (set in settings window) for images.

**Comment by zaps166** [comment]
Done, images are displayed as paused movies :) If you have enabled filter which needs more then one frame (e.g. force-enabled deint filter) - you will not see anything.

**Comment by parkerlreed** [comment]
Will give this a shot, thanks!

**Comment by parkerlreed** [comment]
Seems to not like my 2 row panos but one row is working great (I assume since that's how 360 video cameras do it). I did have to clear my ~/.qmplay2 folder for the images support to work out of the box. Thanks!

**Comment by parkerlreed** [comment]
Video https://www.youtube.com/watch?v=zljuqm6RX0s

**Comment by parkerlreed** [comment]
Hah just realized it's because that one was the only full 360 one I shot. Which makes sense given that the filter is a spherical view :)

**Comment by zaps166** [comment]
@parkerlreed [Now](https://github.com/zaps166/QMPlay2/commit/d4d45281523d0f03a7e6709bf15cf844ba0e9742) images are disabled by default - you must enable it in settings :)
