### ISSUE TITLE
Portable version?

### ISSUE THREAD

**Issue by thumbapps** [zaps166/QMPlay2#90]
Any way -- maybe through command line option -- to move the data from %appdata% to other location?

Or maybe QMPlay2 has some "portable mode" -- in Windows?

And it would be helpful to provide a way to extract the binaries from the installer directly.

Regards,
Ronny
@thumbapps.org

**Comment by zaps166** [comment]
I can release portable Windows x64 7-zipped package which will use settings inside application directory :) Will it be ok?

**Comment by thumbapps** [comment]
Why not for the 32 bit too? There are many that still use this platform. But thanks a lot for the 64 bit. At least we can try it.

**Comment by zaps166** [comment]
So 32-bit can be also released (source code is ready). Next QMPlay2 release will have portable edition :)

**Comment by thumbapps** [comment]
Great! Looking forward for it! Thanks :)

**Comment by zaps166** [comment]
I didn't upload Zipped portable release. If you need it, I can upload it.
Currently for portable version you must create an empty file "portable" in QMPlay2 directory (in directory with QMPlay2.exe) after installation (installer just unpacks files) and then it will be portable (you can Zip the directory). In portable mode QMPlay2 creates `settings` directory and stores everything there :)

**Comment by thumbapps** [comment]
Yes, please :) I can't extract the installers with 7 zip. Or is there any way to just extract the contents from the installers without writing to registry and Windows standard data folders (%appdata%)?

Could you maybe add "portable installation option" like Hexchat or Homebank? Or installer command line option to just extract the contents?

Right now the installer still writes "Trolltech" to the registry and %appdata%--since it automatically run after installation.

Sorry for the trouble :)
Thanks

**Comment by zaps166** [comment]
Done :)
Portable ZIPs are here: https://github.com/zaps166/QMPlay2/releases/tag/17.03.17

Portable will check for updates (for notification), but it won't download it (you can disable it in settings). Also portable won't ask about file association.

> since it automatically run after installation.

Right, I should add a checkbox for portable (in next release).

**Comment by thumbapps** [comment]
Nice! I've downloaded both 32/64 bits.

> Right, I should add a checkbox for portable (in next release).

Thanks :)
