### ISSUE TITLE
{Feature Request UNIX} appdata.xml

### ISSUE THREAD

**Issue by symbianflo** [zaps166/QMPlay2#91]
Hi
Can you please add appdata.xml to qmplay2 for software center integration.
Guidelines :
https://www.freedesktop.org/software/appstream/docs/index.html

Thank you in advance.

**Comment by zaps166** [comment]
Added, please check if the file is correct :)

**Comment by symbianflo** [comment]
`+ appstream-util validate-relax --nonet /home/symbianflo/rpmbuild/BUILDROOT/qmplay2-17.03.17-1-rosa2014.1.x86_64-buildroot/usr/share/appdata/org.zaps166.QMPlay2.appdata.xml
/home/symbianflo/rpmbuild/BUILDROOT/qmplay2-17.03.17-1-rosa2014.1.x86_64-buildroot/usr/share/appdata/org.zaps166.QMPlay2.appdata.xml: FAILED:
? attribute-invalid     : <id> has invalid type attribute
? markup-invalid        : <id> does not have correct extension for kind
? tag-missing           : <metadata_license> is not present
? tag-invalid           : stock icon is not valid [QMPlay2]
Validation of files failed
error: Errato stato di uscita da /var/tmp/rpm-tmp.4402 (%check)
`


I'm sorry....

**Comment by symbianflo** [comment]
A example of appdata.xml :
https://github.com/kokoko3k/xt7-player-mpv/blob/master/xt7-player-mpv.appdata.xml

**Comment by zaps166** [comment]
Did you apply https://github.com/zaps166/QMPlay2/commit/1e817ed17fa2074983224035ae1f98570ed5593f ?
