### ISSUE TITLE
Wrong UI scaling since version 17.03.17

### ISSUE THREAD

**Issue by PeterFeicht** [zaps166/QMPlay2#93]
I updated from version 17.02.12 to 17.03.17 recently and now the UI is way too big.  
I'm running a Dell XPS 13 which has a 13" Full HD display, and for me an unscaled UI is just right. However with the new QMPlay version it's suddenly scaled to twice the size, which is way too big (besides, all the icons are pixelated now).

Could you maybe provide an option for manual UI scaling, or is this just a bug?

Details: Arch Linux with Xfce 4.12, Qt 5.8.0, QMPlay2 from the AUR.

**Comment by zaps166** [comment]
It is a bug. I can't test it on Linux, because I don't have HiDPI screen, so I've tested only on MacBook 15" with Retina display. I'll disable auto HiDPI for Linux, so it'll be adjustable by env vars `QT_SCALE_FACTOR` or `QT_AUTO_SCREEN_SCALE_FACTOR`.

**Comment by PeterFeicht** [comment]
Can I help you with testing?

**Comment by zaps166** [comment]
Yes :)

Could you test if `QT_AUTO_SCREEN_SCALE_FACTOR=0 QMPlay2` helps?

I'll also prepare a patch, then you can just compile `qmplay2-git` and test if it is OK (like in previous version).

Also you can upload here a screenshot :)

**Comment by PeterFeicht** [comment]
So, setting QT_AUTO_SCREEN_SCALE_FACTOR=0 does help.

The first screenshot is of version 17.02.12, the second one shows version 17.03.17 (it maximized the window itself, the unmaximized version doesn't even fit on the screen any more).
![Version 17.02.12](https://cloud.githubusercontent.com/assets/7085977/24255669/69189d84-0fe6-11e7-9e01-9390970d2e0a.png)
![Version 17.03.17](https://cloud.githubusercontent.com/assets/7085977/24255675/6d601750-0fe6-11e7-8d9e-f5d2b4c26979.png)

**Comment by zaps166** [comment]
Thanks! It looks really awful and also font and sliders are not scaled... Icons are pixelated (but it is known for me).

If you add `QT_AUTO_SCREEN_SCALE_FACTOR=0` to new version - does icons look good (not-pixelated) like in 17.02.12?

**Comment by PeterFeicht** [comment]
When setting `QT_AUTO_SCREEN_SCALE_FACTOR=0` everything looks fine in the new version.

**Comment by zaps166** [comment]
Thanks for testing! The simplest way to fix it is to don't enable auto-scaling for other systems than macOS. Currently Windows uses Qt4, so it doesn't matter for this version.

Please try `qmplay2-git` from AUR :)

**Comment by PeterFeicht** [comment]
`qmplay2-git` (373a2c8e) looks fine.
