### ISSUE TITLE
Improved support for chained bitstream Ogg files

### ISSUE THREAD

**Issue by Chromace** [zaps166/QMPlay2#94]
Currently, the implementation for chained bitstream Ogg files is a little strange. Rather than representing the file as a single entity, it puts the file into separate pieces inside a folder. The ideal would be to have it as a single file so it could be properly played through.

This is how it currently is displayed:

![qmplay2 chained bitstream ogg](https://cloud.githubusercontent.com/assets/16624211/24685035/43a76bae-19ee-11e7-9561-99e42581fae1.png)

Attached is a sample chained bitstream file, which should display similarly in QMPlay2:
[07. Plain Asia.ogg.zip](https://github.com/zaps166/QMPlay2/files/894881/07.Plain.Asia.ogg.zip)

Thank-you!

**Comment by zaps166** [comment]
> Rather than representing the file as a single entity, it puts the file into separate pieces inside a folder.

It is intended, it works properly like in Audacity and DeaDBeeF. Chained OGG file is a concatenation of many OGG files. Try to use `cat` on many OGG files and create one big file - then it will be represented properly in QMPlay2. The same is in OGG radio stream - every new song is a separate OGG file with other title/artist, etc. So it is good to have it represented as separate files :)

VLC and pure FFmpeg reads it as single file, but the length is calculated incorrectly and you can't properly seek (especially out of first chain).

**Comment by Chromace** [comment]
I see...so until FFmpeg fixes their support for chained OGGs, there's not much that can be done? I understand. Thank-you for your explanation! :)

Hopefully FFmpeg will improve in the future.

**Comment by zaps166** [comment]
> Hopefully FFmpeg will improve in the future.

Detection chained OGG as many separated files (tracks) is [done by me](https://github.com/zaps166/QMPlay2/blob/17.04.02/src/modules/FFmpeg/OggHelper.cpp#L88) :) At least I can add additional option to restore default FFmpeg behavior with blocked seeking (which doesn't work properly) as it is in network stream, but is it needed?

**Comment by Chromace** [comment]
It's alright. There is no real need for it if it doesn't work properly. It seems like chained OGG files aren't well supported by many media players anyway. For now at least, the best solution is not to use them I think.

Perhaps, when FFmpeg can truly support these files, then such an option would be nice. But that is not the case at this moment.

Thank-you again! :)

**Comment by zaps166** [comment]
> Perhaps, when FFmpeg can truly support these files

Yes, it should properly seek and properly read length on chained files (then I can add option to use it), but IMHO chained OGG files are concatenation of many single OGG files, so that's I've decided to show it as single files in virtual directory (see also DeaDBeef). You can check incorrect seeking on VLC. Additionally you can download more than one song from OGG radio stream and also check that current solution is useful :)
