### ISSUE TITLE
hardware FFmpeg decoding on Mac

### ISSUE THREAD

**Issue by RJVB** [zaps166/QMPlay2#95]
Hi,

Have you ever looked into enabling FFmpeg hardware decoding on Mac? According to [this answer on StackOverflow](http://stackoverflow.com/questions/23289157/how-to-use-hardware-acceleration-with-ffmpeg) it could be as easy as

> To get HW acceleration working on Mac OS you should just use the following: avcodec_find_decoder_by_name("h264_vda"); Note, however that you can accelerate h264 videos only on Mac OS with FFmpeg.

**Comment by zaps166** [comment]
Hi,

I also want to add VDA/VideoToolbox decoder for macOS, but I don't have hardware to test it. It is not as easy as replacing decoder name, because (even if it works) copying frame from GPU to CPU memory is a slow operation, so in "easy" mode you can have slowdowns comparing to full-CPU decoding, and it also uses too much CPU. More advanced method is to reuse decoded frame in OpenGL output (it is already done in CUVID, VA-API and DXVA2, and also in VDPAU, but currently not in OpenGL).

I can try to use someones' real Mac and do it :)

**Comment by RJVB** [comment]
Hi,

This is the sort of thing I have no experience with (last time I had to write a video player I could still use the QuickTime SDK :)) but I can test drive implementations. If they're supposed to work on OS X 10.9, that is.

**Comment by zaps166** [comment]
Do you use macOS 10.9? Does QMPlay2 work there :) ?

**Comment by RJVB** [comment]
On Friday April 07 2017 13:22:18 Błażej Szczygieł wrote:
> Do you use macOS 10.9? Does QMPlay2 work there :) ?

Yes, and yes. I had to put an #ifdef around a single statement that uses a 10.12+ token (https://github.com/RJVB/macstrop/blob/master/multimedia/qmplay2/files/patch-build-pre-1012.diff) but apart from that it works just fine. Even hacked to use a systray icon/menu rather than the Dock menu and a shared Qt5 install. I haven't yet submitted it but the patchfile linked above is part of a MacPorts "port"

R.

**Comment by zaps166** [comment]
Ok! This patch with "NSSystemDefined" I can use. Probably older solution will work in 10.12.x, so it can be used :)

Btw. what about my DMG package? Probably it is not possible to run it, but I didn't test it on older OSes...

**Comment by RJVB** [comment]
On Friday April 07 2017 14:06:38 Błażej Szczygieł wrote:
> Ok! This patch with "NSSystemDefined" I can use. Probably older solution will work in 10.12.x, so it can be used :)

Yes, but the better solution would be what I do, with an #ifdef to detect older systems. The old token is deprecated so it will disappear at some point.

> Btw. what about my DMG package? Probably it is not possible to run it, but I didn't test it on older OSes...

If you haven't taken precautions (like using the appropriate SDK) the build will not work. The Mac OS doesn't just include version info in library filenames, there is also compatibility info stored in the libraries themselves.

I also like to use shared libraries as much as possible, including my own Qt build, hence the MacPorts port.

**Comment by zaps166** [comment]
Compilation for older macOS patch added: https://github.com/zaps166/QMPlay2/commit/29e84a5d409dc5f0510a4a261ead1538fca3217c, thanks!

**Comment by zaps166** [comment]
I can run Videotoolbox on my computer, so I can do it 😄

**Comment by RJVB** [comment]
?

**Comment by zaps166** [comment]
> but I don't have hardware to test it

Now VideoToolBox it works (it didn't work ~2 months ago for unknown for me reason...).

**Comment by zaps166** [comment]
@RJVB Done (experimental state). You can test :)

**Comment by RJVB** [comment]
On Saturday April 15 2017 12:24:15 Błażej Szczygieł wrote:
>@RJVB Done (experimental state). You can test :)

Builds and runs on 10.9 too. How do I verify that the accelerated engine is used?

**Comment by zaps166** [comment]
Go to "Playback settings", move VideoToolBox decoder to the top and apply. Then run a video. In "Information" widget you'll see VideoToolBox decoder. If also you'll see VideoToolBox in OpenGL output then it doesn't copy the video to system RAM (the fastest mode). You can copy it to system RAM (slow mode) by changing settings in FFmpeg module. This is experimental - if some h264 videos can't decode using hw decoder then you'll have black screen. Also if you have OpenGL in RTT mode (default for macOS) you can have playback problems when changing between decoding CPU/GPU - you need to stop/play (this bug is also reproducible on Linux when OpenGL is in RTT mode).

**Comment by RJVB** [comment]
On Sunday April 16 2017 00:54:34 Błażej Szczygieł wrote:

Hmm, I had put the VTB decoder first but don't see any mention of it in the Info widget. Is there a way to get more verbose error/warning logging?

I also don't know exactly what the VTB supports on my system, it was relatively new in OS X 10.9 and I have "only" a 2011 i7 with its built-in HD3000 GPU and (as far as I remember) shared RAM. Which may make the whole distinction between copying to CPU RAM a moot consideration. 
I did notice the need to start/stop to get an image, but that's only when I untick the option to copy to RAM.

A bit off-topic here, but what I find annoying with Qt applications is that they use the "native" fullscreen mode which means that on a multi-head set-up with "spaces use different screens" off all screens are blackened when you put an app in fullscreen mode. For me that's a reason to stick to VLC and an old Quicktime 7 player as then I can continue to keep an eye on email while watching a video.

R.

**Comment by zaps166** [comment]
I have 3rd gen i7 CPU with HD4000 GPU. Also tested on Intel Iris. Some H264 videos doesn't play currently. Try this video: http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_60fps_normal.mp4

![spectacle na1891](https://cloud.githubusercontent.com/assets/6239090/25141349/990be7bc-2463-11e7-88d1-273fe86142b6.png)

You should have info in this place, but with VideoToolBox.

---

> For me that's a reason to stick to VLC and an old Quicktime 7 player as then I can continue to keep an eye on email while watching a video.

Maybe try Alt+V to toggle compact mode and only maximize? I know that Qt has full screen which goes into another desktop. Maybe a new feature should be added into Qt?

**Comment by RJVB** [comment]
On Tuesday April 18 2017 09:21:41 Błażej Szczygieł wrote:

> I have 3rd gen i7 CPU with HD4000 GPU. Also tested on Intel Iris. Some H264 videos doesn't play currently. Try this video: http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_60fps_normal.mp4

Works fine on my lowly N3150 Linux system, but on my Mac I get an "unknown" error from av_videotoolbox_default_init().

I should note that using FFMpeg's h264_vda codec is also hit-and-miss on my system. Sometimes it works (in VLC), sometimes it doesn't. I'm beginning to wonder if CPU-embedded GPUs can go bad; this morning I rebooted (after about 2 months uptime) and then had to reboot once more because XQuartz crashed with some OpenGL-related error.

> Maybe try Alt+V to toggle compact mode and only maximize?

Also not ideal...

> I know that Qt has full screen which goes into another desktop. Maybe a new feature should be added into Qt?

As far as I know it doesn't darken all screens if you allocate different spaces to all screens (but I really don't like that, and you have to log off and back in to toggle the setting).
I looked at how Qt4 did fullscreen mode quite some time ago and remember it looked complex enough that I decided to try and make do with the "native" implementation...

R.

**Comment by zaps166** [comment]
You can try pure ffmpeg from command line which has vda/vtb compiled-in (for testing purposes).

`ffmpeg -hwaccel videotoolbox -threads 1 -i /path/to/file -f null - -benchmark` (https://trac.ffmpeg.org/wiki/HWAccelIntro). Maybe this: https://evermeet.cx/ffmpeg/ . Now I can't check, because I'm on Linux.

---

Hmm, IIRC on 10.12.x I can use this "native" fullscreen and use second monitor for another desktop, but anyway it is annoying... I know that Firefox has something better (e.g. youtube), but how to do it properly in Qt?

**Comment by RJVB** [comment]
On Tuesday April 18 2017 14:25:28 Błażej Szczygieł wrote:
> You can try pure ffmpeg from command line which has vda/vtb compiled-in (for testing purposes).
> 
> `ffmpeg -hwaccel videotoolbox -threads 1 -i /path/to/file -f null - -benchmark`

Well, that remains hit and miss. Yesterday I got a whole list of

Apr 18 23:41:13 Portia.local ffmpeg[14894]: AVF error: Perf capability check failed: 0xe00002bc
Apr 18 23:41:13 Portia.local ffmpeg[14894]: AVF error: Branch_QT0::pushBits, Context Creation Failed.
Apr 18 23:41:13 Portia.local ffmpeg[14894]: AVF error: Perf capability check failed: 0xe00002bc
Apr 18 23:41:13 Portia.local ffmpeg[14894]: AVF error: Branch_QT0::pushBits, Context Creation Failed.
Apr 18 23:41:13 Portia.local ffmpeg[14894]: AVF error: Perf capability check failed: 0xe00002bc
Apr 18 23:41:13 Portia.local ffmpeg[14894]: AVF error: Branch_QT0::pushBits, Context Creation Failed.

errors in my system.log (I'm seeing similar errors when playing video content in browsers). This morning they're gone and I do notice a difference in the benchmark (much lower CPU load with hw accel) so something is indeed different. Must be because I
1) used Fast User Switch to go to the login screen and/or
2) suspended the computer for the night from that screen.

QMPlay2 still gets the unknown error in av_videotoolbox_default_init() but currently I can use h264_vda in VLC even though it aborts on the big rabbit video with

[h264_vda @ 0x7faa9319c600] Discarding mismatching reference
Error in reorder_list, couldn't find short term reference with PicNum 1 
Assertion abs(src_linesize) >= bytewidth failed at libavutil/imgutils.c:279

Of course VLC 2.2.4 still uses an old FFmpeg 2.x version, and with QMPlay2 I use FFmpeg 3.2.4 but it seems we're looking at least at a driver issue here. Could be in FFmpeg, but also in the VTB/AVF frameworks on OS X 10.9.5, and of course my GPU may not be supported any better than what I get currently.

> 
> Hmm, IIRC on 10.12.x I can use this "native" fullscreen and use second monitor for another desktop,

Yes, if your settings for Spaces are chosen such that you have independent virtual desktops for each monitor.

> but anyway it is annoying... I know that Firefox has something better (e.g. youtube), but how to do it properly in Qt?

I think that's actually the Flash plugin, in anyway Flash also does old-style fullscreen. You'd have to look at how Qt4 did this, and hope it doesn't involve too much low-level hacking with native windows. From what I recall you have to create a borderless window that fills the screen and cannot be sent to the back, and then get the whole graphics view to use that window. The old window can be kept (as long as it doesn't receive any GUI events?).

R

**Comment by RJVB** [comment]
On Tuesday April 18 2017 14:25:28 Błażej Szczygieł wrote:

> Hmm, IIRC on 10.12.x I can use this "native" fullscreen and use second monitor for another desktop, but anyway it is annoying... I know that Firefox has something better (e.g. youtube), but how to do it properly in Qt?

Could you get some inspiration from this?
https://github.com/RJVB/shortcut-test-qt5/commit/0a665497cc4e6a19250c068d081fb3b114ca7a25#diff-ea177de95bf7d3ef58ee43f705efbb9e

Not only does that seem to give me the kind of fullscreen behaviour I want, it's also instantaneous. No useless animations.

R.

**Comment by zaps166** [comment]
Thanks, I'll check it :)

**Comment by zaps166** [comment]
Don https://github.com/zaps166/QMPlay2/commit/447a3a6e4592dc81bf3659062f27a6b76838fef2 😄

**Comment by RJVB** [comment]
On Wednesday April 19 2017 12:52:28 Błażej Szczygieł wrote:
> Don https://github.com/zaps166/QMPlay2/commit/447a3a6e4592dc81bf3659062f27a6b76838fef2 😄 

Good, will test tomorrow! :)

Meanwhile, I went a bit further and hacked this legacy mode into my alternative Cocoa QPA (which BTW can be embedded in a standalone app bundle):

https://cgit.kde.org/scratch/rjvbb/osx-integration.git/tree/src/qcocoa-qpa/qcocoawindow.mm?h=qt590#n1906


R.

**Comment by RJVB** [comment]
On Wednesday April 19 2017 12:52:28 Błażej Szczygieł wrote:
> Don https://github.com/zaps166/QMPlay2/commit/447a3a6e4592dc81bf3659062f27a6b76838fef2 😄 

I think you can still polish this a bit by looking at my current implementation here:
https://cgit.kde.org/scratch/rjvbb/osx-integration.git/tree/src/qcocoa-qpa/qcocoawindow.mm?h=qt590#n1906

it shows notably how to hide the menubar only when the window actually has one. Dirty secret: you can add ObjC code to a .cpp file (in a conditional block, of course) and compile it correctly by pointing clang++ to a symlink, i.e.

src/gui/MainWidget.mm -> MainWidget.cpp

Also, you may want to remove the fullscreen button from the main window titlebar. With Qt versions before 5.9 that actually makes QWidget::showFullScreen() invoke a legacy mode like we just implemented. I discovered that only yesterday...

R.

**Comment by zaps166** [comment]
Full screen should be a separate Issue... 😄 

So what I can change, you meant autohide dock? Or something else?

**Comment by RJVB** [comment]
On Thursday April 20 2017 09:50:51 Błażej Szczygieł wrote:
>Full screen should be a separate Issue... 😄 

Yeah it should O:-)

>So what I can change, you meant autohide dock? Or something else?

Yes, the auto-hiding of Dock and menubar shouldn't be activated when they are on a different screen than the window that will be maximised. My Dock is always set to auto-hide, but for the menubar it really looks strange when it disappears from the screen while the rest of that screen's contents don't change.

I think you can also consider removing the fullscreen titlebar button (unset the Qt::WindowFullscreenButtonHint window flag). It applies to the full QMPlay2 MDI which is a function that can be provided by the maximisation button. Keeping it can get you into strange interactions; for instance, when you use the fullscreen button and then double-click the video window you don't get fullscreen video. Instead, QMPlay2 drops out of fullscreen mode.

R.

**Comment by mailinglists35** [comment]
Hi,

I am listening to this stream[*] on macOS, and Apple Quicktime and IINA manage to have two times lower CPU usage than QMPlay2 and VLC. 

I wonder how mpv (the engine behind IINA UI) does it differently that about matches Quicktime on low cpu? 

Also observing in Activity Monitor that QMPlay2 stands out with way too many Idle Wakeups than the others - and also observing IINA despite using a bit less cpu than Quicktime, it manages to use more energy (I assume because of more Idle Wakeups than Quicktime?)

![image](https://github.com/user-attachments/assets/9680cd55-4078-48aa-b7ea-703d4f6e8fd8)

![image](https://github.com/user-attachments/assets/6f6a888f-3b97-4a4b-8107-c1439d61f3c8)

[*] https://stream4.srr.ro:8443/bucuresti-fm

**Comment by zaps166** [comment]
It's audio only, hardware decoding is available for video only.

Do you have visualizations visible? Also refreshing UI might cause it - best minimize or it (Window->Hide) and measure CPU load again.

**Comment by RJVB** [comment]
On Friday September 06 2024 15:41:03 Błażej Szczygieł wrote:
>It's audio only, hardware decoding is available for video only.

Could the GPU be leveraged via OpenCL? With enough tracks an audio file could be compared to a very narrow and very tall image, I guess, and the overhead of getting data onto and off the GPU might not kill any gains that could be had? ;)

But here we have a 128Kbps stream, even on my lowly N3150 system playing it takes maybe 16%CPU on average.

>Do you have visualizations visible? Also refreshing UI might cause it - best minimize or it (Window->Hide) and measure CPU load again.

It seems that the playback stats continue to be refreshed when you hide the window, at least I don't see any effect of it on CPU load. Selecting compact mode does (that only shows the video panel for me).

Long ago I observed that video playback with QMPlay2 is more expensive than with e.g. VLC, on Mac. Can't remember with what Qt version it was, but it's almost inevitable that a player written using a cross-platform toolkit cannot be as well optimised as a player that uses purely native libraries.

**Comment by zaps166** [comment]
> Could the GPU be leveraged via OpenCL?

No, OpenCL is obsolete and poor in general (better use Vulkan Compute with MoltenVK), but it's not how audio is working. You take network stream (maybe decryption is slow?), next FFmpeg decodes it using CPU (it's usually fast and optimized SIMD code), next you have uncompressed audio which is put into (in case of macOS) PortAudio library which outputs it to CoreAudio API. Qt is almost not doing anything in audio in QMPlay2 (except `QByteArray` which allocates using (I guess) `malloc` and thread notification and UI update...).

Maybe GPU could be used for audio filtering (e.g. FFT-based equalizer), but another problem is discrete GPU where you have to process audio data which is accessed from CPU RAM through PCI-E bus and output data using this bus to CPU RAM. I doubt it'll drain less power from out PC's, but the code will be much more complicated.

Why it can drain CPU:
- UI refresh (slider, bitrate, time, etc.) - to avoid it - hide UI (e.g. Window->Hide) or use compact mode
- Visualizations (it drains CPU) - close them or hide UI (it should suspend when UI is hidden)
- network packet decryption
- enabled audio filters like DRC, equalizer, echo, resampling
- FFmpeg for some codecs might not have SIMD optimizations
- memory allocation + potential copy for audio buffers
- PortAudio library

---

I used this URL on Linux to test, I can see about 1% CPU core usage when UI is hidden (PipeWire resamples 44100->48000). With visualizations (relatively small size) it's about 5% CPU core usage. For testing purpose my CPU is running at fixed 3 GHz.

**Comment by zaps166** [comment]
> tests were done with all four apps minimized. no visualizations

What CPU do you have there? Soon I'll have access to real Mac hardware, so I could check it.

**Comment by mailinglists35** [comment]
> > tests were done with all four apps minimized. no visualizations
> 
> What CPU do you have there? Soon I'll have access to real Mac hardware, so I could check it.

it's an M1 macbook air 2020, the base entry model (8gb ram/256gb storage).
I can run debug builds and post traces, if it helps.

**Comment by zaps166** [comment]
Ok, I'll check on M1, too (soon I hope). I have to check where CPU spends most it's time on macOS (if it's PortAudio we have a problem...).

---

Just checked MPV, VLC, QMPlay2 all together with your URL on Linux notebook with Ryzen 2500U and PipeWire: QMPlay2 and MPV are even, VLC drain 2x more CPU than them. QMPlay2 CPU load is about 2,0% - 2.3% at fixed 1.6 GHz.

**Comment by RJVB** [comment]
On Monday September 09 2024 05:07:21 Błażej Szczygieł wrote:
>Also on your screenshots `coreaudiod` drains more CPU than all four players... Maybe resampling in QMPlay2 is done in QMPlay2 process, but for two other players is overloaded there? I don't know, just guessing. Could you check the @RJVB's bit-perfect option in PortAudio settings in QMPlay2?

From what I can recall there is no obligation to resample audio in the client (meaning CoreAudio will take care of it if necessary). But this aspect should only play when the selected output device is set to a different sampling rate so there's that option to test too.

**Comment by zaps166** [comment]
Also these two must be disabled: ![Zrzut ekranu_20240909_142823](https://github.com/user-attachments/assets/e55e81de-353a-4757-841c-38bfc974d962)
