### ISSUE TITLE
Youtube - cannot DL "explicit" videos

### ISSUE THREAD

**Issue by feeltheburn** [zaps166/QMPlay2#96]
steel panther party like tomorrow

^ search the above in the Youtube panel for an example. There's 2 versions of that video, (explicit) and (clean). 

The clean is downloadable, but not the explicit.

It can be downloaded using youtube-dl command line, just finding it odd that it can't be with QMPlay2 if that's the case.

**Comment by zaps166** [comment]
Unfortunately, Downloading Youtube videos in QMPlay2 currently doesn't works properly. Any other downloadable YT videos can have worse quality than in playback.

**Comment by feeltheburn** [comment]
I'm aware of the 1080p / sound issue, but that's kinda irrelevant to this bug.

**Comment by zaps166** [comment]
Problems with downloading from Youtube is a known bug to me and it will be fixed (thanks for the report) :)

> (...) 1080p / sound issue

Do you have Youtube playback problems ?

**Comment by feeltheburn** [comment]
I don't generally stream Youtube videos in Qmplay2, except to confirm it's the video I'm looking for in some cases. So never paid attention.

But it appears when available that the 1080p video shows with the 128k Vorbis audio.

(On downloads, I use MKVToolNix  to mux up the 1080p video with 192kbps audio from the 720p video.)

**Comment by zaps166** [comment]
> 192kbps audio

IMHO not worth if it is AAC unless you can't decode Opus or Vorbis codec (even if they have lower bitrate).

---
About downloading: I need to pass both audio and video URLs to downloader and mux it into single MKV.
