### ISSUE TITLE
Missing library on Arch since update of libass

### ISSUE THREAD

**Issue by PeterFeicht** [zaps166/QMPlay2#98]
`libass` was updated recently on my machine from version 0.13.4 to 0.13.6, which presumably removed the file `/usr/lib/libass.so.5` causing QMPlay to not start any more.

As a temporary workaround I created a symlink from `libass.so.5` to `libass.so.9.0.0`, which seems to work (although I haven't used anything with subtitles).

**Comment by zaps166** [comment]
Please recompile QMPlay2 :) This is normal on Arch Linux - QMPlay2 is built from AUR, so it won't be updated together with libass.

**Comment by PeterFeicht** [comment]
Didn't think of that, I didn't realize QMPlay2 was in the AUR. Works fine now, thanks for the quick reply :-)

You should probably change the package release number in AUR though, so it gets updated automatically.

**Comment by zaps166** [comment]
> You should probably change the package release number in AUR though, so it gets updated automatically.

Done 😄
