### ISSUE TITLE
album art

### ISSUE THREAD

**Issue by Amaunator** [zaps166/QMPlay2#99]
please add feature that it looks for album art in the same folder as media file is located or if nowhere else to be found in a folder above. currently program is searching for folder.jpg and that seems to be all. would be nice if it was searching for front.jpg as well. how about this priority: using the larger available jpg, png, gif from any source, then *front*.* folder*.* and with capital "F" too, then internet, then any *.jpg , lastly upper folder jpg *front*.jpg then any *.jpg from this (upper) folder. thank you

**Comment by zaps166** [comment]
Added "front" image. Priorities not changed.
